SELECT *
FROM
(
  VALUES
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'Good      ', BIGINT '2', INTEGER '1', BIGINT '2', INTEGER '2', BIGINT '2', INTEGER '6', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'Good      ', BIGINT '2', INTEGER '3', BIGINT '2', INTEGER '6', BIGINT '2', INTEGER '1', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'Good      ', BIGINT '2', INTEGER '5', BIGINT '2', INTEGER '3', BIGINT '2', INTEGER '4', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'High Risk ', BIGINT '2', INTEGER '1', BIGINT '2', INTEGER '4', BIGINT '2', INTEGER '3', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'High Risk ', BIGINT '2', INTEGER '3', BIGINT '2', INTEGER '0', BIGINT '2', INTEGER '1', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'High Risk ', BIGINT '2', INTEGER '4', BIGINT '2', INTEGER '0', BIGINT '2', INTEGER '0', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '500', BIGINT '2', CHAR 'High Risk ', BIGINT '2', INTEGER '4', BIGINT '2', INTEGER '2', BIGINT '2', INTEGER '0', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1')
)
