SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAAAAABBA', CHAR 'Troy                ', CHAR 'Webb                          ', CHAR 'N', VARCHAR 'NIGER', NULL),
    (CHAR 'AAAAAAAAAAAAABCA', CHAR 'Paul                ', CHAR 'Brown                         ', CHAR 'N', VARCHAR 'ECUADOR', NULL),
    (CHAR 'AAAAAAAAAAAAACBA', CHAR 'Jason               ', CHAR 'Fuller                        ', CHAR 'N', VARCHAR 'INDIA', NULL),
    (CHAR 'AAAAAAAAAAAAADAA', CHAR 'Clara               ', CHAR 'Karr                          ', CHAR 'N', VARCHAR 'SRI LANKA', NULL),
    (CHAR 'AAAAAAAAAAAAADCA', CHAR 'Molly               ', CHAR 'Werner                        ', CHAR 'Y', VARCHAR 'BELARUS', NULL),
    (CHAR 'AAAAAAAAAAAAAECA', CHAR 'Rebecca             ', CHAR 'Holder                        ', CHAR 'Y', VARCHAR 'AMERICAN SAMOA', NULL),
    (CHAR 'AAAAAAAAAAAAAFCA', CHAR 'Richard             ', CHAR 'Ford                          ', CHAR 'Y', VARCHAR 'LESOTHO', NULL),
    (CHAR 'AAAAAAAAAAAAAFDA', CHAR 'Lovie               ', CHAR 'Cummings                      ', CHAR 'Y', VARCHAR 'MALTA', NULL),
    (CHAR 'AAAAAAAAAAAAAGDA', CHAR 'Charles             ', CHAR 'Brown                         ', CHAR 'N', VARCHAR 'SAN MARINO', NULL),
    (CHAR 'AAAAAAAAAAAAAHDA', CHAR 'Margaret            ', CHAR 'Moreland                      ', CHAR 'N', VARCHAR 'ISLE OF MAN', NULL),
    (CHAR 'AAAAAAAAAAAAAIBA', CHAR 'Ronald              ', CHAR 'Baker                         ', CHAR 'Y', VARCHAR 'MOLDOVA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAAAAAICA', CHAR 'Irene               ', NULL, CHAR 'N', NULL, NULL),
    (CHAR 'AAAAAAAAAAAAAJAA', CHAR 'Arthur              ', CHAR 'Blair                         ', CHAR 'Y', VARCHAR 'SAN MARINO', NULL),
    (CHAR 'AAAAAAAAAAAAAJBA', CHAR 'Cynthia             ', NULL, CHAR 'Y', NULL, NULL),
    (CHAR 'AAAAAAAAAAAAAJCA', CHAR 'Marian              ', CHAR 'Sweet                         ', CHAR 'Y', VARCHAR 'EGYPT', NULL),
    (CHAR 'AAAAAAAAAAAAAJDA', CHAR 'Timothy             ', CHAR 'Simpson                       ', CHAR 'Y', VARCHAR 'KENYA', NULL),
    (CHAR 'AAAAAAAAAAAAAKCA', CHAR 'Herbert             ', CHAR 'Kemp                          ', CHAR 'N', VARCHAR 'IRELAND', NULL),
    (CHAR 'AAAAAAAAAAAAALBA', CHAR 'Charles             ', CHAR 'Dodds                         ', CHAR 'N', VARCHAR 'MADAGASCAR', NULL),
    (CHAR 'AAAAAAAAAAAAAMAA', CHAR 'John                ', CHAR 'Lord                          ', CHAR 'N', VARCHAR 'ARGENTINA', NULL),
    (CHAR 'AAAAAAAAAAAAANAA', CHAR 'Olga                ', CHAR 'Stanley                       ', CHAR 'N', VARCHAR 'GREECE', NULL),
    (CHAR 'AAAAAAAAAAAAAPBA', CHAR 'Gerald              ', CHAR 'Smith                         ', CHAR 'Y', VARCHAR 'VENEZUELA', NULL),
    (CHAR 'AAAAAAAAAAAABAAA', CHAR 'Robert              ', CHAR 'Sanders                       ', CHAR 'N', VARCHAR 'AUSTRALIA', NULL),
    (CHAR 'AAAAAAAAAAAABABA', CHAR 'Loren               ', CHAR 'Coleman                       ', CHAR 'Y', VARCHAR 'ANGUILLA', NULL),
    (CHAR 'AAAAAAAAAAAABCDA', CHAR 'Matthew             ', CHAR 'Simon                         ', CHAR 'N', VARCHAR 'MONACO', NULL),
    (CHAR 'AAAAAAAAAAAABDAA', CHAR 'Margaret            ', CHAR 'Mckinney                      ', CHAR 'Y', VARCHAR 'HONDURAS', NULL),
    (CHAR 'AAAAAAAAAAAABEBA', CHAR 'Hermila             ', CHAR 'Hale                          ', CHAR 'Y', VARCHAR 'MALAWI', NULL),
    (CHAR 'AAAAAAAAAAAABEDA', CHAR 'Eloise              ', CHAR 'Collins                       ', CHAR 'N', VARCHAR 'COMOROS', NULL),
    (CHAR 'AAAAAAAAAAAABFCA', CHAR 'Santos              ', CHAR 'Webb                          ', CHAR 'Y', VARCHAR 'GUINEA', NULL),
    (CHAR 'AAAAAAAAAAAABGBA', CHAR 'Julia               ', CHAR 'Ashworth                      ', CHAR 'Y', VARCHAR 'INDONESIA', NULL),
    (CHAR 'AAAAAAAAAAAABGDA', CHAR 'Mildred             ', CHAR 'Ruiz                          ', CHAR 'N', VARCHAR 'SLOVENIA', NULL),
    (CHAR 'AAAAAAAAAAAABHAA', CHAR 'Irene               ', CHAR 'Cromwell                      ', CHAR 'N', VARCHAR 'SENEGAL', NULL),
    (CHAR 'AAAAAAAAAAAABJBA', CHAR 'Christina           ', CHAR 'Landry                        ', CHAR 'Y', VARCHAR 'PANAMA', NULL),
    (CHAR 'AAAAAAAAAAAABKCA', CHAR 'Sharon              ', CHAR 'Boles                         ', CHAR 'N', VARCHAR 'NEPAL', NULL),
    (CHAR 'AAAAAAAAAAAABKDA', CHAR 'Margaret            ', CHAR 'Hart                          ', CHAR 'Y', VARCHAR 'SAUDI ARABIA', NULL),
    (CHAR 'AAAAAAAAAAAABLAA', CHAR 'Pauline             ', CHAR 'Green                         ', CHAR 'N', VARCHAR 'PORTUGAL', NULL),
    (CHAR 'AAAAAAAAAAAABLBA', CHAR 'Vicky               ', CHAR 'Patrick                       ', CHAR 'Y', VARCHAR 'SENEGAL', NULL),
    (CHAR 'AAAAAAAAAAAABMDA', CHAR 'Susan               ', CHAR 'Weiss                         ', CHAR 'Y', VARCHAR 'KENYA', NULL),
    (CHAR 'AAAAAAAAAAAABNAA', CHAR 'Derek               ', CHAR 'Zuniga                        ', CHAR 'N', VARCHAR 'SOUTH AFRICA', NULL),
    (CHAR 'AAAAAAAAAAAABOAA', CHAR 'Betty               ', CHAR 'Webster                       ', CHAR 'N', VARCHAR 'JERSEY', NULL),
    (CHAR 'AAAAAAAAAAAACACA', CHAR 'Eva                 ', CHAR 'Thomas                        ', CHAR 'N', VARCHAR 'SOLOMON ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAAACBDA', CHAR 'Julie               ', CHAR 'Jackson                       ', CHAR 'N', VARCHAR 'BRUNEI DARUSSALAM', NULL),
    (CHAR 'AAAAAAAAAAAACCCA', CHAR 'Dorothy             ', CHAR 'Walker                        ', CHAR 'Y', VARCHAR 'GUYANA', NULL),
    (CHAR 'AAAAAAAAAAAACEAA', CHAR 'Timothy             ', CHAR 'Keeney                        ', CHAR 'N', NULL, NULL),
    (CHAR 'AAAAAAAAAAAACECA', CHAR 'Travis              ', CHAR 'Hunt                          ', CHAR 'N', VARCHAR 'HUNGARY', NULL),
    (CHAR 'AAAAAAAAAAAACFAA', CHAR 'Barb                ', CHAR 'Hernandez                     ', CHAR 'N', VARCHAR 'GUAM', NULL),
    (CHAR 'AAAAAAAAAAAACFDA', CHAR 'Rebecca             ', CHAR 'Barton                        ', CHAR 'Y', VARCHAR 'MAURITANIA', NULL),
    (CHAR 'AAAAAAAAAAAACGAA', CHAR 'Ruby                ', CHAR 'Dyer                          ', CHAR 'Y', VARCHAR 'ISLE OF MAN', NULL),
    (CHAR 'AAAAAAAAAAAACGCA', CHAR 'Ivan                ', CHAR 'Hearn                         ', CHAR 'Y', VARCHAR 'SOMALIA', NULL),
    (CHAR 'AAAAAAAAAAAACHAA', CHAR 'Dorothy             ', CHAR 'Irvine                        ', CHAR 'N', VARCHAR 'GUYANA', NULL),
    (CHAR 'AAAAAAAAAAAACHDA', CHAR 'Jim                 ', CHAR 'Alford                        ', CHAR 'N', VARCHAR 'RWANDA', NULL),
    (CHAR 'AAAAAAAAAAAACIAA', CHAR 'Deborah             ', CHAR 'Johnston                      ', CHAR 'Y', VARCHAR 'SAN MARINO', NULL),
    (CHAR 'AAAAAAAAAAAACICA', CHAR 'Jon                 ', CHAR 'Martinez                      ', CHAR 'Y', VARCHAR 'BURUNDI', NULL),
    (CHAR 'AAAAAAAAAAAACIDA', CHAR 'Jessica             ', CHAR 'Dotson                        ', CHAR 'N', VARCHAR 'LATVIA', NULL),
    (CHAR 'AAAAAAAAAAAACJAA', CHAR 'Jason               ', CHAR 'Calloway                      ', CHAR 'N', VARCHAR 'AUSTRIA', NULL),
    (CHAR 'AAAAAAAAAAAACJBA', CHAR 'Anthony             ', CHAR 'Parker                        ', CHAR 'Y', VARCHAR 'BANGLADESH', NULL),
    (CHAR 'AAAAAAAAAAAACKCA', CHAR 'Rayford             ', CHAR 'Rodriguez                     ', CHAR 'Y', VARCHAR 'BOUVET ISLAND', NULL),
    (CHAR 'AAAAAAAAAAAACLCA', CHAR 'Joann               ', CHAR 'Reyes                         ', CHAR 'Y', VARCHAR 'ICELAND', NULL),
    (CHAR 'AAAAAAAAAAAACMAA', CHAR 'Clyde               ', CHAR 'Meyers                        ', CHAR 'Y', VARCHAR 'ERITREA', NULL),
    (CHAR 'AAAAAAAAAAAACNCA', CHAR 'Georgie             ', CHAR 'Rice                          ', CHAR 'Y', VARCHAR 'GEORGIA', NULL),
    (CHAR 'AAAAAAAAAAAADAAA', CHAR 'Kathryn             ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'BENIN', NULL),
    (CHAR 'AAAAAAAAAAAADACA', CHAR 'Brian               ', CHAR 'Moore                         ', CHAR 'Y', VARCHAR 'SWAZILAND', NULL),
    (CHAR 'AAAAAAAAAAAADADA', CHAR 'John                ', CHAR 'Wright                        ', CHAR 'N', VARCHAR 'GEORGIA', NULL),
    (CHAR 'AAAAAAAAAAAADBAA', CHAR 'Stanley             ', CHAR 'Meador                        ', CHAR 'N', VARCHAR 'BERMUDA', NULL),
    (CHAR 'AAAAAAAAAAAADCAA', CHAR 'Donald              ', CHAR 'Kemp                          ', CHAR 'N', VARCHAR 'LIBERIA', NULL),
    (CHAR 'AAAAAAAAAAAADCBA', CHAR 'Thomas              ', CHAR 'Mckenzie                      ', CHAR 'Y', VARCHAR 'LIECHTENSTEIN', NULL),
    (CHAR 'AAAAAAAAAAAADDDA', CHAR 'Diane               ', CHAR 'Jimenez                       ', CHAR 'N', VARCHAR 'MALAYSIA', NULL),
    (CHAR 'AAAAAAAAAAAADEBA', CHAR 'Zula                ', CHAR 'Robinette                     ', CHAR 'Y', VARCHAR 'MACAO', NULL),
    (CHAR 'AAAAAAAAAAAADFAA', CHAR 'Julia               ', CHAR 'Mathews                       ', CHAR 'Y', VARCHAR 'MONTENEGRO', NULL),
    (CHAR 'AAAAAAAAAAAADFBA', CHAR 'James               ', CHAR 'Ward                          ', CHAR 'N', VARCHAR 'BELGIUM', NULL),
    (CHAR 'AAAAAAAAAAAADFDA', CHAR 'Tiffany             ', CHAR 'Hamilton                      ', CHAR 'N', VARCHAR 'FRANCE', NULL),
    (CHAR 'AAAAAAAAAAAADGAA', CHAR 'Anthony             ', CHAR 'Snow                          ', CHAR 'Y', VARCHAR 'NIUE', NULL),
    (CHAR 'AAAAAAAAAAAADGCA', CHAR 'Brenda              ', CHAR 'Booth                         ', CHAR 'N', VARCHAR 'BHUTAN', NULL),
    (CHAR 'AAAAAAAAAAAADHCA', CHAR 'Anna                ', CHAR 'Pelletier                     ', CHAR 'Y', VARCHAR 'PUERTO RICO', NULL),
    (CHAR 'AAAAAAAAAAAADHDA', CHAR 'Valerie             ', CHAR 'Peck                          ', CHAR 'N', VARCHAR 'MALDIVES', NULL),
    (CHAR 'AAAAAAAAAAAADIBA', CHAR 'Melvin              ', CHAR 'Gardner                       ', CHAR 'Y', VARCHAR 'BANGLADESH', NULL),
    (CHAR 'AAAAAAAAAAAADJCA', CHAR 'Raul                ', CHAR 'Merrill                       ', CHAR 'Y', VARCHAR 'FIJI', NULL),
    (CHAR 'AAAAAAAAAAAADJDA', CHAR 'Grace               ', CHAR 'Reeves                        ', CHAR 'N', VARCHAR 'IRELAND', NULL),
    (CHAR 'AAAAAAAAAAAADKAA', CHAR 'Leonard             ', CHAR 'Wilson                        ', CHAR 'N', VARCHAR 'ROMANIA', NULL),
    (CHAR 'AAAAAAAAAAAADKCA', CHAR 'Debra               ', CHAR 'Renfro                        ', CHAR 'Y', VARCHAR 'URUGUAY', NULL),
    (CHAR 'AAAAAAAAAAAADMAA', CHAR 'Michael             ', CHAR 'Leslie                        ', CHAR 'Y', VARCHAR 'ARGENTINA', NULL),
    (CHAR 'AAAAAAAAAAAADMBA', CHAR 'Melissa             ', CHAR 'Crews                         ', CHAR 'N', VARCHAR 'ARMENIA', NULL),
    (CHAR 'AAAAAAAAAAAADNAA', CHAR 'John                ', CHAR 'Miller                        ', CHAR 'N', VARCHAR 'NEPAL', NULL),
    (CHAR 'AAAAAAAAAAAADNCA', CHAR 'Norman              ', CHAR 'Dailey                        ', CHAR 'Y', VARCHAR 'GREECE', NULL),
    (CHAR 'AAAAAAAAAAAADNDA', CHAR 'Rebecca             ', CHAR 'Taber                         ', CHAR 'N', VARCHAR 'TUVALU', NULL),
    (CHAR 'AAAAAAAAAAAADOCA', CHAR 'David               ', CHAR 'Wilcox                        ', CHAR 'N', VARCHAR 'LIBERIA', NULL),
    (CHAR 'AAAAAAAAAAAADPCA', CHAR 'Gerald              ', NULL, CHAR 'Y', VARCHAR 'CHRISTMAS ISLAND', NULL),
    (CHAR 'AAAAAAAAAAAAEBCA', CHAR 'Alexander           ', CHAR 'Ramirez                       ', CHAR 'Y', VARCHAR 'BELARUS', NULL),
    (CHAR 'AAAAAAAAAAAAEBDA', CHAR 'Betty               ', CHAR 'Robbins                       ', CHAR 'N', VARCHAR 'TURKMENISTAN', NULL),
    (CHAR 'AAAAAAAAAAAAECCA', CHAR 'Stephen             ', CHAR 'Mahoney                       ', CHAR 'Y', VARCHAR 'UNITED STATES', NULL),
    (CHAR 'AAAAAAAAAAAAEDDA', CHAR 'Shanon              ', CHAR 'Jones                         ', CHAR 'Y', VARCHAR 'URUGUAY', NULL),
    (CHAR 'AAAAAAAAAAAAEFBA', CHAR 'Tabitha             ', CHAR 'Thomas                        ', CHAR 'Y', VARCHAR 'PORTUGAL', NULL),
    (CHAR 'AAAAAAAAAAAAEFCA', CHAR 'Ignacio             ', CHAR 'Bishop                        ', CHAR 'Y', VARCHAR 'HUNGARY', NULL),
    (CHAR 'AAAAAAAAAAAAEGAA', CHAR 'Forrest             ', CHAR 'Johnson                       ', CHAR 'Y', VARCHAR 'MACAO', NULL),
    (CHAR 'AAAAAAAAAAAAEGDA', CHAR 'Frank               ', CHAR 'Gonzalez                      ', CHAR 'Y', VARCHAR 'BOUVET ISLAND', NULL),
    (CHAR 'AAAAAAAAAAAAEHBA', CHAR 'Catherine           ', CHAR 'Lear                          ', CHAR 'Y', VARCHAR 'AMERICAN SAMOA', NULL),
    (CHAR 'AAAAAAAAAAAAEHCA', CHAR 'Olga                ', CHAR 'Mcghee                        ', CHAR 'Y', VARCHAR 'BELARUS', NULL),
    (CHAR 'AAAAAAAAAAAAEHDA', CHAR 'Gerald              ', CHAR 'Blair                         ', CHAR 'N', VARCHAR 'CHILE', NULL),
    (CHAR 'AAAAAAAAAAAAEIBA', CHAR 'Brenda              ', CHAR 'Hatfield                      ', CHAR 'Y', VARCHAR 'ECUADOR', NULL),
    (CHAR 'AAAAAAAAAAAAEJDA', CHAR 'Peggy               ', CHAR 'Gordon                        ', CHAR 'N', VARCHAR 'SAMOA', NULL),
    (CHAR 'AAAAAAAAAAAAEKAA', CHAR 'Charlene            ', CHAR 'Patrick                       ', CHAR 'Y', VARCHAR 'LESOTHO', NULL)
)
