SELECT *
FROM
(
  VALUES
    (CHAR 'ableesebarcallyn stable                           ', CHAR 'brandcorp #3                                      ', CHAR 'pendants                                          ', CHAR 'Jewelry                                           ', DOUBLE '463.04'),
    (CHAR 'ableesebarcallyn stable                           ', CHAR 'brandcorp #3                                      ', CHAR 'pendants                                          ', NULL, DOUBLE '463.04'),
    (CHAR 'ableesebarcallyn stable                           ', CHAR 'brandcorp #3                                      ', NULL, NULL, DOUBLE '463.04'),
    (CHAR 'ableesebarcallyn stable                           ', NULL, NULL, NULL, DOUBLE '463.04'),
    (CHAR 'ationn stationpriantipri                          ', CHAR 'edu packedu pack #2                               ', CHAR 'athletic                                          ', CHAR 'Shoes                                             ', DOUBLE '466.2772435897436'),
    (CHAR 'ationn stationpriantipri                          ', CHAR 'edu packedu pack #2                               ', CHAR 'athletic                                          ', NULL, DOUBLE '466.2772435897436'),
    (CHAR 'ationn stationpriantipri                          ', CHAR 'edu packedu pack #2                               ', NULL, NULL, DOUBLE '466.2772435897436'),
    (CHAR 'ationn stationpriantipri                          ', NULL, NULL, NULL, DOUBLE '466.2772435897436'),
    (CHAR 'ableationableantipriought                         ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', CHAR 'Children                                          ', DOUBLE '467.195775792039'),
    (CHAR 'ableationableantipriought                         ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', NULL, DOUBLE '467.195775792039'),
    (CHAR 'ableationableantipriought                         ', CHAR 'edu packexporti #1                                ', NULL, NULL, DOUBLE '467.195775792039'),
    (CHAR 'ableationableantipriought                         ', NULL, NULL, NULL, DOUBLE '467.195775792039'),
    (CHAR 'callyoughtoughtbarn stpri                         ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', CHAR 'Children                                          ', DOUBLE '467.26434923201293'),
    (CHAR 'callyoughtoughtbarn stpri                         ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', NULL, DOUBLE '467.26434923201293'),
    (CHAR 'callyoughtoughtbarn stpri                         ', CHAR 'edu packexporti #1                                ', NULL, NULL, DOUBLE '467.26434923201293'),
    (CHAR 'callyoughtoughtbarn stpri                         ', NULL, NULL, NULL, DOUBLE '467.26434923201293'),
    (CHAR 'ableablen steingeing                              ', CHAR 'brandmaxi #3                                      ', CHAR 'reference                                         ', CHAR 'Books                                             ', DOUBLE '467.31375703942075'),
    (CHAR 'ableablen steingeing                              ', CHAR 'brandmaxi #3                                      ', CHAR 'reference                                         ', NULL, DOUBLE '467.31375703942075'),
    (CHAR 'ableablen steingeing                              ', CHAR 'brandmaxi #3                                      ', NULL, NULL, DOUBLE '467.31375703942075'),
    (CHAR 'ableablen steingeing                              ', NULL, NULL, NULL, DOUBLE '467.31375703942075'),
    (CHAR 'antieingoughtn stationable                        ', CHAR 'amalgexporti #2                                   ', CHAR 'newborn                                           ', CHAR 'Children                                          ', DOUBLE '467.56107491856676'),
    (CHAR 'antieingoughtn stationable                        ', CHAR 'amalgexporti #2                                   ', CHAR 'newborn                                           ', NULL, DOUBLE '467.56107491856676'),
    (CHAR 'antieingoughtn stationable                        ', CHAR 'amalgexporti #2                                   ', NULL, NULL, DOUBLE '467.56107491856676'),
    (CHAR 'antieingoughtn stationable                        ', NULL, NULL, NULL, DOUBLE '467.56107491856676'),
    (CHAR 'callyesebarantianti                               ', CHAR 'importounivamalg #3                               ', CHAR 'home repair                                       ', CHAR 'Books                                             ', DOUBLE '467.57269789983843'),
    (CHAR 'callyesebarantianti                               ', CHAR 'importounivamalg #3                               ', CHAR 'home repair                                       ', NULL, DOUBLE '467.57269789983843'),
    (CHAR 'callyesebarantianti                               ', CHAR 'importounivamalg #3                               ', NULL, NULL, DOUBLE '467.57269789983843'),
    (CHAR 'callyesebarantianti                               ', NULL, NULL, NULL, DOUBLE '467.57269789983843'),
    (CHAR 'n stoughtn stn stationpri                         ', CHAR 'univnameless #10                                  ', CHAR 'flatware                                          ', CHAR 'Home                                              ', DOUBLE '467.77295081967213'),
    (CHAR 'n stoughtn stn stationpri                         ', CHAR 'univnameless #10                                  ', CHAR 'flatware                                          ', NULL, DOUBLE '467.77295081967213'),
    (CHAR 'n stoughtn stn stationpri                         ', CHAR 'univnameless #10                                  ', NULL, NULL, DOUBLE '467.77295081967213'),
    (CHAR 'n stoughtn stn stationpri                         ', NULL, NULL, NULL, DOUBLE '467.77295081967213'),
    (CHAR 'priantiableeingbarable                            ', CHAR 'exportimaxi #6                                    ', CHAR 'computers                                         ', CHAR 'Books                                             ', DOUBLE '467.9377526273242'),
    (CHAR 'priantiableeingbarable                            ', CHAR 'exportimaxi #6                                    ', CHAR 'computers                                         ', NULL, DOUBLE '467.9377526273242'),
    (CHAR 'priantiableeingbarable                            ', CHAR 'exportimaxi #6                                    ', NULL, NULL, DOUBLE '467.9377526273242'),
    (CHAR 'priantiableeingbarable                            ', NULL, NULL, NULL, DOUBLE '467.9377526273242'),
    (CHAR 'ationableationpripri                              ', CHAR 'corpcorp #8                                       ', CHAR 'rings                                             ', CHAR 'Jewelry                                           ', DOUBLE '468.1307879772543'),
    (CHAR 'ationableationpripri                              ', CHAR 'corpcorp #8                                       ', CHAR 'rings                                             ', NULL, DOUBLE '468.1307879772543'),
    (CHAR 'ationableationpripri                              ', CHAR 'corpcorp #8                                       ', NULL, NULL, DOUBLE '468.1307879772543'),
    (CHAR 'ationableationpripri                              ', NULL, NULL, NULL, DOUBLE '468.1307879772543'),
    (CHAR 'oughtprieseationeingpri                           ', CHAR 'corpcorp #8                                       ', CHAR 'rings                                             ', CHAR 'Jewelry                                           ', DOUBLE '468.2033762057878'),
    (CHAR 'oughtprieseationeingpri                           ', CHAR 'corpcorp #8                                       ', CHAR 'rings                                             ', NULL, DOUBLE '468.2033762057878'),
    (CHAR 'oughtprieseationeingpri                           ', CHAR 'corpcorp #8                                       ', NULL, NULL, DOUBLE '468.2033762057878'),
    (CHAR 'oughtprieseationeingpri                           ', NULL, NULL, NULL, DOUBLE '468.2033762057878'),
    (CHAR 'eseoughtbarcallybarpri                            ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '468.605497170574'),
    (CHAR 'eseoughtbarcallybarpri                            ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', NULL, DOUBLE '468.605497170574'),
    (CHAR 'eseoughtbarcallybarpri                            ', CHAR 'importoscholar #1                                 ', NULL, NULL, DOUBLE '468.605497170574'),
    (CHAR 'eseoughtbarcallybarpri                            ', NULL, NULL, NULL, DOUBLE '468.605497170574'),
    (CHAR 'priationantipriesepri                             ', CHAR 'exportiedu pack #2                                ', CHAR 'kids                                              ', CHAR 'Shoes                                             ', DOUBLE '468.79672131147544'),
    (CHAR 'priationantipriesepri                             ', CHAR 'exportiedu pack #2                                ', CHAR 'kids                                              ', NULL, DOUBLE '468.79672131147544'),
    (CHAR 'priationantipriesepri                             ', CHAR 'exportiedu pack #2                                ', NULL, NULL, DOUBLE '468.79672131147544'),
    (CHAR 'priationantipriesepri                             ', NULL, NULL, NULL, DOUBLE '468.79672131147544'),
    (CHAR 'eseeseoughtoughtpriought                          ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', CHAR 'Children                                          ', DOUBLE '468.9443561208267'),
    (CHAR 'eseeseoughtoughtpriought                          ', CHAR 'edu packexporti #1                                ', CHAR 'school-uniforms                                   ', NULL, DOUBLE '468.9443561208267'),
    (CHAR 'eseeseoughtoughtpriought                          ', CHAR 'edu packexporti #1                                ', NULL, NULL, DOUBLE '468.9443561208267'),
    (CHAR 'eseeseoughtoughtpriought                          ', NULL, NULL, NULL, DOUBLE '468.9443561208267'),
    (CHAR 'pripricallyationcally                             ', CHAR 'exportiamalg #2                                   ', CHAR 'maternity                                         ', CHAR 'Women                                             ', DOUBLE '469.0547504025765'),
    (CHAR 'pripricallyationcally                             ', CHAR 'exportiamalg #2                                   ', CHAR 'maternity                                         ', NULL, DOUBLE '469.0547504025765'),
    (CHAR 'pripricallyationcally                             ', CHAR 'exportiamalg #2                                   ', NULL, NULL, DOUBLE '469.0547504025765'),
    (CHAR 'pripricallyationcally                             ', NULL, NULL, NULL, DOUBLE '469.0547504025765'),
    (CHAR 'ationbaroughtationn stable                        ', CHAR 'importoamalg #2                                   ', CHAR 'fragrances                                        ', CHAR 'Women                                             ', DOUBLE '469.3266129032258'),
    (CHAR 'ationbaroughtationn stable                        ', CHAR 'importoamalg #2                                   ', CHAR 'fragrances                                        ', NULL, DOUBLE '469.3266129032258'),
    (CHAR 'ationbaroughtationn stable                        ', CHAR 'importoamalg #2                                   ', NULL, NULL, DOUBLE '469.3266129032258'),
    (CHAR 'ationbaroughtationn stable                        ', NULL, NULL, NULL, DOUBLE '469.3266129032258'),
    (CHAR 'n stationcallyantieseought                        ', CHAR 'scholarunivamalg #12                              ', CHAR 'fiction                                           ', CHAR 'Books                                             ', DOUBLE '469.3541835905768'),
    (CHAR 'n stationcallyantieseought                        ', CHAR 'scholarunivamalg #12                              ', CHAR 'fiction                                           ', NULL, DOUBLE '469.3541835905768'),
    (CHAR 'n stationcallyantieseought                        ', CHAR 'scholarunivamalg #12                              ', NULL, NULL, DOUBLE '469.3541835905768'),
    (CHAR 'n stationcallyantieseought                        ', NULL, NULL, NULL, DOUBLE '469.3541835905768'),
    (CHAR 'callybarationn stesepri                           ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '469.36739659367396'),
    (CHAR 'callybarationn stesepri                           ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', NULL, DOUBLE '469.36739659367396'),
    (CHAR 'callybarationn stesepri                           ', CHAR 'importoscholar #1                                 ', NULL, NULL, DOUBLE '469.36739659367396'),
    (CHAR 'callybarationn stesepri                           ', NULL, NULL, NULL, DOUBLE '469.36739659367396'),
    (CHAR 'barantiationoughtesepri                           ', CHAR 'importoedu pack #1                                ', CHAR 'mens                                              ', CHAR 'Shoes                                             ', DOUBLE '469.61544715447155'),
    (CHAR 'barantiationoughtesepri                           ', CHAR 'importoedu pack #1                                ', CHAR 'mens                                              ', NULL, DOUBLE '469.61544715447155'),
    (CHAR 'barantiationoughtesepri                           ', CHAR 'importoedu pack #1                                ', NULL, NULL, DOUBLE '469.61544715447155'),
    (CHAR 'barantiationoughtesepri                           ', NULL, NULL, NULL, DOUBLE '469.61544715447155'),
    (CHAR 'antiantipriableation                              ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', CHAR 'Shoes                                             ', DOUBLE '469.6197874080131'),
    (CHAR 'antiantipriableation                              ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', NULL, DOUBLE '469.6197874080131'),
    (CHAR 'antiantipriableation                              ', CHAR 'amalgedu pack #2                                  ', NULL, NULL, DOUBLE '469.6197874080131'),
    (CHAR 'antiantipriableation                              ', NULL, NULL, NULL, DOUBLE '469.6197874080131'),
    (CHAR 'oughtcallyationationable                          ', CHAR 'edu packamalg #2                                  ', CHAR 'swimwear                                          ', CHAR 'Women                                             ', DOUBLE '469.963963963964'),
    (CHAR 'oughtcallyationationable                          ', CHAR 'edu packamalg #2                                  ', CHAR 'swimwear                                          ', NULL, DOUBLE '469.963963963964'),
    (CHAR 'oughtcallyationationable                          ', CHAR 'edu packamalg #2                                  ', NULL, NULL, DOUBLE '469.963963963964'),
    (CHAR 'oughtcallyationationable                          ', NULL, NULL, NULL, DOUBLE '469.963963963964'),
    (CHAR 'ableantiantioughtpriought                         ', CHAR 'amalgbrand #3                                     ', CHAR 'bathroom                                          ', CHAR 'Home                                              ', DOUBLE '469.9759807846277'),
    (CHAR 'ableantiantioughtpriought                         ', CHAR 'amalgbrand #3                                     ', CHAR 'bathroom                                          ', NULL, DOUBLE '469.9759807846277'),
    (CHAR 'ableantiantioughtpriought                         ', CHAR 'amalgbrand #3                                     ', NULL, NULL, DOUBLE '469.9759807846277'),
    (CHAR 'ableantiantioughtpriought                         ', NULL, NULL, NULL, DOUBLE '469.9759807846277'),
    (CHAR 'antin stableantiablepri                           ', CHAR 'exportischolar #2                                 ', CHAR 'pop                                               ', CHAR 'Music                                             ', DOUBLE '470.07487922705315'),
    (CHAR 'antin stableantiablepri                           ', CHAR 'exportischolar #2                                 ', CHAR 'pop                                               ', NULL, DOUBLE '470.07487922705315'),
    (CHAR 'antin stableantiablepri                           ', CHAR 'exportischolar #2                                 ', NULL, NULL, DOUBLE '470.07487922705315'),
    (CHAR 'antin stableantiablepri                           ', NULL, NULL, NULL, DOUBLE '470.07487922705315'),
    (CHAR 'prin stn stablebarable                            ', CHAR 'brandcorp #2                                      ', CHAR 'pendants                                          ', CHAR 'Jewelry                                           ', DOUBLE '470.2435483870968'),
    (CHAR 'prin stn stablebarable                            ', CHAR 'brandcorp #2                                      ', CHAR 'pendants                                          ', NULL, DOUBLE '470.2435483870968'),
    (CHAR 'prin stn stablebarable                            ', CHAR 'brandcorp #2                                      ', NULL, NULL, DOUBLE '470.2435483870968'),
    (CHAR 'prin stn stablebarable                            ', NULL, NULL, NULL, DOUBLE '470.2435483870968'),
    (CHAR 'eseantiablepribarpri                              ', CHAR 'exportibrand #7                                   ', CHAR 'loose stones                                      ', CHAR 'Jewelry                                           ', DOUBLE '470.26854838709676'),
    (CHAR 'eseantiablepribarpri                              ', CHAR 'exportibrand #7                                   ', CHAR 'loose stones                                      ', NULL, DOUBLE '470.26854838709676'),
    (CHAR 'eseantiablepribarpri                              ', CHAR 'exportibrand #7                                   ', NULL, NULL, DOUBLE '470.26854838709676'),
    (CHAR 'eseantiablepribarpri                              ', NULL, NULL, NULL, DOUBLE '470.26854838709676')
)
