SELECT *
FROM
(
  VALUES
    (CHAR 'Aaron                         ', CHAR 'Deborah             ', VARCHAR 'bar', DECIMAL '157455768.68'),
    (CHAR 'Aaron                         ', CHAR 'Tanya               ', VARCHAR 'able', DECIMAL '32773084.92'),
    (CHAR 'Abbott                        ', CHAR 'Cindy               ', VARCHAR 'ation', DECIMAL '20818520.00'),
    (CHAR 'Abbott                        ', CHAR 'Jennifer            ', VARCHAR 'ation', DECIMAL '114428805.12'),
    (CHAR 'Abbott                        ', CHAR 'Jon                 ', VARCHAR 'cally', DECIMAL '25057100.64'),
    (CHAR 'Abbott                        ', CHAR 'Laurie              ', VARCHAR 'cally', DECIMAL '21254479.92'),
    (CHAR 'Abbott                        ', CHAR 'Mai                 ', VARCHAR 'n st', DECIMAL '25969239.10'),
    (CHAR 'Abbott                        ', CHAR 'Regina              ', VARCHAR 'ese', DECIMAL '89732317.20'),
    (CHAR 'Abbott                        ', CHAR 'Richard             ', VARCHAR 'ese', DECIMAL '29684510.70'),
    (CHAR 'Abel                          ', CHAR 'Wilma               ', VARCHAR 'cally', DECIMAL '58800961.12'),
    (CHAR 'Abell                         ', CHAR 'Lanny               ', VARCHAR 'ese', DECIMAL '44578729.08'),
    (CHAR 'Abernathy                     ', CHAR 'Harold              ', VARCHAR 'cally', DECIMAL '4451376.60'),
    (CHAR 'Abner                         ', CHAR 'Kelsie              ', VARCHAR 'able', DECIMAL '97844646.48'),
    (CHAR 'Abraham                       ', CHAR 'Harold              ', VARCHAR 'ese', DECIMAL '239017414.23'),
    (CHAR 'Abraham                       ', CHAR 'Johnny              ', VARCHAR 'able', DECIMAL '42213999.60'),
    (CHAR 'Abraham                       ', CHAR 'Kimberly            ', VARCHAR 'cally', DECIMAL '60114575.84'),
    (CHAR 'Abraham                       ', CHAR 'Marianne            ', VARCHAR 'eing', DECIMAL '136892668.92'),
    (CHAR 'Abrams                        ', CHAR 'Eugene              ', VARCHAR 'eing', DECIMAL '46289498.28'),
    (CHAR 'Abrams                        ', CHAR 'Jamal               ', VARCHAR 'ation', DECIMAL '14401812.50'),
    (CHAR 'Abrams                        ', CHAR 'Sarita              ', VARCHAR 'ese', DECIMAL '175875145.60'),
    (CHAR 'Acevedo                       ', CHAR 'Claudia             ', VARCHAR 'ese', DECIMAL '11142686.72'),
    (CHAR 'Acevedo                       ', CHAR 'Corrina             ', VARCHAR 'able', DECIMAL '51727035.36'),
    (CHAR 'Acevedo                       ', CHAR 'Jasmine             ', VARCHAR 'n st', DECIMAL '1070803.80'),
    (CHAR 'Acker                         ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '36741503.64'),
    (CHAR 'Acker                         ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '37892987.55'),
    (CHAR 'Ackerman                      ', CHAR 'Barbara             ', VARCHAR 'able', DECIMAL '201487316.04'),
    (CHAR 'Acosta                        ', CHAR 'Alfred              ', VARCHAR 'cally', DECIMAL '1010243.52'),
    (CHAR 'Acosta                        ', CHAR 'Cathy               ', VARCHAR 'anti', DECIMAL '29794465.71'),
    (CHAR 'Acosta                        ', CHAR 'David               ', VARCHAR 'ought', DECIMAL '2010706.88'),
    (CHAR 'Acosta                        ', CHAR 'Heather             ', VARCHAR 'bar', DECIMAL '63857664.00'),
    (CHAR 'Acosta                        ', CHAR 'Jack                ', VARCHAR 'bar', DECIMAL '81249247.80'),
    (CHAR 'Acosta                        ', CHAR 'Larry               ', VARCHAR 'ation', DECIMAL '15844111.20'),
    (CHAR 'Acosta                        ', CHAR 'Rick                ', VARCHAR 'ese', DECIMAL '331545236.28'),
    (CHAR 'Acuna                         ', CHAR 'Jone                ', VARCHAR 'n st', DECIMAL '32142541.60'),
    (CHAR 'Adair                         ', CHAR 'Theodore            ', VARCHAR 'able', DECIMAL '8212181.67'),
    (CHAR 'Adair                         ', CHAR 'Wilma               ', VARCHAR 'ese', DECIMAL '187917584.40'),
    (CHAR 'Adam                          ', CHAR 'Tony                ', VARCHAR 'n st', DECIMAL '27268602.00'),
    (CHAR 'Adame                         ', CHAR 'Joanne              ', VARCHAR 'ese', DECIMAL '95861056.32'),
    (CHAR 'Adame                         ', CHAR 'Kimberly            ', VARCHAR 'cally', DECIMAL '4082396.76'),
    (CHAR 'Adams                         ', CHAR 'Angela              ', VARCHAR 'ation', DECIMAL '30751813.02'),
    (CHAR 'Adams                         ', CHAR 'Bethany             ', VARCHAR 'anti', DECIMAL '1853799.00'),
    (CHAR 'Adams                         ', CHAR 'Brian               ', VARCHAR 'able', DECIMAL '10204636.80'),
    (CHAR 'Adams                         ', CHAR 'Cynthia             ', VARCHAR 'n st', DECIMAL '16309956.42'),
    (CHAR 'Adams                         ', CHAR 'Daniel              ', VARCHAR 'ese', DECIMAL '22914888.00'),
    (CHAR 'Adams                         ', CHAR 'David               ', VARCHAR 'ought', DECIMAL '54583758.32'),
    (CHAR 'Adams                         ', CHAR 'Diane               ', VARCHAR 'n st', DECIMAL '33600595.20'),
    (CHAR 'Adams                         ', CHAR 'Dorothy             ', VARCHAR 'ation', DECIMAL '131596204.93'),
    (CHAR 'Adams                         ', CHAR 'Florence            ', VARCHAR 'eing', DECIMAL '40555176.15'),
    (CHAR 'Adams                         ', CHAR 'Garland             ', VARCHAR 'n st', DECIMAL '4105105.84'),
    (CHAR 'Adams                         ', CHAR 'Gary                ', VARCHAR 'cally', DECIMAL '7658121.90'),
    (CHAR 'Adams                         ', CHAR 'George              ', VARCHAR 'anti', DECIMAL '26479097.28'),
    (CHAR 'Adams                         ', CHAR 'Jeanette            ', VARCHAR 'cally', DECIMAL '42068007.24'),
    (CHAR 'Adams                         ', CHAR 'Jeffery             ', VARCHAR 'cally', DECIMAL '409343.22'),
    (CHAR 'Adams                         ', CHAR 'John                ', VARCHAR 'ought', DECIMAL '20466742.66'),
    (CHAR 'Adams                         ', CHAR 'Karina              ', VARCHAR 'able', DECIMAL '1717716.00'),
    (CHAR 'Adams                         ', CHAR 'Keiko               ', VARCHAR 'eing', DECIMAL '13758082.20'),
    (CHAR 'Adams                         ', CHAR 'Monica              ', VARCHAR 'ation', DECIMAL '192103312.50'),
    (CHAR 'Adams                         ', CHAR 'Ralph               ', VARCHAR 'ese', DECIMAL '18836590.50'),
    (CHAR 'Adams                         ', CHAR 'Sylvester           ', VARCHAR 'anti', DECIMAL '154698528.60'),
    (CHAR 'Adcock                        ', CHAR 'Charles             ', VARCHAR 'cally', DECIMAL '4097759.05'),
    (CHAR 'Adcock                        ', CHAR 'Richard             ', VARCHAR 'ese', DECIMAL '9799428.60'),
    (CHAR 'Adkins                        ', CHAR 'Gwen                ', VARCHAR 'able', DECIMAL '16907610.72'),
    (CHAR 'Adkins                        ', CHAR 'Robert              ', VARCHAR 'able', DECIMAL '135517104.80'),
    (CHAR 'Adler                         ', CHAR 'Ramona              ', VARCHAR 'able', DECIMAL '37881582.05'),
    (CHAR 'Agnew                         ', CHAR 'Seth                ', VARCHAR 'cally', DECIMAL '54305495.20'),
    (CHAR 'Aguilar                       ', CHAR 'Brittany            ', VARCHAR 'able', DECIMAL '66740256.00'),
    (CHAR 'Aguilar                       ', CHAR 'Jennifer            ', VARCHAR 'eing', DECIMAL '146440495.91'),
    (CHAR 'Aguilar                       ', CHAR 'Marilyn             ', VARCHAR 'ese', DECIMAL '24274906.11'),
    (CHAR 'Aguilera                      ', CHAR 'Emma                ', VARCHAR 'able', DECIMAL '47456526.88'),
    (CHAR 'Aguirre                       ', CHAR 'Wayne               ', VARCHAR 'cally', DECIMAL '5309710.90'),
    (CHAR 'Ahmed                         ', CHAR 'Helen               ', VARCHAR 'bar', DECIMAL '9906737.75'),
    (CHAR 'Akers                         ', CHAR 'William             ', VARCHAR 'able', DECIMAL '47795124.24'),
    (CHAR 'Akin                          ', CHAR 'Robert              ', VARCHAR 'anti', DECIMAL '135600620.40'),
    (CHAR 'Akin                          ', CHAR 'Ronald              ', VARCHAR 'able', DECIMAL '2850415.54'),
    (CHAR 'Akins                         ', CHAR 'Rebecca             ', VARCHAR 'bar', DECIMAL '32120765.30'),
    (CHAR 'Alaniz                        ', CHAR 'Keisha              ', VARCHAR 'ese', DECIMAL '6258435.30'),
    (CHAR 'Alaniz                        ', CHAR 'Keisha              ', VARCHAR 'n st', DECIMAL '41758544.00'),
    (CHAR 'Alaniz                        ', CHAR 'Thomas              ', VARCHAR 'n st', DECIMAL '220575968.40'),
    (CHAR 'Alaniz                        ', CHAR 'Tobias              ', VARCHAR 'ation', DECIMAL '37729205.52'),
    (CHAR 'Albert                        ', CHAR 'Jessica             ', VARCHAR 'cally', DECIMAL '52730880.84'),
    (CHAR 'Albert                        ', CHAR 'Sandra              ', VARCHAR 'n st', DECIMAL '47759532.00'),
    (CHAR 'Albert                        ', CHAR 'Steven              ', VARCHAR 'n st', DECIMAL '1222608.24'),
    (CHAR 'Albertson                     ', CHAR 'David               ', VARCHAR 'ese', DECIMAL '12656782.82'),
    (CHAR 'Albertson                     ', CHAR 'David               ', VARCHAR 'n st', DECIMAL '4107826.80'),
    (CHAR 'Albritton                     ', CHAR 'Joseph              ', VARCHAR 'able', DECIMAL '21904842.96'),
    (CHAR 'Albritton                     ', CHAR 'Ronald              ', VARCHAR 'cally', DECIMAL '40381482.24'),
    (CHAR 'Alderman                      ', CHAR 'Jeffrey             ', VARCHAR 'cally', DECIMAL '149313521.28'),
    (CHAR 'Aldrich                       ', CHAR 'Adam                ', VARCHAR 'ese', DECIMAL '7973691.39'),
    (CHAR 'Aldrich                       ', CHAR 'John                ', VARCHAR 'able', DECIMAL '2495175.48'),
    (CHAR 'Aldridge                      ', CHAR 'Johanne             ', VARCHAR 'cally', DECIMAL '33233033.52'),
    (CHAR 'Aldridge                      ', CHAR 'Nathaniel           ', VARCHAR 'bar', DECIMAL '4087203.12'),
    (CHAR 'Aldridge                      ', CHAR 'Viola               ', VARCHAR 'ese', DECIMAL '25978375.80'),
    (CHAR 'Aleman                        ', CHAR 'David               ', VARCHAR 'eing', DECIMAL '70772593.62'),
    (CHAR 'Aleman                        ', CHAR 'Forrest             ', VARCHAR 'ation', DECIMAL '34903312.50'),
    (CHAR 'Alexander                     ', CHAR 'Albert              ', VARCHAR 'ese', DECIMAL '35372064.56'),
    (CHAR 'Alexander                     ', CHAR 'Amanda              ', VARCHAR 'able', DECIMAL '30301087.44'),
    (CHAR 'Alexander                     ', CHAR 'Cheryl              ', VARCHAR 'cally', DECIMAL '10532200.80'),
    (CHAR 'Alexander                     ', CHAR 'Daniel              ', VARCHAR 'anti', DECIMAL '2566082.40'),
    (CHAR 'Alexander                     ', CHAR 'Dennis              ', VARCHAR 'n st', DECIMAL '15473326.59'),
    (CHAR 'Alexander                     ', CHAR 'Frederic            ', VARCHAR 'anti', DECIMAL '497336734.08'),
    (CHAR 'Alexander                     ', CHAR 'George              ', VARCHAR 'n st', DECIMAL '10317320.00'),
    (CHAR 'Alexander                     ', CHAR 'Gretchen            ', VARCHAR 'eing', DECIMAL '34862439.20'),
    (CHAR 'Alexander                     ', CHAR 'Helen               ', VARCHAR 'ese', DECIMAL '13805745.47'),
    (CHAR 'Alexander                     ', CHAR 'Jeanette            ', VARCHAR 'bar', DECIMAL '91511649.45'),
    (CHAR 'Alexander                     ', CHAR 'Johnny              ', VARCHAR 'eing', DECIMAL '143482736.82'),
    (CHAR 'Alexander                     ', CHAR 'Kelsey              ', VARCHAR 'able', DECIMAL '35161646.52'),
    (CHAR 'Alexander                     ', CHAR 'Kenneth             ', VARCHAR 'anti', DECIMAL '23380279.92'),
    (CHAR 'Alexander                     ', CHAR 'Mark                ', VARCHAR 'ese', DECIMAL '108312555.00'),
    (CHAR 'Alexander                     ', CHAR 'Martin              ', VARCHAR 'ation', DECIMAL '4712397.50'),
    (CHAR 'Alexander                     ', CHAR 'Michael             ', VARCHAR 'n st', DECIMAL '9208998.75'),
    (CHAR 'Alexander                     ', CHAR 'Raphael             ', VARCHAR 'anti', DECIMAL '2560769.60'),
    (CHAR 'Alexander                     ', CHAR 'Roger               ', VARCHAR 'bar', DECIMAL '6470730.63'),
    (CHAR 'Alexander                     ', CHAR 'Sandra              ', VARCHAR 'able', DECIMAL '2892555.20'),
    (CHAR 'Alexander                     ', CHAR 'Shane               ', VARCHAR 'anti', DECIMAL '780711.44'),
    (CHAR 'Alfaro                        ', CHAR 'Jerome              ', VARCHAR 'ese', DECIMAL '5696363.40'),
    (CHAR 'Alfonso                       ', CHAR 'Amanda              ', VARCHAR 'able', DECIMAL '83291225.16'),
    (CHAR 'Alford                        ', CHAR 'Alice               ', VARCHAR 'n st', DECIMAL '247946627.88'),
    (CHAR 'Alford                        ', CHAR 'Janice              ', VARCHAR 'cally', DECIMAL '6000117.12'),
    (CHAR 'Alford                        ', CHAR 'Sharon              ', VARCHAR 'able', DECIMAL '2718443.24'),
    (CHAR 'Alford                        ', CHAR 'Tara                ', VARCHAR 'able', DECIMAL '27539971.61'),
    (CHAR 'Alford                        ', NULL, VARCHAR 'ese', DECIMAL '101685852.24'),
    (CHAR 'Alicea                        ', CHAR 'Jose                ', VARCHAR 'ese', DECIMAL '9981605.10'),
    (CHAR 'Alicea                        ', CHAR 'Manuel              ', VARCHAR 'bar', DECIMAL '132510196.00'),
    (CHAR 'Alicea                        ', CHAR 'Marian              ', VARCHAR 'anti', DECIMAL '1167065.10'),
    (CHAR 'Allard                        ', CHAR 'Troy                ', VARCHAR 'able', DECIMAL '62601163.80'),
    (CHAR 'Allen                         ', CHAR 'Arlene              ', VARCHAR 'cally', DECIMAL '10228421.28'),
    (CHAR 'Allen                         ', CHAR 'Betty               ', VARCHAR 'cally', DECIMAL '4965014.56'),
    (CHAR 'Allen                         ', CHAR 'Bruce               ', VARCHAR 'n st', DECIMAL '6410835.90'),
    (CHAR 'Allen                         ', CHAR 'Caroline            ', VARCHAR 'n st', DECIMAL '27560863.20'),
    (CHAR 'Allen                         ', CHAR 'Charles             ', VARCHAR 'cally', DECIMAL '24127058.80'),
    (CHAR 'Allen                         ', CHAR 'Charlotte           ', VARCHAR 'cally', DECIMAL '4179843.20'),
    (CHAR 'Allen                         ', CHAR 'Debra               ', VARCHAR 'n st', DECIMAL '273945102.20'),
    (CHAR 'Allen                         ', CHAR 'Dorthy              ', VARCHAR 'ese', DECIMAL '67228068.60'),
    (CHAR 'Allen                         ', CHAR 'Elizabeth           ', VARCHAR 'bar', DECIMAL '408970443.42'),
    (CHAR 'Allen                         ', CHAR 'Erin                ', VARCHAR 'ation', DECIMAL '154161503.97'),
    (CHAR 'Allen                         ', CHAR 'James               ', VARCHAR 'anti', DECIMAL '50273034.10'),
    (CHAR 'Allen                         ', CHAR 'James               ', VARCHAR 'bar', DECIMAL '50019916.80'),
    (CHAR 'Allen                         ', CHAR 'James               ', VARCHAR 'n st', DECIMAL '163529091.44'),
    (CHAR 'Allen                         ', CHAR 'Jane                ', VARCHAR 'n st', DECIMAL '2040540.32'),
    (CHAR 'Allen                         ', CHAR 'Jennie              ', VARCHAR 'ation', DECIMAL '3322474.20'),
    (CHAR 'Allen                         ', CHAR 'Jennifer            ', VARCHAR 'n st', DECIMAL '9908595.40'),
    (CHAR 'Allen                         ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '23809968.00'),
    (CHAR 'Allen                         ', CHAR 'Jose                ', VARCHAR 'able', DECIMAL '9067150.04'),
    (CHAR 'Allen                         ', CHAR 'Kathleen            ', VARCHAR 'able', DECIMAL '64123734.60'),
    (CHAR 'Allen                         ', CHAR 'Kenneth             ', VARCHAR 'able', DECIMAL '4913967.30'),
    (CHAR 'Allen                         ', CHAR 'Marguerite          ', VARCHAR 'cally', DECIMAL '71939229.12'),
    (CHAR 'Allen                         ', CHAR 'Marla               ', VARCHAR 'able', DECIMAL '23532736.64'),
    (CHAR 'Allen                         ', CHAR 'Nathalie            ', VARCHAR 'cally', DECIMAL '9790482.24'),
    (CHAR 'Allen                         ', CHAR 'Owen                ', VARCHAR 'ese', DECIMAL '62928192.60'),
    (CHAR 'Allen                         ', CHAR 'Pamela              ', VARCHAR 'n st', DECIMAL '19621955.43'),
    (CHAR 'Allen                         ', CHAR 'Richard             ', VARCHAR 'bar', DECIMAL '87614004.03'),
    (CHAR 'Allen                         ', CHAR 'Richard             ', VARCHAR 'cally', DECIMAL '17265093.30'),
    (CHAR 'Allen                         ', CHAR 'Rosalee             ', VARCHAR 'able', DECIMAL '11594583.00'),
    (CHAR 'Allen                         ', CHAR 'Rusty               ', VARCHAR 'ese', DECIMAL '22781573.98'),
    (CHAR 'Allen                         ', CHAR 'Vernon              ', VARCHAR 'ation', DECIMAL '72698329.62'),
    (CHAR 'Allen                         ', CHAR 'Wilma               ', VARCHAR 'cally', DECIMAL '198003940.20'),
    (CHAR 'Alley                         ', CHAR 'Dolores             ', VARCHAR 'able', DECIMAL '7201195.48'),
    (CHAR 'Allison                       ', CHAR 'Ashley              ', VARCHAR 'n st', DECIMAL '66348485.28'),
    (CHAR 'Allison                       ', CHAR 'Claire              ', VARCHAR 'ese', DECIMAL '336184982.28'),
    (CHAR 'Allison                       ', CHAR 'Kristi              ', VARCHAR 'ation', DECIMAL '1168847.50'),
    (CHAR 'Allison                       ', CHAR 'Larry               ', VARCHAR 'bar', DECIMAL '7779881.20'),
    (CHAR 'Allred                        ', CHAR 'Mike                ', VARCHAR 'n st', DECIMAL '1065858.52'),
    (CHAR 'Almeida                       ', CHAR 'Juanita             ', VARCHAR 'bar', DECIMAL '269519392.80'),
    (CHAR 'Almond                        ', CHAR 'Ryan                ', VARCHAR 'anti', DECIMAL '27901264.14'),
    (CHAR 'Alonso                        ', CHAR 'Justin              ', VARCHAR 'anti', DECIMAL '1574913.15'),
    (CHAR 'Alonso                        ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '7104939.84'),
    (CHAR 'Alonzo                        ', CHAR 'Amanda              ', VARCHAR 'able', DECIMAL '5024472.72'),
    (CHAR 'Alonzo                        ', CHAR 'Tom                 ', VARCHAR 'able', DECIMAL '112669686.72'),
    (CHAR 'Alston                        ', CHAR 'Julianne            ', VARCHAR 'ese', DECIMAL '7385452.80'),
    (CHAR 'Alston                        ', CHAR 'Tammie              ', VARCHAR 'n st', DECIMAL '198247303.80'),
    (CHAR 'Altman                        ', CHAR 'Charlotte           ', VARCHAR 'n st', DECIMAL '33315634.40'),
    (CHAR 'Altman                        ', CHAR 'Nicole              ', VARCHAR 'cally', DECIMAL '30168871.20'),
    (CHAR 'Alvarado                      ', CHAR 'Kimberly            ', VARCHAR 'n st', DECIMAL '35830782.86'),
    (CHAR 'Alvarado                      ', CHAR 'Susan               ', VARCHAR 'cally', DECIMAL '5282780.80'),
    (CHAR 'Alvarez                       ', CHAR 'August              ', VARCHAR 'ese', DECIMAL '45627780.60'),
    (CHAR 'Alvarez                       ', CHAR 'Brandi              ', VARCHAR 'ese', DECIMAL '15655914.54'),
    (CHAR 'Alvarez                       ', CHAR 'Chris               ', VARCHAR 'anti', DECIMAL '5851385.10'),
    (CHAR 'Alvarez                       ', CHAR 'Judith              ', VARCHAR 'anti', DECIMAL '36698002.56'),
    (CHAR 'Alvarez                       ', CHAR 'Margaret            ', VARCHAR 'n st', DECIMAL '5922510.44'),
    (CHAR 'Alvarez                       ', CHAR 'Virginia            ', VARCHAR 'n st', DECIMAL '13532752.46'),
    (CHAR 'Amaral                        ', CHAR 'Leo                 ', VARCHAR 'cally', DECIMAL '52508478.00'),
    (CHAR 'Amato                         ', CHAR 'James               ', VARCHAR 'n st', DECIMAL '4107087.00'),
    (CHAR 'Ambrose                       ', CHAR 'Nadine              ', VARCHAR 'ese', DECIMAL '26319134.40'),
    (CHAR 'Ambrose                       ', CHAR 'Percy               ', VARCHAR 'bar', DECIMAL '39997652.50'),
    (CHAR 'Ambrose                       ', CHAR 'William             ', VARCHAR 'anti', DECIMAL '12121333.20'),
    (CHAR 'Ames                          ', CHAR 'Frank               ', VARCHAR 'n st', DECIMAL '20061240.32'),
    (CHAR 'Ames                          ', CHAR 'Hugh                ', VARCHAR 'n st', DECIMAL '21444115.00'),
    (CHAR 'Ames                          ', CHAR 'Lizzie              ', VARCHAR 'ese', DECIMAL '7512958.86'),
    (CHAR 'Ammons                        ', CHAR 'Helen               ', VARCHAR 'n st', DECIMAL '156736493.24'),
    (CHAR 'Ammons                        ', CHAR 'Martha              ', VARCHAR 'eing', DECIMAL '231744914.60'),
    (CHAR 'Amos                          ', CHAR 'Carlos              ', VARCHAR 'eing', DECIMAL '96784513.08'),
    (CHAR 'Anders                        ', CHAR 'Francine            ', VARCHAR 'n st', DECIMAL '6733407.78'),
    (CHAR 'Andersen                      ', CHAR 'Darrell             ', VARCHAR 'ese', DECIMAL '46767961.54'),
    (CHAR 'Andersen                      ', CHAR 'Harry               ', VARCHAR 'ation', DECIMAL '132932250.00'),
    (CHAR 'Anderson                      ', CHAR 'Alejandro           ', VARCHAR 'ese', DECIMAL '13824447.00'),
    (CHAR 'Anderson                      ', CHAR 'Alexander           ', VARCHAR 'anti', DECIMAL '5675432.40'),
    (CHAR 'Anderson                      ', CHAR 'Annamarie           ', VARCHAR 'ation', DECIMAL '21782025.00'),
    (CHAR 'Anderson                      ', CHAR 'Antonio             ', VARCHAR 'ese', DECIMAL '959467.58'),
    (CHAR 'Anderson                      ', CHAR 'Barbara             ', VARCHAR 'cally', DECIMAL '25955904.12'),
    (CHAR 'Anderson                      ', CHAR 'Barbara             ', VARCHAR 'n st', DECIMAL '511459669.36'),
    (CHAR 'Anderson                      ', CHAR 'Brandi              ', VARCHAR 'ese', DECIMAL '19365067.20'),
    (CHAR 'Anderson                      ', CHAR 'Christine           ', VARCHAR 'able', DECIMAL '3783288.40'),
    (CHAR 'Anderson                      ', CHAR 'Christine           ', VARCHAR 'ation', DECIMAL '73206730.00'),
    (CHAR 'Anderson                      ', CHAR 'Dallas              ', VARCHAR 'ese', DECIMAL '296454697.20'),
    (CHAR 'Anderson                      ', CHAR 'David               ', VARCHAR 'n st', DECIMAL '106230288.84'),
    (CHAR 'Anderson                      ', CHAR 'Donald              ', VARCHAR 'anti', DECIMAL '5427419.15'),
    (CHAR 'Anderson                      ', CHAR 'Doreen              ', VARCHAR 'n st', DECIMAL '452508.00'),
    (CHAR 'Anderson                      ', CHAR 'Elaine              ', VARCHAR 'ese', DECIMAL '3517577.70'),
    (CHAR 'Anderson                      ', CHAR 'Eleanor             ', VARCHAR 'anti', DECIMAL '10734532.50'),
    (CHAR 'Anderson                      ', CHAR 'Eloise              ', VARCHAR 'ese', DECIMAL '19704343.68'),
    (CHAR 'Anderson                      ', CHAR 'Esther              ', VARCHAR 'able', DECIMAL '6461031.13'),
    (CHAR 'Anderson                      ', CHAR 'Esther              ', VARCHAR 'ese', DECIMAL '16016967.54'),
    (CHAR 'Anderson                      ', CHAR 'Irene               ', VARCHAR 'n st', DECIMAL '153264617.58'),
    (CHAR 'Anderson                      ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '23502407.94'),
    (CHAR 'Anderson                      ', CHAR 'Juan                ', VARCHAR 'ation', DECIMAL '6992161.92'),
    (CHAR 'Anderson                      ', CHAR 'Julie               ', VARCHAR 'anti', DECIMAL '1365721.65'),
    (CHAR 'Anderson                      ', CHAR 'Julius              ', VARCHAR 'ation', DECIMAL '7050696.00'),
    (CHAR 'Anderson                      ', CHAR 'Laurie              ', VARCHAR 'eing', DECIMAL '6655466.04'),
    (CHAR 'Anderson                      ', CHAR 'Lincoln             ', VARCHAR 'bar', DECIMAL '40517536.99'),
    (CHAR 'Anderson                      ', CHAR 'Linda               ', VARCHAR 'bar', DECIMAL '56290289.58'),
    (CHAR 'Anderson                      ', CHAR 'Mark                ', VARCHAR 'bar', DECIMAL '235088497.80'),
    (CHAR 'Anderson                      ', CHAR 'Mark                ', VARCHAR 'n st', DECIMAL '22230900.93'),
    (CHAR 'Anderson                      ', CHAR 'Michael             ', VARCHAR 'cally', DECIMAL '8398581.40'),
    (CHAR 'Anderson                      ', CHAR 'Michael             ', VARCHAR 'ese', DECIMAL '179405648.00'),
    (CHAR 'Anderson                      ', CHAR 'Nathan              ', VARCHAR 'bar', DECIMAL '5091140.25'),
    (CHAR 'Anderson                      ', CHAR 'Nicole              ', VARCHAR 'cally', DECIMAL '52067452.80'),
    (CHAR 'Anderson                      ', CHAR 'Olive               ', VARCHAR 'able', DECIMAL '13512148.65'),
    (CHAR 'Anderson                      ', CHAR 'Paul                ', VARCHAR 'eing', DECIMAL '49957988.24'),
    (CHAR 'Anderson                      ', CHAR 'Peggy               ', VARCHAR 'able', DECIMAL '147610560.72'),
    (CHAR 'Anderson                      ', CHAR 'Raguel              ', VARCHAR 'able', DECIMAL '7294016.73'),
    (CHAR 'Anderson                      ', CHAR 'Raymond             ', VARCHAR 'able', DECIMAL '33718765.08'),
    (CHAR 'Anderson                      ', CHAR 'Richard             ', VARCHAR 'able', DECIMAL '113661591.00'),
    (CHAR 'Anderson                      ', CHAR 'Richard             ', VARCHAR 'ese', DECIMAL '9786488.40'),
    (CHAR 'Anderson                      ', CHAR 'Robert              ', VARCHAR 'able', DECIMAL '121298195.52'),
    (CHAR 'Anderson                      ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '23375172.60'),
    (CHAR 'Anderson                      ', CHAR 'Robert              ', VARCHAR 'n st', DECIMAL '32624437.52'),
    (CHAR 'Anderson                      ', CHAR 'Rodolfo             ', VARCHAR 'eing', DECIMAL '59880254.76'),
    (CHAR 'Anderson                      ', CHAR 'Ronnie              ', VARCHAR 'n st', DECIMAL '8619353.82'),
    (CHAR 'Anderson                      ', CHAR 'Ruth                ', VARCHAR 'ese', DECIMAL '162619479.24'),
    (CHAR 'Anderson                      ', CHAR 'Ruth                ', VARCHAR 'n st', DECIMAL '185836361.48'),
    (CHAR 'Anderson                      ', CHAR 'Sandra              ', VARCHAR 'able', DECIMAL '24266041.20'),
    (CHAR 'Anderson                      ', CHAR 'Sandra              ', VARCHAR 'cally', DECIMAL '133026234.88'),
    (CHAR 'Anderson                      ', CHAR 'Sarah               ', VARCHAR 'ese', DECIMAL '3778714.80'),
    (CHAR 'Anderson                      ', CHAR 'Shane               ', VARCHAR 'n st', DECIMAL '39144941.20'),
    (CHAR 'Anderson                      ', CHAR 'Sherry              ', VARCHAR 'able', DECIMAL '75820975.68'),
    (CHAR 'Anderson                      ', CHAR 'Sonya               ', VARCHAR 'cally', DECIMAL '3907865.00'),
    (CHAR 'Anderson                      ', CHAR 'Suzanne             ', VARCHAR 'able', DECIMAL '107765207.55'),
    (CHAR 'Anderson                      ', CHAR 'Tara                ', VARCHAR 'bar', DECIMAL '36057130.20'),
    (CHAR 'Anderson                      ', CHAR 'Thomas              ', VARCHAR 'ese', DECIMAL '11650852.08'),
    (CHAR 'Anderson                      ', CHAR 'Virginia            ', VARCHAR 'n st', DECIMAL '23888159.10'),
    (CHAR 'Anderson                      ', CHAR 'William             ', VARCHAR 'cally', DECIMAL '1755436.32'),
    (CHAR 'Andrade                       ', CHAR 'Gregory             ', VARCHAR 'able', DECIMAL '420862.20'),
    (CHAR 'Andrade                       ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '14936762.61'),
    (CHAR 'Andrews                       ', CHAR 'Cynthia             ', VARCHAR 'ese', DECIMAL '14221896.00'),
    (CHAR 'Andrews                       ', CHAR 'George              ', VARCHAR 'ation', DECIMAL '84486704.28'),
    (CHAR 'Andrews                       ', CHAR 'Michael             ', VARCHAR 'cally', DECIMAL '292126396.32'),
    (CHAR 'Angel                         ', CHAR 'Becky               ', VARCHAR 'able', DECIMAL '37412537.61'),
    (CHAR 'Anglin                        ', CHAR 'Carolyn             ', VARCHAR 'ought', DECIMAL '680086.68'),
    (CHAR 'Anthony                       ', CHAR 'Daniel              ', VARCHAR 'n st', DECIMAL '200601236.22'),
    (CHAR 'Anthony                       ', CHAR 'John                ', VARCHAR 'n st', DECIMAL '234967042.50'),
    (CHAR 'Anthony                       ', CHAR 'Marlys              ', VARCHAR 'n st', DECIMAL '31891629.76'),
    (CHAR 'Anthony                       ', CHAR 'Nathan              ', VARCHAR 'anti', DECIMAL '22407986.25'),
    (CHAR 'Anthony                       ', CHAR 'Richard             ', VARCHAR 'bar', DECIMAL '21569102.10'),
    (CHAR 'Anthony                       ', CHAR 'William             ', VARCHAR 'able', DECIMAL '21387958.20'),
    (CHAR 'Antoine                       ', CHAR 'Jordan              ', VARCHAR 'bar', DECIMAL '167886205.50'),
    (CHAR 'Appel                         ', CHAR 'John                ', VARCHAR 'bar', DECIMAL '32644827.95'),
    (CHAR 'Applegate                     ', CHAR 'Virginia            ', VARCHAR 'n st', DECIMAL '136882616.40'),
    (CHAR 'Aquino                        ', CHAR 'Robert              ', VARCHAR 'able', DECIMAL '10166791.88'),
    (CHAR 'Aragon                        ', CHAR 'Stephanie           ', VARCHAR 'ese', DECIMAL '2293041.60'),
    (CHAR 'Aragon                        ', CHAR 'Valerie             ', VARCHAR 'able', DECIMAL '214838373.75'),
    (CHAR 'Araujo                        ', CHAR 'Jacqueline          ', VARCHAR 'able', DECIMAL '6990714.50'),
    (CHAR 'Arce                          ', CHAR 'Michelle            ', VARCHAR 'ation', DECIMAL '32751278.16'),
    (CHAR 'Archer                        ', CHAR 'Alan                ', VARCHAR 'cally', DECIMAL '138495202.56'),
    (CHAR 'Archer                        ', CHAR 'Barbara             ', VARCHAR 'anti', DECIMAL '119100434.22'),
    (CHAR 'Archer                        ', CHAR 'Margit              ', VARCHAR 'cally', DECIMAL '66134449.92'),
    (CHAR 'Archibald                     ', CHAR 'Steven              ', VARCHAR 'able', DECIMAL '2886067.12'),
    (CHAR 'Archuleta                     ', CHAR 'Justin              ', VARCHAR 'n st', DECIMAL '19809670.00'),
    (CHAR 'Arellano                      ', CHAR 'Alexandra           ', VARCHAR 'ought', DECIMAL '539510.79'),
    (CHAR 'Arevalo                       ', CHAR 'George              ', VARCHAR 'able', DECIMAL '4351624.64'),
    (CHAR 'Arevalo                       ', CHAR 'Richard             ', VARCHAR 'n st', DECIMAL '28821616.74'),
    (CHAR 'Arias                         ', CHAR 'Charlotte           ', VARCHAR 'n st', DECIMAL '44969003.55'),
    (CHAR 'Arias                         ', CHAR 'Christina           ', VARCHAR 'ese', DECIMAL '75340601.28'),
    (CHAR 'Arias                         ', CHAR 'Donna               ', VARCHAR 'able', DECIMAL '592806.83'),
    (CHAR 'Arias                         ', CHAR 'Teri                ', VARCHAR 'able', DECIMAL '104942868.03'),
    (CHAR 'Armstrong                     ', CHAR 'Arthur              ', VARCHAR 'anti', DECIMAL '18485024.04'),
    (CHAR 'Armstrong                     ', CHAR 'Darnell             ', VARCHAR 'able', DECIMAL '11634145.16'),
    (CHAR 'Armstrong                     ', CHAR 'Douglas             ', VARCHAR 'n st', DECIMAL '93184446.96'),
    (CHAR 'Armstrong                     ', CHAR 'John                ', VARCHAR 'cally', DECIMAL '6444344.40'),
    (CHAR 'Armstrong                     ', CHAR 'Juana               ', VARCHAR 'n st', DECIMAL '5167048.04'),
    (CHAR 'Armstrong                     ', CHAR 'Kari                ', VARCHAR 'able', DECIMAL '38714306.40'),
    (CHAR 'Armstrong                     ', CHAR 'Lucille             ', VARCHAR 'anti', DECIMAL '197750053.15'),
    (CHAR 'Armstrong                     ', CHAR 'Lynne               ', VARCHAR 'able', DECIMAL '886567.00'),
    (CHAR 'Armstrong                     ', CHAR 'Megan               ', VARCHAR 'anti', DECIMAL '395931.20'),
    (CHAR 'Armstrong                     ', CHAR 'Nathan              ', VARCHAR 'n st', DECIMAL '5185366.40'),
    (CHAR 'Armstrong                     ', CHAR 'Peter               ', VARCHAR 'anti', DECIMAL '202383105.12'),
    (CHAR 'Armstrong                     ', CHAR 'Richard             ', VARCHAR 'eing', DECIMAL '14228137.56'),
    (CHAR 'Armstrong                     ', CHAR 'Stephanie           ', VARCHAR 'n st', DECIMAL '583909.48'),
    (CHAR 'Armstrong                     ', CHAR 'Van                 ', VARCHAR 'ese', DECIMAL '110221273.56'),
    (CHAR 'Armstrong                     ', CHAR 'Wendy               ', VARCHAR 'n st', DECIMAL '166158474.30'),
    (CHAR 'Arndt                         ', CHAR 'Elia                ', VARCHAR 'eing', DECIMAL '57568171.24')
)
