SELECT *
FROM
(
  VALUES
    (CHAR 'ableableantiableeingable                          '),
    (CHAR 'ableableationeingoughtable                        '),
    (CHAR 'ableableeingprieingought                          '),
    (CHAR 'ableableeseableeing                               '),
    (CHAR 'ableableoughtantiationable                        '),
    (CHAR 'ableableoughtoughteingable                        '),
    (CHAR 'ableantiableablecally                             '),
    (CHAR 'ableantieingpripri                                '),
    (CHAR 'ableationableought                                '),
    (CHAR 'ableationbarablen stable                          '),
    (CHAR 'ableationbareseableable                           '),
    (CHAR 'ableationbaroughtn stable                         '),
    (CHAR 'ableationeingcallycallypri                        '),
    (CHAR 'ableationesecallyeing                             '),
    (CHAR 'ableationn stprioughtable                         '),
    (CHAR 'ableationprin stcallypri                          '),
    (CHAR 'ableationpripribarpri                             '),
    (CHAR 'ablebareingationeingought                         '),
    (CHAR 'ablebaresecallybarought                           '),
    (CHAR 'ablecallyoughtanticallyable                       '),
    (CHAR 'ablecallyprieingbarought                          '),
    (CHAR 'ableeingationpricallyought                        '),
    (CHAR 'ableeingbareingantiought                          '),
    (CHAR 'ableeseablen stablepri                            '),
    (CHAR 'ableeseationoughteingable                         '),
    (CHAR 'ableesebarbareingpri                              '),
    (CHAR 'ableesebaroughtesepri                             '),
    (CHAR 'ableeseeingoughtpri                               '),
    (CHAR 'ableeseeingprianti                                '),
    (CHAR 'ableeseesen station                               '),
    (CHAR 'ablen stableationcally                            '),
    (CHAR 'ablen stcallyesepri                               '),
    (CHAR 'ablen stoughtantiation                            '),
    (CHAR 'ableoughtantieingeingpri                          '),
    (CHAR 'ableoughtbarablecallyable                         '),
    (CHAR 'ableoughteingationoughtable                       '),
    (CHAR 'antiableableeingn stpri                           '),
    (CHAR 'antiableantieingbarable                           '),
    (CHAR 'antiablecallybaroughtought                        '),
    (CHAR 'antiantiableeingn stpri                           '),
    (CHAR 'antiantianticallyablepri                          '),
    (CHAR 'antiantiantioughtcallyought                       '),
    (CHAR 'antiantiationeingcally                            '),
    (CHAR 'antiantibaranticallypri                           '),
    (CHAR 'antiationeingantipriought                         '),
    (CHAR 'antiationprieingn stpri                           '),
    (CHAR 'antibarbarn stought                               '),
    (CHAR 'antibaresecallycallyought                         '),
    (CHAR 'antibarn stcallyantiable                          '),
    (CHAR 'anticallyeingationbarought                        '),
    (CHAR 'anticallyeingese                                  '),
    (CHAR 'anticallyoughtbarbarought                         '),
    (CHAR 'anticallyprianticallyought                        '),
    (CHAR 'anticallyprin stantiable                          '),
    (CHAR 'antieingeingoughtable                             '),
    (CHAR 'antieseantibaration                               '),
    (CHAR 'antiesecallycallyeingpri                          '),
    (CHAR 'antieseeingn stableought                          '),
    (CHAR 'antin steseationcallyable                         '),
    (CHAR 'antioughtableanticallyought                       '),
    (CHAR 'antioughtationationcallyought                     '),
    (CHAR 'antioughteingn stpri                              '),
    (CHAR 'antipriationeseese                                '),
    (CHAR 'antipriesen stoughtought                          '),
    (CHAR 'antiprioughtbarbarable                            '),
    (CHAR 'antipripriablebarought                            '),
    (CHAR 'ationableableablen st                             '),
    (CHAR 'ationableantiationeseable                         '),
    (CHAR 'ationableeingeseanti                              '),
    (CHAR 'ationantiableeingbarable                          '),
    (CHAR 'ationantiantibarcally                             '),
    (CHAR 'ationantieingbaranti                              '),
    (CHAR 'ationantiesen stbarable                           '),
    (CHAR 'ationantin stantieseought                         '),
    (CHAR 'ationantin steingantiought                        '),
    (CHAR 'ationantipriantiantiought                         '),
    (CHAR 'ationationablecallyationable                      '),
    (CHAR 'ationationationcallybarable                       '),
    (CHAR 'ationationationpripri                             '),
    (CHAR 'ationbarableableeingought                         '),
    (CHAR 'ationbarableprin stable                           '),
    (CHAR 'ationbarcallyablepriable                          '),
    (CHAR 'ationbareingesebarought                           '),
    (CHAR 'ationbarpriationeing                              '),
    (CHAR 'ationcallyationcallyesepri                        '),
    (CHAR 'ationcallybarcallyableable                        '),
    (CHAR 'ationcallycallyesepri                             '),
    (CHAR 'ationcallyn stoughtn stought                      '),
    (CHAR 'ationeingeseantipripri                            '),
    (CHAR 'ationeingoughtn stanti                            '),
    (CHAR 'ationeingpricallyn stpri                          '),
    (CHAR 'ationeseationationbarought                        '),
    (CHAR 'ationeseationationese                             '),
    (CHAR 'ationesebarablepriable                            '),
    (CHAR 'ationesebarn stcallyable                          '),
    (CHAR 'ationeseese                                       '),
    (CHAR 'ationeseeseablebarought                           '),
    (CHAR 'ationn stationbarableought                        '),
    (CHAR 'ationn stcallyesecallyought                       '),
    (CHAR 'ationn steingoughtablepri                         ')
)
