SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAABDOJEAAA', VARCHAR 'Words keep. Types give with a readers. Available, present awards might not plant servants. Services must get for a patterns. Religi', DECIMAL '78.64'),
    (CHAR 'AAAAAAAABMHKBAAA', VARCHAR 'Only english families push alone religious reasons. More than musical millions put photographs. Criticisms convey just sch', DECIMAL '76.34'),
    (CHAR 'AAAAAAAACBOEEAAA', VARCHAR 'Shots attempt today in the times. Things find immediately walls. Various areas may say both ', DECIMAL '90.22'),
    (CHAR 'AAAAAAAACIDIFAAA', VARCHAR 'Years must compose by the answers.', DECIMAL '71.26'),
    (CHAR 'AAAAAAAACKEHCAAA', VARCHAR 'Ever alternative spirits disarm for instance with a proportions. Total policies ought to achieve too due neighbours. Separate', DECIMAL '82.08'),
    (CHAR 'AAAAAAAADCLAGAAA', VARCHAR 'Talks include allegations. Special volunteers carry originally explanations. Senses want; written, other e', DECIMAL '63.66'),
    (CHAR 'AAAAAAAADDCEEAAA', VARCHAR 'Other, past pl', DECIMAL '86.31'),
    (CHAR 'AAAAAAAADDLHBAAA', VARCHAR 'Sharply proposed tim', DECIMAL '66.09'),
    (CHAR 'AAAAAAAADGEFBAAA', VARCHAR 'Real, common examples could check much aware, other rooms. Years say immediately ever short results. Certainly darling weeks slip back, white hands. Animal', DECIMAL '86.30'),
    (CHAR 'AAAAAAAADNJHCAAA', VARCHAR 'Technically medical ci', DECIMAL '63.76'),
    (CHAR 'AAAAAAAAECMCAAAA', VARCHAR 'Rather vast companies pose quiet, actual carers. Close times take only simple possibilities. Current events might say only on a foundation', DECIMAL '67.28'),
    (CHAR 'AAAAAAAAFODHCAAA', VARCHAR 'Marine, small years prompt suddenly green materials. Violent buildings could act to no levels. Especially mediterranean proceedings might go meanwhile lengthy sets. Widespread, ', DECIMAL '82.29'),
    (CHAR 'AAAAAAAAFPCBCAAA', VARCHAR 'Far principles see gently green, mass assessments. Po', DECIMAL '65.12'),
    (CHAR 'AAAAAAAAGHANFAAA', VARCHAR 'Alternative standards become gradually shapes. For example good scales should mark later. Less popular countries ought to think totally no longer actual compani', DECIMAL '72.92'),
    (CHAR 'AAAAAAAAHBBEDAAA', VARCHAR 'Areas encourage then early northern interests; clear, environmental words can like loud even left problems. About junior firms could not ', DECIMAL '66.72'),
    (CHAR 'AAAAAAAAHCKOBAAA', VARCHAR 'British garden', DECIMAL '87.85'),
    (CHAR 'AAAAAAAAIBAMEAAA', VARCHAR 'Appropriate, central options shall assist truly classical ', DECIMAL '81.82'),
    (CHAR 'AAAAAAAAICLODAAA', VARCHAR 'Over neces', DECIMAL '88.88'),
    (CHAR 'AAAAAAAAIPGDDAAA', VARCHAR 'Social techniques shall not take originally young earnings. Clubs offer about; honest, true structures clear however central, other teachers. Much wide men', DECIMAL '64.88'),
    (CHAR 'AAAAAAAAJNLJEAAA', VARCHAR 'Different, past effects seem right roses. Long, whole hundreds get. Producers shall not like earlier. New, potential policies may use services. Tomorrow high restric', DECIMAL '84.29'),
    (CHAR 'AAAAAAAAJPCIDAAA', VARCHAR 'Classical tears can call early women. Left drugs should not want only', DECIMAL '64.07'),
    (CHAR 'AAAAAAAAKOHMEAAA', VARCHAR 'Records could not go early, great eyes. True tonnes discover for the most part successful years. Maj', DECIMAL '85.95'),
    (CHAR 'AAAAAAAAKOIPDAAA', VARCHAR 'Initial, small women might not s', DECIMAL '83.97'),
    (CHAR 'AAAAAAAAKOMGFAAA', VARCHAR 'Things know views. Most continued views should let inside to a interests; activities cope only sentences. Distinct, traditional pictures might not try. Original bank', DECIMAL '81.05'),
    (CHAR 'AAAAAAAALIHCAAAA', VARCHAR 'Things select increased views. Tools imagine for example; ever likely developments live so scottish benefits. Soft, short-term services should give indeed good illu', DECIMAL '86.90'),
    (CHAR 'AAAAAAAALKLNEAAA', VARCHAR 'Far significant events can take strong, previous republics. Local, conscious shareholders forget there men. Agricultural, revolutionary events can sail. Plain days could substitu', DECIMAL '84.99'),
    (CHAR 'AAAAAAAALOIGEAAA', VARCHAR 'Thus kind metres used to cross. Complaints should see healthy contracts. Still severe times rank still long-term, inland items. Numbers lose directly. Contracts modify else. Num', DECIMAL '76.71'),
    (CHAR 'AAAAAAAAMFIPDAAA', VARCHAR 'Women cover just public events. Years ought to identify there spirits. Long vague benefits ge', DECIMAL '73.29'),
    (CHAR 'AAAAAAAAMOBEBAAA', VARCHAR 'Standard improvements pay toget', DECIMAL '64.56'),
    (CHAR 'AAAAAAAANFHLEAAA', VARCHAR 'Currently social attitudes must not rush simply behind a services. Associations know sharply ', DECIMAL '62.21'),
    (CHAR 'AAAAAAAANOIJFAAA', VARCHAR 'Lo', DECIMAL '67.04'),
    (CHAR 'AAAAAAAAOGKABAAA', VARCHAR 'Dry ministers help quite suggestions. Common times see hard silent tasks. Finally general words must care police. Disa', DECIMAL '86.69'),
    (CHAR 'AAAAAAAAOHNIEAAA', VARCHAR 'Potential, national thoughts make. Wet members could reach too private flats. High, long years might not make considerable, good techniques. Probably large yea', DECIMAL '73.51'),
    (CHAR 'AAAAAAAAOJELFAAA', VARCHAR 'Schools accept at all real systems. Increasingly other influences fight men. Almost new beings deliver also other barriers. Major, big women state simply serious hours. Ne', DECIMAL '68.39'),
    (CHAR 'AAAAAAAAONLBCAAA', VARCHAR 'Too prot', DECIMAL '62.68'),
    (CHAR 'AAAAAAAAOPOICAAA', VARCHAR 'Even wide respects would not go western points. Endlessly irish eyes must not identify a', DECIMAL '85.31')
)
