SELECT *
FROM
(
  VALUES
    (DECIMAL '3321589884545.81', NULL, NULL, INTEGER '2', BIGINT '1'),
    (DECIMAL '334569216343.19', CHAR 'Sports                                            ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '334170122226.17', CHAR 'Children                                          ', NULL, INTEGER '1', BIGINT '2'),
    (DECIMAL '332202114404.29', CHAR 'Music                                             ', NULL, INTEGER '1', BIGINT '3'),
    (DECIMAL '332076507270.28', CHAR 'Home                                              ', NULL, INTEGER '1', BIGINT '4'),
    (DECIMAL '331847630819.72', CHAR 'Women                                             ', NULL, INTEGER '1', BIGINT '5'),
    (DECIMAL '331315664899.63', CHAR 'Electronics                                       ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '330523298193.26', CHAR 'Books                                             ', NULL, INTEGER '1', BIGINT '7'),
    (DECIMAL '330037925133.57', CHAR 'Shoes                                             ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '328674704440.36', CHAR 'Jewelry                                           ', NULL, INTEGER '1', BIGINT '9'),
    (DECIMAL '327929886072.77', CHAR 'Men                                               ', NULL, INTEGER '1', BIGINT '10'),
    (DECIMAL '8242814742.57', NULL, NULL, INTEGER '1', BIGINT '11'),
    (DECIMAL '21398488848.04', CHAR 'Books                                             ', CHAR 'history                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '21299074757.31', CHAR 'Books                                             ', CHAR 'cooking                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '21197674926.54', CHAR 'Books                                             ', CHAR 'romance                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '21140193015.95', CHAR 'Books                                             ', CHAR 'reference                                         ', INTEGER '0', BIGINT '4'),
    (DECIMAL '20911877698.09', CHAR 'Books                                             ', CHAR 'self-help                                         ', INTEGER '0', BIGINT '5'),
    (DECIMAL '20814845704.70', CHAR 'Books                                             ', CHAR 'sports                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '20695149576.64', CHAR 'Books                                             ', CHAR 'parenting                                         ', INTEGER '0', BIGINT '7'),
    (DECIMAL '20686022538.02', CHAR 'Books                                             ', CHAR 'entertainments                                    ', INTEGER '0', BIGINT '8'),
    (DECIMAL '20667884080.85', CHAR 'Books                                             ', CHAR 'fiction                                           ', INTEGER '0', BIGINT '9'),
    (DECIMAL '20617400914.28', CHAR 'Books                                             ', CHAR 'home repair                                       ', INTEGER '0', BIGINT '10'),
    (DECIMAL '20569136796.89', CHAR 'Books                                             ', CHAR 'business                                          ', INTEGER '0', BIGINT '11'),
    (DECIMAL '20240169267.10', CHAR 'Books                                             ', CHAR 'arts                                              ', INTEGER '0', BIGINT '12'),
    (DECIMAL '20139288215.10', CHAR 'Books                                             ', CHAR 'travel                                            ', INTEGER '0', BIGINT '13'),
    (DECIMAL '20080945442.88', CHAR 'Books                                             ', CHAR 'mystery                                           ', INTEGER '0', BIGINT '14'),
    (DECIMAL '19842892935.99', CHAR 'Books                                             ', CHAR 'computers                                         ', INTEGER '0', BIGINT '15'),
    (DECIMAL '19746520885.62', CHAR 'Books                                             ', CHAR 'science                                           ', INTEGER '0', BIGINT '16'),
    (DECIMAL '475732589.26', CHAR 'Books                                             ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '84956626276.38', CHAR 'Children                                          ', CHAR 'infants                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '83925744282.68', CHAR 'Children                                          ', CHAR 'toddlers                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '83289345971.58', CHAR 'Children                                          ', CHAR 'newborn                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '81553316871.86', CHAR 'Children                                          ', CHAR 'school-uniforms                                   ', INTEGER '0', BIGINT '4'),
    (DECIMAL '445088823.67', CHAR 'Children                                          ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '21816241985.02', CHAR 'Electronics                                       ', CHAR 'televisions                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '21498116381.11', CHAR 'Electronics                                       ', CHAR 'karoke                                            ', INTEGER '0', BIGINT '2'),
    (DECIMAL '21160170200.97', CHAR 'Electronics                                       ', CHAR 'scanners                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '20992061405.61', CHAR 'Electronics                                       ', CHAR 'dvd/vcr players                                   ', INTEGER '0', BIGINT '4'),
    (DECIMAL '20950396240.91', CHAR 'Electronics                                       ', CHAR 'disk drives                                       ', INTEGER '0', BIGINT '5'),
    (DECIMAL '20920499849.28', CHAR 'Electronics                                       ', CHAR 'portable                                          ', INTEGER '0', BIGINT '6'),
    (DECIMAL '20851019704.47', CHAR 'Electronics                                       ', CHAR 'memory                                            ', INTEGER '0', BIGINT '7'),
    (DECIMAL '20741883635.65', CHAR 'Electronics                                       ', CHAR 'monitors                                          ', INTEGER '0', BIGINT '8'),
    (DECIMAL '20698877125.83', CHAR 'Electronics                                       ', CHAR 'automotive                                        ', INTEGER '0', BIGINT '9'),
    (DECIMAL '20660879549.91', CHAR 'Electronics                                       ', CHAR 'personal                                          ', INTEGER '0', BIGINT '10'),
    (DECIMAL '20513932853.04', CHAR 'Electronics                                       ', CHAR 'stereo                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '20512859659.38', CHAR 'Electronics                                       ', CHAR 'camcorders                                        ', INTEGER '0', BIGINT '12'),
    (DECIMAL '20396265633.71', CHAR 'Electronics                                       ', CHAR 'cameras                                           ', INTEGER '0', BIGINT '13'),
    (DECIMAL '20252444055.35', CHAR 'Electronics                                       ', CHAR 'musical                                           ', INTEGER '0', BIGINT '14'),
    (DECIMAL '19995603210.59', CHAR 'Electronics                                       ', CHAR 'wireless                                          ', INTEGER '0', BIGINT '15'),
    (DECIMAL '18988548726.85', CHAR 'Electronics                                       ', CHAR 'audio                                             ', INTEGER '0', BIGINT '16'),
    (DECIMAL '365864681.95', CHAR 'Electronics                                       ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '21533116771.35', CHAR 'Home                                              ', CHAR 'blinds/shades                                     ', INTEGER '0', BIGINT '1'),
    (DECIMAL '21373506326.91', CHAR 'Home                                              ', CHAR 'flatware                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '21366613545.84', CHAR 'Home                                              ', CHAR 'bedding                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '21312091049.93', CHAR 'Home                                              ', CHAR 'bathroom                                          ', INTEGER '0', BIGINT '4'),
    (DECIMAL '20859540218.87', CHAR 'Home                                              ', CHAR 'curtains/drapes                                   ', INTEGER '0', BIGINT '5'),
    (DECIMAL '20833093727.13', CHAR 'Home                                              ', CHAR 'furniture                                         ', INTEGER '0', BIGINT '6'),
    (DECIMAL '20810600491.58', CHAR 'Home                                              ', CHAR 'glassware                                         ', INTEGER '0', BIGINT '7'),
    (DECIMAL '20775171046.19', CHAR 'Home                                              ', CHAR 'rugs                                              ', INTEGER '0', BIGINT '8'),
    (DECIMAL '20725764258.04', CHAR 'Home                                              ', CHAR 'kids                                              ', INTEGER '0', BIGINT '9'),
    (DECIMAL '20645524884.35', CHAR 'Home                                              ', CHAR 'mattresses                                        ', INTEGER '0', BIGINT '10'),
    (DECIMAL '20539018402.10', CHAR 'Home                                              ', CHAR 'tables                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '20514011561.60', CHAR 'Home                                              ', CHAR 'decor                                             ', INTEGER '0', BIGINT '12'),
    (DECIMAL '20319758581.93', CHAR 'Home                                              ', CHAR 'paint                                             ', INTEGER '0', BIGINT '13'),
    (DECIMAL '20144420533.05', CHAR 'Home                                              ', CHAR 'lighting                                          ', INTEGER '0', BIGINT '14'),
    (DECIMAL '20121981876.64', CHAR 'Home                                              ', CHAR 'wallpaper                                         ', INTEGER '0', BIGINT '15'),
    (DECIMAL '19708538556.04', CHAR 'Home                                              ', CHAR 'accent                                            ', INTEGER '0', BIGINT '16'),
    (DECIMAL '493755438.73', CHAR 'Home                                              ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '22534404770.21', CHAR 'Jewelry                                           ', CHAR 'jewelry boxes                                     ', INTEGER '0', BIGINT '1'),
    (DECIMAL '21414065038.33', CHAR 'Jewelry                                           ', CHAR 'rings                                             ', INTEGER '0', BIGINT '2'),
    (DECIMAL '21252158200.32', CHAR 'Jewelry                                           ', CHAR 'womens watch                                      ', INTEGER '0', BIGINT '3'),
    (DECIMAL '21045358434.66', CHAR 'Jewelry                                           ', CHAR 'mens watch                                        ', INTEGER '0', BIGINT '4'),
    (DECIMAL '20898790328.96', CHAR 'Jewelry                                           ', CHAR 'gold                                              ', INTEGER '0', BIGINT '5'),
    (DECIMAL '20570464882.66', CHAR 'Jewelry                                           ', CHAR 'costume                                           ', INTEGER '0', BIGINT '6'),
    (DECIMAL '20407857439.67', CHAR 'Jewelry                                           ', CHAR 'bracelets                                         ', INTEGER '0', BIGINT '7'),
    (DECIMAL '20323856475.41', CHAR 'Jewelry                                           ', CHAR 'birdal                                            ', INTEGER '0', BIGINT '8'),
    (DECIMAL '20137202863.08', CHAR 'Jewelry                                           ', CHAR 'pendants                                          ', INTEGER '0', BIGINT '9'),
    (DECIMAL '20110165088.53', CHAR 'Jewelry                                           ', CHAR 'earings                                           ', INTEGER '0', BIGINT '10'),
    (DECIMAL '20099351067.99', CHAR 'Jewelry                                           ', CHAR 'diamonds                                          ', INTEGER '0', BIGINT '11'),
    (DECIMAL '20094137796.80', CHAR 'Jewelry                                           ', CHAR 'estate                                            ', INTEGER '0', BIGINT '12'),
    (DECIMAL '20042580358.88', CHAR 'Jewelry                                           ', CHAR 'loose stones                                      ', INTEGER '0', BIGINT '13'),
    (DECIMAL '19871944816.22', CHAR 'Jewelry                                           ', CHAR 'consignment                                       ', INTEGER '0', BIGINT '14'),
    (DECIMAL '19849468916.22', CHAR 'Jewelry                                           ', CHAR 'semi-precious                                     ', INTEGER '0', BIGINT '15'),
    (DECIMAL '19611290551.92', CHAR 'Jewelry                                           ', CHAR 'custom                                            ', INTEGER '0', BIGINT '16'),
    (DECIMAL '411607410.50', CHAR 'Jewelry                                           ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '82700107446.85', CHAR 'Men                                               ', CHAR 'sports-apparel                                    ', INTEGER '0', BIGINT '1'),
    (DECIMAL '82561322214.16', CHAR 'Men                                               ', CHAR 'accessories                                       ', INTEGER '0', BIGINT '2'),
    (DECIMAL '81936511231.88', CHAR 'Men                                               ', CHAR 'shirts                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '80216934588.56', CHAR 'Men                                               ', CHAR 'pants                                             ', INTEGER '0', BIGINT '4'),
    (DECIMAL '515010591.32', CHAR 'Men                                               ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '84525301878.89', CHAR 'Music                                             ', CHAR 'classical                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '83043646025.47', CHAR 'Music                                             ', CHAR 'country                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '82330255826.54', CHAR 'Music                                             ', CHAR 'rock                                              ', INTEGER '0', BIGINT '3'),
    (DECIMAL '81806632164.60', CHAR 'Music                                             ', CHAR 'pop                                               ', INTEGER '0', BIGINT '4'),
    (DECIMAL '496278508.79', CHAR 'Music                                             ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '84017989795.17', CHAR 'Shoes                                             ', CHAR 'womens                                            ', INTEGER '0', BIGINT '1'),
    (DECIMAL '82454102187.02', CHAR 'Shoes                                             ', CHAR 'kids                                              ', INTEGER '0', BIGINT '2'),
    (DECIMAL '82072688195.87', CHAR 'Shoes                                             ', CHAR 'athletic                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '81095562088.03', CHAR 'Shoes                                             ', CHAR 'mens                                              ', INTEGER '0', BIGINT '4'),
    (DECIMAL '397582867.48', CHAR 'Shoes                                             ', NULL, INTEGER '0', BIGINT '5')
)
