SELECT *
FROM
(
  VALUES
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1')
)
