SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAAAAAEAA', NULL, NULL, NULL, VARCHAR 'RWANDA', NULL),
    (CHAR 'AAAAAAAAAAAAAHAA', CHAR 'Kenneth             ', CHAR 'Brinkley                      ', CHAR 'Y', VARCHAR 'ZAMBIA', NULL),
    (CHAR 'AAAAAAAAAAAABBAA', CHAR 'Elizabeth           ', CHAR 'White                         ', CHAR 'Y', VARCHAR 'MALI', NULL),
    (CHAR 'AAAAAAAAAAAABGAA', CHAR 'Albert              ', NULL, CHAR 'Y', NULL, NULL),
    (CHAR 'AAAAAAAAAAAABJAA', CHAR 'Lorraine            ', CHAR 'Delgadillo                    ', CHAR 'N', VARCHAR 'MARTINIQUE', NULL),
    (CHAR 'AAAAAAAAAAAADAAA', CHAR 'Kathryn             ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'BENIN', NULL),
    (CHAR 'AAAAAAAAAAAADFAA', CHAR 'Julia               ', CHAR 'Mathews                       ', CHAR 'Y', VARCHAR 'MONTENEGRO', NULL),
    (CHAR 'AAAAAAAAAAAADJAA', CHAR 'Irwin               ', CHAR 'Lee                           ', CHAR 'N', VARCHAR 'FIJI', NULL),
    (CHAR 'AAAAAAAAAAAAEDAA', CHAR 'Robert              ', CHAR 'Mitchell                      ', CHAR 'Y', VARCHAR 'NIGERIA', NULL),
    (CHAR 'AAAAAAAAAAAAEEAA', CHAR 'Michael             ', CHAR 'Fisher                        ', CHAR 'N', VARCHAR 'PAPUA NEW GUINEA', NULL),
    (CHAR 'AAAAAAAAAAAAEFAA', CHAR 'Jason               ', CHAR 'Lee                           ', CHAR 'Y', VARCHAR 'NEW ZEALAND', NULL),
    (CHAR 'AAAAAAAAAAAAEJAA', CHAR 'Roxanne             ', CHAR 'Mcneely                       ', CHAR 'Y', VARCHAR 'RUSSIAN FEDERATION', NULL),
    (CHAR 'AAAAAAAAAAAAEKAA', CHAR 'Charlene            ', CHAR 'Patrick                       ', CHAR 'Y', VARCHAR 'LESOTHO', NULL),
    (CHAR 'AAAAAAAAAAAAFDAA', CHAR 'Edward              ', CHAR 'Clifton                       ', CHAR 'N', VARCHAR 'ARGENTINA', NULL),
    (CHAR 'AAAAAAAAAAAAFJAA', CHAR 'George              ', CHAR 'Cain                          ', CHAR 'Y', VARCHAR 'GHANA', NULL),
    (CHAR 'AAAAAAAAAAAAGIAA', CHAR 'Brett               ', CHAR 'Martinez                      ', CHAR 'N', VARCHAR 'JERSEY', NULL),
    (CHAR 'AAAAAAAAAAAAHFAA', CHAR 'Richard             ', CHAR 'Allen                         ', CHAR 'N', VARCHAR 'MONTSERRAT', NULL),
    (CHAR 'AAAAAAAAAAAAHKAA', CHAR 'Roberto             ', CHAR 'Payton                        ', CHAR 'Y', VARCHAR 'THAILAND', NULL),
    (CHAR 'AAAAAAAAAAAAHLAA', CHAR 'Phyllis             ', CHAR 'Yazzie                        ', CHAR 'N', VARCHAR 'CAYMAN ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAAAJKAA', CHAR 'Hollis              ', CHAR 'Lopez                         ', CHAR 'N', VARCHAR 'MADAGASCAR', NULL),
    (CHAR 'AAAAAAAAAAAAKAAA', CHAR 'Bertha              ', CHAR 'Caldwell                      ', CHAR 'Y', VARCHAR 'ESTONIA', NULL),
    (CHAR 'AAAAAAAAAAAALFAA', CHAR 'Martin              ', CHAR 'Ault                          ', CHAR 'N', VARCHAR 'FINLAND', NULL),
    (CHAR 'AAAAAAAAAAAANBAA', CHAR 'Juan                ', CHAR 'Ballard                       ', CHAR 'Y', VARCHAR 'GHANA', NULL),
    (CHAR 'AAAAAAAAAAAANCAA', CHAR 'David               ', CHAR 'Hidalgo                       ', CHAR 'N', VARCHAR 'BANGLADESH', NULL),
    (CHAR 'AAAAAAAAAAAANFAA', CHAR 'Mabel               ', CHAR 'Wilson                        ', CHAR 'N', VARCHAR 'MAURITANIA', NULL),
    (CHAR 'AAAAAAAAAAAANGAA', CHAR 'James               ', CHAR 'Blackburn                     ', CHAR 'N', VARCHAR 'PORTUGAL', NULL),
    (CHAR 'AAAAAAAAAAAAOBAA', CHAR 'Daisy               ', CHAR 'Briggs                        ', CHAR 'Y', VARCHAR 'BERMUDA', NULL),
    (CHAR 'AAAAAAAAAAAAOCAA', CHAR 'Ada                 ', CHAR 'Shields                       ', CHAR 'N', VARCHAR 'GUERNSEY', NULL),
    (CHAR 'AAAAAAAAAAAAPCAA', CHAR 'Samuel              ', CHAR 'Langston                      ', CHAR 'N', VARCHAR 'UZBEKISTAN', NULL),
    (CHAR 'AAAAAAAAAAAAPDAA', CHAR 'Lora                ', CHAR 'Haas                          ', CHAR 'Y', VARCHAR 'SENEGAL', NULL),
    (CHAR 'AAAAAAAAAAAAPGAA', CHAR 'Rita                ', CHAR 'Price                         ', CHAR 'Y', VARCHAR 'DOMINICA', NULL),
    (CHAR 'AAAAAAAAAAAAPHAA', CHAR 'Glenda              ', CHAR 'Nelson                        ', CHAR 'Y', VARCHAR 'AUSTRIA', NULL),
    (CHAR 'AAAAAAAAAAAAPJAA', CHAR 'Elizabeth           ', CHAR 'James                         ', CHAR 'N', VARCHAR 'BHUTAN', NULL),
    (CHAR 'AAAAAAAAAAABBEAA', CHAR 'Fred                ', CHAR 'Thibodeaux                    ', CHAR 'N', VARCHAR 'VIET NAM', NULL),
    (CHAR 'AAAAAAAAAAABBJAA', CHAR 'Ana                 ', CHAR 'Smith                         ', CHAR 'N', VARCHAR 'ETHIOPIA', NULL),
    (CHAR 'AAAAAAAAAAABCAAA', CHAR 'Edgar               ', CHAR 'Clark                         ', CHAR 'N', VARCHAR 'SYRIAN ARAB REPUBLIC', NULL),
    (CHAR 'AAAAAAAAAAABCDAA', CHAR 'Larry               ', CHAR 'Shaw                          ', CHAR 'Y', VARCHAR 'FRANCE', NULL),
    (CHAR 'AAAAAAAAAAABCJAA', CHAR 'Lindy               ', CHAR 'Rivera                        ', CHAR 'Y', VARCHAR 'BOUVET ISLAND', NULL),
    (CHAR 'AAAAAAAAAAABDCAA', CHAR 'Pablo               ', CHAR 'Garcia                        ', CHAR 'Y', VARCHAR 'URUGUAY', NULL),
    (CHAR 'AAAAAAAAAAABDEAA', CHAR 'Tom                 ', CHAR 'Stone                         ', CHAR 'Y', VARCHAR 'WALLIS AND FUTUNA', NULL),
    (CHAR 'AAAAAAAAAAABDGAA', CHAR 'Roderick            ', CHAR 'Mendez                        ', CHAR 'N', VARCHAR 'AUSTRALIA', NULL),
    (CHAR 'AAAAAAAAAAABEBAA', CHAR 'Cecilia             ', CHAR 'Fontenot                      ', CHAR 'N', VARCHAR 'TIMOR-LESTE', NULL),
    (CHAR 'AAAAAAAAAAABELAA', CHAR 'Hilda               ', CHAR 'Kozlowski                     ', CHAR 'Y', VARCHAR 'KIRIBATI', NULL),
    (CHAR 'AAAAAAAAAAABFFAA', CHAR 'Gregory             ', CHAR 'Bailey                        ', CHAR 'N', VARCHAR 'KYRGYZSTAN', NULL),
    (CHAR 'AAAAAAAAAAABFGAA', CHAR 'Julia               ', CHAR 'Hall                          ', CHAR 'Y', VARCHAR 'BURUNDI', NULL),
    (CHAR 'AAAAAAAAAAABGAAA', CHAR 'Diane               ', CHAR 'Hart                          ', CHAR 'Y', VARCHAR 'TOGO', NULL),
    (CHAR 'AAAAAAAAAAABGBAA', CHAR 'Steven              ', CHAR 'Nowell                        ', CHAR 'N', VARCHAR 'DJIBOUTI', NULL),
    (CHAR 'AAAAAAAAAAABHDAA', CHAR 'Helen               ', CHAR 'Mcclung                       ', CHAR 'Y', VARCHAR 'BELIZE', NULL),
    (CHAR 'AAAAAAAAAAABHFAA', CHAR 'Gabrielle           ', CHAR 'Shields                       ', CHAR 'N', VARCHAR 'FRENCH GUIANA', NULL),
    (CHAR 'AAAAAAAAAAABICAA', CHAR 'Nancy               ', CHAR 'Person                        ', CHAR 'Y', VARCHAR 'QATAR', NULL),
    (CHAR 'AAAAAAAAAAABIGAA', CHAR 'Timothy             ', CHAR 'Arroyo                        ', CHAR 'Y', VARCHAR 'BANGLADESH', NULL),
    (CHAR 'AAAAAAAAAAABJAAA', CHAR 'Virginia            ', CHAR 'Fitts                         ', CHAR 'N', VARCHAR 'KOREA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAAABJGAA', CHAR 'Billy               ', NULL, NULL, NULL, NULL),
    (CHAR 'AAAAAAAAAAABJHAA', CHAR 'Louis               ', CHAR 'Ward                          ', CHAR 'N', VARCHAR 'SINGAPORE', NULL),
    (CHAR 'AAAAAAAAAAABJIAA', CHAR 'Kathleen            ', CHAR 'Overstreet                    ', CHAR 'Y', VARCHAR 'NORWAY', NULL),
    (CHAR 'AAAAAAAAAAABKCAA', CHAR 'Wendy               ', CHAR 'Leonard                       ', CHAR 'N', VARCHAR 'ZAMBIA', NULL),
    (CHAR 'AAAAAAAAAAABLGAA', CHAR 'Juan                ', CHAR 'Ward                          ', CHAR 'Y', VARCHAR 'NICARAGUA', NULL),
    (CHAR 'AAAAAAAAAAABMBAA', CHAR 'Jacqueline          ', CHAR 'Carlson                       ', CHAR 'N', VARCHAR 'FRANCE', NULL),
    (CHAR 'AAAAAAAAAAABMDAA', CHAR 'Joe                 ', CHAR 'Heinz                         ', CHAR 'Y', VARCHAR 'PORTUGAL', NULL),
    (CHAR 'AAAAAAAAAAABOFAA', CHAR 'Marie               ', CHAR 'Montgomery                    ', CHAR 'Y', VARCHAR 'CHRISTMAS ISLAND', NULL),
    (CHAR 'AAAAAAAAAAABPCAA', CHAR 'David               ', CHAR 'Herring                       ', CHAR 'N', VARCHAR 'BRUNEI DARUSSALAM', NULL),
    (CHAR 'AAAAAAAAAAACAHAA', CHAR 'Frank               ', CHAR 'Denson                        ', CHAR 'N', VARCHAR 'CROATIA', NULL),
    (CHAR 'AAAAAAAAAAACBKAA', CHAR 'Stanley             ', CHAR 'Luna                          ', CHAR 'Y', VARCHAR 'BOTSWANA', NULL),
    (CHAR 'AAAAAAAAAAACCCAA', CHAR 'Barbara             ', CHAR 'Spencer                       ', CHAR 'N', VARCHAR 'URUGUAY', NULL),
    (CHAR 'AAAAAAAAAAACCDAA', CHAR 'Roseann             ', CHAR 'Nichols                       ', CHAR 'Y', VARCHAR 'MYANMAR', NULL),
    (CHAR 'AAAAAAAAAAACCHAA', CHAR 'Jodi                ', CHAR 'Rivera                        ', CHAR 'N', VARCHAR 'FRENCH POLYNESIA', NULL),
    (CHAR 'AAAAAAAAAAACDJAA', CHAR 'Jennifer            ', CHAR 'Tyson                         ', CHAR 'N', VARCHAR 'SWEDEN', NULL),
    (CHAR 'AAAAAAAAAAACDLAA', CHAR 'Ryan                ', CHAR 'Brunner                       ', CHAR 'Y', VARCHAR 'FRENCH GUIANA', NULL),
    (CHAR 'AAAAAAAAAAACEJAA', CHAR 'Melissa             ', CHAR 'Brooks                        ', CHAR 'Y', VARCHAR 'EGYPT', NULL),
    (CHAR 'AAAAAAAAAAACFDAA', CHAR 'Betty               ', CHAR 'Singh                         ', CHAR 'Y', VARCHAR 'NEPAL', NULL),
    (CHAR 'AAAAAAAAAAACFFAA', CHAR 'Linda               ', CHAR 'Christensen                   ', CHAR 'N', VARCHAR 'NETHERLANDS', NULL),
    (CHAR 'AAAAAAAAAAACFGAA', CHAR 'Martha              ', CHAR 'Mcmullin                      ', CHAR 'Y', VARCHAR 'GUYANA', NULL),
    (CHAR 'AAAAAAAAAAACGBAA', CHAR 'Margaret            ', CHAR 'Bender                        ', CHAR 'Y', VARCHAR 'HONG KONG', NULL),
    (CHAR 'AAAAAAAAAAACGCAA', CHAR 'Alicia              ', CHAR 'Lang                          ', CHAR 'Y', VARCHAR 'MACAO', NULL),
    (CHAR 'AAAAAAAAAAACHBAA', CHAR 'Francis             ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'CROATIA', NULL),
    (CHAR 'AAAAAAAAAAACHEAA', CHAR 'Ben                 ', CHAR 'Mcneil                        ', CHAR 'Y', VARCHAR 'INDIA', NULL),
    (CHAR 'AAAAAAAAAAACHHAA', CHAR 'Hubert              ', CHAR 'Perkins                       ', CHAR 'Y', VARCHAR 'ZAMBIA', NULL),
    (CHAR 'AAAAAAAAAAACHKAA', CHAR 'Mari                ', CHAR 'Garcia                        ', CHAR 'Y', VARCHAR 'DOMINICA', NULL),
    (CHAR 'AAAAAAAAAAACIAAA', CHAR 'Evelyn              ', CHAR 'Ferris                        ', CHAR 'Y', VARCHAR 'CUBA', NULL),
    (CHAR 'AAAAAAAAAAACIEAA', CHAR 'William             ', CHAR 'Brown                         ', NULL, VARCHAR 'DENMARK', NULL),
    (CHAR 'AAAAAAAAAAACIGAA', CHAR 'Tony                ', CHAR 'Weston                        ', CHAR 'N', VARCHAR 'BERMUDA', NULL),
    (CHAR 'AAAAAAAAAAACJBAA', CHAR 'Kenneth             ', CHAR 'Bragg                         ', CHAR 'N', VARCHAR 'SOMALIA', NULL),
    (CHAR 'AAAAAAAAAAACJEAA', CHAR 'Samantha            ', CHAR 'Weaver                        ', CHAR 'N', VARCHAR 'ANTARCTICA', NULL),
    (CHAR 'AAAAAAAAAAACJIAA', CHAR 'Gary                ', CHAR 'Madden                        ', CHAR 'N', VARCHAR 'SAINT LUCIA', NULL),
    (CHAR 'AAAAAAAAAAACLBAA', CHAR 'Robert              ', CHAR 'Quiroz                        ', CHAR 'N', VARCHAR 'CAPE VERDE', NULL),
    (CHAR 'AAAAAAAAAAACLFAA', CHAR 'Marcus              ', CHAR 'Evans                         ', CHAR 'N', VARCHAR 'FRANCE', NULL),
    (CHAR 'AAAAAAAAAAACMAAA', CHAR 'Kathy               ', CHAR 'Burrell                       ', CHAR 'N', VARCHAR 'TOGO', NULL),
    (CHAR 'AAAAAAAAAAACMDAA', CHAR 'Aaron               ', CHAR 'Beck                          ', CHAR 'N', VARCHAR 'MOLDOVA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAAACOEAA', CHAR 'Sheila              ', CHAR 'Lopez                         ', CHAR 'Y', VARCHAR 'SAINT HELENA', NULL),
    (CHAR 'AAAAAAAAAAACOFAA', CHAR 'Jimmy               ', CHAR 'Shaw                          ', CHAR 'Y', VARCHAR 'JORDAN', NULL),
    (CHAR 'AAAAAAAAAAACOJAA', CHAR 'Pearl               ', CHAR 'Schaefer                      ', CHAR 'N', VARCHAR 'GEORGIA', NULL),
    (CHAR 'AAAAAAAAAAACPBAA', CHAR 'Robert              ', CHAR 'Theriault                     ', CHAR 'N', VARCHAR 'SOLOMON ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAACPEAA', CHAR 'Michael             ', CHAR 'Gordon                        ', CHAR 'Y', VARCHAR 'BRUNEI DARUSSALAM', NULL),
    (CHAR 'AAAAAAAAAAACPGAA', CHAR 'Roger               ', CHAR 'Mayo                          ', CHAR 'N', VARCHAR 'GIBRALTAR', NULL),
    (CHAR 'AAAAAAAAAAADAHAA', CHAR 'Elizabeth           ', CHAR 'Carrera                       ', CHAR 'Y', VARCHAR 'HONDURAS', NULL),
    (CHAR 'AAAAAAAAAAADAIAA', CHAR 'Abraham             ', CHAR 'Berry                         ', CHAR 'Y', VARCHAR 'ZIMBABWE', NULL),
    (CHAR 'AAAAAAAAAAADCAAA', CHAR 'Henry               ', CHAR 'Collazo                       ', CHAR 'Y', VARCHAR 'FINLAND', NULL),
    (CHAR 'AAAAAAAAAAADCKAA', CHAR 'Adalberto           ', CHAR 'Coker                         ', CHAR 'N', VARCHAR 'SWITZERLAND', NULL),
    (CHAR 'AAAAAAAAAAADEAAA', CHAR 'Kristopher          ', CHAR 'Hawkins                       ', CHAR 'N', VARCHAR 'ANTARCTICA', NULL),
    (CHAR 'AAAAAAAAAAADECAA', CHAR 'Oliver              ', NULL, CHAR 'Y', NULL, NULL)
)
