SELECT *
FROM
(
  VALUES
    (CHAR 'oughtoughtbareingeingought                        ', CHAR 'brandbrand #2                                     ', CHAR 'decor                                             ', CHAR 'Home                                              ', DOUBLE '457.2067209775967'),
    (CHAR 'oughtoughtbareingeingought                        ', CHAR 'brandbrand #2                                     ', CHAR 'decor                                             ', NULL, DOUBLE '457.2067209775967'),
    (CHAR 'oughtoughtbareingeingought                        ', CHAR 'brandbrand #2                                     ', NULL, NULL, DOUBLE '457.2067209775967'),
    (CHAR 'oughtoughtbareingeingought                        ', NULL, NULL, NULL, DOUBLE '457.2067209775967'),
    (CHAR 'n stoughteseationanti                             ', CHAR 'edu packmaxi #12                                  ', CHAR 'entertainments                                    ', CHAR 'Books                                             ', DOUBLE '459.13453815261045'),
    (CHAR 'n stoughteseationanti                             ', CHAR 'edu packmaxi #12                                  ', CHAR 'entertainments                                    ', NULL, DOUBLE '459.13453815261045'),
    (CHAR 'n stoughteseationanti                             ', CHAR 'edu packmaxi #12                                  ', NULL, NULL, DOUBLE '459.13453815261045'),
    (CHAR 'n stoughteseationanti                             ', NULL, NULL, NULL, DOUBLE '459.13453815261045'),
    (CHAR 'ationn stn stantibarable                          ', CHAR 'importoscholar #2                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '460.4856557377049'),
    (CHAR 'ationn stn stantibarable                          ', CHAR 'importoscholar #2                                 ', CHAR 'country                                           ', NULL, DOUBLE '460.4856557377049'),
    (CHAR 'ationn stn stantibarable                          ', CHAR 'importoscholar #2                                 ', NULL, NULL, DOUBLE '460.4856557377049'),
    (CHAR 'ationn stn stantibarable                          ', NULL, NULL, NULL, DOUBLE '460.4856557377049'),
    (CHAR 'ableoughtcallyableableought                       ', CHAR 'edu packamalg #1                                  ', CHAR 'swimwear                                          ', CHAR 'Women                                             ', DOUBLE '461.005076142132'),
    (CHAR 'ableoughtcallyableableought                       ', CHAR 'edu packamalg #1                                  ', CHAR 'swimwear                                          ', NULL, DOUBLE '461.005076142132'),
    (CHAR 'ableoughtcallyableableought                       ', CHAR 'edu packamalg #1                                  ', NULL, NULL, DOUBLE '461.005076142132'),
    (CHAR 'ableoughtcallyableableought                       ', NULL, NULL, NULL, DOUBLE '461.005076142132'),
    (CHAR 'n stprin stesebarought                            ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', CHAR 'Shoes                                             ', DOUBLE '462.2741116751269'),
    (CHAR 'n stprin stesebarought                            ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', NULL, DOUBLE '462.2741116751269'),
    (CHAR 'n stprin stesebarought                            ', CHAR 'amalgedu pack #2                                  ', NULL, NULL, DOUBLE '462.2741116751269'),
    (CHAR 'n stprin stesebarought                            ', NULL, NULL, NULL, DOUBLE '462.2741116751269'),
    (CHAR 'callyoughtoughteingantiable                       ', CHAR 'edu packamalgamalg #6                             ', CHAR 'automotive                                        ', CHAR 'Electronics                                       ', DOUBLE '462.97761953204474'),
    (CHAR 'callyoughtoughteingantiable                       ', CHAR 'edu packamalgamalg #6                             ', CHAR 'automotive                                        ', NULL, DOUBLE '462.97761953204474'),
    (CHAR 'callyoughtoughteingantiable                       ', CHAR 'edu packamalgamalg #6                             ', NULL, NULL, DOUBLE '462.97761953204474'),
    (CHAR 'callyoughtoughteingantiable                       ', NULL, NULL, NULL, DOUBLE '462.97761953204474'),
    (CHAR 'pribarpriablen st                                 ', CHAR 'exportiexporti #2                                 ', CHAR 'toddlers                                          ', CHAR 'Children                                          ', DOUBLE '463.1137724550898'),
    (CHAR 'pribarpriablen st                                 ', CHAR 'exportiexporti #2                                 ', CHAR 'toddlers                                          ', NULL, DOUBLE '463.1137724550898'),
    (CHAR 'pribarpriablen st                                 ', CHAR 'exportiexporti #2                                 ', NULL, NULL, DOUBLE '463.1137724550898'),
    (CHAR 'pribarpriablen st                                 ', NULL, NULL, NULL, DOUBLE '463.1137724550898'),
    (CHAR 'ationeseableantin stought                         ', CHAR 'exportiunivamalg #8                               ', CHAR 'self-help                                         ', CHAR 'Books                                             ', DOUBLE '463.62184024266935'),
    (CHAR 'ationeseableantin stought                         ', CHAR 'exportiunivamalg #8                               ', CHAR 'self-help                                         ', NULL, DOUBLE '463.62184024266935'),
    (CHAR 'ationeseableantin stought                         ', CHAR 'exportiunivamalg #8                               ', NULL, NULL, DOUBLE '463.62184024266935'),
    (CHAR 'ationeseableantin stought                         ', NULL, NULL, NULL, DOUBLE '463.62184024266935'),
    (CHAR 'esen stn stoughtcally                             ', CHAR 'edu packscholar #1                                ', CHAR 'classical                                         ', CHAR 'Music                                             ', DOUBLE '463.9315206445116'),
    (CHAR 'esen stn stoughtcally                             ', CHAR 'edu packscholar #1                                ', CHAR 'classical                                         ', NULL, DOUBLE '463.9315206445116'),
    (CHAR 'esen stn stoughtcally                             ', CHAR 'edu packscholar #1                                ', NULL, NULL, DOUBLE '463.9315206445116'),
    (CHAR 'esen stn stoughtcally                             ', NULL, NULL, NULL, DOUBLE '463.9315206445116'),
    (CHAR 'eseantin steingoughtable                          ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '464.24419778002016'),
    (CHAR 'eseantin steingoughtable                          ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', NULL, DOUBLE '464.24419778002016'),
    (CHAR 'eseantin steingoughtable                          ', CHAR 'importoscholar #1                                 ', NULL, NULL, DOUBLE '464.24419778002016'),
    (CHAR 'eseantin steingoughtable                          ', NULL, NULL, NULL, DOUBLE '464.24419778002016'),
    (CHAR 'oughtn steingpribarought                          ', CHAR 'scholarunivamalg #8                               ', CHAR 'fiction                                           ', CHAR 'Books                                             ', DOUBLE '464.32016210739613'),
    (CHAR 'oughtn steingpribarought                          ', CHAR 'scholarunivamalg #8                               ', CHAR 'fiction                                           ', NULL, DOUBLE '464.32016210739613'),
    (CHAR 'oughtn steingpribarought                          ', CHAR 'scholarunivamalg #8                               ', NULL, NULL, DOUBLE '464.32016210739613'),
    (CHAR 'oughtn steingpribarought                          ', NULL, NULL, NULL, DOUBLE '464.32016210739613'),
    (CHAR 'n stantibarprioughtought                          ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '464.8932527693857'),
    (CHAR 'n stantibarprioughtought                          ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '464.8932527693857'),
    (CHAR 'n stantibarprioughtought                          ', CHAR 'amalgimporto #2                                   ', NULL, NULL, DOUBLE '464.8932527693857'),
    (CHAR 'n stantibarprioughtought                          ', NULL, NULL, NULL, DOUBLE '464.8932527693857'),
    (CHAR 'eingeseeingeseanti                                ', CHAR 'importoimporto #1                                 ', CHAR 'shirts                                            ', CHAR 'Men                                               ', DOUBLE '464.926'),
    (CHAR 'eingeseeingeseanti                                ', CHAR 'importoimporto #1                                 ', CHAR 'shirts                                            ', NULL, DOUBLE '464.926'),
    (CHAR 'eingeseeingeseanti                                ', CHAR 'importoimporto #1                                 ', NULL, NULL, DOUBLE '464.926'),
    (CHAR 'eingeseeingeseanti                                ', NULL, NULL, NULL, DOUBLE '464.926'),
    (CHAR 'ationantieseought                                 ', CHAR 'univmaxi #8                                       ', CHAR 'pools                                             ', CHAR 'Sports                                            ', DOUBLE '465.1421319796954'),
    (CHAR 'ationantieseought                                 ', CHAR 'univmaxi #8                                       ', CHAR 'pools                                             ', NULL, DOUBLE '465.1421319796954'),
    (CHAR 'ationantieseought                                 ', CHAR 'univmaxi #8                                       ', NULL, NULL, DOUBLE '465.1421319796954'),
    (CHAR 'ationantieseought                                 ', NULL, NULL, NULL, DOUBLE '465.1421319796954'),
    (CHAR 'prieingcallyationcallyought                       ', CHAR 'corpnameless #4                                   ', CHAR 'furniture                                         ', CHAR 'Home                                              ', DOUBLE '465.20837589376913'),
    (CHAR 'prieingcallyationcallyought                       ', CHAR 'corpnameless #4                                   ', CHAR 'furniture                                         ', NULL, DOUBLE '465.20837589376913'),
    (CHAR 'prieingcallyationcallyought                       ', CHAR 'corpnameless #4                                   ', NULL, NULL, DOUBLE '465.20837589376913'),
    (CHAR 'prieingcallyationcallyought                       ', NULL, NULL, NULL, DOUBLE '465.20837589376913'),
    (CHAR 'ableantipripriation                               ', CHAR 'univbrand #1                                      ', CHAR 'jewelry boxes                                     ', CHAR 'Jewelry                                           ', DOUBLE '465.3756243756244'),
    (CHAR 'ableantipripriation                               ', CHAR 'univbrand #1                                      ', CHAR 'jewelry boxes                                     ', NULL, DOUBLE '465.3756243756244'),
    (CHAR 'ableantipripriation                               ', CHAR 'univbrand #1                                      ', NULL, NULL, DOUBLE '465.3756243756244'),
    (CHAR 'ableantipripriation                               ', NULL, NULL, NULL, DOUBLE '465.3756243756244'),
    (CHAR 'oughtantipriableableought                         ', CHAR 'importocorp #8                                    ', CHAR 'diamonds                                          ', CHAR 'Jewelry                                           ', DOUBLE '465.6099290780142'),
    (CHAR 'oughtantipriableableought                         ', CHAR 'importocorp #8                                    ', CHAR 'diamonds                                          ', NULL, DOUBLE '465.6099290780142'),
    (CHAR 'oughtantipriableableought                         ', CHAR 'importocorp #8                                    ', NULL, NULL, DOUBLE '465.6099290780142'),
    (CHAR 'oughtantipriableableought                         ', NULL, NULL, NULL, DOUBLE '465.6099290780142'),
    (CHAR 'n stpricallypriableable                           ', CHAR 'importoscholar #2                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '465.9582484725051'),
    (CHAR 'n stpricallypriableable                           ', CHAR 'importoscholar #2                                 ', CHAR 'country                                           ', NULL, DOUBLE '465.9582484725051'),
    (CHAR 'n stpricallypriableable                           ', CHAR 'importoscholar #2                                 ', NULL, NULL, DOUBLE '465.9582484725051'),
    (CHAR 'n stpricallypriableable                           ', NULL, NULL, NULL, DOUBLE '465.9582484725051'),
    (CHAR 'oughtprieseeseeing                                ', CHAR 'exporticorp #8                                    ', CHAR 'gold                                              ', CHAR 'Jewelry                                           ', DOUBLE '466.0050505050505'),
    (CHAR 'oughtprieseeseeing                                ', CHAR 'exporticorp #8                                    ', CHAR 'gold                                              ', NULL, DOUBLE '466.0050505050505'),
    (CHAR 'oughtprieseeseeing                                ', CHAR 'exporticorp #8                                    ', NULL, NULL, DOUBLE '466.0050505050505'),
    (CHAR 'oughtprieseeseeing                                ', NULL, NULL, NULL, DOUBLE '466.0050505050505'),
    (CHAR 'oughtn stn stoughtn stable                        ', CHAR 'edu packscholar #2                                ', CHAR 'classical                                         ', CHAR 'Music                                             ', DOUBLE '466.23147208121827'),
    (CHAR 'oughtn stn stoughtn stable                        ', CHAR 'edu packscholar #2                                ', CHAR 'classical                                         ', NULL, DOUBLE '466.23147208121827'),
    (CHAR 'oughtn stn stoughtn stable                        ', CHAR 'edu packscholar #2                                ', NULL, NULL, DOUBLE '466.23147208121827'),
    (CHAR 'oughtn stn stoughtn stable                        ', NULL, NULL, NULL, DOUBLE '466.23147208121827'),
    (CHAR 'ablen stationesecallyought                        ', CHAR 'scholarnameless #3                                ', CHAR 'tables                                            ', CHAR 'Home                                              ', DOUBLE '466.47479838709677'),
    (CHAR 'ablen stationesecallyought                        ', CHAR 'scholarnameless #3                                ', CHAR 'tables                                            ', NULL, DOUBLE '466.47479838709677'),
    (CHAR 'ablen stationesecallyought                        ', CHAR 'scholarnameless #3                                ', NULL, NULL, DOUBLE '466.47479838709677'),
    (CHAR 'ablen stationesecallyought                        ', NULL, NULL, NULL, DOUBLE '466.47479838709677'),
    (CHAR 'eseeingoughteingoughtought                        ', CHAR 'scholarmaxi #9                                    ', CHAR 'history                                           ', CHAR 'Books                                             ', DOUBLE '466.48487903225805'),
    (CHAR 'eseeingoughteingoughtought                        ', CHAR 'scholarmaxi #9                                    ', CHAR 'history                                           ', NULL, DOUBLE '466.48487903225805'),
    (CHAR 'eseeingoughteingoughtought                        ', CHAR 'scholarmaxi #9                                    ', NULL, NULL, DOUBLE '466.48487903225805'),
    (CHAR 'eseeingoughteingoughtought                        ', NULL, NULL, NULL, DOUBLE '466.48487903225805'),
    (CHAR 'callyationableeseableable                         ', CHAR 'importonameless #7                                ', CHAR 'baseball                                          ', CHAR 'Sports                                            ', DOUBLE '466.62044534412956'),
    (CHAR 'callyationableeseableable                         ', CHAR 'importonameless #7                                ', CHAR 'baseball                                          ', NULL, DOUBLE '466.62044534412956'),
    (CHAR 'callyationableeseableable                         ', CHAR 'importonameless #7                                ', NULL, NULL, DOUBLE '466.62044534412956'),
    (CHAR 'callyationableeseableable                         ', NULL, NULL, NULL, DOUBLE '466.62044534412956'),
    (CHAR 'esecallypricallycallyought                        ', CHAR 'edu packimporto #1                                ', CHAR 'sports-apparel                                    ', CHAR 'Men                                               ', DOUBLE '466.785498489426'),
    (CHAR 'esecallypricallycallyought                        ', CHAR 'edu packimporto #1                                ', CHAR 'sports-apparel                                    ', NULL, DOUBLE '466.785498489426'),
    (CHAR 'esecallypricallycallyought                        ', CHAR 'edu packimporto #1                                ', NULL, NULL, DOUBLE '466.785498489426'),
    (CHAR 'esecallypricallycallyought                        ', NULL, NULL, NULL, DOUBLE '466.785498489426'),
    (CHAR 'eingcallyationoughtation                          ', CHAR 'amalgbrand #1                                     ', CHAR 'semi-precious                                     ', CHAR 'Jewelry                                           ', DOUBLE '466.8943089430894'),
    (CHAR 'eingcallyationoughtation                          ', CHAR 'amalgbrand #1                                     ', CHAR 'semi-precious                                     ', NULL, DOUBLE '466.8943089430894'),
    (CHAR 'eingcallyationoughtation                          ', CHAR 'amalgbrand #1                                     ', NULL, NULL, DOUBLE '466.8943089430894'),
    (CHAR 'eingcallyationoughtation                          ', NULL, NULL, NULL, DOUBLE '466.8943089430894')
)
