SELECT *
FROM
(
  VALUES
    (CHAR 'Almeida                       ', CHAR 'Luis                ', VARCHAR 'anti', DECIMAL '3044767.32'),
    (CHAR 'Anderson                      ', CHAR 'Heather             ', VARCHAR 'able', DECIMAL '443818.20'),
    (CHAR 'Anderson                      ', CHAR 'John                ', VARCHAR 'cally', DECIMAL '879741.10'),
    (CHAR 'Anderson                      ', CHAR 'Karen               ', VARCHAR 'ese', DECIMAL '11830684.32'),
    (CHAR 'Anderson                      ', CHAR 'Katherine           ', VARCHAR 'ation', DECIMAL '648149.32'),
    (CHAR 'Andrews                       ', CHAR 'Stephen             ', VARCHAR 'ation', DECIMAL '24852857.40'),
    (CHAR 'Armstead                      ', CHAR 'Ryan                ', VARCHAR 'n st', DECIMAL '2727741.12'),
    (CHAR 'Armstrong                     ', CHAR 'Nina                ', VARCHAR 'cally', DECIMAL '11362068.45'),
    (CHAR 'Babb                          ', CHAR 'Mark                ', VARCHAR 'able', DECIMAL '3842116.15'),
    (CHAR 'Ball                          ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '912899.92'),
    (CHAR 'Barnard                       ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '4675597.50'),
    (CHAR 'Bartley                       ', CHAR 'Sheri               ', VARCHAR 'ation', DECIMAL '9219450.24'),
    (CHAR 'Baylor                        ', CHAR 'Kendra              ', VARCHAR 'ation', DECIMAL '508311.44'),
    (CHAR 'Benitez                       ', CHAR 'Janice              ', VARCHAR 'n st', DECIMAL '400465.80'),
    (CHAR 'Bennett                       ', CHAR 'Glenn               ', VARCHAR 'ation', DECIMAL '7647617.25'),
    (CHAR 'Berg                          ', CHAR 'Michael             ', VARCHAR 'able', DECIMAL '3144727.32'),
    (CHAR 'Billiot                       ', CHAR 'Rebecca             ', VARCHAR 'able', DECIMAL '3227343.90'),
    (CHAR 'Blair                         ', CHAR 'Stephen             ', VARCHAR 'n st', DECIMAL '9878956.32'),
    (CHAR 'Boatwright                    ', CHAR 'Emma                ', VARCHAR 'cally', DECIMAL '117092.04'),
    (CHAR 'Bolling                       ', CHAR 'Thomas              ', VARCHAR 'pri', DECIMAL '4767124.44'),
    (CHAR 'Boothe                        ', CHAR 'Stanley             ', VARCHAR 'eing', DECIMAL '174267.45'),
    (CHAR 'Boyd                          ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '10598472.00'),
    (CHAR 'Boyle                         ', CHAR 'Thomas              ', VARCHAR 'ation', DECIMAL '5744001.60'),
    (CHAR 'Brant                         ', CHAR 'Joseph              ', VARCHAR 'eing', DECIMAL '15265955.25'),
    (CHAR 'Bray                          ', CHAR 'Anna                ', VARCHAR 'ese', DECIMAL '2774759.04'),
    (CHAR 'Brooks                        ', CHAR 'Jermaine            ', VARCHAR 'n st', DECIMAL '5147851.72'),
    (CHAR 'Broussard                     ', CHAR 'Daniel              ', VARCHAR 'anti', DECIMAL '144267.76'),
    (CHAR 'Brown                         ', CHAR 'Julia               ', VARCHAR 'ation', DECIMAL '166104.12'),
    (CHAR 'Brown                         ', CHAR 'Kristin             ', VARCHAR 'cally', DECIMAL '7496975.20'),
    (CHAR 'Brown                         ', CHAR 'Michael             ', VARCHAR 'ese', DECIMAL '513072.56'),
    (CHAR 'Brown                         ', CHAR 'Michelle            ', VARCHAR 'cally', DECIMAL '1501405.20'),
    (CHAR 'Brown                         ', CHAR 'Susan               ', VARCHAR 'cally', DECIMAL '47653693.20'),
    (CHAR 'Brown                         ', CHAR 'Susan               ', VARCHAR 'ese', DECIMAL '6173141.52'),
    (CHAR 'Burdette                      ', CHAR 'Amy                 ', VARCHAR 'eing', DECIMAL '43927557.52'),
    (CHAR 'Burke                         ', CHAR 'Barbara             ', VARCHAR 'able', DECIMAL '40378428.90'),
    (CHAR 'Burke                         ', CHAR 'Shea                ', VARCHAR 'able', DECIMAL '4688571.75'),
    (CHAR 'Carroll                       ', CHAR 'Doris               ', VARCHAR 'pri', DECIMAL '434004.48'),
    (CHAR 'Carroll                       ', CHAR 'Elizabeth           ', VARCHAR 'able', DECIMAL '43144487.10'),
    (CHAR 'Carter                        ', CHAR 'Jerry               ', VARCHAR 'ese', DECIMAL '6164226.95'),
    (CHAR 'Carter                        ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '5259903.48'),
    (CHAR 'Chavez                        ', CHAR 'Albert              ', VARCHAR 'able', DECIMAL '2203423.20'),
    (CHAR 'Cheney                        ', CHAR 'Claudette           ', VARCHAR 'ought', DECIMAL '2421768.96'),
    (CHAR 'Christensen                   ', CHAR 'Matilda             ', VARCHAR 'bar', DECIMAL '59114302.38'),
    (CHAR 'Christiansen                  ', CHAR 'Phyllis             ', VARCHAR 'cally', DECIMAL '10430179.76'),
    (CHAR 'Clark                         ', CHAR 'Micheline           ', VARCHAR 'bar', DECIMAL '34236489.69'),
    (CHAR 'Clayton                       ', CHAR 'Inge                ', VARCHAR 'able', DECIMAL '646417.80'),
    (CHAR 'Cochran                       ', CHAR 'Teresa              ', VARCHAR 'ought', DECIMAL '219693.24'),
    (CHAR 'Cole                          ', CHAR 'Henry               ', VARCHAR 'ation', DECIMAL '9668985.30'),
    (CHAR 'Cook                          ', CHAR 'Michael             ', VARCHAR 'cally', DECIMAL '67824484.35'),
    (CHAR 'Cooper                        ', CHAR 'Michael             ', VARCHAR 'ese', DECIMAL '3157427.16'),
    (CHAR 'Cortez                        ', CHAR 'William             ', VARCHAR 'ation', DECIMAL '4372855.08'),
    (CHAR 'Cote                          ', CHAR 'Veronica            ', VARCHAR 'able', DECIMAL '381402.10'),
    (CHAR 'Cruz                          ', CHAR 'John                ', VARCHAR 'n st', DECIMAL '8913873.36'),
    (CHAR 'Curtis                        ', CHAR 'Alicia              ', VARCHAR 'n st', DECIMAL '1816182.00'),
    (CHAR 'Davis                         ', CHAR 'Donna               ', VARCHAR 'ese', DECIMAL '18134879.40'),
    (CHAR 'Davis                         ', CHAR 'Ellen               ', VARCHAR 'n st', DECIMAL '25319286.00'),
    (CHAR 'Davis                         ', CHAR 'Mildred             ', VARCHAR 'bar', DECIMAL '36230206.05'),
    (CHAR 'Davis                         ', CHAR 'Miriam              ', VARCHAR 'cally', DECIMAL '22359116.88'),
    (CHAR 'Davis                         ', CHAR 'Tamara              ', VARCHAR 'eing', DECIMAL '2622416.30'),
    (CHAR 'Delarosa                      ', CHAR 'Rosie               ', VARCHAR 'ation', DECIMAL '12658254.00'),
    (CHAR 'Deleon                        ', CHAR 'Richard             ', VARCHAR 'ese', DECIMAL '24376581.74'),
    (CHAR 'Dixon                         ', CHAR 'Curtis              ', VARCHAR 'eing', DECIMAL '11438706.42'),
    (CHAR 'Donley                        ', CHAR 'Jesse               ', VARCHAR 'able', DECIMAL '76863222.80'),
    (CHAR 'Doran                         ', CHAR 'Judi                ', VARCHAR 'eing', DECIMAL '3489192.00'),
    (CHAR 'Dotson                        ', CHAR 'Candice             ', VARCHAR 'pri', DECIMAL '2451142.20'),
    (CHAR 'Dunlap                        ', CHAR 'Tracy               ', VARCHAR 'ation', DECIMAL '3507513.10'),
    (CHAR 'Dye                           ', CHAR 'Mona                ', VARCHAR 'able', DECIMAL '9727722.00'),
    (CHAR 'Edwards                       ', CHAR 'Chelsey             ', VARCHAR 'able', DECIMAL '63527050.95'),
    (CHAR 'Edwards                       ', CHAR 'Larry               ', VARCHAR 'bar', DECIMAL '1820674.44'),
    (CHAR 'Edwards                       ', CHAR 'Steven              ', VARCHAR 'cally', DECIMAL '16874886.60'),
    (CHAR 'Edwards                       ', CHAR 'Wai                 ', VARCHAR 'n st', DECIMAL '8903655.00'),
    (CHAR 'Enriquez                      ', CHAR 'Ana                 ', VARCHAR 'bar', DECIMAL '1536590.52'),
    (CHAR 'Erickson                      ', CHAR 'Ryan                ', VARCHAR 'bar', DECIMAL '27029079.28'),
    (CHAR 'Evans                         ', CHAR 'Timothy             ', VARCHAR 'ese', DECIMAL '111318.15'),
    (CHAR 'Fernandez                     ', CHAR 'Rhonda              ', VARCHAR 'able', DECIMAL '547463.10'),
    (CHAR 'Figueroa                      ', CHAR 'Byron               ', VARCHAR 'cally', DECIMAL '1307084.48'),
    (CHAR 'Flores                        ', CHAR 'Yolanda             ', VARCHAR 'bar', DECIMAL '273138.48'),
    (CHAR 'Floyd                         ', CHAR 'Kelvin              ', VARCHAR 'ation', DECIMAL '279938.60'),
    (CHAR 'Flynn                         ', CHAR 'Cindy               ', VARCHAR 'pri', DECIMAL '661519.56'),
    (CHAR 'Flynn                         ', CHAR 'Johnny              ', VARCHAR 'eing', DECIMAL '14963742.50'),
    (CHAR 'Fong                          ', CHAR 'Joanna              ', VARCHAR 'eing', DECIMAL '9272956.00'),
    (CHAR 'Ford                          ', CHAR 'Monte               ', VARCHAR 'eing', DECIMAL '24041112.48'),
    (CHAR 'Foster                        ', CHAR 'Merlin              ', VARCHAR 'able', DECIMAL '939487.50'),
    (CHAR 'Fowler                        ', CHAR 'Jessica             ', VARCHAR 'cally', DECIMAL '1211699.25'),
    (CHAR 'Gallagher                     ', CHAR 'Eric                ', VARCHAR 'eing', DECIMAL '22512403.98'),
    (CHAR 'Gannon                        ', CHAR 'Antoinette          ', VARCHAR 'n st', DECIMAL '62434422.12'),
    (CHAR 'Garcia                        ', CHAR 'Dennis              ', VARCHAR 'eing', DECIMAL '2819589.99'),
    (CHAR 'Garcia                        ', CHAR 'Rebecca             ', VARCHAR 'bar', DECIMAL '21368460.96'),
    (CHAR 'Gardner                       ', CHAR 'Claudia             ', VARCHAR 'able', DECIMAL '11867091.40'),
    (CHAR 'Glover                        ', CHAR 'Brenda              ', VARCHAR 'n st', DECIMAL '4995780.79'),
    (CHAR 'Gonzalez                      ', CHAR 'Eric                ', VARCHAR 'cally', DECIMAL '29587695.28'),
    (CHAR 'Gonzalez                      ', CHAR 'Yvonne              ', VARCHAR 'able', DECIMAL '46752312.10'),
    (CHAR 'Gordon                        ', CHAR 'Faustino            ', VARCHAR 'n st', DECIMAL '4725778.88'),
    (CHAR 'Gray                          ', CHAR 'Mark                ', VARCHAR 'able', DECIMAL '12834115.32'),
    (CHAR 'Green                         ', CHAR 'Terry               ', VARCHAR 'ought', DECIMAL '5882304.87'),
    (CHAR 'Grimm                         ', CHAR 'Theron              ', VARCHAR 'ese', DECIMAL '18991459.20'),
    (CHAR 'Grissom                       ', CHAR 'Jeffrey             ', VARCHAR 'bar', DECIMAL '2243753.01'),
    (CHAR 'Guthrie                       ', CHAR 'Ella                ', VARCHAR 'cally', DECIMAL '1785888.00'),
    (CHAR 'Halcomb                       ', CHAR 'Robert              ', VARCHAR 'able', DECIMAL '425311.92'),
    (CHAR 'Haley                         ', CHAR 'William             ', VARCHAR 'able', DECIMAL '20480655.60'),
    (CHAR 'Hansen                        ', CHAR 'Silvia              ', VARCHAR 'n st', DECIMAL '3768151.68'),
    (CHAR 'Hardin                        ', CHAR 'Vicki               ', VARCHAR 'n st', DECIMAL '18335907.90'),
    (CHAR 'Harkins                       ', CHAR 'Jeffrey             ', VARCHAR 'pri', DECIMAL '209288.04'),
    (CHAR 'Harris                        ', CHAR 'Edwin               ', VARCHAR 'eing', DECIMAL '1636454.34'),
    (CHAR 'Harrison                      ', CHAR 'Ronald              ', VARCHAR 'bar', DECIMAL '5022091.26'),
    (CHAR 'Haynes                        ', CHAR 'James               ', VARCHAR 'bar', DECIMAL '17071667.20'),
    (CHAR 'Henry                         ', CHAR 'Monica              ', VARCHAR 'cally', DECIMAL '1525865.37'),
    (CHAR 'Hester                        ', CHAR 'Craig               ', VARCHAR 'ese', DECIMAL '11243278.08'),
    (CHAR 'Hobson                        ', CHAR 'Brent               ', VARCHAR 'ation', DECIMAL '8268677.10'),
    (CHAR 'Hoffman                       ', CHAR 'Kristen             ', VARCHAR 'able', DECIMAL '17116567.50'),
    (CHAR 'House                         ', CHAR 'Nellie              ', VARCHAR 'cally', DECIMAL '20610326.10'),
    (CHAR 'Hughes                        ', CHAR 'Alfred              ', VARCHAR 'eing', DECIMAL '1509272.91'),
    (CHAR 'Isaacs                        ', CHAR 'Joseph              ', VARCHAR 'able', DECIMAL '17884471.05'),
    (CHAR 'James                         ', CHAR 'Mildred             ', VARCHAR 'able', DECIMAL '2441292.75'),
    (CHAR 'Jamison                       ', CHAR 'John                ', VARCHAR 'pri', DECIMAL '649607.40'),
    (CHAR 'Johnson                       ', CHAR 'Alberto             ', VARCHAR 'anti', DECIMAL '6535709.18'),
    (CHAR 'Johnson                       ', CHAR 'Amanda              ', VARCHAR 'cally', DECIMAL '18323084.50'),
    (CHAR 'Johnson                       ', CHAR 'James               ', VARCHAR 'eing', DECIMAL '4214537.46'),
    (CHAR 'Jones                         ', CHAR 'Eileen              ', VARCHAR 'able', DECIMAL '27955926.90'),
    (CHAR 'Jordon                        ', CHAR 'Charles             ', VARCHAR 'ation', DECIMAL '2968127.55'),
    (CHAR 'Jorgensen                     ', CHAR 'Joseph              ', VARCHAR 'ought', DECIMAL '509372.37'),
    (CHAR 'Keller                        ', CHAR 'Angela              ', VARCHAR 'eing', DECIMAL '3693978.18'),
    (CHAR 'Kendrick                      ', CHAR 'Donald              ', VARCHAR 'able', DECIMAL '63622484.20'),
    (CHAR 'Kenny                         ', CHAR 'Marisa              ', VARCHAR 'ation', DECIMAL '10959711.84'),
    (CHAR 'King                          ', CHAR 'Douglas             ', VARCHAR 'ation', DECIMAL '12716141.76'),
    (CHAR 'King                          ', CHAR 'Pearl               ', VARCHAR 'cally', DECIMAL '1387911.00'),
    (CHAR 'Kirby                         ', CHAR 'Julie               ', VARCHAR 'eing', DECIMAL '6876034.20'),
    (CHAR 'Knapp                         ', CHAR 'Wilbert             ', VARCHAR 'bar', DECIMAL '28891949.10'),
    (CHAR 'Kovach                        ', CHAR 'Fred                ', VARCHAR 'n st', DECIMAL '2154148.20'),
    (CHAR 'Kruger                        ', CHAR 'Jonathan            ', VARCHAR 'pri', DECIMAL '2978506.44'),
    (CHAR 'Laflamme                      ', CHAR 'Jennie              ', VARCHAR 'able', DECIMAL '883237.55'),
    (CHAR 'Lawson                        ', CHAR 'Charlotte           ', VARCHAR 'eing', DECIMAL '445446.75'),
    (CHAR 'Lentz                         ', NULL, VARCHAR 'able', DECIMAL '4624068.00'),
    (CHAR 'Lewis                         ', CHAR 'Deloris             ', VARCHAR 'able', DECIMAL '661492.80'),
    (CHAR 'Long                          ', CHAR 'Matthew             ', VARCHAR 'able', DECIMAL '1997559.20'),
    (CHAR 'Long                          ', CHAR 'Virginia            ', VARCHAR 'able', DECIMAL '12791257.05'),
    (CHAR 'Lowery                        ', CHAR 'Rick                ', VARCHAR 'able', DECIMAL '2795040.00'),
    (CHAR 'Lozano                        ', CHAR 'Brian               ', VARCHAR 'ese', DECIMAL '15512246.96'),
    (CHAR 'Lutz                          ', CHAR 'Kathleen            ', VARCHAR 'able', DECIMAL '2962029.70'),
    (CHAR 'Mackie                        ', CHAR 'Michael             ', VARCHAR 'eing', DECIMAL '30262418.64'),
    (CHAR 'Marks                         ', CHAR 'Deborah             ', VARCHAR 'n st', DECIMAL '12523947.80'),
    (CHAR 'Martin                        ', CHAR 'Christopher         ', VARCHAR 'bar', DECIMAL '420777.54'),
    (CHAR 'Martin                        ', CHAR 'Cordelia            ', VARCHAR 'ese', DECIMAL '22925168.20'),
    (CHAR 'Martinez                      ', CHAR 'Richard             ', VARCHAR 'able', DECIMAL '5533305.75'),
    (CHAR 'Massey                        ', CHAR 'Charles             ', VARCHAR 'ought', DECIMAL '2076055.76'),
    (CHAR 'Matthews                      ', CHAR 'Ann                 ', VARCHAR 'able', DECIMAL '1044994.50'),
    (CHAR 'Mauldin                       ', CHAR 'Geralyn             ', VARCHAR 'n st', DECIMAL '10359615.36'),
    (CHAR 'Mays                          ', CHAR 'Doris               ', VARCHAR 'eing', DECIMAL '2931171.39'),
    (CHAR 'Mcdowell                      ', CHAR 'Charles             ', VARCHAR 'bar', DECIMAL '25102643.44'),
    (CHAR 'Mckinney                      ', CHAR 'Hilda               ', VARCHAR 'n st', DECIMAL '5885688.64'),
    (CHAR 'Mcqueen                       ', CHAR 'William             ', VARCHAR 'able', DECIMAL '5201318.01'),
    (CHAR 'Mitchell                      ', CHAR 'Karen               ', VARCHAR 'ation', DECIMAL '23595148.80'),
    (CHAR 'Monk                          ', CHAR 'Susan               ', VARCHAR 'eing', DECIMAL '6599559.89'),
    (CHAR 'Moore                         ', CHAR 'Raymond             ', VARCHAR 'bar', DECIMAL '16930830.84'),
    (CHAR 'Moran                         ', CHAR 'Steven              ', VARCHAR 'able', DECIMAL '16381693.35'),
    (CHAR 'Morris                        ', CHAR 'Earl                ', VARCHAR 'pri', DECIMAL '5220647.64'),
    (CHAR 'Murphy                        ', CHAR 'Bruce               ', VARCHAR 'n st', DECIMAL '13110082.80'),
    (CHAR 'Murray                        ', CHAR 'Carolyn             ', VARCHAR 'cally', DECIMAL '931457.28'),
    (CHAR 'Murray                        ', CHAR 'Megan               ', VARCHAR 'n st', DECIMAL '2855714.40'),
    (CHAR 'Nichols                       ', CHAR 'Cherri              ', VARCHAR 'ese', DECIMAL '277830.74'),
    (CHAR 'Norwood                       ', CHAR 'Fredrick            ', VARCHAR 'eing', DECIMAL '287159.60'),
    (CHAR 'Numbers                       ', CHAR 'Marcie              ', VARCHAR 'cally', DECIMAL '681180.24'),
    (CHAR 'Olvera                        ', CHAR 'Warren              ', VARCHAR 'able', DECIMAL '1022609.00'),
    (CHAR 'Owens                         ', CHAR 'Elizabeth           ', VARCHAR 'cally', DECIMAL '29518130.88'),
    (CHAR 'Owens                         ', NULL, VARCHAR 'n st', DECIMAL '49407702.84'),
    (CHAR 'Parham                        ', NULL, VARCHAR 'anti', DECIMAL '20015712.36'),
    (CHAR 'Patterson                     ', CHAR 'Rebecca             ', VARCHAR 'able', DECIMAL '18658056.60'),
    (CHAR 'Payne                         ', CHAR 'Howard              ', VARCHAR 'able', DECIMAL '1416697.92'),
    (CHAR 'Peck                          ', CHAR 'William             ', VARCHAR 'able', DECIMAL '33434311.68'),
    (CHAR 'Peters                        ', CHAR 'Nancy               ', VARCHAR 'ese', DECIMAL '4242772.80'),
    (CHAR 'Petty                         ', CHAR 'Opal                ', VARCHAR 'cally', DECIMAL '2714746.02'),
    (CHAR 'Pierre                        ', CHAR 'Deborah             ', VARCHAR 'n st', DECIMAL '597940.20'),
    (CHAR 'Pierre                        ', CHAR 'Trina               ', VARCHAR 'ation', DECIMAL '5975820.08'),
    (CHAR 'Posey                         ', CHAR 'Jeffrey             ', VARCHAR 'n st', DECIMAL '3107518.40'),
    (CHAR 'Powers                        ', CHAR 'Jennifer            ', VARCHAR 'able', DECIMAL '10193962.50'),
    (CHAR 'Powers                        ', CHAR 'Joshua              ', VARCHAR 'eing', DECIMAL '544284.65'),
    (CHAR 'Pyle                          ', CHAR 'Angela              ', VARCHAR 'anti', DECIMAL '1254207.50'),
    (CHAR 'Ramos                         ', CHAR 'Gregory             ', VARCHAR 'cally', DECIMAL '5550073.65'),
    (CHAR 'Ramos                         ', CHAR 'Jose                ', VARCHAR 'cally', DECIMAL '28199765.88'),
    (CHAR 'Raney                         ', CHAR 'Daniel              ', VARCHAR 'cally', DECIMAL '4829433.30'),
    (CHAR 'Reese                         ', CHAR 'Lottie              ', VARCHAR 'able', DECIMAL '3772529.46'),
    (CHAR 'Reynolds                      ', CHAR 'Sarah               ', VARCHAR 'n st', DECIMAL '3684773.96'),
    (CHAR 'Roberge                       ', CHAR 'Rosita              ', VARCHAR 'able', DECIMAL '24511020.10'),
    (CHAR 'Robertson                     ', CHAR 'Sheila              ', VARCHAR 'n st', DECIMAL '65942880.00'),
    (CHAR 'Robles                        ', CHAR 'Tiara               ', VARCHAR 'n st', DECIMAL '1441616.75'),
    (CHAR 'Rogers                        ', CHAR 'William             ', VARCHAR 'able', DECIMAL '16802058.90'),
    (CHAR 'Rowland                       ', CHAR 'Terri               ', VARCHAR 'ation', DECIMAL '25518846.08'),
    (CHAR 'Ruiz                          ', CHAR 'Eloise              ', VARCHAR 'ought', DECIMAL '746892.93'),
    (CHAR 'Rush                          ', CHAR 'David               ', VARCHAR 'n st', DECIMAL '8404449.76'),
    (CHAR 'Sabo                          ', CHAR 'Richard             ', VARCHAR 'ese', DECIMAL '881558.85'),
    (CHAR 'Salgado                       ', CHAR 'Elizabeth           ', VARCHAR 'ation', DECIMAL '3863226.64'),
    (CHAR 'Santiago                      ', CHAR 'Larry               ', VARCHAR 'bar', DECIMAL '1797407.22'),
    (CHAR 'Santos                        ', CHAR 'Richard             ', VARCHAR 'able', DECIMAL '313933.90'),
    (CHAR 'Schubert                      ', CHAR 'John                ', VARCHAR 'pri', DECIMAL '7092363.72'),
    (CHAR 'Scott                         ', CHAR 'Paul                ', VARCHAR 'ought', DECIMAL '1563508.05'),
    (CHAR 'Sexton                        ', NULL, VARCHAR 'eing', DECIMAL '28749657.30'),
    (CHAR 'Shearer                       ', CHAR 'Andrew              ', VARCHAR 'bar', DECIMAL '50991816.96'),
    (CHAR 'Shelton                       ', CHAR 'Priscilla           ', VARCHAR 'bar', DECIMAL '6024531.87'),
    (CHAR 'Sherman                       ', CHAR 'Faye                ', VARCHAR 'eing', DECIMAL '13559659.68'),
    (CHAR 'Shields                       ', CHAR 'Gabriel             ', VARCHAR 'cally', DECIMAL '608934.04'),
    (CHAR 'Shirley                       ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '10172677.13'),
    (CHAR 'Shoemaker                     ', CHAR 'Karen               ', VARCHAR 'ation', DECIMAL '49179841.20'),
    (CHAR 'Simmons                       ', CHAR 'Debbie              ', VARCHAR 'bar', DECIMAL '1446290.64'),
    (CHAR 'Simpson                       ', CHAR 'Sandra              ', VARCHAR 'n st', DECIMAL '4368775.20'),
    (CHAR 'Singer                        ', CHAR 'Arthur              ', VARCHAR 'able', DECIMAL '688335.00'),
    (CHAR 'Smith                         ', CHAR 'Elizabeth           ', VARCHAR 'ation', DECIMAL '2052775.50'),
    (CHAR 'Smith                         ', CHAR 'Hugh                ', VARCHAR 'cally', DECIMAL '1643934.60'),
    (CHAR 'Smith                         ', CHAR 'Joseph              ', VARCHAR 'ese', DECIMAL '6580412.16'),
    (CHAR 'Smith                         ', CHAR 'Kevin               ', VARCHAR 'cally', DECIMAL '18076216.20'),
    (CHAR 'Stallings                     ', CHAR 'Sheryl              ', VARCHAR 'cally', DECIMAL '292807.20'),
    (CHAR 'Stepp                         ', CHAR 'Lori                ', VARCHAR 'cally', DECIMAL '1771777.80'),
    (CHAR 'Stevens                       ', CHAR 'Jennifer            ', VARCHAR 'able', DECIMAL '6786520.00'),
    (CHAR 'Stewart                       ', CHAR 'Roger               ', VARCHAR 'cally', DECIMAL '747881.00'),
    (CHAR 'Strunk                        ', CHAR 'Guadalupe           ', VARCHAR 'cally', DECIMAL '3567237.80'),
    (CHAR 'Tanner                        ', CHAR 'Larry               ', VARCHAR 'ese', DECIMAL '1377534.06'),
    (CHAR 'Taylor                        ', CHAR 'Michael             ', VARCHAR 'able', DECIMAL '8072151.78'),
    (CHAR 'Taylor                        ', CHAR 'William             ', VARCHAR 'able', DECIMAL '13106883.70'),
    (CHAR 'Tellez                        ', CHAR 'Mitchell            ', VARCHAR 'pri', DECIMAL '28758537.60'),
    (CHAR 'Thompson                      ', CHAR 'Judith              ', VARCHAR 'able', DECIMAL '31765864.83'),
    (CHAR 'Torres                        ', CHAR 'Tamara              ', VARCHAR 'bar', DECIMAL '6689623.14'),
    (CHAR 'Valadez                       ', CHAR 'Amy                 ', VARCHAR 'cally', DECIMAL '33173298.90'),
    (CHAR 'Vargas                        ', CHAR 'Lin                 ', VARCHAR 'bar', DECIMAL '2644132.23'),
    (CHAR 'Vega                          ', CHAR 'Michele             ', VARCHAR 'eing', DECIMAL '6830521.60'),
    (CHAR 'Ventura                       ', CHAR 'Carlos              ', VARCHAR 'able', DECIMAL '27674856.00'),
    (CHAR 'Walker                        ', CHAR 'Diane               ', VARCHAR 'eing', DECIMAL '18089144.64'),
    (CHAR 'Wallace                       ', CHAR 'William             ', VARCHAR 'able', DECIMAL '1761619.95'),
    (CHAR 'Walsh                         ', CHAR 'Christian           ', VARCHAR 'bar', DECIMAL '2504951.01'),
    (CHAR 'Warden                        ', CHAR 'David               ', VARCHAR 'ought', DECIMAL '415506.78'),
    (CHAR 'Warner                        ', CHAR 'Peggy               ', VARCHAR 'n st', DECIMAL '6223967.49'),
    (CHAR 'Watts                         ', CHAR 'Bennie              ', VARCHAR 'bar', DECIMAL '9515691.90'),
    (CHAR 'Weeks                         ', CHAR 'Robert              ', VARCHAR 'ation', DECIMAL '1903878.32'),
    (CHAR 'Welch                         ', CHAR 'Brian               ', VARCHAR 'cally', DECIMAL '1740440.16'),
    (CHAR 'Wilcox                        ', CHAR 'Jacqueline          ', VARCHAR 'bar', DECIMAL '102711.33'),
    (CHAR 'Wilcox                        ', CHAR 'Phoebe              ', VARCHAR 'ation', DECIMAL '1819526.40'),
    (CHAR 'Wilkerson                     ', CHAR 'Marc                ', VARCHAR 'n st', DECIMAL '1847915.16'),
    (CHAR 'Williams                      ', CHAR 'Christopher         ', VARCHAR 'n st', DECIMAL '667803.78'),
    (CHAR 'Williams                      ', CHAR 'Howard              ', VARCHAR 'able', DECIMAL '16513222.60'),
    (CHAR 'Williams                      ', CHAR 'Marti               ', VARCHAR 'ese', DECIMAL '7157935.62'),
    (CHAR 'Willis                        ', CHAR 'Joelle              ', VARCHAR 'able', DECIMAL '6822641.80'),
    (CHAR 'Willis                        ', CHAR 'Josephine           ', VARCHAR 'able', DECIMAL '488771.01'),
    (CHAR 'Wilson                        ', CHAR 'George              ', VARCHAR 'n st', DECIMAL '7229211.00'),
    (CHAR 'Wilson                        ', CHAR 'Matthew             ', VARCHAR 'cally', DECIMAL '2534892.36'),
    (CHAR 'Wood                          ', CHAR 'Charles             ', VARCHAR 'ation', DECIMAL '14097321.00'),
    (CHAR 'Wood                          ', CHAR 'Paul                ', VARCHAR 'cally', DECIMAL '30217078.32'),
    (CHAR 'Woods                         ', CHAR 'Frank               ', VARCHAR 'n st', DECIMAL '3672388.96'),
    (CHAR 'Woods                         ', CHAR 'Olivia              ', VARCHAR 'ation', DECIMAL '15971515.56'),
    (CHAR 'Wright                        ', CHAR 'Wayne               ', VARCHAR 'n st', DECIMAL '8296030.16'),
    (CHAR 'Wynne                         ', CHAR 'Joane               ', VARCHAR 'cally', DECIMAL '29641662.96'),
    (CHAR 'Yost                          ', CHAR 'Stephen             ', VARCHAR 'n st', DECIMAL '23641367.75'),
    (CHAR 'Zamora                        ', CHAR 'Thomas              ', VARCHAR 'able', DECIMAL '92104.10'),
    (CHAR 'Zimmerman                     ', CHAR 'Laura               ', VARCHAR 'bar', DECIMAL '594669.60'),
    (NULL, CHAR 'Steve               ', VARCHAR 'ought', DECIMAL '1524929.12'),
    (NULL, NULL, VARCHAR 'ese', DECIMAL '6454084.00'),
    (NULL, NULL, VARCHAR 'n st', DECIMAL '16809148.09'),
    (NULL, NULL, VARCHAR 'ought', DECIMAL '32620221.27')
)
