SELECT *
FROM
(
  VALUES
    (CHAR 'Aaron                         ', CHAR 'Charles             ', VARCHAR 'bar', DECIMAL '2932405.47'),
    (CHAR 'Aaron                         ', CHAR 'Roland              ', VARCHAR 'pri', DECIMAL '11449882.08'),
    (CHAR 'Aaron                         ', CHAR 'Tanya               ', VARCHAR 'n st', DECIMAL '1850239.20'),
    (CHAR 'Abraham                       ', CHAR 'Richard             ', VARCHAR 'n st', DECIMAL '15045848.86'),
    (CHAR 'Abrams                        ', CHAR 'Irene               ', VARCHAR 'able', DECIMAL '1040424.84'),
    (CHAR 'Abreu                         ', CHAR 'Jane                ', VARCHAR 'bar', DECIMAL '25670929.05'),
    (CHAR 'Abreu                         ', CHAR 'Warren              ', VARCHAR 'n st', DECIMAL '971779.68'),
    (CHAR 'Acevedo                       ', CHAR 'Willis              ', VARCHAR 'bar', DECIMAL '515057.40'),
    (CHAR 'Ackley                        ', CHAR 'David               ', VARCHAR 'ation', DECIMAL '6307180.88'),
    (CHAR 'Adams                         ', CHAR 'Alice               ', VARCHAR 'cally', DECIMAL '11433976.20'),
    (CHAR 'Adams                         ', CHAR 'Bobbie              ', VARCHAR 'anti', DECIMAL '1884242.08'),
    (CHAR 'Adams                         ', CHAR 'Dixie               ', VARCHAR 'bar', DECIMAL '7602619.41'),
    (CHAR 'Adams                         ', CHAR 'Doris               ', VARCHAR 'ese', DECIMAL '24748723.56'),
    (CHAR 'Adams                         ', CHAR 'Jesse               ', VARCHAR 'ese', DECIMAL '1487850.66'),
    (CHAR 'Adams                         ', CHAR 'Juanita             ', VARCHAR 'pri', DECIMAL '2746004.04'),
    (CHAR 'Adams                         ', CHAR 'Raymond             ', VARCHAR 'able', DECIMAL '879913.53'),
    (CHAR 'Adams                         ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '6960126.15'),
    (CHAR 'Adams                         ', CHAR 'Robert              ', VARCHAR 'n st', DECIMAL '4641406.40'),
    (CHAR 'Adams                         ', CHAR 'Thomas              ', VARCHAR 'ese', DECIMAL '12897341.71'),
    (CHAR 'Adkins                        ', CHAR 'Allan               ', VARCHAR 'pri', DECIMAL '47089486.08'),
    (CHAR 'Agnew                         ', CHAR 'Michael             ', VARCHAR 'ation', DECIMAL '165731.40'),
    (CHAR 'Ahern                         ', CHAR 'Evelyn              ', VARCHAR 'ought', DECIMAL '9672380.64'),
    (CHAR 'Ainsworth                     ', CHAR 'Martha              ', VARCHAR 'bar', DECIMAL '294086.97'),
    (CHAR 'Akin                          ', CHAR 'Calvin              ', VARCHAR 'bar', DECIMAL '3182635.44'),
    (CHAR 'Akins                         ', CHAR 'Rebecca             ', VARCHAR 'eing', DECIMAL '1858010.28'),
    (CHAR 'Aldridge                      ', CHAR 'Ryan                ', VARCHAR 'n st', DECIMAL '470247.57'),
    (CHAR 'Alexander                     ', CHAR 'Annie               ', VARCHAR 'pri', DECIMAL '1445246.40'),
    (CHAR 'Alexander                     ', CHAR 'Elda                ', VARCHAR 'cally', DECIMAL '40201098.08'),
    (CHAR 'Alexander                     ', CHAR 'Nancy               ', VARCHAR 'bar', DECIMAL '7192932.60'),
    (CHAR 'Allen                         ', CHAR 'Barbara             ', VARCHAR 'n st', DECIMAL '4312883.68'),
    (CHAR 'Allen                         ', CHAR 'Charles             ', VARCHAR 'bar', DECIMAL '5104470.96'),
    (CHAR 'Allen                         ', CHAR 'Gregory             ', VARCHAR 'ese', DECIMAL '12749965.20'),
    (CHAR 'Allen                         ', CHAR 'Ira                 ', VARCHAR 'bar', DECIMAL '1043801.64'),
    (CHAR 'Allen                         ', CHAR 'Jeff                ', VARCHAR 'able', DECIMAL '28863197.55'),
    (CHAR 'Allen                         ', CHAR 'Sybil               ', VARCHAR 'able', DECIMAL '9175601.60'),
    (CHAR 'Allison                       ', CHAR 'Angela              ', VARCHAR 'n st', DECIMAL '70392280.32'),
    (CHAR 'Alvarado                      ', CHAR 'James               ', VARCHAR 'ese', DECIMAL '2186283.00'),
    (CHAR 'Alvarado                      ', CHAR 'John                ', VARCHAR 'able', DECIMAL '367957.60'),
    (CHAR 'Anderson                      ', CHAR 'Carlos              ', VARCHAR 'able', DECIMAL '10833361.35'),
    (CHAR 'Anderson                      ', CHAR 'Florence            ', VARCHAR 'ought', DECIMAL '3394407.51'),
    (CHAR 'Anderson                      ', CHAR 'Helen               ', VARCHAR 'eing', DECIMAL '27152973.75'),
    (CHAR 'Anderson                      ', CHAR 'Jennifer            ', VARCHAR 'ese', DECIMAL '19248657.45'),
    (CHAR 'Anderson                      ', CHAR 'Lamont              ', VARCHAR 'cally', DECIMAL '24404091.60'),
    (CHAR 'Anderson                      ', CHAR 'Lester              ', VARCHAR 'ation', DECIMAL '6744342.15'),
    (CHAR 'Anderson                      ', CHAR 'Margarita           ', VARCHAR 'cally', DECIMAL '1075981.20'),
    (CHAR 'Anderson                      ', CHAR 'Pat                 ', VARCHAR 'eing', DECIMAL '30171198.75'),
    (CHAR 'Anderson                      ', CHAR 'Penny               ', VARCHAR 'ation', DECIMAL '10712898.00'),
    (CHAR 'Anderson                      ', CHAR 'Raymond             ', VARCHAR 'n st', DECIMAL '13377144.11'),
    (CHAR 'Anderson                      ', CHAR 'Scott               ', VARCHAR 'bar', DECIMAL '5141209.32'),
    (CHAR 'Anderson                      ', CHAR 'Shaun               ', VARCHAR 'bar', DECIMAL '19185588.00'),
    (CHAR 'Anderson                      ', CHAR 'Shaun               ', VARCHAR 'cally', DECIMAL '6518005.20'),
    (CHAR 'Anderson                      ', CHAR 'Thomas              ', VARCHAR 'n st', DECIMAL '3225687.84'),
    (CHAR 'Anderson                      ', CHAR 'Tom                 ', VARCHAR 'cally', DECIMAL '554192.90'),
    (CHAR 'Anderson                      ', CHAR 'Wendell             ', VARCHAR 'cally', DECIMAL '10701480.96'),
    (CHAR 'Andrade                       ', CHAR 'James               ', VARCHAR 'n st', DECIMAL '31673597.76'),
    (CHAR 'Andre                         ', NULL, VARCHAR 'bar', DECIMAL '171205.56'),
    (CHAR 'Andrews                       ', CHAR 'Claude              ', VARCHAR 'ese', DECIMAL '155832.90'),
    (CHAR 'Andrews                       ', CHAR 'Joanne              ', VARCHAR 'ation', DECIMAL '1825242.51'),
    (CHAR 'Antoine                       ', CHAR 'Ivy                 ', VARCHAR 'cally', DECIMAL '8991276.00'),
    (CHAR 'Archie                        ', CHAR 'Pat                 ', VARCHAR 'able', DECIMAL '11374608.00'),
    (CHAR 'Arias                         ', CHAR 'James               ', VARCHAR 'n st', DECIMAL '2110172.16'),
    (CHAR 'Armstead                      ', CHAR 'Henry               ', VARCHAR 'able', DECIMAL '2579151.30'),
    (CHAR 'Armstrong                     ', CHAR 'Kimberly            ', VARCHAR 'n st', DECIMAL '804892.92'),
    (CHAR 'Arnold                        ', CHAR 'Amy                 ', VARCHAR 'able', DECIMAL '2956072.55'),
    (CHAR 'Arnold                        ', CHAR 'Brian               ', VARCHAR 'ese', DECIMAL '1536129.00'),
    (CHAR 'Arreola                       ', CHAR 'Angela              ', VARCHAR 'able', DECIMAL '1883090.85'),
    (CHAR 'Arrington                     ', CHAR 'Adele               ', VARCHAR 'ation', DECIMAL '3092489.55'),
    (CHAR 'Arsenault                     ', CHAR 'Jack                ', VARCHAR 'ese', DECIMAL '4024394.64'),
    (CHAR 'Arthur                        ', CHAR 'Luisa               ', VARCHAR 'able', DECIMAL '4168368.75'),
    (CHAR 'Arthur                        ', CHAR 'Ramon               ', VARCHAR 'eing', DECIMAL '3759566.67'),
    (CHAR 'Ashby                         ', CHAR 'Charles             ', VARCHAR 'able', DECIMAL '2011493.90'),
    (CHAR 'Ashley                        ', CHAR 'Dennis              ', VARCHAR 'ought', DECIMAL '4939546.56'),
    (CHAR 'Atkinson                      ', CHAR 'Betty               ', VARCHAR 'n st', DECIMAL '511490.00'),
    (CHAR 'Atkinson                      ', CHAR 'Carley              ', VARCHAR 'ation', DECIMAL '41266991.70'),
    (CHAR 'Atwell                        ', CHAR 'Michael             ', VARCHAR 'n st', DECIMAL '5361203.68'),
    (CHAR 'Austin                        ', CHAR 'Richard             ', VARCHAR 'ation', DECIMAL '15721825.12'),
    (CHAR 'Ayala                         ', CHAR 'Bruce               ', VARCHAR 'bar', DECIMAL '1184811.88'),
    (CHAR 'Babin                         ', CHAR 'Josh                ', VARCHAR 'able', DECIMAL '631026.90'),
    (CHAR 'Bachman                       ', CHAR 'Lonnie              ', VARCHAR 'n st', DECIMAL '2684337.60'),
    (CHAR 'Baer                          ', CHAR 'Steven              ', VARCHAR 'cally', DECIMAL '2226699.75'),
    (CHAR 'Baggett                       ', CHAR 'Margaret            ', VARCHAR 'ation', DECIMAL '21817682.28'),
    (CHAR 'Bailey                        ', CHAR 'Colleen             ', VARCHAR 'able', DECIMAL '450133.20'),
    (CHAR 'Bailey                        ', CHAR 'Douglas             ', VARCHAR 'able', DECIMAL '6054522.48'),
    (CHAR 'Bailey                        ', CHAR 'Geneva              ', VARCHAR 'ought', DECIMAL '44566010.58'),
    (CHAR 'Bailey                        ', CHAR 'Lewis               ', VARCHAR 'cally', DECIMAL '5862380.40'),
    (CHAR 'Bailey                        ', CHAR 'Michael             ', VARCHAR 'cally', DECIMAL '1247608.80'),
    (CHAR 'Bailey                        ', CHAR 'Nicole              ', VARCHAR 'eing', DECIMAL '2518168.80'),
    (CHAR 'Baird                         ', CHAR 'Rita                ', VARCHAR 'eing', DECIMAL '1531217.70'),
    (CHAR 'Baker                         ', CHAR 'Annie               ', VARCHAR 'eing', DECIMAL '10593754.08'),
    (CHAR 'Baker                         ', CHAR 'Bobby               ', VARCHAR 'able', DECIMAL '5619208.95'),
    (CHAR 'Baker                         ', CHAR 'Daniel              ', VARCHAR 'able', DECIMAL '104464.62'),
    (CHAR 'Baker                         ', CHAR 'Phyllis             ', VARCHAR 'able', DECIMAL '17724375.24'),
    (CHAR 'Baldwin                       ', CHAR 'Vera                ', VARCHAR 'n st', DECIMAL '3275854.20'),
    (CHAR 'Ballou                        ', CHAR 'Gertrude            ', VARCHAR 'ese', DECIMAL '7137812.22'),
    (CHAR 'Banks                         ', CHAR 'Javier              ', VARCHAR 'able', DECIMAL '7817257.98'),
    (CHAR 'Banks                         ', CHAR 'Javier              ', VARCHAR 'cally', DECIMAL '2525198.20'),
    (CHAR 'Barger                        ', CHAR 'Christie            ', VARCHAR 'ese', DECIMAL '1778232.42'),
    (CHAR 'Barlow                        ', CHAR 'Bobby               ', VARCHAR 'eing', DECIMAL '249014.97'),
    (CHAR 'Barlow                        ', CHAR 'Gina                ', VARCHAR 'cally', DECIMAL '2578341.72'),
    (CHAR 'Barnes                        ', CHAR 'Jeffrey             ', VARCHAR 'ought', DECIMAL '266898.95'),
    (CHAR 'Barnes                        ', CHAR 'Larry               ', VARCHAR 'able', DECIMAL '2631937.77'),
    (CHAR 'Barnes                        ', CHAR 'Stella              ', VARCHAR 'ation', DECIMAL '379748.25'),
    (CHAR 'Barnett                       ', CHAR 'Donald              ', VARCHAR 'able', DECIMAL '2131566.36'),
    (CHAR 'Barney                        ', CHAR 'Brenda              ', VARCHAR 'cally', DECIMAL '1373503.56'),
    (CHAR 'Barrett                       ', CHAR 'Michael             ', VARCHAR 'able', DECIMAL '146040.84'),
    (CHAR 'Barron                        ', CHAR 'Venus               ', VARCHAR 'able', DECIMAL '419515.25'),
    (CHAR 'Barron                        ', CHAR 'Venus               ', VARCHAR 'ese', DECIMAL '123202.65'),
    (CHAR 'Barrow                        ', CHAR 'Julie               ', VARCHAR 'n st', DECIMAL '9061576.50'),
    (CHAR 'Barth                         ', CHAR 'Chad                ', VARCHAR 'able', DECIMAL '20013554.88'),
    (CHAR 'Bartlett                      ', CHAR 'Faviola             ', VARCHAR 'eing', DECIMAL '6972937.65'),
    (CHAR 'Bass                          ', CHAR 'Ruth                ', VARCHAR 'able', DECIMAL '53600788.08'),
    (CHAR 'Bateman                       ', CHAR 'Daniel              ', VARCHAR 'ese', DECIMAL '1159732.56'),
    (CHAR 'Battle                        ', CHAR 'Dawn                ', VARCHAR 'n st', DECIMAL '8093190.60'),
    (CHAR 'Batts                         ', CHAR 'Marjorie            ', VARCHAR 'eing', DECIMAL '4821891.21'),
    (CHAR 'Baumgartner                   ', CHAR 'Adam                ', VARCHAR 'n st', DECIMAL '10134670.98'),
    (CHAR 'Baxter                        ', CHAR 'Gregory             ', VARCHAR 'ation', DECIMAL '4805604.00'),
    (CHAR 'Beamon                        ', CHAR 'Marshall            ', VARCHAR 'ation', DECIMAL '670386.08'),
    (CHAR 'Bear                          ', CHAR 'Meagan              ', VARCHAR 'cally', DECIMAL '10150140.00'),
    (CHAR 'Beasley                       ', CHAR 'Craig               ', VARCHAR 'ation', DECIMAL '5132824.00'),
    (CHAR 'Beaudry                       ', CHAR 'Malcolm             ', VARCHAR 'able', DECIMAL '2511692.82'),
    (CHAR 'Becerra                       ', CHAR 'John                ', VARCHAR 'n st', DECIMAL '8780576.40'),
    (CHAR 'Beck                          ', CHAR 'Stan                ', VARCHAR 'able', DECIMAL '10667933.10'),
    (CHAR 'Bedard                        ', CHAR 'Cliff               ', VARCHAR 'cally', DECIMAL '10008407.50'),
    (CHAR 'Bell                          ', CHAR 'Angelia             ', VARCHAR 'eing', DECIMAL '615857.34'),
    (CHAR 'Bell                          ', CHAR 'Joel                ', VARCHAR 'n st', DECIMAL '8822995.16'),
    (CHAR 'Bell                          ', CHAR 'Virginia            ', VARCHAR 'ation', DECIMAL '6284677.04'),
    (CHAR 'Bell                          ', CHAR 'Wallace             ', VARCHAR 'cally', DECIMAL '875341.80'),
    (CHAR 'Bellamy                       ', CHAR 'Debbie              ', VARCHAR 'ese', DECIMAL '2642544.80'),
    (CHAR 'Beltran                       ', CHAR 'Gina                ', VARCHAR 'eing', DECIMAL '32659011.00'),
    (CHAR 'Benavides                     ', CHAR 'Susan               ', VARCHAR 'bar', DECIMAL '720088.60'),
    (CHAR 'Bender                        ', CHAR 'Esteban             ', VARCHAR 'ese', DECIMAL '3235836.60'),
    (CHAR 'Bennett                       ', CHAR 'Judy                ', VARCHAR 'ese', DECIMAL '1293007.10'),
    (CHAR 'Bennett                       ', CHAR 'Juliana             ', VARCHAR 'cally', DECIMAL '21987028.80'),
    (CHAR 'Bennett                       ', CHAR 'Lawrence            ', VARCHAR 'bar', DECIMAL '3367683.00'),
    (CHAR 'Benson                        ', CHAR 'Renee               ', VARCHAR 'able', DECIMAL '22121441.10'),
    (CHAR 'Berg                          ', CHAR 'Sylvia              ', VARCHAR 'pri', DECIMAL '2276586.00'),
    (CHAR 'Bergeron                      ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '10307203.20'),
    (CHAR 'Bermudez                      ', CHAR 'Sharon              ', VARCHAR 'ation', DECIMAL '45083168.64'),
    (CHAR 'Bernard                       ', CHAR 'Donna               ', VARCHAR 'n st', DECIMAL '1646789.76'),
    (CHAR 'Berry                         ', CHAR 'Neva                ', VARCHAR 'n st', DECIMAL '3082722.00'),
    (CHAR 'Bess                          ', CHAR 'Juan                ', VARCHAR 'ese', DECIMAL '12569153.13'),
    (CHAR 'Billingsley                   ', CHAR 'Fidel               ', VARCHAR 'cally', DECIMAL '99740.70'),
    (CHAR 'Binder                        ', CHAR 'Fannie              ', VARCHAR 'ation', DECIMAL '2726950.59'),
    (CHAR 'Bisson                        ', CHAR 'Harry               ', VARCHAR 'ation', DECIMAL '5883488.52'),
    (CHAR 'Bivens                        ', CHAR 'Dennis              ', VARCHAR 'cally', DECIMAL '3700146.56'),
    (CHAR 'Black                         ', CHAR 'Amy                 ', VARCHAR 'cally', DECIMAL '19053998.19'),
    (CHAR 'Black                         ', CHAR 'Eloise              ', VARCHAR 'pri', DECIMAL '2542564.44'),
    (CHAR 'Black                         ', CHAR 'Jeffrey             ', VARCHAR 'anti', DECIMAL '3764187.00'),
    (CHAR 'Black                         ', CHAR 'Susie               ', VARCHAR 'ation', DECIMAL '4311767.46'),
    (CHAR 'Blackmon                      ', CHAR 'William             ', VARCHAR 'ation', DECIMAL '1396364.80'),
    (CHAR 'Blackwell                     ', CHAR 'Jason               ', VARCHAR 'able', DECIMAL '1223531.25'),
    (CHAR 'Blackwell                     ', NULL, VARCHAR 'n st', DECIMAL '799617.00'),
    (CHAR 'Blake                         ', CHAR 'Allison             ', VARCHAR 'eing', DECIMAL '332060.94'),
    (CHAR 'Blanchard                     ', CHAR 'Mark                ', VARCHAR 'cally', DECIMAL '5565535.80'),
    (CHAR 'Blanton                       ', CHAR 'Louis               ', VARCHAR 'pri', DECIMAL '1270582.56'),
    (CHAR 'Bliss                         ', CHAR 'George              ', VARCHAR 'cally', DECIMAL '40108068.00'),
    (CHAR 'Block                         ', CHAR 'Reyna               ', VARCHAR 'n st', DECIMAL '10549503.90'),
    (CHAR 'Blodgett                      ', CHAR 'John                ', VARCHAR 'eing', DECIMAL '1772610.39'),
    (CHAR 'Bloom                         ', CHAR 'Georgia             ', VARCHAR 'n st', DECIMAL '3554008.20'),
    (CHAR 'Blount                        ', CHAR 'Verla               ', VARCHAR 'able', DECIMAL '8908399.50'),
    (CHAR 'Blue                          ', CHAR 'Ashley              ', VARCHAR 'n st', DECIMAL '11724288.00'),
    (CHAR 'Boggs                         ', CHAR 'Ronald              ', VARCHAR 'bar', DECIMAL '14570481.60'),
    (CHAR 'Bolton                        ', CHAR 'Arlene              ', VARCHAR 'n st', DECIMAL '308817.60'),
    (CHAR 'Bolton                        ', CHAR 'Sheldon             ', VARCHAR 'able', DECIMAL '20115982.77'),
    (CHAR 'Bond                          ', CHAR 'Edward              ', VARCHAR 'ation', DECIMAL '22682756.58'),
    (CHAR 'Boone                         ', CHAR 'Gerald              ', VARCHAR 'able', DECIMAL '11285487.36'),
    (CHAR 'Boone                         ', CHAR 'Janet               ', VARCHAR 'cally', DECIMAL '1050124.80'),
    (CHAR 'Boren                         ', CHAR 'Ellen               ', VARCHAR 'cally', DECIMAL '739874.10'),
    (CHAR 'Bostick                       ', CHAR 'Shannon             ', VARCHAR 'n st', DECIMAL '25116351.10'),
    (CHAR 'Boudreau                      ', CHAR 'Walter              ', VARCHAR 'ese', DECIMAL '13797878.40'),
    (CHAR 'Bowden                        ', CHAR 'George              ', VARCHAR 'anti', DECIMAL '1407048.72'),
    (CHAR 'Bowen                         ', CHAR 'Arlie               ', VARCHAR 'cally', DECIMAL '18879557.84'),
    (CHAR 'Bowen                         ', CHAR 'Dennis              ', VARCHAR 'ese', DECIMAL '18741799.44'),
    (CHAR 'Bowlin                        ', CHAR 'Dianne              ', VARCHAR 'able', DECIMAL '22891596.60'),
    (CHAR 'Bowling                       ', CHAR 'Jacob               ', VARCHAR 'eing', DECIMAL '2242186.24'),
    (CHAR 'Bowser                        ', CHAR 'Dorothy             ', VARCHAR 'cally', DECIMAL '9615503.36'),
    (CHAR 'Boyce                         ', CHAR 'Donald              ', VARCHAR 'ese', DECIMAL '8691038.40'),
    (CHAR 'Boyd                          ', CHAR 'Carl                ', VARCHAR 'ese', DECIMAL '23467128.39'),
    (CHAR 'Boyd                          ', CHAR 'Robert              ', VARCHAR 'cally', DECIMAL '3391780.05'),
    (CHAR 'Bradford                      ', CHAR 'Dennis              ', VARCHAR 'ation', DECIMAL '15415630.72'),
    (CHAR 'Brady                         ', CHAR 'Heather             ', VARCHAR 'ese', DECIMAL '2113064.10'),
    (CHAR 'Brantley                      ', CHAR 'Carolyn             ', VARCHAR 'ese', DECIMAL '3952949.14'),
    (CHAR 'Braun                         ', CHAR 'Earl                ', VARCHAR 'cally', DECIMAL '553238.40'),
    (CHAR 'Bravo                         ', CHAR 'Alice               ', VARCHAR 'eing', DECIMAL '18972368.80'),
    (CHAR 'Braxton                       ', CHAR 'Ahmed               ', VARCHAR 'able', DECIMAL '903844.90'),
    (CHAR 'Brazil                        ', CHAR 'Raymond             ', VARCHAR 'ation', DECIMAL '2391866.40'),
    (CHAR 'Breaux                        ', CHAR 'Daria               ', VARCHAR 'ation', DECIMAL '11954746.48'),
    (CHAR 'Brennan                       ', CHAR 'Scott               ', VARCHAR 'cally', DECIMAL '18710835.00'),
    (CHAR 'Bridges                       ', CHAR 'Carl                ', VARCHAR 'able', DECIMAL '1582703.76'),
    (CHAR 'Bridges                       ', CHAR 'Virginia            ', VARCHAR 'ation', DECIMAL '563527.38'),
    (CHAR 'Briggs                        ', CHAR 'Linda               ', VARCHAR 'able', DECIMAL '13597170.84'),
    (CHAR 'Briggs                        ', CHAR 'Raymond             ', VARCHAR 'able', DECIMAL '971159.94'),
    (CHAR 'Bright                        ', CHAR 'Roscoe              ', VARCHAR 'n st', DECIMAL '15205752.00'),
    (CHAR 'Briscoe                       ', CHAR 'Carolyn             ', VARCHAR 'eing', DECIMAL '805005.81'),
    (CHAR 'Brittain                      ', CHAR 'Evelyn              ', VARCHAR 'cally', DECIMAL '36971754.57'),
    (CHAR 'Brock                         ', CHAR 'Chris               ', VARCHAR 'able', DECIMAL '1873550.25'),
    (CHAR 'Brock                         ', CHAR 'Mel                 ', VARCHAR 'eing', DECIMAL '42498145.08'),
    (CHAR 'Brooks                        ', CHAR 'Alisha              ', VARCHAR 'ese', DECIMAL '6074327.70'),
    (CHAR 'Brooks                        ', CHAR 'James               ', VARCHAR 'ought', DECIMAL '4609444.84'),
    (CHAR 'Brooks                        ', CHAR 'Jermaine            ', VARCHAR 'ese', DECIMAL '1061886.24'),
    (CHAR 'Brooks                        ', CHAR 'Melvin              ', VARCHAR 'able', DECIMAL '9277753.32'),
    (CHAR 'Brown                         ', CHAR 'Andres              ', VARCHAR 'n st', DECIMAL '232362.60'),
    (CHAR 'Brown                         ', CHAR 'Ashley              ', VARCHAR 'cally', DECIMAL '9328551.87'),
    (CHAR 'Brown                         ', CHAR 'Cecil               ', VARCHAR 'cally', DECIMAL '404319.45'),
    (CHAR 'Brown                         ', CHAR 'Charles             ', VARCHAR 'n st', DECIMAL '1700478.00'),
    (CHAR 'Brown                         ', CHAR 'Clifford            ', VARCHAR 'ation', DECIMAL '17213731.20'),
    (CHAR 'Brown                         ', CHAR 'Elizabeth           ', VARCHAR 'cally', DECIMAL '6542710.20'),
    (CHAR 'Brown                         ', CHAR 'Ida                 ', VARCHAR 'cally', DECIMAL '513508.80'),
    (CHAR 'Brown                         ', CHAR 'Joseph              ', VARCHAR 'n st', DECIMAL '2074081.80'),
    (CHAR 'Brown                         ', CHAR 'Kimberly            ', VARCHAR 'ation', DECIMAL '2948341.44'),
    (CHAR 'Brown                         ', CHAR 'Lucy                ', VARCHAR 'cally', DECIMAL '7229401.20'),
    (CHAR 'Brown                         ', CHAR 'Lydia               ', VARCHAR 'able', DECIMAL '2154799.29'),
    (CHAR 'Brown                         ', CHAR 'Martin              ', VARCHAR 'n st', DECIMAL '1323261.60'),
    (CHAR 'Brown                         ', CHAR 'Michael             ', VARCHAR 'ese', DECIMAL '605482.36'),
    (CHAR 'Brown                         ', CHAR 'Neil                ', VARCHAR 'n st', DECIMAL '33409143.60'),
    (CHAR 'Brown                         ', CHAR 'Richard             ', VARCHAR 'cally', DECIMAL '1609001.68'),
    (CHAR 'Brown                         ', CHAR 'Richard             ', VARCHAR 'n st', DECIMAL '2130355.85'),
    (CHAR 'Brown                         ', CHAR 'Ronald              ', VARCHAR 'cally', DECIMAL '1825768.95'),
    (CHAR 'Brown                         ', CHAR 'Rufus               ', VARCHAR 'ation', DECIMAL '3827669.70'),
    (CHAR 'Brown                         ', CHAR 'Steve               ', VARCHAR 'ought', DECIMAL '33079352.86'),
    (CHAR 'Brown                         ', CHAR 'Theresa             ', VARCHAR 'ought', DECIMAL '252941.13'),
    (CHAR 'Browne                        ', CHAR 'Julie               ', VARCHAR 'bar', DECIMAL '52522662.92'),
    (CHAR 'Bruner                        ', CHAR 'Holly               ', VARCHAR 'able', DECIMAL '17217754.02'),
    (CHAR 'Bruton                        ', CHAR 'Nicholas            ', VARCHAR 'n st', DECIMAL '3866044.00'),
    (CHAR 'Bruton                        ', CHAR 'Raymond             ', VARCHAR 'able', DECIMAL '475431.50'),
    (CHAR 'Bryant                        ', CHAR 'Aaron               ', VARCHAR 'ese', DECIMAL '1134472.71'),
    (CHAR 'Bryant                        ', CHAR 'Burton              ', VARCHAR 'n st', DECIMAL '31801102.40'),
    (CHAR 'Bryant                        ', CHAR 'Nicole              ', VARCHAR 'able', DECIMAL '2134396.50'),
    (CHAR 'Bryant                        ', CHAR 'Vannessa            ', VARCHAR 'ese', DECIMAL '12774038.20'),
    (CHAR 'Buchanan                      ', CHAR 'Angela              ', VARCHAR 'able', DECIMAL '138970.52'),
    (CHAR 'Buchanan                      ', CHAR 'Eric                ', VARCHAR 'ation', DECIMAL '5608028.25'),
    (CHAR 'Buck                          ', CHAR 'Robert              ', VARCHAR 'able', DECIMAL '11248811.28'),
    (CHAR 'Bullock                       ', CHAR 'Susie               ', VARCHAR 'ation', DECIMAL '3313038.20'),
    (CHAR 'Bunch                         ', CHAR 'John                ', VARCHAR 'cally', DECIMAL '42196028.16'),
    (CHAR 'Bunker                        ', CHAR 'Trenton             ', VARCHAR 'able', DECIMAL '15197414.40'),
    (CHAR 'Bunn                          ', CHAR 'Jennifer            ', VARCHAR 'bar', DECIMAL '43567702.02'),
    (CHAR 'Burch                         ', CHAR 'Martin              ', VARCHAR 'able', DECIMAL '357003.75'),
    (CHAR 'Burgess                       ', CHAR 'Jennifer            ', VARCHAR 'cally', DECIMAL '222856.92'),
    (CHAR 'Burgess                       ', CHAR 'Selena              ', VARCHAR 'n st', DECIMAL '4639536.00'),
    (CHAR 'Burk                          ', CHAR 'Jesus               ', VARCHAR 'able', DECIMAL '1935856.35'),
    (CHAR 'Burkhart                      ', CHAR 'Christopher         ', VARCHAR 'able', DECIMAL '3438706.95'),
    (CHAR 'Burnett                       ', CHAR 'Norman              ', VARCHAR 'able', DECIMAL '5019547.50'),
    (CHAR 'Burnette                      ', CHAR 'Olga                ', VARCHAR 'cally', DECIMAL '11497097.04'),
    (CHAR 'Burton                        ', CHAR 'Martha              ', VARCHAR 'cally', DECIMAL '20687785.20'),
    (CHAR 'Burton                        ', CHAR 'Thomas              ', VARCHAR 'ese', DECIMAL '29494727.08'),
    (CHAR 'Busch                         ', CHAR 'Pamela              ', VARCHAR 'cally', DECIMAL '1704347.40'),
    (CHAR 'Bush                          ', CHAR 'Viola               ', VARCHAR 'ese', DECIMAL '14944258.56'),
    (CHAR 'Butler                        ', CHAR 'Letha               ', VARCHAR 'n st', DECIMAL '2072192.13'),
    (CHAR 'Butler                        ', CHAR 'Yvonne              ', VARCHAR 'bar', DECIMAL '20278974.42'),
    (CHAR 'Byers                         ', CHAR 'Rosaura             ', VARCHAR 'able', DECIMAL '11609383.44'),
    (CHAR 'Byrd                          ', CHAR 'Angela              ', VARCHAR 'able', DECIMAL '1312512.10'),
    (CHAR 'Byrd                          ', CHAR 'Eugene              ', VARCHAR 'able', DECIMAL '148777.65'),
    (CHAR 'Cabral                        ', CHAR 'Edith               ', VARCHAR 'eing', DECIMAL '24335874.50'),
    (CHAR 'Cabrera                       ', CHAR 'Dawn                ', VARCHAR 'eing', DECIMAL '24785885.60'),
    (CHAR 'Cagle                         ', CHAR 'Thomas              ', VARCHAR 'ought', DECIMAL '4342860.21'),
    (CHAR 'Cain                          ', CHAR 'Jimmy               ', VARCHAR 'cally', DECIMAL '2057605.44'),
    (CHAR 'Cain                          ', CHAR 'Nettie              ', VARCHAR 'ese', DECIMAL '178105.06'),
    (CHAR 'Calhoun                       ', CHAR 'Tinisha             ', VARCHAR 'ation', DECIMAL '19487396.76'),
    (CHAR 'Callahan                      ', CHAR 'Catherine           ', VARCHAR 'bar', DECIMAL '6349039.29'),
    (CHAR 'Callahan                      ', CHAR 'Melissa             ', VARCHAR 'cally', DECIMAL '19855836.00'),
    (CHAR 'Callahan                      ', CHAR 'Patrick             ', VARCHAR 'ought', DECIMAL '1932578.64'),
    (CHAR 'Camarillo                     ', CHAR 'Deanna              ', VARCHAR 'ation', DECIMAL '866659.50'),
    (CHAR 'Campbell                      ', CHAR 'Ann                 ', VARCHAR 'bar', DECIMAL '16806287.79'),
    (CHAR 'Campbell                      ', CHAR 'Charlene            ', VARCHAR 'able', DECIMAL '3494731.68'),
    (CHAR 'Candelaria                    ', CHAR 'Genevive            ', VARCHAR 'ought', DECIMAL '24884239.38'),
    (CHAR 'Cantrell                      ', CHAR 'Lori                ', VARCHAR 'cally', DECIMAL '43247974.80'),
    (CHAR 'Cantrell                      ', CHAR 'Terri               ', VARCHAR 'able', DECIMAL '740859.90'),
    (CHAR 'Cardenas                      ', CHAR 'Sandra              ', VARCHAR 'cally', DECIMAL '3623292.00'),
    (CHAR 'Cardwell                      ', CHAR 'Thomas              ', VARCHAR 'cally', DECIMAL '10553022.48'),
    (CHAR 'Carey                         ', CHAR 'Christopher         ', VARCHAR 'ation', DECIMAL '29801775.90'),
    (CHAR 'Carney                        ', CHAR 'Leonardo            ', VARCHAR 'eing', DECIMAL '7289264.92'),
    (CHAR 'Carpenter                     ', CHAR 'Stephen             ', VARCHAR 'bar', DECIMAL '5699895.88'),
    (CHAR 'Carr                          ', CHAR 'Ann                 ', VARCHAR 'cally', DECIMAL '70890309.00'),
    (CHAR 'Carr                          ', CHAR 'Bert                ', VARCHAR 'ought', DECIMAL '14490997.95'),
    (CHAR 'Carr                          ', CHAR 'Deeann              ', VARCHAR 'cally', DECIMAL '10116951.60'),
    (CHAR 'Carr                          ', CHAR 'Margaret            ', VARCHAR 'ation', DECIMAL '429429.60'),
    (CHAR 'Carr                          ', CHAR 'Tina                ', VARCHAR 'eing', DECIMAL '23516080.00'),
    (CHAR 'Carrera                       ', CHAR 'Diann               ', VARCHAR 'bar', DECIMAL '385888.95'),
    (CHAR 'Carrier                       ', CHAR 'Kristina            ', VARCHAR 'able', DECIMAL '6827946.40'),
    (CHAR 'Carroll                       ', CHAR 'Linda               ', VARCHAR 'able', DECIMAL '1952335.44'),
    (CHAR 'Carroll                       ', CHAR 'Lorraine            ', VARCHAR 'n st', DECIMAL '3426207.40'),
    (CHAR 'Carson                        ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '832199.20'),
    (CHAR 'Carter                        ', CHAR 'Charles             ', VARCHAR 'ation', DECIMAL '2292464.16'),
    (CHAR 'Carter                        ', CHAR 'Grace               ', VARCHAR 'ese', DECIMAL '673215.48'),
    (CHAR 'Carter                        ', CHAR 'Jerry               ', VARCHAR 'ese', DECIMAL '19398900.08'),
    (CHAR 'Carter                        ', CHAR 'Paul                ', VARCHAR 'cally', DECIMAL '8998777.95'),
    (CHAR 'Carter                        ', CHAR 'Santos              ', VARCHAR 'able', DECIMAL '17694635.65'),
    (CHAR 'Carvalho                      ', CHAR 'Roderick            ', VARCHAR 'ese', DECIMAL '11322899.91'),
    (CHAR 'Case                          ', CHAR 'Dewey               ', VARCHAR 'n st', DECIMAL '53604692.40'),
    (CHAR 'Casey                         ', CHAR 'Ryan                ', VARCHAR 'eing', DECIMAL '5133524.27'),
    (CHAR 'Cass                          ', CHAR 'Leonard             ', VARCHAR 'ation', DECIMAL '24121435.20'),
    (CHAR 'Cassidy                       ', CHAR 'Christine           ', VARCHAR 'able', DECIMAL '4277243.91'),
    (CHAR 'Castellanos                   ', CHAR 'Manuel              ', VARCHAR 'able', DECIMAL '18504259.20'),
    (CHAR 'Castillo                      ', CHAR 'Rita                ', VARCHAR 'able', DECIMAL '2534826.75'),
    (CHAR 'Caudill                       ', CHAR 'Andrea              ', VARCHAR 'ese', DECIMAL '844225.20'),
    (CHAR 'Cave                          ', CHAR 'Robert              ', VARCHAR 'bar', DECIMAL '9164213.38'),
    (CHAR 'Chambers                      ', CHAR 'Dan                 ', VARCHAR 'eing', DECIMAL '634247.46'),
    (CHAR 'Chambers                      ', CHAR 'Patrick             ', VARCHAR 'ation', DECIMAL '21199318.14'),
    (CHAR 'Chan                          ', CHAR 'David               ', VARCHAR 'able', DECIMAL '26421163.74'),
    (CHAR 'Chandler                      ', CHAR 'Antoinette          ', VARCHAR 'able', DECIMAL '753567.78')
)
