SELECT *
FROM
(
  VALUES
    (CHAR 'ableableantiableeingable                          '),
    (CHAR 'ableableationeingoughtable                        '),
    (CHAR 'ableableeingprieingought                          '),
    (CHAR 'ableableeseableeing                               '),
    (CHAR 'ableableoughtantiationable                        '),
    (CHAR 'ableableoughtoughteingable                        '),
    (CHAR 'ableantiableablecally                             '),
    (CHAR 'ableantieingpripri                                '),
    (CHAR 'ableationableought                                '),
    (CHAR 'ableationbarablen stable                          '),
    (CHAR 'ableationbareseableable                           '),
    (CHAR 'ableationbaroughtn stable                         '),
    (CHAR 'ableationesecallyeing                             '),
    (CHAR 'ablebareingationeingought                         '),
    (CHAR 'ablebaresecallybarought                           '),
    (CHAR 'ablecallyoughtanticallyable                       '),
    (CHAR 'ablecallyprieingbarought                          '),
    (CHAR 'ableeingationpricallyought                        '),
    (CHAR 'ableeingbareingantiought                          '),
    (CHAR 'ableeseationoughteingable                         '),
    (CHAR 'ableeseeingoughtpri                               '),
    (CHAR 'ableeseeingprianti                                '),
    (CHAR 'ableeseesen station                               '),
    (CHAR 'ablen stableationcally                            '),
    (CHAR 'ablen stcallyesepri                               '),
    (CHAR 'ablen stoughtantiation                            '),
    (CHAR 'ableoughtbarablecallyable                         '),
    (CHAR 'ableoughteingationoughtable                       '),
    (CHAR 'antiableantieingbarable                           '),
    (CHAR 'antiablecallybaroughtought                        '),
    (CHAR 'antiantiantioughtcallyought                       '),
    (CHAR 'antiantiationeingcally                            '),
    (CHAR 'antiationeingantipriought                         '),
    (CHAR 'antibarbarn stought                               '),
    (CHAR 'antibaresecallycallyought                         '),
    (CHAR 'antibarn stcallyantiable                          '),
    (CHAR 'anticallyeingationbarought                        '),
    (CHAR 'anticallyeingese                                  '),
    (CHAR 'anticallyoughtbarbarought                         '),
    (CHAR 'anticallyprianticallyought                        '),
    (CHAR 'anticallyprin stantiable                          '),
    (CHAR 'antieingeingoughtable                             '),
    (CHAR 'antieseantibaration                               '),
    (CHAR 'antieseeingn stableought                          '),
    (CHAR 'antin steseationcallyable                         '),
    (CHAR 'antioughtableanticallyought                       '),
    (CHAR 'antioughtationationcallyought                     '),
    (CHAR 'antioughteingn stpri                              '),
    (CHAR 'antipriationeseese                                '),
    (CHAR 'antipriesen stoughtought                          '),
    (CHAR 'antiprioughtbarbarable                            '),
    (CHAR 'antipripriablebarought                            '),
    (CHAR 'ationableableablen st                             '),
    (CHAR 'ationableantiationeseable                         '),
    (CHAR 'ationableeingeseanti                              '),
    (CHAR 'ationantiantibarcally                             '),
    (CHAR 'ationantieingbaranti                              '),
    (CHAR 'ationantiesen stbarable                           '),
    (CHAR 'ationantin stantieseought                         '),
    (CHAR 'ationantin steingantiought                        '),
    (CHAR 'ationantipriantiantiought                         '),
    (CHAR 'ationationablecallyationable                      '),
    (CHAR 'ationationationcallybarable                       '),
    (CHAR 'ationationationpripri                             '),
    (CHAR 'ationbarableableeingought                         '),
    (CHAR 'ationbarableprin stable                           '),
    (CHAR 'ationbarcallyablepriable                          '),
    (CHAR 'ationbareingesebarought                           '),
    (CHAR 'ationbarpriationeing                              '),
    (CHAR 'ationcallybarcallyableable                        '),
    (CHAR 'ationcallycallyesepri                             '),
    (CHAR 'ationeseationationbarought                        '),
    (CHAR 'ationeseationationese                             '),
    (CHAR 'ationesebarablepriable                            '),
    (CHAR 'ationesebarn stcallyable                          '),
    (CHAR 'ationeseese                                       '),
    (CHAR 'ationeseeseablebarought                           '),
    (CHAR 'ationn stationbarableought                        '),
    (CHAR 'ationn stcallyesecallyought                       '),
    (CHAR 'ationn steseeingable                              '),
    (CHAR 'ationoughtn steing                                '),
    (CHAR 'ationoughtn stn stationought                      '),
    (CHAR 'ationprin stoughtought                            '),
    (CHAR 'barableantiableableought                          '),
    (CHAR 'barablebarationeingable                           '),
    (CHAR 'barablen stesecally                               '),
    (CHAR 'barantiantiablepriable                            '),
    (CHAR 'barationationcallyoughtought                      '),
    (CHAR 'barbarbareseoughtought                            '),
    (CHAR 'barbareingcallyoughtable                          '),
    (CHAR 'bareingableableationable                          '),
    (CHAR 'bareingantieingbarable                            '),
    (CHAR 'bareingationpricallyought                         '),
    (CHAR 'bareingbarableableable                            '),
    (CHAR 'bareingeingeseese                                 '),
    (CHAR 'baresecallyeseableought                           '),
    (CHAR 'bareseoughtcallyable                              '),
    (CHAR 'barn stesecallyeing                               '),
    (CHAR 'barn stoughtantiation                             '),
    (CHAR 'barn stoughtprin stought                          ')
)
