SELECT *
FROM
(
  VALUES
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '52', INTEGER '500', BIGINT '52', CHAR 'Good      ', BIGINT '52'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '57', INTEGER '500', BIGINT '57', CHAR 'High Risk ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '70', INTEGER '500', BIGINT '70', CHAR 'Low Risk  ', BIGINT '70'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '48', INTEGER '500', BIGINT '48', CHAR 'Unknown   ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '1000', BIGINT '50', CHAR 'Good      ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '47', INTEGER '1000', BIGINT '47', CHAR 'High Risk ', BIGINT '47'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '42', INTEGER '1000', BIGINT '42', CHAR 'Low Risk  ', BIGINT '42'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '42', INTEGER '1000', BIGINT '42', CHAR 'Unknown   ', BIGINT '42'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '47', INTEGER '1500', BIGINT '47', CHAR 'Good      ', BIGINT '47'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '1500', BIGINT '50', CHAR 'High Risk ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '55', INTEGER '1500', BIGINT '55', CHAR 'Low Risk  ', BIGINT '55'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '53', INTEGER '1500', BIGINT '53', CHAR 'Unknown   ', BIGINT '53'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '55', INTEGER '2000', BIGINT '55', CHAR 'Good      ', BIGINT '55'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '55', INTEGER '2000', BIGINT '55', CHAR 'High Risk ', BIGINT '55'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '51', INTEGER '2000', BIGINT '51', CHAR 'Low Risk  ', BIGINT '51'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '67', INTEGER '2000', BIGINT '67', CHAR 'Unknown   ', BIGINT '67'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '65', INTEGER '2500', BIGINT '65', CHAR 'Good      ', BIGINT '65'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '38', INTEGER '2500', BIGINT '38', CHAR 'High Risk ', BIGINT '38'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '2500', BIGINT '50', CHAR 'Low Risk  ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '48', INTEGER '2500', BIGINT '48', CHAR 'Unknown   ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '52', INTEGER '3000', BIGINT '52', CHAR 'Good      ', BIGINT '52'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '57', INTEGER '3000', BIGINT '57', CHAR 'High Risk ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '65', INTEGER '3000', BIGINT '65', CHAR 'Low Risk  ', BIGINT '65'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '63', INTEGER '3000', BIGINT '63', CHAR 'Unknown   ', BIGINT '63'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '59', INTEGER '3500', BIGINT '59', CHAR 'Good      ', BIGINT '59'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '51', INTEGER '3500', BIGINT '51', CHAR 'High Risk ', BIGINT '51'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '60', INTEGER '3500', BIGINT '60', CHAR 'Low Risk  ', BIGINT '60'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '56', INTEGER '3500', BIGINT '56', CHAR 'Unknown   ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '56', INTEGER '4000', BIGINT '56', CHAR 'Good      ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '64', INTEGER '4000', BIGINT '64', CHAR 'High Risk ', BIGINT '64'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '57', INTEGER '4000', BIGINT '57', CHAR 'Low Risk  ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '57', INTEGER '4000', BIGINT '57', CHAR 'Unknown   ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '46', INTEGER '4500', BIGINT '46', CHAR 'Good      ', BIGINT '46'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '53', INTEGER '4500', BIGINT '53', CHAR 'High Risk ', BIGINT '53'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '66', INTEGER '4500', BIGINT '66', CHAR 'Low Risk  ', BIGINT '66'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '32', INTEGER '4500', BIGINT '32', CHAR 'Unknown   ', BIGINT '32'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '52', INTEGER '5000', BIGINT '52', CHAR 'Good      ', BIGINT '52'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '40', INTEGER '5000', BIGINT '40', CHAR 'High Risk ', BIGINT '40'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '5000', BIGINT '50', CHAR 'Low Risk  ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '56', INTEGER '5000', BIGINT '56', CHAR 'Unknown   ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '58', INTEGER '5500', BIGINT '58', CHAR 'Good      ', BIGINT '58'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '53', INTEGER '5500', BIGINT '53', CHAR 'High Risk ', BIGINT '53'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '60', INTEGER '5500', BIGINT '60', CHAR 'Low Risk  ', BIGINT '60'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '60', INTEGER '5500', BIGINT '60', CHAR 'Unknown   ', BIGINT '60'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '65', INTEGER '6000', BIGINT '65', CHAR 'Good      ', BIGINT '65'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '6000', BIGINT '50', CHAR 'High Risk ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '6000', BIGINT '50', CHAR 'Low Risk  ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '70', INTEGER '6000', BIGINT '70', CHAR 'Unknown   ', BIGINT '70'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '47', INTEGER '6500', BIGINT '47', CHAR 'Good      ', BIGINT '47'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '54', INTEGER '6500', BIGINT '54', CHAR 'High Risk ', BIGINT '54'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '50', INTEGER '6500', BIGINT '50', CHAR 'Low Risk  ', BIGINT '50'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '42', INTEGER '6500', BIGINT '42', CHAR 'Unknown   ', BIGINT '42'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '49', INTEGER '7000', BIGINT '49', CHAR 'Good      ', BIGINT '49'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '61', INTEGER '7000', BIGINT '61', CHAR 'High Risk ', BIGINT '61'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '53', INTEGER '7000', BIGINT '53', CHAR 'Low Risk  ', BIGINT '53'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '48', INTEGER '7000', BIGINT '48', CHAR 'Unknown   ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '48', INTEGER '7500', BIGINT '48', CHAR 'Good      ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '67', INTEGER '7500', BIGINT '67', CHAR 'High Risk ', BIGINT '67'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '67', INTEGER '7500', BIGINT '67', CHAR 'Low Risk  ', BIGINT '67'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '60', INTEGER '7500', BIGINT '60', CHAR 'Unknown   ', BIGINT '60'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '45', INTEGER '8000', BIGINT '45', CHAR 'Good      ', BIGINT '45'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '66', INTEGER '8000', BIGINT '66', CHAR 'High Risk ', BIGINT '66'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '55', INTEGER '8000', BIGINT '55', CHAR 'Low Risk  ', BIGINT '55'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '56', INTEGER '8000', BIGINT '56', CHAR 'Unknown   ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '49', INTEGER '8500', BIGINT '49', CHAR 'Good      ', BIGINT '49'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '49', INTEGER '8500', BIGINT '49', CHAR 'High Risk ', BIGINT '49'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '62', INTEGER '8500', BIGINT '62', CHAR 'Low Risk  ', BIGINT '62'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '54', INTEGER '8500', BIGINT '54', CHAR 'Unknown   ', BIGINT '54'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '56', INTEGER '9000', BIGINT '56', CHAR 'Good      ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '40', INTEGER '9000', BIGINT '40', CHAR 'High Risk ', BIGINT '40'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '60', INTEGER '9000', BIGINT '60', CHAR 'Low Risk  ', BIGINT '60'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '62', INTEGER '9000', BIGINT '62', CHAR 'Unknown   ', BIGINT '62'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '53', INTEGER '9500', BIGINT '53', CHAR 'Good      ', BIGINT '53'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '45', INTEGER '9500', BIGINT '45', CHAR 'High Risk ', BIGINT '45'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '59', INTEGER '9500', BIGINT '59', CHAR 'Low Risk  ', BIGINT '59'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '65', INTEGER '9500', BIGINT '65', CHAR 'Unknown   ', BIGINT '65'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '62', INTEGER '10000', BIGINT '62', CHAR 'Good      ', BIGINT '62'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '49', INTEGER '10000', BIGINT '49', CHAR 'High Risk ', BIGINT '49'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '47', INTEGER '10000', BIGINT '47', CHAR 'Low Risk  ', BIGINT '47'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '48', INTEGER '10000', BIGINT '48', CHAR 'Unknown   ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '43', INTEGER '500', BIGINT '43', CHAR 'Good      ', BIGINT '43'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '65', INTEGER '500', BIGINT '65', CHAR 'High Risk ', BIGINT '65'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '56', INTEGER '500', BIGINT '56', CHAR 'Low Risk  ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '49', INTEGER '500', BIGINT '49', CHAR 'Unknown   ', BIGINT '49'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '47', INTEGER '1000', BIGINT '47', CHAR 'Good      ', BIGINT '47'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '48', INTEGER '1000', BIGINT '48', CHAR 'High Risk ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '68', INTEGER '1000', BIGINT '68', CHAR 'Low Risk  ', BIGINT '68'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '45', INTEGER '1000', BIGINT '45', CHAR 'Unknown   ', BIGINT '45'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '57', INTEGER '1500', BIGINT '57', CHAR 'Good      ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '48', INTEGER '1500', BIGINT '48', CHAR 'High Risk ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '62', INTEGER '1500', BIGINT '62', CHAR 'Low Risk  ', BIGINT '62'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '59', INTEGER '1500', BIGINT '59', CHAR 'Unknown   ', BIGINT '59'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '56', INTEGER '2000', BIGINT '56', CHAR 'Good      ', BIGINT '56'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '54', INTEGER '2000', BIGINT '54', CHAR 'High Risk ', BIGINT '54'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '57', INTEGER '2000', BIGINT '57', CHAR 'Low Risk  ', BIGINT '57'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '44', INTEGER '2000', BIGINT '44', CHAR 'Unknown   ', BIGINT '44'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '48', INTEGER '2500', BIGINT '48', CHAR 'Good      ', BIGINT '48'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '42', INTEGER '2500', BIGINT '42', CHAR 'High Risk ', BIGINT '42'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '58', INTEGER '2500', BIGINT '58', CHAR 'Low Risk  ', BIGINT '58'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '54', INTEGER '2500', BIGINT '54', CHAR 'Unknown   ', BIGINT '54')
)
