SELECT *
FROM
(
  VALUES
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5212', BIGINT '0', BIGINT '68', BIGINT '68'),
    (NULL, VARCHAR 'Governments should', INTEGER '5214', BIGINT '0', BIGINT '63', BIGINT '63'),
    (NULL, VARCHAR 'Please central m', INTEGER '5215', BIGINT '0', BIGINT '63', BIGINT '63'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5217', BIGINT '0', BIGINT '62', BIGINT '62'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5214', BIGINT '0', BIGINT '59', BIGINT '59'),
    (NULL, VARCHAR 'Please central m', INTEGER '5214', BIGINT '0', BIGINT '58', BIGINT '58'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5217', BIGINT '0', BIGINT '57', BIGINT '57'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5210', BIGINT '0', BIGINT '56', BIGINT '56'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5217', BIGINT '0', BIGINT '56', BIGINT '56'),
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5214', BIGINT '0', BIGINT '55', BIGINT '55'),
    (NULL, VARCHAR 'Months woul', INTEGER '5217', BIGINT '0', BIGINT '55', BIGINT '55'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5212', BIGINT '0', BIGINT '53', BIGINT '53'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5216', BIGINT '0', BIGINT '53', BIGINT '53'),
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5210', BIGINT '0', BIGINT '53', BIGINT '53'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5210', BIGINT '0', BIGINT '53', BIGINT '53'),
    (NULL, VARCHAR 'Important dem', INTEGER '5211', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5211', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5213', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5211', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5214', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, NULL, INTEGER '5210', BIGINT '0', BIGINT '52', BIGINT '52'),
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5211', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5212', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5203', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5214', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5213', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5210', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5216', BIGINT '0', BIGINT '51', BIGINT '51'),
    (NULL, VARCHAR 'Governments should', INTEGER '5212', BIGINT '0', BIGINT '50', BIGINT '50'),
    (NULL, VARCHAR 'Months woul', INTEGER '5210', BIGINT '0', BIGINT '50', BIGINT '50'),
    (NULL, VARCHAR 'National, comple', INTEGER '5210', BIGINT '0', BIGINT '50', BIGINT '50'),
    (NULL, VARCHAR 'Important dem', INTEGER '5214', BIGINT '0', BIGINT '49', BIGINT '49'),
    (NULL, VARCHAR 'Months woul', INTEGER '5212', BIGINT '0', BIGINT '49', BIGINT '49'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5216', BIGINT '0', BIGINT '49', BIGINT '49'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5210', BIGINT '0', BIGINT '49', BIGINT '49'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5210', BIGINT '0', BIGINT '48', BIGINT '48'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5212', BIGINT '0', BIGINT '48', BIGINT '48'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5215', BIGINT '0', BIGINT '48', BIGINT '48'),
    (NULL, VARCHAR 'National, comple', INTEGER '5214', BIGINT '0', BIGINT '48', BIGINT '48'),
    (NULL, NULL, INTEGER '5215', BIGINT '0', BIGINT '48', BIGINT '48'),
    (NULL, VARCHAR 'National, comple', INTEGER '5217', BIGINT '0', BIGINT '47', BIGINT '47'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5217', BIGINT '0', BIGINT '47', BIGINT '47'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5215', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5210', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5215', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5217', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5216', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5200', BIGINT '0', BIGINT '46', BIGINT '46'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5200', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5210', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5212', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5213', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5210', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, NULL, INTEGER '5216', BIGINT '0', BIGINT '45', BIGINT '45'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5217', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5215', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Months woul', INTEGER '5202', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Months woul', INTEGER '5206', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'National, comple', INTEGER '5211', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5216', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5213', BIGINT '0', BIGINT '44', BIGINT '44'),
    (NULL, VARCHAR 'Governments should', INTEGER '5216', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5214', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5200', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5213', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5217', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5212', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5212', BIGINT '0', BIGINT '43', BIGINT '43'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5217', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Conventional childr', INTEGER '5210', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Conventional childr', INTEGER '5217', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5216', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Governments should', INTEGER '5211', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Important dem', INTEGER '5210', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'National, comple', INTEGER '5216', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5211', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5216', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Please central m', INTEGER '5211', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Please central m', INTEGER '5217', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, NULL, INTEGER '5214', BIGINT '0', BIGINT '42', BIGINT '42'),
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5216', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Empty, middle women ', INTEGER '5217', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5213', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Governments should', INTEGER '5215', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Important dem', INTEGER '5200', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5216', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Therefore urg', INTEGER '5208', BIGINT '0', BIGINT '41', BIGINT '41'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5211', BIGINT '0', BIGINT '40', BIGINT '40'),
    (NULL, VARCHAR 'Conventional childr', INTEGER '5216', BIGINT '0', BIGINT '40', BIGINT '40'),
    (NULL, VARCHAR 'Months woul', INTEGER '5215', BIGINT '0', BIGINT '40', BIGINT '40'),
    (NULL, VARCHAR 'Surprising emot', INTEGER '5217', BIGINT '0', BIGINT '40', BIGINT '40'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5215', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5216', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'Important dem', INTEGER '5208', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5210', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'Months woul', INTEGER '5214', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'National, comple', INTEGER '5200', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5212', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5215', BIGINT '0', BIGINT '39', BIGINT '39'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5212', BIGINT '0', BIGINT '39', BIGINT '39')
)
