SELECT *
FROM
(
  VALUES
    (DECIMAL '332211798493.14', NULL, NULL, INTEGER '2', BIGINT '1'),
    (DECIMAL '33593668128.88', CHAR 'Sports                                            ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '33539112650.39', CHAR 'Women                                             ', NULL, INTEGER '1', BIGINT '2'),
    (DECIMAL '33437940021.37', CHAR 'Children                                          ', NULL, INTEGER '1', BIGINT '3'),
    (DECIMAL '33160910924.75', CHAR 'Music                                             ', NULL, INTEGER '1', BIGINT '4'),
    (DECIMAL '33124997519.83', CHAR 'Books                                             ', NULL, INTEGER '1', BIGINT '5'),
    (DECIMAL '32982882903.92', CHAR 'Electronics                                       ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '32959963508.93', CHAR 'Home                                              ', NULL, INTEGER '1', BIGINT '7'),
    (DECIMAL '32940505455.25', CHAR 'Men                                               ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '32884582105.76', CHAR 'Shoes                                             ', NULL, INTEGER '1', BIGINT '9'),
    (DECIMAL '32787969556.29', CHAR 'Jewelry                                           ', NULL, INTEGER '1', BIGINT '10'),
    (DECIMAL '799265717.77', NULL, NULL, INTEGER '1', BIGINT '11'),
    (DECIMAL '2192292141.48', CHAR 'Books                                             ', CHAR 'history                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '2109528491.54', CHAR 'Books                                             ', CHAR 'reference                                         ', INTEGER '0', BIGINT '2'),
    (DECIMAL '2104938823.15', CHAR 'Books                                             ', CHAR 'romance                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '2096601625.26', CHAR 'Books                                             ', CHAR 'fiction                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '2095860008.05', CHAR 'Books                                             ', CHAR 'cooking                                           ', INTEGER '0', BIGINT '5'),
    (DECIMAL '2090768776.21', CHAR 'Books                                             ', CHAR 'sports                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '2083633360.10', CHAR 'Books                                             ', CHAR 'self-help                                         ', INTEGER '0', BIGINT '7'),
    (DECIMAL '2069460081.04', CHAR 'Books                                             ', CHAR 'business                                          ', INTEGER '0', BIGINT '8'),
    (DECIMAL '2064884693.57', CHAR 'Books                                             ', CHAR 'home repair                                       ', INTEGER '0', BIGINT '9'),
    (DECIMAL '2062266764.67', CHAR 'Books                                             ', CHAR 'parenting                                         ', INTEGER '0', BIGINT '10'),
    (DECIMAL '2058084724.52', CHAR 'Books                                             ', CHAR 'travel                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '2057595831.95', CHAR 'Books                                             ', CHAR 'entertainments                                    ', INTEGER '0', BIGINT '12'),
    (DECIMAL '2037081621.52', CHAR 'Books                                             ', CHAR 'arts                                              ', INTEGER '0', BIGINT '13'),
    (DECIMAL '2003404920.12', CHAR 'Books                                             ', CHAR 'mystery                                           ', INTEGER '0', BIGINT '14'),
    (DECIMAL '1997501647.84', CHAR 'Books                                             ', CHAR 'science                                           ', INTEGER '0', BIGINT '15'),
    (DECIMAL '1952819813.04', CHAR 'Books                                             ', CHAR 'computers                                         ', INTEGER '0', BIGINT '16'),
    (DECIMAL '48274195.77', CHAR 'Books                                             ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '8515900545.57', CHAR 'Children                                          ', CHAR 'infants                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '8415702808.34', CHAR 'Children                                          ', CHAR 'toddlers                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '8330272885.24', CHAR 'Children                                          ', CHAR 'newborn                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '8131813019.66', CHAR 'Children                                          ', CHAR 'school-uniforms                                   ', INTEGER '0', BIGINT '4'),
    (DECIMAL '44250762.56', CHAR 'Children                                          ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '2170597778.03', CHAR 'Electronics                                       ', CHAR 'televisions                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '2156489724.09', CHAR 'Electronics                                       ', CHAR 'dvd/vcr players                                   ', INTEGER '0', BIGINT '2'),
    (DECIMAL '2151828443.92', CHAR 'Electronics                                       ', CHAR 'monitors                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '2134430452.44', CHAR 'Electronics                                       ', CHAR 'karoke                                            ', INTEGER '0', BIGINT '4'),
    (DECIMAL '2104353812.01', CHAR 'Electronics                                       ', CHAR 'memory                                            ', INTEGER '0', BIGINT '5'),
    (DECIMAL '2071084450.04', CHAR 'Electronics                                       ', CHAR 'disk drives                                       ', INTEGER '0', BIGINT '6'),
    (DECIMAL '2068548621.15', CHAR 'Electronics                                       ', CHAR 'personal                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '2062815944.52', CHAR 'Electronics                                       ', CHAR 'scanners                                          ', INTEGER '0', BIGINT '8'),
    (DECIMAL '2036352813.47', CHAR 'Electronics                                       ', CHAR 'stereo                                            ', INTEGER '0', BIGINT '9'),
    (DECIMAL '2023503089.18', CHAR 'Electronics                                       ', CHAR 'camcorders                                        ', INTEGER '0', BIGINT '10'),
    (DECIMAL '2016652057.13', CHAR 'Electronics                                       ', CHAR 'portable                                          ', INTEGER '0', BIGINT '11'),
    (DECIMAL '2011029508.95', CHAR 'Electronics                                       ', CHAR 'musical                                           ', INTEGER '0', BIGINT '12'),
    (DECIMAL '2006657608.97', CHAR 'Electronics                                       ', CHAR 'automotive                                        ', INTEGER '0', BIGINT '13'),
    (DECIMAL '2004826258.76', CHAR 'Electronics                                       ', CHAR 'cameras                                           ', INTEGER '0', BIGINT '14'),
    (DECIMAL '1978640659.66', CHAR 'Electronics                                       ', CHAR 'wireless                                          ', INTEGER '0', BIGINT '15'),
    (DECIMAL '1947765172.82', CHAR 'Electronics                                       ', CHAR 'audio                                             ', INTEGER '0', BIGINT '16'),
    (DECIMAL '37306508.78', CHAR 'Electronics                                       ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '2181101986.56', CHAR 'Home                                              ', CHAR 'blinds/shades                                     ', INTEGER '0', BIGINT '1'),
    (DECIMAL '2165711746.01', CHAR 'Home                                              ', CHAR 'bedding                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '2116665697.55', CHAR 'Home                                              ', CHAR 'flatware                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '2109922738.24', CHAR 'Home                                              ', CHAR 'bathroom                                          ', INTEGER '0', BIGINT '4'),
    (DECIMAL '2099132786.02', CHAR 'Home                                              ', CHAR 'rugs                                              ', INTEGER '0', BIGINT '5'),
    (DECIMAL '2076638534.22', CHAR 'Home                                              ', CHAR 'curtains/drapes                                   ', INTEGER '0', BIGINT '6'),
    (DECIMAL '2073066377.50', CHAR 'Home                                              ', CHAR 'kids                                              ', INTEGER '0', BIGINT '7'),
    (DECIMAL '2053699050.73', CHAR 'Home                                              ', CHAR 'glassware                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '2053112179.93', CHAR 'Home                                              ', CHAR 'furniture                                         ', INTEGER '0', BIGINT '9'),
    (DECIMAL '2049654475.61', CHAR 'Home                                              ', CHAR 'tables                                            ', INTEGER '0', BIGINT '10'),
    (DECIMAL '2035033498.17', CHAR 'Home                                              ', CHAR 'paint                                             ', INTEGER '0', BIGINT '11'),
    (DECIMAL '2001148328.54', CHAR 'Home                                              ', CHAR 'mattresses                                        ', INTEGER '0', BIGINT '12'),
    (DECIMAL '1997353317.33', CHAR 'Home                                              ', CHAR 'lighting                                          ', INTEGER '0', BIGINT '13'),
    (DECIMAL '1979694451.67', CHAR 'Home                                              ', CHAR 'accent                                            ', INTEGER '0', BIGINT '14'),
    (DECIMAL '1975462684.65', CHAR 'Home                                              ', CHAR 'decor                                             ', INTEGER '0', BIGINT '15'),
    (DECIMAL '1954999668.64', CHAR 'Home                                              ', CHAR 'wallpaper                                         ', INTEGER '0', BIGINT '16'),
    (DECIMAL '37565987.56', CHAR 'Home                                              ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '2302311961.91', CHAR 'Jewelry                                           ', CHAR 'jewelry boxes                                     ', INTEGER '0', BIGINT '1'),
    (DECIMAL '2166353168.43', CHAR 'Jewelry                                           ', CHAR 'rings                                             ', INTEGER '0', BIGINT '2'),
    (DECIMAL '2125483243.18', CHAR 'Jewelry                                           ', CHAR 'womens watch                                      ', INTEGER '0', BIGINT '3'),
    (DECIMAL '2125449469.63', CHAR 'Jewelry                                           ', CHAR 'mens watch                                        ', INTEGER '0', BIGINT '4'),
    (DECIMAL '2090265480.62', CHAR 'Jewelry                                           ', CHAR 'gold                                              ', INTEGER '0', BIGINT '5'),
    (DECIMAL '2071860808.98', CHAR 'Jewelry                                           ', CHAR 'costume                                           ', INTEGER '0', BIGINT '6'),
    (DECIMAL '2041268805.92', CHAR 'Jewelry                                           ', CHAR 'estate                                            ', INTEGER '0', BIGINT '7'),
    (DECIMAL '2032374803.89', CHAR 'Jewelry                                           ', CHAR 'bracelets                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '2021968240.32', CHAR 'Jewelry                                           ', CHAR 'birdal                                            ', INTEGER '0', BIGINT '9'),
    (DECIMAL '1997561428.48', CHAR 'Jewelry                                           ', CHAR 'pendants                                          ', INTEGER '0', BIGINT '10'),
    (DECIMAL '1986399493.05', CHAR 'Jewelry                                           ', CHAR 'consignment                                       ', INTEGER '0', BIGINT '11'),
    (DECIMAL '1984313742.61', CHAR 'Jewelry                                           ', CHAR 'custom                                            ', INTEGER '0', BIGINT '12'),
    (DECIMAL '1981180535.74', CHAR 'Jewelry                                           ', CHAR 'diamonds                                          ', INTEGER '0', BIGINT '13'),
    (DECIMAL '1961144429.11', CHAR 'Jewelry                                           ', CHAR 'semi-precious                                     ', INTEGER '0', BIGINT '14'),
    (DECIMAL '1936878155.41', CHAR 'Jewelry                                           ', CHAR 'earings                                           ', INTEGER '0', BIGINT '15'),
    (DECIMAL '1925418970.84', CHAR 'Jewelry                                           ', CHAR 'loose stones                                      ', INTEGER '0', BIGINT '16'),
    (DECIMAL '37736818.17', CHAR 'Jewelry                                           ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '8416860173.03', CHAR 'Men                                               ', CHAR 'accessories                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '8284230876.43', CHAR 'Men                                               ', CHAR 'sports-apparel                                    ', INTEGER '0', BIGINT '2'),
    (DECIMAL '8240348798.20', CHAR 'Men                                               ', CHAR 'shirts                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '7946806544.49', CHAR 'Men                                               ', CHAR 'pants                                             ', INTEGER '0', BIGINT '4'),
    (DECIMAL '52259063.10', CHAR 'Men                                               ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '8458136499.22', CHAR 'Music                                             ', CHAR 'classical                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '8342299709.44', CHAR 'Music                                             ', CHAR 'country                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '8211260060.37', CHAR 'Music                                             ', CHAR 'rock                                              ', INTEGER '0', BIGINT '3'),
    (DECIMAL '8098671695.40', CHAR 'Music                                             ', CHAR 'pop                                               ', INTEGER '0', BIGINT '4'),
    (DECIMAL '50542960.32', CHAR 'Music                                             ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '8326323191.76', CHAR 'Shoes                                             ', CHAR 'athletic                                          ', INTEGER '0', BIGINT '1'),
    (DECIMAL '8232437754.81', CHAR 'Shoes                                             ', CHAR 'kids                                              ', INTEGER '0', BIGINT '2'),
    (DECIMAL '8219045049.73', CHAR 'Shoes                                             ', CHAR 'womens                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '8070840334.86', CHAR 'Shoes                                             ', CHAR 'mens                                              ', INTEGER '0', BIGINT '4'),
    (DECIMAL '35935774.60', CHAR 'Shoes                                             ', NULL, INTEGER '0', BIGINT '5')
)
