SELECT *
FROM
(
  VALUES
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '3000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '3000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '3000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '3500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '3500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '6000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '6500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '10000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '6000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '6500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '1', INTEGER '10000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '2500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '3500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '3500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '7500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '8500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '9000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '2', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'Advanced Degree     ', BIGINT '1', INTEGER '9500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '1000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '1500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '2000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '3000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '3500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '4000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '4000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '1', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '4500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '1', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '0', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5000', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '5', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'High Risk ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '5500', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '6', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '6000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '3', BIGINT '1', INTEGER '2', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Low Risk  ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '0', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '7000', BIGINT '1', CHAR 'Unknown   ', BIGINT '1', INTEGER '6', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '3', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR 'College             ', BIGINT '1', INTEGER '8000', BIGINT '1', CHAR 'Good      ', BIGINT '1', INTEGER '5', BIGINT '1', INTEGER '4', BIGINT '1', INTEGER '2', BIGINT '1')
)
