SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAAAADAAA', CHAR 'Kathryn             ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'BENIN', NULL),
    (CHAR 'AAAAAAAAAAAAEAAA', CHAR 'Robert              ', CHAR 'Patterson                     ', CHAR 'N', VARCHAR 'UNITED STATES', NULL),
    (CHAR 'AAAAAAAAAAAALAAA', CHAR 'Cathy               ', CHAR 'Salinas                       ', CHAR 'Y', VARCHAR 'PANAMA', NULL),
    (CHAR 'AAAAAAAAAAABMBAA', CHAR 'Jacqueline          ', CHAR 'Carlson                       ', CHAR 'N', VARCHAR 'FRANCE', NULL),
    (CHAR 'AAAAAAAAAAACGBAA', CHAR 'Margaret            ', CHAR 'Bender                        ', CHAR 'Y', VARCHAR 'HONG KONG', NULL),
    (CHAR 'AAAAAAAAAAACHBAA', CHAR 'Francis             ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'CROATIA', NULL),
    (CHAR 'AAAAAAAAAAACIAAA', CHAR 'Evelyn              ', CHAR 'Ferris                        ', CHAR 'Y', VARCHAR 'CUBA', NULL),
    (CHAR 'AAAAAAAAAAACJBAA', CHAR 'Kenneth             ', CHAR 'Bragg                         ', CHAR 'N', VARCHAR 'SOMALIA', NULL),
    (CHAR 'AAAAAAAAAAACOBAA', CHAR 'Sandra              ', CHAR 'Cowan                         ', CHAR 'N', VARCHAR 'CAYMAN ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAAEDAAA', CHAR 'Paula               ', CHAR 'Ferguson                      ', CHAR 'N', VARCHAR 'BAHRAIN', NULL),
    (CHAR 'AAAAAAAAAAAEEAAA', CHAR 'Richard             ', CHAR 'Jolley                        ', CHAR 'Y', VARCHAR 'FIJI', NULL),
    (CHAR 'AAAAAAAAAAAFEBAA', CHAR 'Elizabeth           ', CHAR 'Gordon                        ', CHAR 'Y', VARCHAR 'NIUE', NULL),
    (CHAR 'AAAAAAAAAAAFNBAA', CHAR 'Jeanette            ', CHAR 'Burnett                       ', CHAR 'Y', VARCHAR 'ARMENIA', NULL),
    (CHAR 'AAAAAAAAAAAGCBAA', CHAR 'Gregory             ', CHAR 'Goodwin                       ', CHAR 'Y', VARCHAR 'PAPUA NEW GUINEA', NULL),
    (CHAR 'AAAAAAAAAAAGJBAA', CHAR 'Allison             ', CHAR 'Peebles                       ', CHAR 'Y', VARCHAR 'KOREA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAAAGLAAA', CHAR 'Stephanie           ', CHAR 'Allen                         ', CHAR 'N', VARCHAR 'TONGA', NULL),
    (CHAR 'AAAAAAAAAAAGPAAA', CHAR 'Gwendolyn           ', CHAR 'Prosser                       ', CHAR 'N', VARCHAR 'SIERRA LEONE', NULL),
    (CHAR 'AAAAAAAAAAAHDAAA', CHAR 'Joyce               ', CHAR 'John                          ', CHAR 'Y', VARCHAR 'TUNISIA', NULL),
    (CHAR 'AAAAAAAAAAAHGBAA', CHAR 'William             ', CHAR 'Hernandez                     ', CHAR 'N', VARCHAR 'MONTENEGRO', NULL),
    (CHAR 'AAAAAAAAAAAHJAAA', CHAR 'William             ', CHAR 'Heck                          ', CHAR 'N', VARCHAR 'RÉUNION', NULL),
    (CHAR 'AAAAAAAAAAAIIAAA', CHAR 'Ashley              ', CHAR 'Shannon                       ', CHAR 'Y', VARCHAR 'GREECE', NULL),
    (CHAR 'AAAAAAAAAAAIJAAA', CHAR 'Nellie              ', CHAR 'Hughes                        ', CHAR 'N', VARCHAR 'SAINT HELENA', NULL),
    (CHAR 'AAAAAAAAAAAIMAAA', CHAR 'Barbara             ', NULL, NULL, NULL, NULL),
    (CHAR 'AAAAAAAAAAAINBAA', CHAR 'Salina              ', CHAR 'Harper                        ', CHAR 'Y', VARCHAR 'VANUATU', NULL),
    (CHAR 'AAAAAAAAAAAJEBAA', CHAR 'Magdalena           ', CHAR 'Steward                       ', CHAR 'N', VARCHAR 'MAYOTTE', NULL),
    (CHAR 'AAAAAAAAAAAJGAAA', CHAR 'Charles             ', CHAR 'Green                         ', CHAR 'Y', VARCHAR 'AZERBAIJAN', NULL),
    (CHAR 'AAAAAAAAAAAJHAAA', CHAR 'Anne                ', CHAR 'Chambliss                     ', CHAR 'N', VARCHAR 'SOLOMON ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAAJJAAA', CHAR 'Kimberly            ', CHAR 'Phillips                      ', CHAR 'Y', VARCHAR 'ITALY', NULL),
    (CHAR 'AAAAAAAAAAAJNBAA', CHAR 'William             ', CHAR 'Montoya                       ', CHAR 'N', VARCHAR 'AMERICAN SAMOA', NULL),
    (CHAR 'AAAAAAAAAAAJOAAA', CHAR 'Stephen             ', CHAR 'Smith                         ', CHAR 'N', VARCHAR 'SOLOMON ISLANDS', NULL),
    (CHAR 'AAAAAAAAAAAKABAA', CHAR 'Carla               ', CHAR 'Chase                         ', CHAR 'N', VARCHAR 'SLOVAKIA', NULL),
    (CHAR 'AAAAAAAAAAALEBAA', CHAR 'Marie               ', CHAR 'Ornelas                       ', CHAR 'N', VARCHAR 'SYRIAN ARAB REPUBLIC', NULL),
    (CHAR 'AAAAAAAAAAAMCBAA', NULL, CHAR 'Smith                         ', NULL, NULL, NULL),
    (CHAR 'AAAAAAAAAAAMLBAA', CHAR 'Bennie              ', CHAR 'Peters                        ', CHAR 'N', VARCHAR 'PERU', NULL),
    (CHAR 'AAAAAAAAAAAMMAAA', CHAR 'Thomas              ', CHAR 'Hanlon                        ', CHAR 'N', VARCHAR 'COMOROS', NULL),
    (CHAR 'AAAAAAAAAAANCAAA', CHAR 'Michael             ', CHAR 'Lachance                      ', CHAR 'N', VARCHAR 'MOLDOVA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAAANJBAA', CHAR 'Melvin              ', CHAR 'Baird                         ', CHAR 'N', VARCHAR 'BELARUS', NULL),
    (CHAR 'AAAAAAAAAAAODBAA', CHAR 'Barbara             ', CHAR 'Newby                         ', CHAR 'Y', VARCHAR 'NEW ZEALAND', NULL),
    (CHAR 'AAAAAAAAAAAOGBAA', CHAR 'Bonnie              ', CHAR 'Burge                         ', CHAR 'Y', VARCHAR 'QATAR', NULL),
    (CHAR 'AAAAAAAAAAAOHAAA', NULL, CHAR 'Williams                      ', CHAR 'Y', VARCHAR 'SLOVENIA', NULL),
    (CHAR 'AAAAAAAAAAAOKBAA', CHAR 'Tara                ', CHAR 'Libby                         ', CHAR 'N', VARCHAR 'MALI', NULL),
    (CHAR 'AAAAAAAAAAAPPAAA', CHAR 'Arleen              ', CHAR 'Wright                        ', CHAR 'N', VARCHAR 'CZECH REPUBLIC', NULL),
    (CHAR 'AAAAAAAAAABAFBAA', CHAR 'Susan               ', CHAR 'Wood                          ', CHAR 'N', VARCHAR 'SAUDI ARABIA', NULL),
    (CHAR 'AAAAAAAAAABALBAA', CHAR 'Thomas              ', CHAR 'Pate                          ', CHAR 'Y', VARCHAR 'SUDAN', NULL),
    (CHAR 'AAAAAAAAAABAOBAA', CHAR 'Jose                ', CHAR 'Chavez                        ', CHAR 'Y', VARCHAR 'GEORGIA', NULL),
    (CHAR 'AAAAAAAAAABBDAAA', CHAR 'Barbara             ', CHAR 'White                         ', CHAR 'Y', VARCHAR 'DOMINICA', NULL),
    (CHAR 'AAAAAAAAAABBDBAA', CHAR 'Anthony             ', CHAR 'Webb                          ', CHAR 'Y', VARCHAR 'ITALY', NULL),
    (CHAR 'AAAAAAAAAABBEBAA', CHAR 'Michael             ', CHAR 'Grossman                      ', CHAR 'Y', VARCHAR 'CANADA', NULL),
    (CHAR 'AAAAAAAAAABBGAAA', CHAR 'Cheryl              ', CHAR 'Forest                        ', CHAR 'Y', VARCHAR 'SURINAME', NULL),
    (CHAR 'AAAAAAAAAABBHBAA', CHAR 'Wendy               ', CHAR 'Guillen                       ', CHAR 'Y', VARCHAR 'ROMANIA', NULL),
    (CHAR 'AAAAAAAAAABBJBAA', CHAR 'Gerald              ', CHAR 'Christenson                   ', CHAR 'N', VARCHAR 'ALGERIA', NULL),
    (CHAR 'AAAAAAAAAABBMBAA', CHAR 'Larry               ', CHAR 'Blair                         ', CHAR 'Y', VARCHAR 'HONG KONG', NULL),
    (CHAR 'AAAAAAAAAABCCBAA', CHAR 'Emily               ', CHAR 'Cole                          ', CHAR 'Y', VARCHAR 'PERU', NULL),
    (CHAR 'AAAAAAAAAABCDAAA', CHAR 'Jennifer            ', CHAR 'Mclaughlin                    ', CHAR 'Y', VARCHAR 'MOLDOVA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAABCIBAA', CHAR 'Lisa                ', CHAR 'Luckett                       ', CHAR 'Y', VARCHAR 'GUYANA', NULL),
    (CHAR 'AAAAAAAAAABCOAAA', CHAR 'Cheryl              ', CHAR 'Green                         ', CHAR 'Y', VARCHAR 'MOZAMBIQUE', NULL),
    (CHAR 'AAAAAAAAAABDCAAA', CHAR 'Deborah             ', CHAR 'Miller                        ', CHAR 'N', VARCHAR 'MAURITANIA', NULL),
    (CHAR 'AAAAAAAAAABDKAAA', CHAR 'Lorraine            ', CHAR 'Mckinley                      ', CHAR 'N', VARCHAR 'BOTSWANA', NULL),
    (CHAR 'AAAAAAAAAABDOAAA', CHAR 'Charles             ', CHAR 'Jackson                       ', CHAR 'Y', VARCHAR 'GUATEMALA', NULL),
    (CHAR 'AAAAAAAAAABEBAAA', CHAR 'Lisa                ', CHAR 'Weaver                        ', CHAR 'Y', VARCHAR 'BENIN', NULL),
    (CHAR 'AAAAAAAAAABEEBAA', CHAR 'Mark                ', NULL, CHAR 'Y', VARCHAR 'KENYA', NULL),
    (CHAR 'AAAAAAAAAABEHAAA', CHAR 'Steve               ', CHAR 'Pratt                         ', CHAR 'N', VARCHAR 'ESTONIA', NULL),
    (CHAR 'AAAAAAAAAABEMBAA', CHAR 'Willie              ', CHAR 'Echevarria                    ', CHAR 'N', VARCHAR 'SOLOMON ISLANDS', NULL),
    (CHAR 'AAAAAAAAAABFCAAA', CHAR 'Bennett             ', CHAR 'Watson                        ', CHAR 'N', VARCHAR 'LATVIA', NULL),
    (CHAR 'AAAAAAAAAABFHAAA', CHAR 'Odessa              ', CHAR 'Ring                          ', CHAR 'N', VARCHAR 'CHINA', NULL),
    (CHAR 'AAAAAAAAAABFHBAA', CHAR 'Sherri              ', CHAR 'Caballero                     ', CHAR 'Y', VARCHAR 'GIBRALTAR', NULL),
    (CHAR 'AAAAAAAAAABGFBAA', CHAR 'Tim                 ', CHAR 'Morse                         ', CHAR 'Y', VARCHAR 'NIGERIA', NULL),
    (CHAR 'AAAAAAAAAABGGAAA', CHAR 'Marcus              ', CHAR 'Nelson                        ', CHAR 'Y', VARCHAR 'NICARAGUA', NULL),
    (CHAR 'AAAAAAAAAABGKAAA', CHAR 'Victor              ', CHAR 'Robinson                      ', CHAR 'Y', VARCHAR 'MAURITIUS', NULL),
    (CHAR 'AAAAAAAAAABGNBAA', CHAR 'Lino                ', CHAR 'Bivens                        ', CHAR 'N', VARCHAR 'BAHAMAS', NULL),
    (CHAR 'AAAAAAAAAABHLAAA', CHAR 'Ruth                ', CHAR 'Steward                       ', CHAR 'Y', VARCHAR 'LESOTHO', NULL),
    (CHAR 'AAAAAAAAAABIIBAA', NULL, CHAR 'Thompson                      ', CHAR 'N', VARCHAR 'CHINA', NULL),
    (CHAR 'AAAAAAAAAABILAAA', CHAR 'Alex                ', CHAR 'Gonzalez                      ', CHAR 'N', VARCHAR 'GUADELOUPE', NULL),
    (CHAR 'AAAAAAAAAABINBAA', CHAR 'Jesus               ', CHAR 'Mathis                        ', CHAR 'Y', VARCHAR 'LITHUANIA', NULL),
    (CHAR 'AAAAAAAAAABJBBAA', CHAR 'Alice               ', CHAR 'Barton                        ', CHAR 'Y', VARCHAR 'PANAMA', NULL),
    (CHAR 'AAAAAAAAAABKCAAA', CHAR 'Amanda              ', CHAR 'Bourgeois                     ', CHAR 'N', VARCHAR 'NICARAGUA', NULL),
    (CHAR 'AAAAAAAAAABKJBAA', CHAR 'Monique             ', CHAR 'Walters                       ', CHAR 'Y', VARCHAR 'TURKEY', NULL),
    (CHAR 'AAAAAAAAAABKMBAA', CHAR 'Velma               ', CHAR 'Thompson                      ', CHAR 'Y', VARCHAR 'LEBANON', NULL),
    (CHAR 'AAAAAAAAAABLEBAA', CHAR 'Mayra               ', CHAR 'Oconner                       ', CHAR 'N', VARCHAR 'AMERICAN SAMOA', NULL),
    (CHAR 'AAAAAAAAAABLKBAA', CHAR 'Jessica             ', CHAR 'Beaver                        ', CHAR 'Y', VARCHAR 'EQUATORIAL GUINEA', NULL),
    (CHAR 'AAAAAAAAAABMCBAA', CHAR 'Douglas             ', CHAR 'Butler                        ', CHAR 'Y', VARCHAR 'UNITED ARAB EMIRATES', NULL),
    (CHAR 'AAAAAAAAAABMNAAA', CHAR 'Shellie             ', CHAR 'Green                         ', CHAR 'Y', VARCHAR 'TURKEY', NULL),
    (CHAR 'AAAAAAAAAABNAAAA', CHAR 'Gary                ', CHAR 'Johnson                       ', CHAR 'Y', VARCHAR 'TRINIDAD AND TOBAGO', NULL),
    (CHAR 'AAAAAAAAAABNHBAA', CHAR 'Brian               ', CHAR 'Thurston                      ', CHAR 'N', VARCHAR 'BURUNDI', NULL),
    (CHAR 'AAAAAAAAAABNNBAA', CHAR 'Herbert             ', CHAR 'Watts                         ', CHAR 'N', VARCHAR 'EQUATORIAL GUINEA', NULL),
    (CHAR 'AAAAAAAAAABNPAAA', CHAR 'Dale                ', CHAR 'Fulton                        ', CHAR 'Y', VARCHAR 'EL SALVADOR', NULL),
    (CHAR 'AAAAAAAAAABOABAA', CHAR 'Robert              ', CHAR 'Rankin                        ', CHAR 'Y', VARCHAR 'MADAGASCAR', NULL),
    (CHAR 'AAAAAAAAAABOEAAA', CHAR 'Joshua              ', CHAR 'Velazquez                     ', CHAR 'Y', VARCHAR 'GHANA', NULL),
    (CHAR 'AAAAAAAAAABOIBAA', CHAR 'Melissa             ', CHAR 'Thompson                      ', CHAR 'N', VARCHAR 'KOREA, REPUBLIC OF', NULL),
    (CHAR 'AAAAAAAAAABPHBAA', CHAR 'Rebecca             ', CHAR 'Coleman                       ', CHAR 'N', VARCHAR 'AMERICAN SAMOA', NULL),
    (CHAR 'AAAAAAAAAACABBAA', CHAR 'Timothy             ', CHAR 'Gonzalez                      ', CHAR 'Y', VARCHAR 'PERU', NULL),
    (CHAR 'AAAAAAAAAACAOAAA', CHAR 'Tim                 ', CHAR 'Roberson                      ', CHAR 'N', VARCHAR 'ERITREA', NULL),
    (CHAR 'AAAAAAAAAACBMBAA', CHAR 'Stephen             ', CHAR 'Brown                         ', CHAR 'N', VARCHAR 'CYPRUS', NULL),
    (CHAR 'AAAAAAAAAACBNAAA', CHAR 'Nestor              ', CHAR 'Willoughby                    ', CHAR 'N', VARCHAR 'ISRAEL', NULL),
    (CHAR 'AAAAAAAAAACCEBAA', CHAR 'Nick                ', CHAR 'Swartz                        ', CHAR 'Y', VARCHAR 'NETHERLANDS ANTILLES', NULL),
    (CHAR 'AAAAAAAAAACCGAAA', CHAR 'Brian               ', CHAR 'Mason                         ', CHAR 'N', VARCHAR 'BAHAMAS', NULL),
    (CHAR 'AAAAAAAAAACCIAAA', CHAR 'Gretchen            ', CHAR 'Dellinger                     ', CHAR 'Y', VARCHAR 'THAILAND', NULL),
    (CHAR 'AAAAAAAAAACCLBAA', CHAR 'Arnoldo             ', CHAR 'Doucette                      ', CHAR 'N', VARCHAR 'ARGENTINA', NULL),
    (CHAR 'AAAAAAAAAACDJBAA', CHAR 'Barbara             ', CHAR 'Sanchez                       ', CHAR 'Y', VARCHAR 'GUYANA', NULL),
    (CHAR 'AAAAAAAAAACDMBAA', CHAR 'Joseph              ', CHAR 'George                        ', CHAR 'N', VARCHAR 'ALAND ISLANDS', NULL)
)
