SELECT *
FROM
(
  VALUES
    (CHAR 'eseationesen stanti                               ', CHAR 'edu packamalg #1                                  ', CHAR 'swimwear                                          ', CHAR 'Women                                             ', DOUBLE '451.7947658402204'),
    (CHAR 'eseationesen stanti                               ', CHAR 'edu packamalg #1                                  ', CHAR 'swimwear                                          ', NULL, DOUBLE '451.7947658402204'),
    (CHAR 'eseationesen stanti                               ', CHAR 'edu packamalg #1                                  ', NULL, NULL, DOUBLE '451.7947658402204'),
    (CHAR 'eseationesen stanti                               ', NULL, NULL, NULL, DOUBLE '451.7947658402204'),
    (CHAR 'oughtantiableoughtbarought                        ', CHAR 'importobrand #2                                   ', CHAR 'bedding                                           ', CHAR 'Home                                              ', DOUBLE '455.86151797603196'),
    (CHAR 'oughtantiableoughtbarought                        ', CHAR 'importobrand #2                                   ', CHAR 'bedding                                           ', NULL, DOUBLE '455.86151797603196'),
    (CHAR 'oughtantiableoughtbarought                        ', CHAR 'importobrand #2                                   ', NULL, NULL, DOUBLE '455.86151797603196'),
    (CHAR 'oughtantiableoughtbarought                        ', NULL, NULL, NULL, DOUBLE '455.86151797603196'),
    (CHAR 'callypricallyationn stought                       ', CHAR 'amalgcorp #5                                      ', CHAR 'birdal                                            ', CHAR 'Jewelry                                           ', DOUBLE '457.4351351351351'),
    (CHAR 'callypricallyationn stought                       ', CHAR 'amalgcorp #5                                      ', CHAR 'birdal                                            ', NULL, DOUBLE '457.4351351351351'),
    (CHAR 'callypricallyationn stought                       ', CHAR 'amalgcorp #5                                      ', NULL, NULL, DOUBLE '457.4351351351351'),
    (CHAR 'callypricallyationn stought                       ', NULL, NULL, NULL, DOUBLE '457.4351351351351'),
    (CHAR 'ableationantieingcallyought                       ', CHAR 'importoedu pack #1                                ', CHAR 'mens                                              ', CHAR 'Shoes                                             ', DOUBLE '457.97983870967744'),
    (CHAR 'ableationantieingcallyought                       ', CHAR 'importoedu pack #1                                ', CHAR 'mens                                              ', NULL, DOUBLE '457.97983870967744'),
    (CHAR 'ableationantieingcallyought                       ', CHAR 'importoedu pack #1                                ', NULL, NULL, DOUBLE '457.97983870967744'),
    (CHAR 'ableationantieingcallyought                       ', NULL, NULL, NULL, DOUBLE '457.97983870967744'),
    (CHAR 'n stbarn stcallyable                              ', CHAR 'edu packimporto #2                                ', CHAR 'sports-apparel                                    ', CHAR 'Men                                               ', DOUBLE '459.0810810810811'),
    (CHAR 'n stbarn stcallyable                              ', CHAR 'edu packimporto #2                                ', CHAR 'sports-apparel                                    ', NULL, DOUBLE '459.0810810810811'),
    (CHAR 'n stbarn stcallyable                              ', CHAR 'edu packimporto #2                                ', NULL, NULL, DOUBLE '459.0810810810811'),
    (CHAR 'n stbarn stcallyable                              ', NULL, NULL, NULL, DOUBLE '459.0810810810811'),
    (CHAR 'ationn stbarationpri                              ', CHAR 'edu packamalg #2                                  ', CHAR 'swimwear                                          ', CHAR 'Women                                             ', DOUBLE '460.0258152173913'),
    (CHAR 'ationn stbarationpri                              ', CHAR 'edu packamalg #2                                  ', CHAR 'swimwear                                          ', NULL, DOUBLE '460.0258152173913'),
    (CHAR 'ationn stbarationpri                              ', CHAR 'edu packamalg #2                                  ', NULL, NULL, DOUBLE '460.0258152173913'),
    (CHAR 'ationn stbarationpri                              ', NULL, NULL, NULL, DOUBLE '460.0258152173913'),
    (CHAR 'ationcallyantin stationought                      ', CHAR 'namelessbrand #8                                  ', CHAR 'lighting                                          ', CHAR 'Home                                              ', DOUBLE '460.1364256480218'),
    (CHAR 'ationcallyantin stationought                      ', CHAR 'namelessbrand #8                                  ', CHAR 'lighting                                          ', NULL, DOUBLE '460.1364256480218'),
    (CHAR 'ationcallyantin stationought                      ', CHAR 'namelessbrand #8                                  ', NULL, NULL, DOUBLE '460.1364256480218'),
    (CHAR 'ationcallyantin stationought                      ', NULL, NULL, NULL, DOUBLE '460.1364256480218'),
    (CHAR 'priantiationableoughtought                        ', CHAR 'scholarunivamalg #2                               ', CHAR 'fiction                                           ', CHAR 'Books                                             ', DOUBLE '460.28724832214766'),
    (CHAR 'priantiationableoughtought                        ', CHAR 'scholarunivamalg #2                               ', CHAR 'fiction                                           ', NULL, DOUBLE '460.28724832214766'),
    (CHAR 'priantiationableoughtought                        ', CHAR 'scholarunivamalg #2                               ', NULL, NULL, DOUBLE '460.28724832214766'),
    (CHAR 'priantiationableoughtought                        ', NULL, NULL, NULL, DOUBLE '460.28724832214766'),
    (CHAR 'esebarn stationeingought                          ', CHAR 'univamalgamalg #4                                 ', CHAR 'memory                                            ', CHAR 'Electronics                                       ', DOUBLE '460.739837398374'),
    (CHAR 'esebarn stationeingought                          ', CHAR 'univamalgamalg #4                                 ', CHAR 'memory                                            ', NULL, DOUBLE '460.739837398374'),
    (CHAR 'esebarn stationeingought                          ', CHAR 'univamalgamalg #4                                 ', NULL, NULL, DOUBLE '460.739837398374'),
    (CHAR 'esebarn stationeingought                          ', NULL, NULL, NULL, DOUBLE '460.739837398374'),
    (CHAR 'ableationoughtbaration                            ', CHAR 'importoexporti #1                                 ', CHAR 'infants                                           ', CHAR 'Children                                          ', DOUBLE '461.1588785046729'),
    (CHAR 'ableationoughtbaration                            ', CHAR 'importoexporti #1                                 ', CHAR 'infants                                           ', NULL, DOUBLE '461.1588785046729'),
    (CHAR 'ableationoughtbaration                            ', CHAR 'importoexporti #1                                 ', NULL, NULL, DOUBLE '461.1588785046729'),
    (CHAR 'ableationoughtbaration                            ', NULL, NULL, NULL, DOUBLE '461.1588785046729'),
    (CHAR 'eingoughtcallycallyanti                           ', CHAR 'scholarnameless #9                                ', CHAR 'fitness                                           ', CHAR 'Sports                                            ', DOUBLE '461.19241192411926'),
    (CHAR 'eingoughtcallycallyanti                           ', CHAR 'scholarnameless #9                                ', CHAR 'fitness                                           ', NULL, DOUBLE '461.19241192411926'),
    (CHAR 'eingoughtcallycallyanti                           ', CHAR 'scholarnameless #9                                ', NULL, NULL, DOUBLE '461.19241192411926'),
    (CHAR 'eingoughtcallycallyanti                           ', NULL, NULL, NULL, DOUBLE '461.19241192411926'),
    (CHAR 'callyablen steseable                              ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', CHAR 'Music                                             ', DOUBLE '461.35636856368563'),
    (CHAR 'callyablen steseable                              ', CHAR 'importoscholar #1                                 ', CHAR 'country                                           ', NULL, DOUBLE '461.35636856368563'),
    (CHAR 'callyablen steseable                              ', CHAR 'importoscholar #1                                 ', NULL, NULL, DOUBLE '461.35636856368563'),
    (CHAR 'callyablen steseable                              ', NULL, NULL, NULL, DOUBLE '461.35636856368563'),
    (CHAR 'pripriantieseeing                                 ', CHAR 'edu packbrand #6                                  ', CHAR 'estate                                            ', CHAR 'Jewelry                                           ', DOUBLE '461.37651821862346'),
    (CHAR 'pripriantieseeing                                 ', CHAR 'edu packbrand #6                                  ', CHAR 'estate                                            ', NULL, DOUBLE '461.37651821862346'),
    (CHAR 'pripriantieseeing                                 ', CHAR 'edu packbrand #6                                  ', NULL, NULL, DOUBLE '461.37651821862346'),
    (CHAR 'pripriantieseeing                                 ', NULL, NULL, NULL, DOUBLE '461.37651821862346'),
    (CHAR 'barationableableantiought                         ', CHAR 'exportiamalg #1                                   ', CHAR 'maternity                                         ', CHAR 'Women                                             ', DOUBLE '461.514131897712'),
    (CHAR 'barationableableantiought                         ', CHAR 'exportiamalg #1                                   ', CHAR 'maternity                                         ', NULL, DOUBLE '461.514131897712'),
    (CHAR 'barationableableantiought                         ', CHAR 'exportiamalg #1                                   ', NULL, NULL, DOUBLE '461.514131897712'),
    (CHAR 'barationableableantiought                         ', NULL, NULL, NULL, DOUBLE '461.514131897712'),
    (CHAR 'callyantipripripri                                ', CHAR 'amalgimporto #1                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '461.7991858887381'),
    (CHAR 'callyantipripripri                                ', CHAR 'amalgimporto #1                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '461.7991858887381'),
    (CHAR 'callyantipripripri                                ', CHAR 'amalgimporto #1                                   ', NULL, NULL, DOUBLE '461.7991858887381'),
    (CHAR 'callyantipripripri                                ', NULL, NULL, NULL, DOUBLE '461.7991858887381'),
    (CHAR 'n stanticallyoughtought                           ', CHAR 'maxiunivamalg #15                                 ', CHAR 'televisions                                       ', CHAR 'Electronics                                       ', DOUBLE '461.8075370121131'),
    (CHAR 'n stanticallyoughtought                           ', CHAR 'maxiunivamalg #15                                 ', CHAR 'televisions                                       ', NULL, DOUBLE '461.8075370121131'),
    (CHAR 'n stanticallyoughtought                           ', CHAR 'maxiunivamalg #15                                 ', NULL, NULL, DOUBLE '461.8075370121131'),
    (CHAR 'n stanticallyoughtought                           ', NULL, NULL, NULL, DOUBLE '461.8075370121131'),
    (CHAR 'pricallycallyeingcally                            ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '461.90040927694406'),
    (CHAR 'pricallycallyeingcally                            ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '461.90040927694406'),
    (CHAR 'pricallycallyeingcally                            ', CHAR 'amalgimporto #2                                   ', NULL, NULL, DOUBLE '461.90040927694406'),
    (CHAR 'pricallycallyeingcally                            ', NULL, NULL, NULL, DOUBLE '461.90040927694406'),
    (CHAR 'callyableeingought                                ', CHAR 'corpcorp #3                                       ', CHAR 'rings                                             ', CHAR 'Jewelry                                           ', DOUBLE '462.6864064602961'),
    (CHAR 'callyableeingought                                ', CHAR 'corpcorp #3                                       ', CHAR 'rings                                             ', NULL, DOUBLE '462.6864064602961'),
    (CHAR 'callyableeingought                                ', CHAR 'corpcorp #3                                       ', NULL, NULL, DOUBLE '462.6864064602961'),
    (CHAR 'callyableeingought                                ', NULL, NULL, NULL, DOUBLE '462.6864064602961'),
    (CHAR 'eingprieseablen st                                ', CHAR 'maxiunivamalg #10                                 ', CHAR 'televisions                                       ', CHAR 'Electronics                                       ', DOUBLE '462.70794078061914'),
    (CHAR 'eingprieseablen st                                ', CHAR 'maxiunivamalg #10                                 ', CHAR 'televisions                                       ', NULL, DOUBLE '462.70794078061914'),
    (CHAR 'eingprieseablen st                                ', CHAR 'maxiunivamalg #10                                 ', NULL, NULL, DOUBLE '462.70794078061914'),
    (CHAR 'eingprieseablen st                                ', NULL, NULL, NULL, DOUBLE '462.70794078061914'),
    (CHAR 'oughtn stcallyantieing                            ', CHAR 'importonameless #2                                ', CHAR 'paint                                             ', CHAR 'Home                                              ', DOUBLE '462.92739726027395'),
    (CHAR 'oughtn stcallyantieing                            ', CHAR 'importonameless #2                                ', CHAR 'paint                                             ', NULL, DOUBLE '462.92739726027395'),
    (CHAR 'oughtn stcallyantieing                            ', CHAR 'importonameless #2                                ', NULL, NULL, DOUBLE '462.92739726027395'),
    (CHAR 'oughtn stcallyantieing                            ', NULL, NULL, NULL, DOUBLE '462.92739726027395'),
    (CHAR 'oughtablebarbarn stought                          ', CHAR 'exportischolar #2                                 ', CHAR 'pop                                               ', CHAR 'Music                                             ', DOUBLE '463.05962059620595'),
    (CHAR 'oughtablebarbarn stought                          ', CHAR 'exportischolar #2                                 ', CHAR 'pop                                               ', NULL, DOUBLE '463.05962059620595'),
    (CHAR 'oughtablebarbarn stought                          ', CHAR 'exportischolar #2                                 ', NULL, NULL, DOUBLE '463.05962059620595'),
    (CHAR 'oughtablebarbarn stought                          ', NULL, NULL, NULL, DOUBLE '463.05962059620595'),
    (CHAR 'prieingationablebarable                           ', CHAR 'importoexporti #2                                 ', CHAR 'infants                                           ', CHAR 'Children                                          ', DOUBLE '463.0945945945946'),
    (CHAR 'prieingationablebarable                           ', CHAR 'importoexporti #2                                 ', CHAR 'infants                                           ', NULL, DOUBLE '463.0945945945946'),
    (CHAR 'prieingationablebarable                           ', CHAR 'importoexporti #2                                 ', NULL, NULL, DOUBLE '463.0945945945946'),
    (CHAR 'prieingationablebarable                           ', NULL, NULL, NULL, DOUBLE '463.0945945945946'),
    (CHAR 'n stationeseesecallyought                         ', CHAR 'corpnameless #10                                  ', CHAR 'furniture                                         ', CHAR 'Home                                              ', DOUBLE '463.18353576248313'),
    (CHAR 'n stationeseesecallyought                         ', CHAR 'corpnameless #10                                  ', CHAR 'furniture                                         ', NULL, DOUBLE '463.18353576248313'),
    (CHAR 'n stationeseesecallyought                         ', CHAR 'corpnameless #10                                  ', NULL, NULL, DOUBLE '463.18353576248313'),
    (CHAR 'n stationeseesecallyought                         ', NULL, NULL, NULL, DOUBLE '463.18353576248313'),
    (CHAR 'eingableantieingcally                             ', CHAR 'importoimporto #1                                 ', CHAR 'shirts                                            ', CHAR 'Men                                               ', DOUBLE '463.24054054054056'),
    (CHAR 'eingableantieingcally                             ', CHAR 'importoimporto #1                                 ', CHAR 'shirts                                            ', NULL, DOUBLE '463.24054054054056'),
    (CHAR 'eingableantieingcally                             ', CHAR 'importoimporto #1                                 ', NULL, NULL, DOUBLE '463.24054054054056'),
    (CHAR 'eingableantieingcally                             ', NULL, NULL, NULL, DOUBLE '463.24054054054056'),
    (CHAR 'ationantieseeinganti                              ', CHAR 'exportimaxi #8                                    ', CHAR 'sailing                                           ', CHAR 'Sports                                            ', DOUBLE '463.45417789757414'),
    (CHAR 'ationantieseeinganti                              ', CHAR 'exportimaxi #8                                    ', CHAR 'sailing                                           ', NULL, DOUBLE '463.45417789757414'),
    (CHAR 'ationantieseeinganti                              ', CHAR 'exportimaxi #8                                    ', NULL, NULL, DOUBLE '463.45417789757414'),
    (CHAR 'ationantieseeinganti                              ', NULL, NULL, NULL, DOUBLE '463.45417789757414')
)
