SELECT *
FROM
(
  VALUES
    (CHAR 'Aaron                         ', CHAR 'Frank               ', VARCHAR 'cally', DECIMAL '2148943.86'),
    (CHAR 'Acosta                        ', CHAR 'Rick                ', VARCHAR 'ese', DECIMAL '107171.10'),
    (CHAR 'Adams                         ', CHAR 'Juanita             ', VARCHAR 'bar', DECIMAL '893396.24'),
    (CHAR 'Alexander                     ', CHAR 'Henry               ', VARCHAR 'able', DECIMAL '445241.35'),
    (CHAR 'Anderson                      ', CHAR 'John                ', VARCHAR 'anti', DECIMAL '23133.60'),
    (CHAR 'Arnold                        ', CHAR 'Bridgette           ', VARCHAR 'ese', DECIMAL '2565892.62'),
    (CHAR 'Ball                          ', CHAR 'Jerry               ', VARCHAR 'ese', DECIMAL '150803.10'),
    (CHAR 'Barnes                        ', CHAR 'Annie               ', VARCHAR 'cally', DECIMAL '6747685.56'),
    (CHAR 'Bates                         ', CHAR 'Barry               ', VARCHAR 'ese', DECIMAL '4479097.50'),
    (CHAR 'Beall                         ', CHAR 'Roxie               ', VARCHAR 'ese', DECIMAL '6129003.20'),
    (CHAR 'Benson                        ', CHAR 'David               ', VARCHAR 'cally', DECIMAL '375103.41'),
    (CHAR 'Bernal                        ', CHAR 'Carlos              ', VARCHAR 'able', DECIMAL '622876.50'),
    (CHAR 'Betts                         ', CHAR 'Don                 ', VARCHAR 'cally', DECIMAL '363895.20'),
    (CHAR 'Blackburn                     ', CHAR 'Jacqueline          ', VARCHAR 'cally', DECIMAL '71278.28'),
    (CHAR 'Blackwell                     ', CHAR 'Dina                ', VARCHAR 'ought', DECIMAL '113643.00'),
    (CHAR 'Blankenship                   ', CHAR 'Eric                ', VARCHAR 'cally', DECIMAL '1267043.05'),
    (CHAR 'Boyer                         ', CHAR 'David               ', VARCHAR 'able', DECIMAL '1980217.80'),
    (CHAR 'Brown                         ', CHAR 'Gina                ', VARCHAR 'able', DECIMAL '5079947.40'),
    (CHAR 'Brown                         ', CHAR 'Israel              ', VARCHAR 'n st', DECIMAL '5348173.50'),
    (CHAR 'Bryan                         ', NULL, VARCHAR 'anti', DECIMAL '6442502.40'),
    (CHAR 'Burns                         ', CHAR 'Richard             ', VARCHAR 'bar', DECIMAL '157651.98'),
    (CHAR 'Bustos                        ', CHAR 'Eleanor             ', VARCHAR 'ese', DECIMAL '2881452.96'),
    (CHAR 'Butler                        ', CHAR 'Michael             ', VARCHAR 'ese', DECIMAL '1188184.20'),
    (CHAR 'Byrne                         ', CHAR 'Jessica             ', VARCHAR 'cally', DECIMAL '88877.70'),
    (CHAR 'Cabrera                       ', CHAR 'Ruth                ', VARCHAR 'cally', DECIMAL '82587.36'),
    (CHAR 'Caraballo                     ', CHAR 'Jerry               ', VARCHAR 'ese', DECIMAL '464478.80'),
    (CHAR 'Carson                        ', CHAR 'Vernell             ', VARCHAR 'cally', DECIMAL '346711.26'),
    (CHAR 'Chandler                      ', CHAR 'Jane                ', VARCHAR 'cally', DECIMAL '2413479.75'),
    (CHAR 'Chavarria                     ', CHAR 'Cynthia             ', VARCHAR 'able', DECIMAL '244530.00'),
    (CHAR 'Collins                       ', CHAR 'Anna                ', VARCHAR 'eing', DECIMAL '919638.72'),
    (CHAR 'Corcoran                      ', CHAR 'Fredrick            ', VARCHAR 'ese', DECIMAL '388122.80'),
    (CHAR 'Cortez                        ', CHAR 'Charles             ', VARCHAR 'anti', DECIMAL '139352.40'),
    (CHAR 'Cottrell                      ', CHAR 'Angela              ', VARCHAR 'cally', DECIMAL '204918.98'),
    (CHAR 'Crane                         ', CHAR 'Rebeca              ', VARCHAR 'cally', DECIMAL '3010934.94'),
    (CHAR 'Croft                         ', NULL, VARCHAR 'bar', DECIMAL '695863.41'),
    (CHAR 'Crooks                        ', CHAR 'Carlos              ', VARCHAR 'ese', DECIMAL '1878403.77'),
    (CHAR 'Curran                        ', CHAR 'Dennis              ', VARCHAR 'n st', DECIMAL '681296.61'),
    (CHAR 'Danforth                      ', CHAR 'Maureen             ', VARCHAR 'able', DECIMAL '16235.94'),
    (CHAR 'Davidson                      ', CHAR 'Michael             ', VARCHAR 'cally', DECIMAL '3977846.32'),
    (CHAR 'Day                           ', CHAR 'Kimberly            ', VARCHAR 'ese', DECIMAL '421473.00'),
    (CHAR 'Day                           ', CHAR 'Peter               ', VARCHAR 'able', DECIMAL '92552.34'),
    (CHAR 'Dennis                        ', CHAR 'Esther              ', VARCHAR 'cally', DECIMAL '2877574.70'),
    (CHAR 'Doan                          ', CHAR 'Mack                ', VARCHAR 'anti', DECIMAL '2642382.00'),
    (CHAR 'Dominguez                     ', CHAR 'Barbara             ', VARCHAR 'able', DECIMAL '3135666.60'),
    (CHAR 'Doyle                         ', CHAR 'Lorraine            ', VARCHAR 'n st', DECIMAL '348588.00'),
    (CHAR 'Elliott                       ', CHAR 'James               ', VARCHAR 'bar', DECIMAL '9092787.57'),
    (CHAR 'Esposito                      ', CHAR 'Rosa                ', VARCHAR 'ought', DECIMAL '505245.60'),
    (CHAR 'Fields                        ', CHAR 'Judson              ', VARCHAR 'bar', DECIMAL '2066975.84'),
    (CHAR 'Fields                        ', CHAR 'Susan               ', VARCHAR 'ese', DECIMAL '5115650.00'),
    (CHAR 'Fisher                        ', CHAR 'Natalie             ', VARCHAR 'ese', DECIMAL '2780348.20'),
    (CHAR 'Ford                          ', CHAR 'Melissa             ', VARCHAR 'n st', DECIMAL '3001999.44'),
    (CHAR 'Fowler                        ', CHAR 'Leo                 ', VARCHAR 'ese', DECIMAL '2102007.84'),
    (CHAR 'Freeman                       ', CHAR 'Richard             ', VARCHAR 'ought', DECIMAL '7416313.20'),
    (CHAR 'Frye                          ', CHAR 'Aaron               ', VARCHAR 'able', DECIMAL '3844665.00'),
    (CHAR 'Gardner                       ', CHAR 'Samuel              ', VARCHAR 'eing', DECIMAL '2401304.40'),
    (CHAR 'Green                         ', CHAR 'Steve               ', VARCHAR 'ought', DECIMAL '562077.45'),
    (CHAR 'Griffin                       ', CHAR 'Amanda              ', VARCHAR 'cally', DECIMAL '4657194.59'),
    (CHAR 'Griffin                       ', CHAR 'Gary                ', VARCHAR 'ought', DECIMAL '1373445.00'),
    (CHAR 'Griffin                       ', CHAR 'Pablo               ', VARCHAR 'n st', DECIMAL '894282.06'),
    (CHAR 'Gunther                       ', CHAR 'John                ', VARCHAR 'eing', DECIMAL '6185091.00'),
    (CHAR 'Hansen                        ', CHAR 'Norman              ', VARCHAR 'bar', DECIMAL '121178.75'),
    (CHAR 'Harmon                        ', CHAR 'So                  ', VARCHAR 'eing', DECIMAL '441894.75'),
    (CHAR 'Harrell                       ', CHAR 'Michael             ', VARCHAR 'able', DECIMAL '233962.14'),
    (CHAR 'Hawkins                       ', CHAR 'Ernest              ', VARCHAR 'bar', DECIMAL '1435605.60'),
    (CHAR 'Heller                        ', CHAR 'Charles             ', VARCHAR 'anti', DECIMAL '45781.20'),
    (CHAR 'Heller                        ', CHAR 'Charles             ', VARCHAR 'bar', DECIMAL '6131619.57'),
    (CHAR 'Henderson                     ', CHAR 'John                ', VARCHAR 'able', DECIMAL '998444.70'),
    (CHAR 'Henderson                     ', CHAR 'John                ', VARCHAR 'n st', DECIMAL '668883.16'),
    (CHAR 'Hernandez                     ', CHAR 'Teresa              ', VARCHAR 'ese', DECIMAL '983810.70'),
    (CHAR 'Hilliard                      ', CHAR 'Bryan               ', VARCHAR 'n st', DECIMAL '919854.99'),
    (CHAR 'Hines                         ', CHAR 'Vera                ', VARCHAR 'cally', DECIMAL '4782412.80'),
    (CHAR 'Hoang                         ', CHAR 'Effie               ', VARCHAR 'anti', DECIMAL '72684.00'),
    (CHAR 'Hobbs                         ', CHAR 'Ryan                ', VARCHAR 'ese', DECIMAL '2651160.00'),
    (CHAR 'Hogue                         ', CHAR 'David               ', VARCHAR 'n st', DECIMAL '770013.03'),
    (CHAR 'Holder                        ', CHAR 'Charles             ', VARCHAR 'eing', DECIMAL '727032.90'),
    (CHAR 'Holder                        ', CHAR 'Thomas              ', VARCHAR 'anti', DECIMAL '2858943.60'),
    (CHAR 'Howe                          ', CHAR 'Joanne              ', VARCHAR 'able', DECIMAL '81104.88'),
    (CHAR 'Hudgens                       ', CHAR 'Robert              ', VARCHAR 'ese', DECIMAL '939328.65'),
    (CHAR 'Hughey                        ', CHAR 'Christopher         ', VARCHAR 'ese', DECIMAL '3468744.00'),
    (CHAR 'Hunter                        ', CHAR 'Deborah             ', VARCHAR 'ese', DECIMAL '1842750.00'),
    (CHAR 'Hurst                         ', CHAR 'Donna               ', VARCHAR 'cally', DECIMAL '3074777.25'),
    (CHAR 'Irwin                         ', CHAR 'Janet               ', VARCHAR 'anti', DECIMAL '119750.40'),
    (CHAR 'Jackson                       ', CHAR 'Lee                 ', VARCHAR 'ese', DECIMAL '45813.60'),
    (CHAR 'Jarvis                        ', CHAR 'Marc                ', VARCHAR 'ought', DECIMAL '8213594.40'),
    (CHAR 'Johnson                       ', CHAR 'Adrian              ', VARCHAR 'bar', DECIMAL '209701.80'),
    (CHAR 'Johnson                       ', CHAR 'Eric                ', VARCHAR 'ese', DECIMAL '420887.20'),
    (CHAR 'Jones                         ', CHAR 'Daniel              ', VARCHAR 'anti', DECIMAL '3418448.40'),
    (CHAR 'Jones                         ', CHAR 'Georgina            ', VARCHAR 'cally', DECIMAL '224175.60'),
    (CHAR 'Jones                         ', CHAR 'Jay                 ', VARCHAR 'eing', DECIMAL '4633794.00'),
    (CHAR 'Jones                         ', CHAR 'Melvin              ', VARCHAR 'able', DECIMAL '2198780.10'),
    (CHAR 'Jones                         ', CHAR 'Nancy               ', VARCHAR 'cally', DECIMAL '79775.50'),
    (CHAR 'Kane                          ', CHAR 'Christopher         ', VARCHAR 'cally', DECIMAL '300926.18'),
    (CHAR 'Keenan                        ', CHAR 'Gonzalo             ', VARCHAR 'ought', DECIMAL '5506065.45'),
    (CHAR 'Kennedy                       ', CHAR 'Kenneth             ', VARCHAR 'cally', DECIMAL '2899269.60'),
    (CHAR 'Klein                         ', CHAR 'Anna                ', VARCHAR 'bar', DECIMAL '2401702.38'),
    (CHAR 'Lackey                        ', CHAR 'Angelo              ', VARCHAR 'ese', DECIMAL '2110480.00'),
    (CHAR 'Lacy                          ', CHAR 'Eric                ', VARCHAR 'cally', DECIMAL '573439.46'),
    (CHAR 'Lane                          ', CHAR 'Brenda              ', VARCHAR 'ese', DECIMAL '401450.67'),
    (CHAR 'Lane                          ', CHAR 'Brian               ', VARCHAR 'eing', DECIMAL '1030038.24'),
    (CHAR 'Larson                        ', CHAR 'Marjorie            ', VARCHAR 'ese', DECIMAL '3034040.00'),
    (CHAR 'Layton                        ', CHAR 'Summer              ', VARCHAR 'able', DECIMAL '422037.00'),
    (CHAR 'Leavitt                       ', CHAR 'Zonia               ', VARCHAR 'able', DECIMAL '17585692.80'),
    (CHAR 'Leon                          ', CHAR 'Rodney              ', VARCHAR 'anti', DECIMAL '85363.20'),
    (CHAR 'Lester                        ', CHAR 'Karen               ', VARCHAR 'cally', DECIMAL '750804.89'),
    (CHAR 'Lewis                         ', CHAR 'Magaret             ', VARCHAR 'n st', DECIMAL '3834643.12'),
    (CHAR 'Lima                          ', CHAR 'Ronald              ', VARCHAR 'eing', DECIMAL '927907.20'),
    (CHAR 'Little                        ', CHAR 'Jane                ', VARCHAR 'eing', DECIMAL '3995226.18'),
    (CHAR 'Little                        ', CHAR 'Ron                 ', VARCHAR 'ese', DECIMAL '186372.72'),
    (CHAR 'Lovell                        ', CHAR 'Billy               ', VARCHAR 'cally', DECIMAL '326702.97'),
    (CHAR 'Lugo                          ', CHAR 'Clayton             ', VARCHAR 'ese', DECIMAL '60500.00'),
    (CHAR 'Malone                        ', CHAR 'Frank               ', VARCHAR 'bar', DECIMAL '58417.60'),
    (CHAR 'Markley                       ', CHAR 'Wm                  ', VARCHAR 'cally', DECIMAL '1417546.22'),
    (CHAR 'Martinez                      ', CHAR 'Anthony             ', VARCHAR 'cally', DECIMAL '179445.33'),
    (CHAR 'Mason                         ', CHAR 'Jack                ', VARCHAR 'able', DECIMAL '1299311.65'),
    (CHAR 'Massey                        ', CHAR 'Heather             ', VARCHAR 'eing', DECIMAL '1955725.20'),
    (CHAR 'Masters                       ', CHAR 'Thomas              ', VARCHAR 'able', DECIMAL '3953129.40'),
    (CHAR 'Mathis                        ', CHAR 'Linda               ', VARCHAR 'cally', DECIMAL '9325260.45'),
    (CHAR 'Mazza                         ', CHAR 'Brenda              ', VARCHAR 'able', DECIMAL '899464.50'),
    (CHAR 'Mckay                         ', CHAR 'Linda               ', VARCHAR 'n st', DECIMAL '814713.68'),
    (CHAR 'Mcqueen                       ', CHAR 'Glenn               ', VARCHAR 'eing', DECIMAL '373804.20'),
    (CHAR 'Michel                        ', CHAR 'Francis             ', VARCHAR 'bar', DECIMAL '1054462.86'),
    (CHAR 'Miller                        ', CHAR 'Bradley             ', VARCHAR 'able', DECIMAL '8232008.40'),
    (CHAR 'Miller                        ', CHAR 'Donna               ', VARCHAR 'able', DECIMAL '1342469.70'),
    (CHAR 'Moore                         ', CHAR 'Ericka              ', VARCHAR 'bar', DECIMAL '1254099.00'),
    (CHAR 'Mueller                       ', CHAR 'Chad                ', VARCHAR 'n st', DECIMAL '93095.73'),
    (CHAR 'Mundy                         ', CHAR 'Susan               ', VARCHAR 'bar', DECIMAL '300951.36'),
    (CHAR 'Navarro                       ', CHAR 'Sheila              ', VARCHAR 'n st', DECIMAL '174597.12'),
    (CHAR 'Neal                          ', CHAR 'Shanna              ', VARCHAR 'able', DECIMAL '7503884.85'),
    (CHAR 'Nelson                        ', CHAR 'Debbie              ', VARCHAR 'ought', DECIMAL '264359.70'),
    (CHAR 'Newton                        ', CHAR 'Brian               ', VARCHAR 'ese', DECIMAL '188250.00'),
    (CHAR 'Oneill                        ', CHAR 'Katie               ', VARCHAR 'cally', DECIMAL '595839.12'),
    (CHAR 'Parks                         ', CHAR 'Lisa                ', VARCHAR 'ese', DECIMAL '2038944.60'),
    (CHAR 'Pearson                       ', CHAR 'Rhonda              ', VARCHAR 'n st', DECIMAL '2702585.40'),
    (CHAR 'Pelletier                     ', CHAR 'Judith              ', VARCHAR 'ought', DECIMAL '140346.00'),
    (CHAR 'Perez                         ', CHAR 'Velma               ', VARCHAR 'able', DECIMAL '70686.00'),
    (CHAR 'Phillips                      ', CHAR 'Sharon              ', VARCHAR 'able', DECIMAL '5931783.00'),
    (CHAR 'Pinto                         ', CHAR 'Jeffrey             ', VARCHAR 'bar', DECIMAL '643273.46'),
    (CHAR 'Pollack                       ', CHAR 'Gloria              ', VARCHAR 'able', DECIMAL '188090.10'),
    (CHAR 'Pool                          ', CHAR 'Peter               ', VARCHAR 'ought', DECIMAL '654223.50'),
    (CHAR 'Pruett                        ', CHAR 'David               ', VARCHAR 'ese', DECIMAL '17079.10'),
    (CHAR 'Purnell                       ', CHAR 'Sylvia              ', VARCHAR 'able', DECIMAL '1577205.60'),
    (CHAR 'Ragan                         ', CHAR 'Robert              ', VARCHAR 'anti', DECIMAL '9832071.60'),
    (CHAR 'Randall                       ', CHAR 'Eddie               ', VARCHAR 'anti', DECIMAL '3957120.00'),
    (CHAR 'Reed                          ', CHAR 'Glenda              ', VARCHAR 'able', DECIMAL '39105.92'),
    (CHAR 'Reich                         ', CHAR 'Brett               ', VARCHAR 'anti', DECIMAL '2753157.60'),
    (CHAR 'Reno                          ', CHAR 'John                ', VARCHAR 'ese', DECIMAL '3482250.00'),
    (CHAR 'Rice                          ', CHAR 'Matthew             ', VARCHAR 'ese', DECIMAL '1450990.00'),
    (CHAR 'Richard                       ', CHAR 'Edwin               ', VARCHAR 'cally', DECIMAL '86444.93'),
    (CHAR 'Richter                       ', CHAR 'Jesus               ', VARCHAR 'bar', DECIMAL '136090.79'),
    (CHAR 'Roberts                       ', CHAR 'Colleen             ', VARCHAR 'bar', DECIMAL '2265457.19'),
    (CHAR 'Russell                       ', CHAR 'James               ', VARCHAR 'ese', DECIMAL '2042944.74'),
    (CHAR 'Sanchez                       ', CHAR 'Beth                ', VARCHAR 'able', DECIMAL '288614.70'),
    (CHAR 'Sanderson                     ', CHAR 'Judith              ', VARCHAR 'bar', DECIMAL '5636572.92'),
    (CHAR 'Santana                       ', CHAR 'Donna               ', VARCHAR 'able', DECIMAL '211196.70'),
    (CHAR 'Schreiner                     ', CHAR 'Evelyn              ', VARCHAR 'n st', DECIMAL '10798953.12'),
    (CHAR 'Sexton                        ', NULL, VARCHAR 'ese', DECIMAL '113581.44'),
    (CHAR 'Shannon                       ', CHAR 'Brian               ', VARCHAR 'able', DECIMAL '813126.60'),
    (CHAR 'Shrader                       ', CHAR 'Marc                ', VARCHAR 'anti', DECIMAL '9227196.00'),
    (CHAR 'Silva                         ', CHAR 'Christine           ', VARCHAR 'eing', DECIMAL '2713095.00'),
    (CHAR 'Smith                         ', CHAR 'Katherine           ', VARCHAR 'anti', DECIMAL '2297700.00'),
    (CHAR 'Smith                         ', CHAR 'Patty               ', VARCHAR 'bar', DECIMAL '11843161.20'),
    (CHAR 'Sosa                          ', CHAR 'Roberto             ', VARCHAR 'bar', DECIMAL '519555.30'),
    (CHAR 'Steinberg                     ', CHAR 'Calvin              ', VARCHAR 'n st', DECIMAL '97402.56'),
    (CHAR 'Stewart                       ', CHAR 'Kathryn             ', VARCHAR 'n st', DECIMAL '1137899.85'),
    (CHAR 'Strickland                    ', CHAR 'Richard             ', VARCHAR 'able', DECIMAL '1543611.42'),
    (CHAR 'Taylor                        ', NULL, VARCHAR 'eing', DECIMAL '2237446.86'),
    (CHAR 'Thompson                      ', CHAR 'Jerri               ', VARCHAR 'n st', DECIMAL '1359909.99'),
    (CHAR 'Thompson                      ', CHAR 'Susan               ', VARCHAR 'eing', DECIMAL '4610864.28'),
    (CHAR 'Torres                        ', CHAR 'Aracely             ', VARCHAR 'bar', DECIMAL '1896205.08'),
    (CHAR 'Underwood                     ', CHAR 'Randy               ', VARCHAR 'ese', DECIMAL '2603052.80'),
    (CHAR 'Vandiver                      ', CHAR 'Daniel              ', VARCHAR 'bar', DECIMAL '1704341.10'),
    (CHAR 'Vasquez                       ', CHAR 'Lee                 ', VARCHAR 'ese', DECIMAL '2295066.24'),
    (CHAR 'Ward                          ', CHAR 'William             ', VARCHAR 'cally', DECIMAL '7723132.68'),
    (CHAR 'Watts                         ', CHAR 'Sharyn              ', VARCHAR 'ese', DECIMAL '2213500.00'),
    (CHAR 'Weathers                      ', CHAR 'Michelle            ', VARCHAR 'bar', DECIMAL '3057221.20'),
    (CHAR 'Weiss                         ', CHAR 'Isela               ', VARCHAR 'eing', DECIMAL '6268914.63'),
    (CHAR 'Williams                      ', CHAR 'Charles             ', VARCHAR 'eing', DECIMAL '2441909.91'),
    (CHAR 'Wilson                        ', CHAR 'Janet               ', VARCHAR 'n st', DECIMAL '7045898.68'),
    (CHAR 'Wilson                        ', CHAR 'Michelle            ', VARCHAR 'able', DECIMAL '1068691.47'),
    (CHAR 'Wingate                       ', CHAR 'Katie               ', VARCHAR 'cally', DECIMAL '727612.02'),
    (CHAR 'Wood                          ', CHAR 'Billy               ', VARCHAR 'anti', DECIMAL '5944881.60'),
    (CHAR 'Wright                        ', CHAR 'William             ', VARCHAR 'ese', DECIMAL '1507273.50'),
    (CHAR 'Zimmerman                     ', CHAR 'Lakiesha            ', VARCHAR 'bar', DECIMAL '646580.55'),
    (NULL, CHAR 'Gary                ', VARCHAR 'n st', DECIMAL '8421969.36'),
    (NULL, CHAR 'Jennifer            ', VARCHAR 'eing', DECIMAL '2121956.10'),
    (NULL, CHAR 'Tamela              ', VARCHAR 'ese', DECIMAL '676508.10'),
    (NULL, NULL, VARCHAR 'cally', DECIMAL '2107827.27')
)
