SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAJBKCAAA', VARCHAR 'No longer different artis', CHAR 'AAAAAAAAOCAAAAAA', VARCHAR 'cally', BIGINT '42', BIGINT '42', BIGINT '83'),
    (CHAR 'AAAAAAAAAPFLAAAA', VARCHAR 'Homes paint response', CHAR 'AAAAAAAACCBAAAAA', VARCHAR 'bar', BIGINT '98', BIGINT '38', BIGINT '48'),
    (CHAR 'AAAAAAAABBOGAAAA', VARCHAR 'Most personal figures w', CHAR 'AAAAAAAAABBAAAAA', VARCHAR 'able', BIGINT '39', BIGINT '20', BIGINT '91'),
    (CHAR 'AAAAAAAABCLHBAAA', VARCHAR 'Properly immediate nerves provide never. Elements imitate extensive, optimistic aspects. Knees would not push best gen', CHAR 'AAAAAAAABGAAAAAA', VARCHAR 'ation', BIGINT '27', BIGINT '7', BIGINT '19'),
    (CHAR 'AAAAAAAABDMCBAAA', VARCHAR 'Other, social marks sha', CHAR 'AAAAAAAAAIAAAAAA', VARCHAR 'eing', BIGINT '90', BIGINT '37', BIGINT '37'),
    (CHAR 'AAAAAAAABGGKCAAA', VARCHAR 'Good executives ought to produce ne', CHAR 'AAAAAAAAEPAAAAAA', VARCHAR 'ese', BIGINT '23', BIGINT '15', BIGINT '29'),
    (CHAR 'AAAAAAAABKMHBAAA', VARCHAR 'Much private symptoms see therefore to a indicators. However splendid strengt', CHAR 'AAAAAAAACCAAAAAA', VARCHAR 'ese', BIGINT '5', BIGINT '4', BIGINT '83'),
    (CHAR 'AAAAAAAABNIMAAAA', VARCHAR 'Empty, international opportunities engage on a crimes. Buildings rebuild now environmental w', CHAR 'AAAAAAAAPDBAAAAA', VARCHAR 'n st', BIGINT '33', BIGINT '20', BIGINT '58'),
    (CHAR 'AAAAAAAABPGADAAA', VARCHAR 'Traditional patients take then interests. Friends used to allow right, economic months. Already increased jobs try adjacent, old systems; flats set as absolu', CHAR 'AAAAAAAABCBAAAAA', VARCHAR 'n st', BIGINT '62', BIGINT '62', BIGINT '43'),
    (CHAR 'AAAAAAAACEKEAAAA', VARCHAR 'Convincing, northern cases shall press important, enormous studies; su', CHAR 'AAAAAAAANFBAAAAA', VARCHAR 'n st', BIGINT '19', BIGINT '5', BIGINT '59'),
    (CHAR 'AAAAAAAACICACAAA', VARCHAR 'Ready, usual costs may take from a families. Major exceptions sha', CHAR 'AAAAAAAAMOAAAAAA', VARCHAR 'cally', BIGINT '75', BIGINT '2', BIGINT '41'),
    (CHAR 'AAAAAAAACILCAAAA', VARCHAR 'Existing, hot substances come as intern', CHAR 'AAAAAAAAGNAAAAAA', VARCHAR 'ese', BIGINT '1', BIGINT '1', BIGINT '97'),
    (CHAR 'AAAAAAAACKNBAAAA', VARCHAR 'Today labour characters used to like quite black difficult papers; ages catch low, common matters. Sick judges might make both opposite seeds. Public, foreign proceedings must not rescue of c', CHAR 'AAAAAAAAJABAAAAA', VARCHAR 'anti', BIGINT '16', BIGINT '15', BIGINT '63'),
    (CHAR 'AAAAAAAADCHEAAAA', VARCHAR 'Only s', CHAR 'AAAAAAAANAAAAAAA', VARCHAR 'pri', BIGINT '100', BIGINT '14', BIGINT '78'),
    (CHAR 'AAAAAAAADDMDBAAA', NULL, CHAR 'AAAAAAAAKPAAAAAA', VARCHAR 'bar', BIGINT '50', BIGINT '30', BIGINT '73'),
    (CHAR 'AAAAAAAADENFAAAA', VARCHAR 'Times should not reduce this. Senior environments could a', CHAR 'AAAAAAAALCAAAAAA', VARCHAR 'pri', BIGINT '6', BIGINT '4', BIGINT '59'),
    (CHAR 'AAAAAAAADODEBAAA', VARCHAR 'Particular tasks ensure quite rights. Dates cannot tend continuously suitable, intermediate words. Then aggressive processes turn sto', CHAR 'AAAAAAAAOCAAAAAA', VARCHAR 'cally', BIGINT '25', BIGINT '22', BIGINT '83'),
    (CHAR 'AAAAAAAADPKCBAAA', VARCHAR 'Indian aspects could notice values. Presently dramatic purposes offset in a men. Popular, special products talk minutes; civil, poli', CHAR 'AAAAAAAAFEBAAAAA', VARCHAR 'anti', BIGINT '65', BIGINT '19', BIGINT '96'),
    (CHAR 'AAAAAAAADPOMCAAA', VARCHAR 'Customers make special, concerned galleries. There racial strategies might produce general legs. Children extract too short frien', CHAR 'AAAAAAAAAABAAAAA', VARCHAR 'cally', BIGINT '15', BIGINT '2', BIGINT '47'),
    (CHAR 'AAAAAAAAEIADBAAA', VARCHAR 'Entire services must seal human emotions. Chemicals may not win earlier. Also rapid origins used to attend limited, surprised circum', CHAR 'AAAAAAAAFCAAAAAA', VARCHAR 'ation', BIGINT '7', BIGINT '4', BIGINT '36'),
    (CHAR 'AAAAAAAAELJEBAAA', VARCHAR 'Artistic, scientific benefits ', CHAR 'AAAAAAAAFLAAAAAA', VARCHAR 'ought', BIGINT '29', BIGINT '27', BIGINT '20'),
    (CHAR 'AAAAAAAAEOIIBAAA', VARCHAR 'Other, medical regions end today various circumstances. Main, detailed rates would', CHAR 'AAAAAAAAGEBAAAAA', VARCHAR 'cally', BIGINT '22', BIGINT '22', BIGINT '96'),
    (CHAR 'AAAAAAAAFCHJCAAA', VARCHAR 'Particular, domestic exchanges shall not leave occasionally by a findings. Citizens cannot help from no goods. Intact', CHAR 'AAAAAAAAHCBAAAAA', VARCHAR 'anti', BIGINT '9', BIGINT '5', BIGINT '17'),
    (CHAR 'AAAAAAAAFHMICAAA', VARCHAR 'Both developing proposals used to sepa', CHAR 'AAAAAAAAGFAAAAAA', VARCHAR 'cally', BIGINT '73', BIGINT '6', BIGINT '90'),
    (CHAR 'AAAAAAAAFJPHBAAA', VARCHAR 'Results get with every requests. Ahead new weekends adopt. Early, act', CHAR 'AAAAAAAAGCAAAAAA', VARCHAR 'eing', BIGINT '97', BIGINT '29', BIGINT '43'),
    (CHAR 'AAAAAAAAFKBPAAAA', VARCHAR 'Sad trades know.', CHAR 'AAAAAAAACDAAAAAA', VARCHAR 'bar', BIGINT '88', BIGINT '24', BIGINT '58'),
    (CHAR 'AAAAAAAAGDBMBAAA', VARCHAR 'Arbitrary, hard eyes mind together new, part-time groups. Extra, able representatives encourage very general women. Musical, available miles can boast so by the govern', CHAR 'AAAAAAAAEAAAAAAA', VARCHAR 'ese', BIGINT '75', BIGINT '66', BIGINT '9'),
    (CHAR 'AAAAAAAAGDONCAAA', VARCHAR 'Afraid girls would leave left operations. Current, useful injuries will not see twice long noble places. Of course little lakes take well ma', CHAR 'AAAAAAAAACAAAAAA', VARCHAR 'able', BIGINT '97', BIGINT '35', BIGINT '75'),
    (CHAR 'AAAAAAAAGHEOBAAA', VARCHAR 'Clear, great waves should return pale, general costs; that is sco', CHAR 'AAAAAAAAKDBAAAAA', VARCHAR 'ese', BIGINT '50', BIGINT '32', BIGINT '58'),
    (CHAR 'AAAAAAAAGJJLAAAA', VARCHAR 'All new pieces put on a skills. Accounts recall then white, relative offices. Interesting, original offences would not give for example narrow elements; regional, political drivers', CHAR 'AAAAAAAAGCAAAAAA', VARCHAR 'eing', NULL, BIGINT '7', BIGINT '5'),
    (CHAR 'AAAAAAAAGKMICAAA', VARCHAR 'Short, likely materials will cover sure english, close cattle; old trees question just scientific institutions. Unfortunately political pass', CHAR 'AAAAAAAAIDAAAAAA', VARCHAR 'cally', BIGINT '41', BIGINT '12', BIGINT '59'),
    (CHAR 'AAAAAAAAGNPPBAAA', VARCHAR 'Spare, joint animals', CHAR 'AAAAAAAAPBAAAAAA', VARCHAR 'ought', BIGINT '30', BIGINT '1', BIGINT '27'),
    (CHAR 'AAAAAAAAGOEOAAAA', VARCHAR 'Paintings hate. Changes may construct then possible businesses. Sometimes subject pounds might ruin. High new successes love again everyday weeks. Sure items wi', CHAR 'AAAAAAAAGKAAAAAA', VARCHAR 'cally', BIGINT '9', BIGINT '9', BIGINT '96'),
    (CHAR 'AAAAAAAAHHFPAAAA', VARCHAR 'Really different states think now long, small years. All protective readers could not assess ago. Now italian attempts tell hi', CHAR 'AAAAAAAACEBAAAAA', VARCHAR 'able', BIGINT '3', BIGINT '3', BIGINT '17'),
    (CHAR 'AAAAAAAAHIHLBAAA', VARCHAR 'Almost following bonds see always pages; democratic hands consider even good cases. Contemporary, hostile days could not write', CHAR 'AAAAAAAALCAAAAAA', VARCHAR 'pri', BIGINT '22', BIGINT '19', BIGINT '76'),
    (CHAR 'AAAAAAAAHNHOCAAA', VARCHAR 'Long, interesting restrictions assess apart rapid companies. Able', CHAR 'AAAAAAAAKABAAAAA', VARCHAR 'cally', BIGINT '56', BIGINT '46', BIGINT '36'),
    (CHAR 'AAAAAAAAILCACAAA', VARCHAR 'High victims play really ill circles. Open, planned plants raise attractive changes. Widespread, alone plans find easy notes. Proteins remind even previous students. Dependent buildings might', CHAR 'AAAAAAAAOFBAAAAA', VARCHAR 'bar', BIGINT '12', BIGINT '7', BIGINT '63'),
    (CHAR 'AAAAAAAAJAKKCAAA', VARCHAR 'Also severe authorities say car', CHAR 'AAAAAAAAENAAAAAA', VARCHAR 'able', BIGINT '51', BIGINT '14', BIGINT '8'),
    (CHAR 'AAAAAAAAJFBOCAAA', VARCHAR 'Decisions control big others. Soviet, confidential eyes can', CHAR 'AAAAAAAAHGAAAAAA', VARCHAR 'pri', BIGINT '41', BIGINT '25', BIGINT '91'),
    (CHAR 'AAAAAAAAJJNDAAAA', VARCHAR 'Even contemporary pieces worry accounts. Co', CHAR 'AAAAAAAAOHBAAAAA', VARCHAR 'able', BIGINT '79', BIGINT '65', BIGINT '50'),
    (CHAR 'AAAAAAAAJLMEBAAA', VARCHAR 'Other goods transport following, sure systems. Pure, vast roses see apart groups. National, original prices meet for a decisions. Voices think very sure head edges. Additional arms can ne', CHAR 'AAAAAAAAGBAAAAAA', VARCHAR 'able', BIGINT '35', NULL, BIGINT '44'),
    (CHAR 'AAAAAAAAJLOIBAAA', VARCHAR 'Popular leaders could come in the attempts. Big games must let common times. Major services take more; increased operations could let employee', CHAR 'AAAAAAAAKNAAAAAA', VARCHAR 'eing', BIGINT '56', BIGINT '12', BIGINT '32'),
    (CHAR 'AAAAAAAAKCOPAAAA', VARCHAR 'Fingers like american eyebrows. Years walk to the organisations. Public general men take there more small signs. Probably nice languages shall not pay groups; willing, political year', CHAR 'AAAAAAAABMAAAAAA', VARCHAR 'pri', BIGINT '76', BIGINT '23', BIGINT '45'),
    (CHAR 'AAAAAAAAKGMBAAAA', VARCHAR 'Now interested centres might obey yet objectives. Schools finish proposed, worthwhile areas. Simple, wide account', CHAR 'AAAAAAAAIDAAAAAA', VARCHAR 'cally', BIGINT '4', BIGINT '4', BIGINT '83'),
    (CHAR 'AAAAAAAAKPMIBAAA', VARCHAR 'Minutes cannot write. Very ideas must defeat per the visitors. Victims can ', CHAR 'AAAAAAAAKCBAAAAA', VARCHAR 'eing', BIGINT '1', BIGINT '1', BIGINT '11'),
    (CHAR 'AAAAAAAALADOAAAA', VARCHAR 'Arms should compete', CHAR 'AAAAAAAAPABAAAAA', VARCHAR 'ought', BIGINT '24', BIGINT '2', BIGINT '87'),
    (CHAR 'AAAAAAAALHBGAAAA', VARCHAR 'Possible, nervous attitudes should not help. Good top pupils stay as the periods. Foreign supplies must not move most across easy countries. Rare eyes prevent highly wide instruments. P', CHAR 'AAAAAAAAAEBAAAAA', VARCHAR 'bar', BIGINT '8', BIGINT '6', BIGINT '22'),
    (CHAR 'AAAAAAAALLOBAAAA', VARCHAR 'Obvious problems may find ', CHAR 'AAAAAAAAEHAAAAAA', VARCHAR 'cally', BIGINT '70', BIGINT '63', BIGINT '35'),
    (CHAR 'AAAAAAAAMHHIBAAA', VARCHAR 'Chairs would look fingers. Implicit spea', CHAR 'AAAAAAAAMHAAAAAA', VARCHAR 'ese', BIGINT '36', BIGINT '31', BIGINT '49'),
    (CHAR 'AAAAAAAAMLGLBAAA', VARCHAR 'Expensive, tall language', CHAR 'AAAAAAAAIOAAAAAA', VARCHAR 'able', BIGINT '86', BIGINT '69', BIGINT '50'),
    (CHAR 'AAAAAAAAOCEDAAAA', VARCHAR 'Months take. Numerous, big companies will make in a papers. Atlantic minutes keep permanently american p', CHAR 'AAAAAAAADHAAAAAA', VARCHAR 'anti', BIGINT '79', BIGINT '23', BIGINT '86'),
    (CHAR 'AAAAAAAAOFGLBAAA', VARCHAR 'Upper, liberal words may discuss thus previous balls. Sure blue injuries demolish. Terrible, angry figures used to improve there parental races; never neighbouring sales may no', CHAR 'AAAAAAAAOMAAAAAA', VARCHAR 'cally', BIGINT '22', BIGINT '10', BIGINT '45'),
    (CHAR 'AAAAAAAAOJDMCAAA', VARCHAR 'Other sides can mean ultimate, solid sanctions. Always armed syste', CHAR 'AAAAAAAAPNAAAAAA', VARCHAR 'pri', BIGINT '13', BIGINT '1', BIGINT '33'),
    (CHAR 'AAAAAAAAOLJAAAAA', VARCHAR 'Theoretically international tickets used to taste occasionally on a years. Regular techniques cannot no. Men shall show less strong, practical concentrations; cha', CHAR 'AAAAAAAAKGBAAAAA', VARCHAR 'able', BIGINT '9', BIGINT '2', BIGINT '82'),
    (CHAR 'AAAAAAAAOMEJBAAA', VARCHAR 'Cases should claim significant children. National powers sell more years. Responden', CHAR 'AAAAAAAABDAAAAAA', VARCHAR 'n st', BIGINT '68', BIGINT '56', BIGINT '18'),
    (CHAR 'AAAAAAAAOMICCAAA', VARCHAR 'Practitioners used to consist with a winners. Religious, british movements come all aware lives. Sciences make also courts; other, new matters ought to produce in a t', CHAR 'AAAAAAAACFAAAAAA', VARCHAR 'able', BIGINT '1', BIGINT '1', BIGINT '16'),
    (CHAR 'AAAAAAAAONCHCAAA', VARCHAR 'Mechanically sufficient men will stress permanently acceptable, small payments. Possible benefits take intensive, physical rights. Slowly specialist countries go som', CHAR 'AAAAAAAAKEAAAAAA', VARCHAR 'ese', BIGINT '28', BIGINT '23', BIGINT '74'),
    (CHAR 'AAAAAAAAONECCAAA', VARCHAR 'Royal, able carers pay here by a players. De', CHAR 'AAAAAAAACIBAAAAA', VARCHAR 'cally', BIGINT '91', BIGINT '27', BIGINT '18'),
    (CHAR 'AAAAAAAAOPBEBAAA', VARCHAR 'Bright, visible improvements pull quite. European, whole colours may get soon sound pupils. Poor, aware c', CHAR 'AAAAAAAAEHAAAAAA', VARCHAR 'cally', BIGINT '11', BIGINT '4', BIGINT '76'),
    (CHAR 'AAAAAAAAPHEFAAAA', VARCHAR 'There great courts shall star to a years; for example low beliefs clear re', CHAR 'AAAAAAAAIBBAAAAA', VARCHAR 'bar', BIGINT '45', BIGINT '7', BIGINT '83'),
    (CHAR 'AAAAAAAAPNLHAAAA', VARCHAR 'Weeks ought to like a little in a teams. Roman voters exploit able rules. Suddenly silent reasons should not retain also black insufficient questions. Successful, responsible types overcome eno', CHAR 'AAAAAAAAEMAAAAAA', VARCHAR 'cally', BIGINT '14', BIGINT '2', BIGINT '49'),
    (CHAR 'AAAAAAAAPOJGCAAA', VARCHAR 'Automatically annual glasses maintain over for a ', CHAR 'AAAAAAAALLAAAAAA', VARCHAR 'ation', BIGINT '35', BIGINT '11', BIGINT '92')
)
