SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAAABBAAA', CHAR 'Donald              ', CHAR 'Brewer                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAACCAAA', CHAR 'Terry               ', CHAR 'Simmons                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAACHBAA', CHAR 'Francis             ', CHAR 'Thompson                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAACIAAA', CHAR 'Evelyn              ', CHAR 'Ferris                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAACJBAA', CHAR 'Kenneth             ', CHAR 'Bragg                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAEABAA', NULL, NULL, NULL),
    (CHAR 'AAAAAAAAAAAFCAAA', CHAR 'Nathan              ', CHAR 'Moore                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAGKBAA', CHAR 'Leslie              ', CHAR 'Lee                           ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAAGLAAA', CHAR 'Stephanie           ', CHAR 'Allen                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAHLBAA', CHAR 'George              ', CHAR 'Belt                          ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAIJAAA', CHAR 'Nellie              ', CHAR 'Hughes                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAJEBAA', CHAR 'Magdalena           ', CHAR 'Steward                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAJHAAA', CHAR 'Anne                ', CHAR 'Chambliss                     ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAJKBAA', CHAR 'Linda               ', CHAR 'Moore                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAAODBAA', CHAR 'Barbara             ', CHAR 'Newby                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAAOHAAA', NULL, CHAR 'Williams                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAAOJAAA', CHAR 'Timothy             ', CHAR 'Williams                      ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABANAAA', CHAR 'Vanessa             ', CHAR 'Rubio                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABBDAAA', CHAR 'Barbara             ', CHAR 'White                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABBGAAA', CHAR 'Cheryl              ', CHAR 'Forest                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABBIAAA', CHAR 'Isaac               ', CHAR 'Collins                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABBMBAA', CHAR 'Larry               ', CHAR 'Blair                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABCDBAA', CHAR 'Jeffrey             ', CHAR 'Knapp                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABCEAAA', CHAR 'Alice               ', CHAR 'Gibbons                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABCOAAA', CHAR 'Cheryl              ', CHAR 'Green                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABEHAAA', CHAR 'Steve               ', CHAR 'Pratt                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABEPAAA', CHAR 'Marjorie            ', CHAR 'Quinn                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABFEBAA', CHAR 'Eric                ', CHAR 'Melton                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABFHBAA', CHAR 'Sherri              ', CHAR 'Caballero                     ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABFMBAA', CHAR 'Lashay              ', CHAR 'Schreiner                     ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABGKAAA', CHAR 'Victor              ', CHAR 'Robinson                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABHDBAA', CHAR 'Christopher         ', CHAR 'Thomas                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABKDAAA', CHAR 'Dave                ', CHAR 'Francis                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABKFBAA', CHAR 'Megan               ', CHAR 'Dykes                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABKMBAA', CHAR 'Velma               ', CHAR 'Thompson                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABMNAAA', CHAR 'Shellie             ', CHAR 'Green                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAABOIBAA', CHAR 'Melissa             ', CHAR 'Thompson                      ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABPHBAA', CHAR 'Rebecca             ', CHAR 'Coleman                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAABPPAAA', CHAR 'Michael             ', CHAR 'Somers                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACABBAA', CHAR 'Timothy             ', CHAR 'Gonzalez                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACANAAA', CHAR 'Jane                ', CHAR 'Odum                          ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACBIBAA', CHAR 'Ben                 ', CHAR 'Jordan                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACBMBAA', CHAR 'Stephen             ', CHAR 'Brown                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACCIAAA', CHAR 'Gretchen            ', CHAR 'Dellinger                     ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACCJBAA', CHAR 'Casey               ', CHAR 'Dale                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACCLAAA', CHAR 'Marlene             ', NULL, NULL),
    (CHAR 'AAAAAAAAAACFABAA', CHAR 'Charlotte           ', CHAR 'Knutson                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACFOAAA', CHAR 'Matthew             ', CHAR 'Mcmanus                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACGBAAA', CHAR 'Joshua              ', CHAR 'Wood                          ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACHGAAA', CHAR 'Rachel              ', CHAR 'Martindale                    ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACHLAAA', CHAR 'Betty               ', CHAR 'Thompson                      ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACIABAA', CHAR 'Judith              ', CHAR 'Hall                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAACNBAAA', CHAR 'Tyler               ', CHAR 'Osborne                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAACNEAAA', CHAR 'Scott               ', NULL, NULL),
    (CHAR 'AAAAAAAAAACONBAA', CHAR 'John                ', CHAR 'Wells                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADBPAAA', CHAR 'Fred                ', CHAR 'Stevens                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADCDAAA', CHAR 'Nicholas            ', CHAR 'Brown                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADCGAAA', CHAR 'Paul                ', CHAR 'White                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADEJBAA', CHAR 'Teresa              ', CHAR 'Sparks                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADFDAAA', CHAR 'Randall             ', CHAR 'Smith                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADFGBAA', CHAR 'Tyler               ', CHAR 'Davis                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADGAAAA', CHAR 'Ann                 ', CHAR 'Mcnamee                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADGDAAA', CHAR 'Alice               ', CHAR 'Holland                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADGEBAA', CHAR 'Richard             ', CHAR 'Novak                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADGFBAA', CHAR 'Reginald            ', CHAR 'Lenz                          ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADHBAAA', CHAR 'Juan                ', CHAR 'Ball                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADHEBAA', CHAR 'Shauna              ', CHAR 'Villarreal                    ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADHHBAA', CHAR 'Jennifer            ', CHAR 'Scott                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADIJAAA', CHAR 'Jason               ', CHAR 'Baylor                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADJLBAA', CHAR 'Theresa             ', CHAR 'Terry                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADKBBAA', CHAR 'Edward              ', CHAR 'Jenkins                       ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADKCBAA', CHAR 'Edward              ', CHAR 'Casey                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADLEAAA', CHAR 'Josette             ', CHAR 'Lopez                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADLLBAA', CHAR 'Gene                ', CHAR 'Boyd                          ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADMNAAA', CHAR 'Phillip             ', CHAR 'Boyd                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADNNAAA', CHAR 'Ernest              ', CHAR 'Lowe                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAADOOAAA', CHAR 'Ronald              ', CHAR 'Chappell                      ', CHAR 'N'),
    (CHAR 'AAAAAAAAAADPFAAA', CHAR 'Lina                ', CHAR 'Atkinson                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEBEBAA', CHAR 'Jose                ', CHAR 'Monk                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEBFBAA', CHAR 'Kevin               ', CHAR 'Caldwell                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAECLAAA', CHAR 'Brian               ', CHAR 'Schrader                      ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAECLBAA', CHAR 'Ray                 ', CHAR 'Smith                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAECMBAA', CHAR 'Brandon             ', CHAR 'Spencer                       ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEDBBAA', CHAR 'Nilda               ', CHAR 'Smith                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEDDAAA', CHAR 'Randall             ', CHAR 'Hall                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEDNBAA', CHAR 'Edward              ', CHAR 'Ward                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEEABAA', CHAR 'Rodolfo             ', CHAR 'Cody                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEFABAA', CHAR 'Marsha              ', CHAR 'Brooks                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEFEBAA', CHAR 'Allison             ', CHAR 'Worthington                   ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAEFJAAA', CHAR 'Bobby               ', CHAR 'Ferguson                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEHKBAA', CHAR 'William             ', CHAR 'Hill                          ', NULL),
    (CHAR 'AAAAAAAAAAEHOBAA', NULL, CHAR 'Vallejo                       ', NULL),
    (CHAR 'AAAAAAAAAAEIHAAA', CHAR 'Louise              ', CHAR 'Kline                         ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAEKKAAA', CHAR 'Darcy               ', CHAR 'Cash                          ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEKNAAA', CHAR 'Tricia              ', CHAR 'Gonzalez                      ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAELCBAA', CHAR 'Edward              ', CHAR 'Lewis                         ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAELPAAA', CHAR 'Maxine              ', CHAR 'Hilton                        ', CHAR 'Y'),
    (CHAR 'AAAAAAAAAAEMBAAA', CHAR 'Jerry               ', CHAR 'Kaplan                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAEMDAAA', CHAR 'Donna               ', CHAR 'Rivera                        ', CHAR 'N'),
    (CHAR 'AAAAAAAAAAEMHBAA', CHAR 'Quinton             ', CHAR 'Downes                        ', CHAR 'N')
)
