SELECT *
FROM
(
  VALUES
    (CHAR 'ableantiableablecally                             '),
    (CHAR 'ableantieingpripri                                '),
    (CHAR 'ableationableought                                '),
    (CHAR 'ableationesecallyeing                             '),
    (CHAR 'ablebareingationeingought                         '),
    (CHAR 'ablecallyprieingbarought                          '),
    (CHAR 'ableeingationpricallyought                        '),
    (CHAR 'ableeingbareingantiought                          '),
    (CHAR 'ableeseeingoughtpri                               '),
    (CHAR 'ableeseeingprianti                                '),
    (CHAR 'ablen stableationcally                            '),
    (CHAR 'ablen stoughtantiation                            '),
    (CHAR 'antiantiationeingcally                            '),
    (CHAR 'antibaresecallycallyought                         '),
    (CHAR 'anticallyeingationbarought                        '),
    (CHAR 'anticallyeingese                                  '),
    (CHAR 'anticallyprianticallyought                        '),
    (CHAR 'antieingeingoughtable                             '),
    (CHAR 'antieseeingn stableought                          '),
    (CHAR 'antioughteingn stpri                              '),
    (CHAR 'antipriationeseese                                '),
    (CHAR 'antipriesen stoughtought                          '),
    (CHAR 'antiprioughtbarbarable                            '),
    (CHAR 'antipripriablebarought                            '),
    (CHAR 'ationableeingeseanti                              '),
    (CHAR 'ationantiantibarcally                             '),
    (CHAR 'ationantieingbaranti                              '),
    (CHAR 'ationantipriantiantiought                         '),
    (CHAR 'ationbarableableeingought                         '),
    (CHAR 'ationbareingesebarought                           '),
    (CHAR 'ationbarpriationeing                              '),
    (CHAR 'ationeseationationbarought                        '),
    (CHAR 'ationeseeseablebarought                           '),
    (CHAR 'ationn stcallyesecallyought                       '),
    (CHAR 'ationn steseeingable                              '),
    (CHAR 'ationoughtn steing                                '),
    (CHAR 'ationoughtn stn stationought                      '),
    (CHAR 'barableantiableableought                          '),
    (CHAR 'barationationcallyoughtought                      '),
    (CHAR 'barbarbareseoughtought                            '),
    (CHAR 'bareingationpricallyought                         '),
    (CHAR 'bareingeingeseese                                 '),
    (CHAR 'barn stesecallyeing                               '),
    (CHAR 'barn stoughtantiation                             '),
    (CHAR 'barn stoughtprin stought                          '),
    (CHAR 'baroughtantibarese                                '),
    (CHAR 'barpriesecallyeseought                            '),
    (CHAR 'callyableablen steseought                         '),
    (CHAR 'callyableeingeseanti                              '),
    (CHAR 'callyantiantibarcally                             '),
    (CHAR 'callyantioughtpri                                 '),
    (CHAR 'callyantipriantiantiought                         '),
    (CHAR 'callycallyeingese                                 '),
    (CHAR 'callycallyn stationantiought                      '),
    (CHAR 'callycallyprianticallyought                       '),
    (CHAR 'callyeingeseantiationought                        '),
    (CHAR 'callyeseantieingbarought                          '),
    (CHAR 'callyesecallycallyn st                            '),
    (CHAR 'callyeseeseablebarought                           '),
    (CHAR 'callyn stcallyesecallyought                       '),
    (CHAR 'callypriesen stoughtought                         '),
    (CHAR 'eingablebaroughtcally                             '),
    (CHAR 'eingableesecallyeseought                          '),
    (CHAR 'eingableoughtn stableought                        '),
    (CHAR 'eingantiablebarcally                              '),
    (CHAR 'einganticallyn st                                 '),
    (CHAR 'eingationcallyantieingought                       '),
    (CHAR 'eingbarableableeingought                          '),
    (CHAR 'eingbarn steingought                              '),
    (CHAR 'eingcallypribarpriought                           '),
    (CHAR 'eingesebaresen stought                            '),
    (CHAR 'eingn stoughtbaroughtought                        '),
    (CHAR 'eingoughtn stbarpri                               '),
    (CHAR 'eseablepriableese                                 '),
    (CHAR 'esebarantin stantiought                           '),
    (CHAR 'esecallyableeseanti                               '),
    (CHAR 'esecallyationoughtationought                      '),
    (CHAR 'esecallycallyationbarought                        '),
    (CHAR 'esecallyprianticallyought                         '),
    (CHAR 'eseeseeingprianti                                 '),
    (CHAR 'eseoughtn steingableought                         '),
    (CHAR 'n stablebaroughtcally                             '),
    (CHAR 'n stableesecallyeseought                          '),
    (CHAR 'n stableoughtoughtbarable                         '),
    (CHAR 'n stantiesecallypriought                          '),
    (CHAR 'n steingationantipriought                         '),
    (CHAR 'n steingesecallyeing                              '),
    (CHAR 'n stesebaroughtbarable                            '),
    (CHAR 'n stn stn stprioughtought                         '),
    (CHAR 'n stprin stanticallyought                         '),
    (CHAR 'oughtableeingbaroughtought                        '),
    (CHAR 'oughtableprieingantiought                         '),
    (CHAR 'oughtationableought                               '),
    (CHAR 'oughtationationcallyoughtought                    '),
    (CHAR 'oughtationesecallyeing                            '),
    (CHAR 'oughtationpriationese                             '),
    (CHAR 'oughteingationpricallyought                       '),
    (CHAR 'oughtn stoughtantiation                           '),
    (CHAR 'oughtoughtableantipriought                        '),
    (CHAR 'oughtoughtantibarese                              ')
)
