SELECT *
FROM
(
  VALUES
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '500', BIGINT '6', CHAR 'Good      ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '500', BIGINT '7', CHAR 'High Risk ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '500', BIGINT '10', CHAR 'Low Risk  ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '500', BIGINT '6', CHAR 'Unknown   ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '1000', BIGINT '8', CHAR 'Good      ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '1000', BIGINT '8', CHAR 'High Risk ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '1000', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '1000', BIGINT '8', CHAR 'Unknown   ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '1500', BIGINT '6', CHAR 'Good      ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '1500', BIGINT '9', CHAR 'High Risk ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '1500', BIGINT '6', CHAR 'Low Risk  ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '1500', BIGINT '7', CHAR 'Unknown   ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '2000', BIGINT '8', CHAR 'Good      ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '2000', BIGINT '6', CHAR 'High Risk ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '2000', BIGINT '9', CHAR 'Low Risk  ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '2000', BIGINT '9', CHAR 'Unknown   ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '2500', BIGINT '6', CHAR 'Good      ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '2500', BIGINT '5', CHAR 'High Risk ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '2500', BIGINT '5', CHAR 'Low Risk  ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '2500', BIGINT '9', CHAR 'Unknown   ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '11', INTEGER '3000', BIGINT '11', CHAR 'Good      ', BIGINT '11'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '3000', BIGINT '7', CHAR 'High Risk ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '3', INTEGER '3000', BIGINT '3', CHAR 'Low Risk  ', BIGINT '3'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '3000', BIGINT '6', CHAR 'Unknown   ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '3500', BIGINT '10', CHAR 'Good      ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '3500', BIGINT '6', CHAR 'High Risk ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '11', INTEGER '3500', BIGINT '11', CHAR 'Low Risk  ', BIGINT '11'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '3500', BIGINT '9', CHAR 'Unknown   ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '4000', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '4000', BIGINT '9', CHAR 'High Risk ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '4000', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '4000', BIGINT '10', CHAR 'Unknown   ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '4500', BIGINT '8', CHAR 'Good      ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '4500', BIGINT '9', CHAR 'High Risk ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '4500', BIGINT '9', CHAR 'Low Risk  ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '4500', BIGINT '5', CHAR 'Unknown   ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '5000', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '2', INTEGER '5000', BIGINT '2', CHAR 'High Risk ', BIGINT '2'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '5000', BIGINT '5', CHAR 'Low Risk  ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '5000', BIGINT '7', CHAR 'Unknown   ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '5500', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '5500', BIGINT '10', CHAR 'High Risk ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '5500', BIGINT '8', CHAR 'Low Risk  ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '5500', BIGINT '6', CHAR 'Unknown   ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '11', INTEGER '6000', BIGINT '11', CHAR 'Good      ', BIGINT '11'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '4', INTEGER '6000', BIGINT '4', CHAR 'High Risk ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '6000', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '6000', BIGINT '10', CHAR 'Unknown   ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '6500', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '10', INTEGER '6500', BIGINT '10', CHAR 'High Risk ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '6500', BIGINT '9', CHAR 'Low Risk  ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '6', INTEGER '6500', BIGINT '6', CHAR 'Unknown   ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '7000', BIGINT '9', CHAR 'Good      ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '12', INTEGER '7000', BIGINT '12', CHAR 'High Risk ', BIGINT '12'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '7000', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '3', INTEGER '7000', BIGINT '3', CHAR 'Unknown   ', BIGINT '3'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '4', INTEGER '7500', BIGINT '4', CHAR 'Good      ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '7500', BIGINT '9', CHAR 'High Risk ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '3', INTEGER '7500', BIGINT '3', CHAR 'Low Risk  ', BIGINT '3'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '7500', BIGINT '8', CHAR 'Unknown   ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '8000', BIGINT '8', CHAR 'Good      ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '4', INTEGER '8000', BIGINT '4', CHAR 'High Risk ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '13', INTEGER '8000', BIGINT '13', CHAR 'Low Risk  ', BIGINT '13'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '8000', BIGINT '7', CHAR 'Unknown   ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '8500', BIGINT '8', CHAR 'Good      ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '8500', BIGINT '9', CHAR 'High Risk ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '12', INTEGER '8500', BIGINT '12', CHAR 'Low Risk  ', BIGINT '12'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '1', INTEGER '8500', BIGINT '1', CHAR 'Unknown   ', BIGINT '1'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '9000', BIGINT '5', CHAR 'Good      ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '8', INTEGER '9000', BIGINT '8', CHAR 'High Risk ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '9000', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '9000', BIGINT '7', CHAR 'Unknown   ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '4', INTEGER '9500', BIGINT '4', CHAR 'Good      ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '11', INTEGER '9500', BIGINT '11', CHAR 'High Risk ', BIGINT '11'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '12', INTEGER '9500', BIGINT '12', CHAR 'Low Risk  ', BIGINT '12'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '3', INTEGER '9500', BIGINT '3', CHAR 'Unknown   ', BIGINT '3'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '7', INTEGER '10000', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '14', INTEGER '10000', BIGINT '14', CHAR 'High Risk ', BIGINT '14'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '5', INTEGER '10000', BIGINT '5', CHAR 'Low Risk  ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '2 yr Degree         ', BIGINT '9', INTEGER '10000', BIGINT '9', CHAR 'Unknown   ', BIGINT '9'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '10', INTEGER '500', BIGINT '10', CHAR 'Good      ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '8', INTEGER '500', BIGINT '8', CHAR 'High Risk ', BIGINT '8'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '4', INTEGER '500', BIGINT '4', CHAR 'Low Risk  ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '6', INTEGER '500', BIGINT '6', CHAR 'Unknown   ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '12', INTEGER '1000', BIGINT '12', CHAR 'Good      ', BIGINT '12'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '7', INTEGER '1000', BIGINT '7', CHAR 'High Risk ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '6', INTEGER '1000', BIGINT '6', CHAR 'Low Risk  ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '11', INTEGER '1000', BIGINT '11', CHAR 'Unknown   ', BIGINT '11'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '6', INTEGER '1500', BIGINT '6', CHAR 'Good      ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '4', INTEGER '1500', BIGINT '4', CHAR 'High Risk ', BIGINT '4'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '6', INTEGER '1500', BIGINT '6', CHAR 'Low Risk  ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '7', INTEGER '1500', BIGINT '7', CHAR 'Unknown   ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '10', INTEGER '2000', BIGINT '10', CHAR 'Good      ', BIGINT '10'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '6', INTEGER '2000', BIGINT '6', CHAR 'High Risk ', BIGINT '6'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '12', INTEGER '2000', BIGINT '12', CHAR 'Low Risk  ', BIGINT '12'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '5', INTEGER '2000', BIGINT '5', CHAR 'Unknown   ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '7', INTEGER '2500', BIGINT '7', CHAR 'Good      ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '5', INTEGER '2500', BIGINT '5', CHAR 'High Risk ', BIGINT '5'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '7', INTEGER '2500', BIGINT '7', CHAR 'Low Risk  ', BIGINT '7'),
    (CHAR 'F', CHAR 'D', CHAR '4 yr Degree         ', BIGINT '11', INTEGER '2500', BIGINT '11', CHAR 'Unknown   ', BIGINT '11')
)
