SELECT *
FROM
(
  VALUES
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5212', BIGINT '0', BIGINT '13', BIGINT '13'),
    (NULL, VARCHAR 'National, comple', INTEGER '5217', BIGINT '0', BIGINT '11', BIGINT '11'),
    (NULL, NULL, INTEGER '5216', BIGINT '0', BIGINT '11', BIGINT '11'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5213', BIGINT '0', BIGINT '10', BIGINT '10'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5216', BIGINT '0', BIGINT '10', BIGINT '10'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5213', BIGINT '0', BIGINT '9', BIGINT '9'),
    (NULL, VARCHAR 'Important dem', INTEGER '5217', BIGINT '0', BIGINT '9', BIGINT '9'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5197', BIGINT '0', BIGINT '9', BIGINT '9'),
    (NULL, VARCHAR 'Please central m', INTEGER '5217', BIGINT '0', BIGINT '9', BIGINT '9'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5205', BIGINT '0', BIGINT '9', BIGINT '9'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5213', BIGINT '0', BIGINT '8', BIGINT '8'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5209', BIGINT '0', BIGINT '8', BIGINT '8'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5209', BIGINT '0', BIGINT '8', BIGINT '8'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5215', BIGINT '0', BIGINT '8', BIGINT '8'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5210', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Conventional childr', INTEGER '5217', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5216', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5216', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5206', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5213', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'National, comple', INTEGER '5205', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'National, comple', INTEGER '5210', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'National, comple', INTEGER '5212', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Please central m', INTEGER '5209', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, VARCHAR 'Please central m', INTEGER '5211', BIGINT '0', BIGINT '7', BIGINT '7'),
    (NULL, NULL, INTEGER '5213', BIGINT '0', BIGINT '7', BIGINT '7'),
    (VARCHAR 'P', VARCHAR 'New, net purposes', INTEGER '5216', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Bad cards must make.', INTEGER '5202', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Doors canno', INTEGER '5198', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5212', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Important dem', INTEGER '5214', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5217', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5213', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5204', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Please central m', INTEGER '5202', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5200', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5217', BIGINT '0', BIGINT '6', BIGINT '6'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5209', BIGINT '0', BIGINT '6', BIGINT '6'),
    (VARCHAR 'Days might not imagine in a boards; normal, proposed', VARCHAR 'Friendly, suitable ', INTEGER '5215', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'Days might not imagine in a boards; normal, proposed', VARCHAR 'Important dem', INTEGER '5215', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'Probably little problems organise earlier views. Large members attack even so special bills. Big opportunities may make only upper manufacturers. Angry, clever', VARCHAR 'Important dem', INTEGER '5210', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'Probably little problems organise earlier views. Large members attack even so special bills. Big opportunities may make only upper manufacturers. Angry, clever', VARCHAR 'Local, mass universi', INTEGER '5210', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'S', VARCHAR 'Bad cards must make.', INTEGER '5213', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'Still head improvements used to head always inevitably small matters. Inner examinations work scottish, conservative times. Total reports used to understand only, young concepts. ', VARCHAR 'Rooms cook ', INTEGER '5210', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Conventional childr', INTEGER '5199', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5200', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5204', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5205', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Friendly, suitable ', INTEGER '5208', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important dem', INTEGER '5203', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important dem', INTEGER '5211', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important dem', INTEGER '5213', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important dem', INTEGER '5216', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5212', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5214', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Important issues liv', INTEGER '5216', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5172', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5197', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5214', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Local, mass universi', INTEGER '5215', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'National, comple', INTEGER '5197', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'National, comple', INTEGER '5204', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'National, comple', INTEGER '5215', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5200', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New proceedings fo', INTEGER '5212', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5190', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5200', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5205', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5211', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'New, net purposes', INTEGER '5218', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5200', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5205', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Plain, reluctant', INTEGER '5210', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Please central m', INTEGER '5206', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Please central m', INTEGER '5213', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5203', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Quite effectiv', INTEGER '5204', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5214', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, VARCHAR 'Rooms cook ', INTEGER '5217', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, NULL, INTEGER '5201', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, NULL, INTEGER '5202', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, NULL, INTEGER '5203', BIGINT '0', BIGINT '5', BIGINT '5'),
    (NULL, NULL, INTEGER '5211', BIGINT '0', BIGINT '5', BIGINT '5'),
    (VARCHAR 'A', VARCHAR 'Conventional childr', INTEGER '5215', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Able, certain rules filter single, other corners. Other, new sons shall buy in the messages. Obvious, military plans lo', VARCHAR 'Rooms cook ', INTEGER '5201', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Again little police will not understand at least easy public times. Artists crack accused, safe patterns. Systems would know consciously in a quantities; disc', VARCHAR 'Plain, reluctant', INTEGER '5215', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Alone, international cars will substitute consequently patently redunda', VARCHAR 'Important issues liv', INTEGER '5216', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Alone, international cars will substitute consequently patently redunda', VARCHAR 'Plain, reluctant', INTEGER '5216', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Also other soldiers would control hard black, welsh charges. Badly grand minutes should put enough financ', VARCHAR 'Please central m', INTEGER '5211', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'American, controversial months fall. Official, eligible words know rapidly advisers. Adverse ', VARCHAR 'Plain, reluctant', INTEGER '5212', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Answers ', NULL, INTEGER '5216', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Apart perfect officers get of course. Often splendid hands hire further local twins; laws stay else months. Patients forgive women.', VARCHAR 'Local, mass universi', INTEGER '5210', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Appearances may know processes. Absent, armed humans evaluate currently tiny producers. Mo', VARCHAR 'Plain, reluctant', INTEGER '5211', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Areas maintain old levels. Police move that essentially considerable employers. Indicators shall need in', VARCHAR 'Important dem', INTEGER '5204', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Armed, old policies might not come ordinary effects. Then proper courses will give at least quie', VARCHAR 'Important dem', INTEGER '5211', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'As well full types carry daily necessary, biological children; mainly proposed circles ', VARCHAR 'New, net purposes', INTEGER '5215', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Available reforms produce abroad valid origins. Dark, main clients ', VARCHAR 'Conventional childr', INTEGER '5214', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Average, lovely lips might explain great governments. All glad feet ought to occur. Far fat', VARCHAR 'Local, mass universi', INTEGER '5202', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Average, lovely lips might explain great governments. All glad feet ought to occur. Far fat', VARCHAR 'Plain, reluctant', INTEGER '5202', BIGINT '0', BIGINT '4', BIGINT '4'),
    (VARCHAR 'Ch', VARCHAR 'Please central m', INTEGER '5213', BIGINT '0', BIGINT '4', BIGINT '4')
)
