SELECT *
FROM
(
  VALUES
    (CHAR 'Aaron                         ', CHAR 'Joseph              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '18716676', BIGINT '5'),
    (CHAR 'Adams                         ', CHAR 'Margaret            ', NULL, NULL, BIGINT '23621161', BIGINT '5'),
    (CHAR 'Akins                         ', CHAR 'Amy                 ', CHAR 'Miss      ', CHAR 'N', BIGINT '5573393', BIGINT '5'),
    (CHAR 'Allen                         ', CHAR 'Vincent             ', CHAR 'Sir       ', CHAR 'N', BIGINT '7343704', BIGINT '5'),
    (CHAR 'Andrade                       ', CHAR 'Kaylee              ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '11707306', BIGINT '5'),
    (CHAR 'Barnes                        ', CHAR 'Marian              ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '19260355', BIGINT '5'),
    (CHAR 'Bennett                       ', CHAR 'Jane                ', CHAR 'Miss      ', CHAR 'Y', BIGINT '1271688', BIGINT '5'),
    (CHAR 'Black                         ', CHAR 'Christopher         ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '8368078', BIGINT '5'),
    (CHAR 'Blanco                        ', CHAR 'Sung                ', CHAR 'Sir       ', CHAR 'Y', BIGINT '15277937', BIGINT '5'),
    (CHAR 'Bloom                         ', CHAR 'Tina                ', CHAR 'Ms.       ', CHAR 'N', BIGINT '18623594', BIGINT '5'),
    (CHAR 'Bobo                          ', CHAR 'Helen               ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '6638394', BIGINT '5'),
    (CHAR 'Booker                        ', CHAR 'Curtis              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '2170684', BIGINT '5'),
    (CHAR 'Bradshaw                      ', CHAR 'Heather             ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '6750199', BIGINT '5'),
    (CHAR 'Bryant                        ', CHAR 'Sandra              ', CHAR 'Ms.       ', CHAR 'N', BIGINT '6109829', BIGINT '5'),
    (CHAR 'Butler                        ', CHAR 'Julia               ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '17910304', BIGINT '5'),
    (CHAR 'Campbell                      ', CHAR 'Michael             ', CHAR 'Mr.       ', CHAR 'N', BIGINT '10114198', BIGINT '5'),
    (CHAR 'Cline                         ', CHAR 'Paulina             ', CHAR 'Dr.       ', CHAR 'N', BIGINT '23452093', BIGINT '5'),
    (CHAR 'Connolly                      ', CHAR 'Theresa             ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '11161178', BIGINT '5'),
    (CHAR 'Contreras                     ', CHAR 'David               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '10733777', BIGINT '5'),
    (CHAR 'Cornell                       ', CHAR 'Ruth                ', CHAR 'Dr.       ', CHAR 'N', BIGINT '18898076', BIGINT '5'),
    (CHAR 'Cox                           ', CHAR 'Anna                ', CHAR 'Miss      ', CHAR 'Y', BIGINT '8417830', BIGINT '5'),
    (CHAR 'Delarosa                      ', CHAR 'Rose                ', CHAR 'Miss      ', CHAR 'N', BIGINT '10521170', BIGINT '5'),
    (CHAR 'Draper                        ', CHAR 'Jayson              ', CHAR 'Mr.       ', CHAR 'N', BIGINT '6807594', BIGINT '5'),
    (CHAR 'Eaves                         ', CHAR 'Jessica             ', CHAR 'Ms.       ', CHAR 'N', BIGINT '7717313', BIGINT '5'),
    (CHAR 'Edward                        ', CHAR 'Kimberly            ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '17367328', BIGINT '5'),
    (CHAR 'Foster                        ', CHAR 'Charles             ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '11872596', BIGINT '5'),
    (CHAR 'Gardner                       ', CHAR 'Daniel              ', CHAR 'Sir       ', CHAR 'N', BIGINT '19630159', BIGINT '5'),
    (CHAR 'Gonzales                      ', CHAR 'Edward              ', CHAR 'Mr.       ', CHAR 'N', BIGINT '20818238', BIGINT '5'),
    (CHAR 'Graham                        ', CHAR 'Marian              ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '15933335', BIGINT '5'),
    (CHAR 'Greathouse                    ', CHAR 'Wilfred             ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '23233747', BIGINT '5'),
    (CHAR 'Green                         ', CHAR 'James               ', CHAR 'Dr.       ', CHAR 'N', BIGINT '20727322', BIGINT '5'),
    (CHAR 'Gruber                        ', CHAR 'Keith               ', CHAR 'Mr.       ', CHAR 'N', BIGINT '3102367', BIGINT '5'),
    (CHAR 'Gutierrez                     ', CHAR 'Jeremy              ', CHAR 'Sir       ', CHAR 'N', BIGINT '12323897', BIGINT '5'),
    (CHAR 'Harper                        ', CHAR 'Jonathon            ', CHAR 'Mr.       ', CHAR 'N', BIGINT '4019186', BIGINT '5'),
    (CHAR 'Harris                        ', CHAR 'Edna                ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '20618803', BIGINT '5'),
    (CHAR 'Harris                        ', CHAR 'William             ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '13715010', BIGINT '5'),
    (CHAR 'Harvey                        ', CHAR 'Judith              ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '12927239', BIGINT '5'),
    (CHAR 'Hastings                      ', CHAR 'Kathy               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '17286273', BIGINT '5'),
    (CHAR 'Hernandez                     ', CHAR 'Joe                 ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '18393077', BIGINT '5'),
    (CHAR 'Hernandez                     ', NULL, CHAR 'Dr.       ', CHAR 'Y', BIGINT '4447879', BIGINT '5'),
    (CHAR 'Herring                       ', CHAR 'Jennifer            ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '10054887', BIGINT '5'),
    (CHAR 'Howard                        ', CHAR 'Christine           ', CHAR 'Dr.       ', CHAR 'N', BIGINT '17499319', BIGINT '5'),
    (CHAR 'Howard                        ', CHAR 'Marcus              ', CHAR 'Dr.       ', CHAR 'N', BIGINT '11686178', BIGINT '5'),
    (CHAR 'Hudson                        ', CHAR 'Bonnie              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '6819434', BIGINT '5'),
    (CHAR 'Hunt                          ', CHAR 'Jeff                ', CHAR 'Sir       ', CHAR 'N', BIGINT '8828563', BIGINT '5'),
    (CHAR 'Jackson                       ', CHAR 'Michel              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '19713192', BIGINT '5'),
    (CHAR 'Jennings                      ', CHAR 'Karissa             ', CHAR 'Miss      ', CHAR 'N', BIGINT '3142801', BIGINT '5'),
    (CHAR 'Jones                         ', CHAR 'Gertrude            ', CHAR 'Ms.       ', CHAR 'N', BIGINT '4587335', BIGINT '5'),
    (CHAR 'Joyner                        ', CHAR 'Bonnie              ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '17395446', BIGINT '5'),
    (CHAR 'Kennedy                       ', CHAR 'Jack                ', CHAR 'Sir       ', CHAR 'N', BIGINT '18667374', BIGINT '5'),
    (CHAR 'Kerns                         ', CHAR 'David               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '19622592', BIGINT '5'),
    (CHAR 'Lee                           ', CHAR 'Michele             ', CHAR 'Ms.       ', CHAR 'N', BIGINT '20961161', BIGINT '5'),
    (CHAR 'Long                          ', CHAR 'Margaret            ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '20428588', BIGINT '5'),
    (CHAR 'Lopez                         ', CHAR 'Opal                ', CHAR 'Dr.       ', CHAR 'N', BIGINT '4278821', BIGINT '5'),
    (CHAR 'Martinez                      ', CHAR 'Robert              ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '6520199', BIGINT '5'),
    (CHAR 'Mayes                         ', CHAR 'Dale                ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '9258609', BIGINT '5'),
    (CHAR 'Mcfadden                      ', CHAR 'Joel                ', CHAR 'Sir       ', CHAR 'N', BIGINT '5511314', BIGINT '5'),
    (CHAR 'Mejia                         ', CHAR 'Terry               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '19964035', BIGINT '5'),
    (CHAR 'Meyer                         ', CHAR 'David               ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '9838432', BIGINT '5'),
    (CHAR 'Mills                         ', CHAR 'Hazel               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '16959777', BIGINT '5'),
    (CHAR 'Molina                        ', CHAR 'Martha              ', CHAR 'Miss      ', CHAR 'N', BIGINT '3662501', BIGINT '5'),
    (CHAR 'Moore                         ', CHAR 'Marie               ', CHAR 'Dr.       ', NULL, BIGINT '3656392', BIGINT '5'),
    (CHAR 'Moses                         ', CHAR 'Paula               ', CHAR 'Miss      ', CHAR 'Y', BIGINT '5060159', BIGINT '5'),
    (CHAR 'Munson                        ', CHAR 'Michael             ', CHAR 'Sir       ', CHAR 'N', BIGINT '8423887', BIGINT '5'),
    (CHAR 'Nelson                        ', CHAR 'Victoria            ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '20979706', BIGINT '5'),
    (CHAR 'Oneil                         ', CHAR 'Helen               ', CHAR 'Miss      ', CHAR 'Y', BIGINT '23563046', BIGINT '5'),
    (CHAR 'Parrott                       ', CHAR 'Joanne              ', CHAR 'Ms.       ', CHAR 'Y', BIGINT '9610136', BIGINT '5'),
    (CHAR 'Partridge                     ', CHAR 'Ira                 ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '8426122', BIGINT '5'),
    (CHAR 'Payne                         ', CHAR 'Edward              ', CHAR 'Sir       ', CHAR 'Y', BIGINT '5768988', BIGINT '5'),
    (CHAR 'Pearl                         ', CHAR 'Agnes               ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '19875689', BIGINT '5'),
    (CHAR 'Peterson                      ', CHAR 'Julia               ', CHAR 'Ms.       ', CHAR 'N', BIGINT '12664752', BIGINT '5'),
    (CHAR 'Phelps                        ', CHAR 'Alex                ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '3589434', BIGINT '5'),
    (CHAR 'Porter                        ', CHAR 'Leroy               ', CHAR 'Mr.       ', CHAR 'N', BIGINT '23256155', BIGINT '5'),
    (CHAR 'Redding                       ', CHAR 'Linda               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '13250667', BIGINT '5'),
    (CHAR 'Reynolds                      ', CHAR 'Gabriel             ', CHAR 'Sir       ', CHAR 'N', BIGINT '8394722', BIGINT '5'),
    (CHAR 'Rinehart                      ', CHAR 'Robert              ', CHAR 'Dr.       ', CHAR 'N', BIGINT '4263613', BIGINT '5'),
    (CHAR 'Rodgers                       ', CHAR 'Jennifer            ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '11243001', BIGINT '5'),
    (CHAR 'Rodriguez                     ', CHAR 'Paul                ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '5656859', BIGINT '5'),
    (CHAR 'Sanderson                     ', CHAR 'Marlene             ', CHAR 'Miss      ', CHAR 'Y', BIGINT '20756179', BIGINT '5'),
    (CHAR 'Sandlin                       ', CHAR 'Wendy               ', CHAR 'Miss      ', CHAR 'Y', BIGINT '19966875', BIGINT '5'),
    (CHAR 'Shell                         ', CHAR 'Laura               ', CHAR 'Ms.       ', CHAR 'Y', BIGINT '1620473', BIGINT '5'),
    (CHAR 'Smith                         ', CHAR 'Jennifer            ', CHAR 'Dr.       ', CHAR 'N', BIGINT '10273096', BIGINT '5'),
    (CHAR 'Sneed                         ', CHAR 'Bertha              ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '22940994', BIGINT '5'),
    (CHAR 'Solomon                       ', CHAR 'Thomas              ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '23625158', BIGINT '5'),
    (CHAR 'Speight                       ', CHAR 'Leann               ', CHAR 'Ms.       ', CHAR 'Y', BIGINT '5965193', BIGINT '5'),
    (CHAR 'Stephenson                    ', CHAR 'Donald              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '9613846', BIGINT '5'),
    (CHAR 'Stevens                       ', CHAR 'Stanley             ', CHAR 'Mr.       ', CHAR 'N', BIGINT '1385940', BIGINT '5'),
    (CHAR 'Styles                        ', CHAR 'Pennie              ', CHAR 'Dr.       ', CHAR 'N', BIGINT '23932625', BIGINT '5'),
    (CHAR 'Vaughn                        ', CHAR 'Robert              ', CHAR 'Mr.       ', CHAR 'N', BIGINT '11419229', BIGINT '5'),
    (CHAR 'Velasco                       ', CHAR 'Robert              ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '556366', BIGINT '5'),
    (CHAR 'Ward                          ', CHAR 'Ruth                ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '1709031', BIGINT '5'),
    (CHAR 'Watson                        ', CHAR 'Margaret            ', CHAR 'Mrs.      ', CHAR 'Y', BIGINT '3646976', BIGINT '5'),
    (CHAR 'White                         ', CHAR 'Barbara             ', CHAR 'Dr.       ', CHAR 'N', BIGINT '22126607', BIGINT '5'),
    (CHAR 'Whitley                       ', CHAR 'Willie              ', CHAR 'Sir       ', CHAR 'N', BIGINT '3434608', BIGINT '5'),
    (CHAR 'Wilkins                       ', CHAR 'Sierra              ', CHAR 'Mrs.      ', CHAR 'N', BIGINT '13293147', BIGINT '5'),
    (CHAR 'Wood                          ', CHAR 'Barbara             ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '17272752', BIGINT '5'),
    (CHAR 'Zeller                        ', NULL, NULL, CHAR 'N', BIGINT '3317453', BIGINT '5'),
    (NULL, NULL, NULL, NULL, BIGINT '6044976', BIGINT '5'),
    (NULL, CHAR 'Preston             ', NULL, CHAR 'Y', BIGINT '5541634', BIGINT '5'),
    (NULL, CHAR 'Ann                 ', NULL, NULL, BIGINT '12187650', BIGINT '5'),
    (CHAR 'Chisolm                       ', CHAR 'Betsy               ', CHAR 'Miss      ', CHAR 'Y', BIGINT '18249443', BIGINT '4'),
    (CHAR 'Doyle                         ', CHAR 'Charlene            ', CHAR 'Dr.       ', CHAR 'N', BIGINT '3446954', BIGINT '4'),
    (CHAR 'Dugan                         ', CHAR 'George              ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '1483651', BIGINT '4'),
    (CHAR 'Edwards                       ', CHAR 'Harold              ', CHAR 'Mr.       ', CHAR 'Y', BIGINT '9483502', BIGINT '4'),
    (CHAR 'Ma                            ', CHAR 'Janet               ', CHAR 'Dr.       ', CHAR 'Y', BIGINT '1897867', BIGINT '4'),
    (CHAR 'Sexton                        ', CHAR 'Donna               ', CHAR 'Miss      ', CHAR 'N', BIGINT '958658', BIGINT '4'),
    (CHAR 'Taylor                        ', CHAR 'Margery             ', CHAR 'Miss      ', CHAR 'N', BIGINT '2297373', BIGINT '4'),
    (CHAR 'Willis                        ', CHAR 'Stephanie           ', CHAR 'Ms.       ', CHAR 'Y', BIGINT '21225508', BIGINT '4'),
    (NULL, CHAR 'Lillian             ', NULL, NULL, BIGINT '7512139', BIGINT '4'),
    (CHAR 'Montoya                       ', CHAR 'Sue                 ', CHAR 'Miss      ', CHAR 'N', BIGINT '4962322', BIGINT '3'),
    (CHAR 'Teeter                        ', CHAR 'Tara                ', CHAR 'Miss      ', CHAR 'Y', BIGINT '6750127', BIGINT '3')
)
