SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAAAAAADAAA', CHAR 'Kathryn             ', CHAR 'Thompson                      '),
    (CHAR 'AAAAAAAAAAAAEAAA', CHAR 'Robert              ', CHAR 'Patterson                     '),
    (CHAR 'AAAAAAAAAAAALAAA', CHAR 'Cathy               ', CHAR 'Salinas                       '),
    (CHAR 'AAAAAAAAAAABMAAA', CHAR 'Darrin              ', CHAR 'Williams                      '),
    (CHAR 'AAAAAAAAAAABMBAA', CHAR 'Jacqueline          ', CHAR 'Carlson                       '),
    (CHAR 'AAAAAAAAAAACBBAA', CHAR 'George              ', CHAR 'Beck                          '),
    (CHAR 'AAAAAAAAAAACGBAA', CHAR 'Margaret            ', CHAR 'Bender                        '),
    (CHAR 'AAAAAAAAAAACJBAA', CHAR 'Kenneth             ', CHAR 'Bragg                         '),
    (CHAR 'AAAAAAAAAAACOBAA', CHAR 'Sandra              ', CHAR 'Cowan                         '),
    (CHAR 'AAAAAAAAAAAEDAAA', CHAR 'Paula               ', CHAR 'Ferguson                      '),
    (CHAR 'AAAAAAAAAAAEEAAA', CHAR 'Richard             ', CHAR 'Jolley                        '),
    (CHAR 'AAAAAAAAAAAFEBAA', CHAR 'Elizabeth           ', CHAR 'Gordon                        '),
    (CHAR 'AAAAAAAAAAAFNBAA', CHAR 'Jeanette            ', CHAR 'Burnett                       '),
    (CHAR 'AAAAAAAAAAAGCBAA', CHAR 'Gregory             ', CHAR 'Goodwin                       '),
    (CHAR 'AAAAAAAAAAAGJBAA', CHAR 'Allison             ', CHAR 'Peebles                       '),
    (CHAR 'AAAAAAAAAAAGLAAA', CHAR 'Stephanie           ', CHAR 'Allen                         '),
    (CHAR 'AAAAAAAAAAAGPAAA', CHAR 'Gwendolyn           ', CHAR 'Prosser                       '),
    (CHAR 'AAAAAAAAAAAHDAAA', CHAR 'Joyce               ', CHAR 'John                          '),
    (CHAR 'AAAAAAAAAAAHGBAA', CHAR 'William             ', CHAR 'Hernandez                     '),
    (CHAR 'AAAAAAAAAAAHJAAA', CHAR 'William             ', CHAR 'Heck                          '),
    (CHAR 'AAAAAAAAAAAIIAAA', CHAR 'Ashley              ', CHAR 'Shannon                       '),
    (CHAR 'AAAAAAAAAAAIJAAA', CHAR 'Nellie              ', CHAR 'Hughes                        '),
    (CHAR 'AAAAAAAAAAAIMAAA', CHAR 'Barbara             ', NULL),
    (CHAR 'AAAAAAAAAAAINBAA', CHAR 'Salina              ', CHAR 'Harper                        '),
    (CHAR 'AAAAAAAAAAAJEBAA', CHAR 'Magdalena           ', CHAR 'Steward                       '),
    (CHAR 'AAAAAAAAAAAJHAAA', CHAR 'Anne                ', CHAR 'Chambliss                     '),
    (CHAR 'AAAAAAAAAAAJJAAA', CHAR 'Kimberly            ', CHAR 'Phillips                      '),
    (CHAR 'AAAAAAAAAAAJNBAA', CHAR 'William             ', CHAR 'Montoya                       '),
    (CHAR 'AAAAAAAAAAAJOAAA', CHAR 'Stephen             ', CHAR 'Smith                         '),
    (CHAR 'AAAAAAAAAAAKABAA', CHAR 'Carla               ', CHAR 'Chase                         '),
    (CHAR 'AAAAAAAAAAALCAAA', CHAR 'Jeffrey             ', CHAR 'Harrison                      '),
    (CHAR 'AAAAAAAAAAALEBAA', CHAR 'Marie               ', CHAR 'Ornelas                       '),
    (CHAR 'AAAAAAAAAAAMCBAA', NULL, CHAR 'Smith                         '),
    (CHAR 'AAAAAAAAAAAMLBAA', CHAR 'Bennie              ', CHAR 'Peters                        '),
    (CHAR 'AAAAAAAAAAAMMAAA', CHAR 'Thomas              ', CHAR 'Hanlon                        '),
    (CHAR 'AAAAAAAAAAANABAA', CHAR 'Dena                ', CHAR 'Cox                           '),
    (CHAR 'AAAAAAAAAAANCAAA', CHAR 'Michael             ', CHAR 'Lachance                      '),
    (CHAR 'AAAAAAAAAAANJBAA', CHAR 'Melvin              ', CHAR 'Baird                         '),
    (CHAR 'AAAAAAAAAAAODBAA', CHAR 'Barbara             ', CHAR 'Newby                         '),
    (CHAR 'AAAAAAAAAAAOGBAA', CHAR 'Bonnie              ', CHAR 'Burge                         '),
    (CHAR 'AAAAAAAAAAAOHAAA', NULL, CHAR 'Williams                      '),
    (CHAR 'AAAAAAAAAAAOKBAA', CHAR 'Tara                ', CHAR 'Libby                         '),
    (CHAR 'AAAAAAAAAABAFBAA', CHAR 'Susan               ', CHAR 'Wood                          '),
    (CHAR 'AAAAAAAAAABANAAA', CHAR 'Vanessa             ', CHAR 'Rubio                         '),
    (CHAR 'AAAAAAAAAABAOBAA', CHAR 'Jose                ', CHAR 'Chavez                        '),
    (CHAR 'AAAAAAAAAABBDAAA', CHAR 'Barbara             ', CHAR 'White                         '),
    (CHAR 'AAAAAAAAAABBDBAA', CHAR 'Anthony             ', CHAR 'Webb                          '),
    (CHAR 'AAAAAAAAAABBEBAA', CHAR 'Michael             ', CHAR 'Grossman                      '),
    (CHAR 'AAAAAAAAAABBGAAA', CHAR 'Cheryl              ', CHAR 'Forest                        '),
    (CHAR 'AAAAAAAAAABBHBAA', CHAR 'Wendy               ', CHAR 'Guillen                       '),
    (CHAR 'AAAAAAAAAABBJBAA', CHAR 'Gerald              ', CHAR 'Christenson                   '),
    (CHAR 'AAAAAAAAAABBMBAA', CHAR 'Larry               ', CHAR 'Blair                         '),
    (CHAR 'AAAAAAAAAABCCBAA', CHAR 'Emily               ', CHAR 'Cole                          '),
    (CHAR 'AAAAAAAAAABCDAAA', CHAR 'Jennifer            ', CHAR 'Mclaughlin                    '),
    (CHAR 'AAAAAAAAAABCIBAA', CHAR 'Lisa                ', CHAR 'Luckett                       '),
    (CHAR 'AAAAAAAAAABCOAAA', CHAR 'Cheryl              ', CHAR 'Green                         '),
    (CHAR 'AAAAAAAAAABDCAAA', CHAR 'Deborah             ', CHAR 'Miller                        '),
    (CHAR 'AAAAAAAAAABDKAAA', CHAR 'Lorraine            ', CHAR 'Mckinley                      '),
    (CHAR 'AAAAAAAAAABDOAAA', CHAR 'Charles             ', CHAR 'Jackson                       '),
    (CHAR 'AAAAAAAAAABEBAAA', CHAR 'Lisa                ', CHAR 'Weaver                        '),
    (CHAR 'AAAAAAAAAABEEBAA', CHAR 'Mark                ', NULL),
    (CHAR 'AAAAAAAAAABEHAAA', CHAR 'Steve               ', CHAR 'Pratt                         '),
    (CHAR 'AAAAAAAAAABEMBAA', CHAR 'Willie              ', CHAR 'Echevarria                    '),
    (CHAR 'AAAAAAAAAABEPAAA', CHAR 'Marjorie            ', CHAR 'Quinn                         '),
    (CHAR 'AAAAAAAAAABFCAAA', CHAR 'Bennett             ', CHAR 'Watson                        '),
    (CHAR 'AAAAAAAAAABFHAAA', CHAR 'Odessa              ', CHAR 'Ring                          '),
    (CHAR 'AAAAAAAAAABFHBAA', CHAR 'Sherri              ', CHAR 'Caballero                     '),
    (CHAR 'AAAAAAAAAABGFBAA', CHAR 'Tim                 ', CHAR 'Morse                         '),
    (CHAR 'AAAAAAAAAABGKAAA', CHAR 'Victor              ', CHAR 'Robinson                      '),
    (CHAR 'AAAAAAAAAABGNBAA', CHAR 'Lino                ', CHAR 'Bivens                        '),
    (CHAR 'AAAAAAAAAABIIBAA', NULL, CHAR 'Thompson                      '),
    (CHAR 'AAAAAAAAAABILAAA', CHAR 'Alex                ', CHAR 'Gonzalez                      '),
    (CHAR 'AAAAAAAAAABINBAA', CHAR 'Jesus               ', CHAR 'Mathis                        '),
    (CHAR 'AAAAAAAAAABJBBAA', CHAR 'Alice               ', CHAR 'Barton                        '),
    (CHAR 'AAAAAAAAAABJMAAA', CHAR 'Amy                 ', CHAR 'Brackett                      '),
    (CHAR 'AAAAAAAAAABKCAAA', CHAR 'Amanda              ', CHAR 'Bourgeois                     '),
    (CHAR 'AAAAAAAAAABKJBAA', CHAR 'Monique             ', CHAR 'Walters                       '),
    (CHAR 'AAAAAAAAAABKMBAA', CHAR 'Velma               ', CHAR 'Thompson                      '),
    (CHAR 'AAAAAAAAAABLCAAA', NULL, NULL),
    (CHAR 'AAAAAAAAAABLEBAA', CHAR 'Mayra               ', CHAR 'Oconner                       '),
    (CHAR 'AAAAAAAAAABLKBAA', CHAR 'Jessica             ', CHAR 'Beaver                        '),
    (CHAR 'AAAAAAAAAABNAAAA', CHAR 'Gary                ', CHAR 'Johnson                       '),
    (CHAR 'AAAAAAAAAABNHBAA', CHAR 'Brian               ', CHAR 'Thurston                      '),
    (CHAR 'AAAAAAAAAABNNBAA', CHAR 'Herbert             ', CHAR 'Watts                         '),
    (CHAR 'AAAAAAAAAABNPAAA', CHAR 'Dale                ', CHAR 'Fulton                        '),
    (CHAR 'AAAAAAAAAABOABAA', CHAR 'Robert              ', CHAR 'Rankin                        '),
    (CHAR 'AAAAAAAAAABOEAAA', CHAR 'Joshua              ', CHAR 'Velazquez                     '),
    (CHAR 'AAAAAAAAAABOIBAA', CHAR 'Melissa             ', CHAR 'Thompson                      '),
    (CHAR 'AAAAAAAAAABPHBAA', CHAR 'Rebecca             ', CHAR 'Coleman                       '),
    (CHAR 'AAAAAAAAAACABBAA', CHAR 'Timothy             ', CHAR 'Gonzalez                      '),
    (CHAR 'AAAAAAAAAACAOAAA', CHAR 'Tim                 ', CHAR 'Roberson                      '),
    (CHAR 'AAAAAAAAAACBMBAA', CHAR 'Stephen             ', CHAR 'Brown                         '),
    (CHAR 'AAAAAAAAAACBNAAA', CHAR 'Nestor              ', CHAR 'Willoughby                    '),
    (CHAR 'AAAAAAAAAACCEBAA', CHAR 'Nick                ', CHAR 'Swartz                        '),
    (CHAR 'AAAAAAAAAACCGAAA', CHAR 'Brian               ', CHAR 'Mason                         '),
    (CHAR 'AAAAAAAAAACCIAAA', CHAR 'Gretchen            ', CHAR 'Dellinger                     '),
    (CHAR 'AAAAAAAAAACCLBAA', CHAR 'Arnoldo             ', CHAR 'Doucette                      '),
    (CHAR 'AAAAAAAAAACDJBAA', CHAR 'Barbara             ', CHAR 'Sanchez                       '),
    (CHAR 'AAAAAAAAAACDMBAA', CHAR 'Joseph              ', CHAR 'George                        '),
    (CHAR 'AAAAAAAAAACDNBAA', CHAR 'Mike                ', CHAR 'Kennedy                       ')
)
