SELECT *
FROM
(
  VALUES
    (DECIMAL '33198941642.94', NULL, NULL, INTEGER '2', BIGINT '1'),
    (DECIMAL '3362668983.44', CHAR 'Sports                                            ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '3326230218.96', CHAR 'Children                                          ', NULL, INTEGER '1', BIGINT '2'),
    (DECIMAL '3322426297.98', CHAR 'Women                                             ', NULL, INTEGER '1', BIGINT '3'),
    (DECIMAL '3322357618.81', CHAR 'Electronics                                       ', NULL, INTEGER '1', BIGINT '4'),
    (DECIMAL '3313717334.86', CHAR 'Music                                             ', NULL, INTEGER '1', BIGINT '5'),
    (DECIMAL '3313356205.32', CHAR 'Books                                             ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '3295907951.77', CHAR 'Home                                              ', NULL, INTEGER '1', BIGINT '7'),
    (DECIMAL '3294344966.02', CHAR 'Shoes                                             ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '3283901669.26', CHAR 'Jewelry                                           ', NULL, INTEGER '1', BIGINT '9'),
    (DECIMAL '3280370106.40', CHAR 'Men                                               ', NULL, INTEGER '1', BIGINT '10'),
    (DECIMAL '83660290.12', NULL, NULL, INTEGER '1', BIGINT '11'),
    (DECIMAL '219050351.40', CHAR 'Books                                             ', CHAR 'history                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '214638703.58', CHAR 'Books                                             ', CHAR 'entertainments                                    ', INTEGER '0', BIGINT '2'),
    (DECIMAL '213999906.98', CHAR 'Books                                             ', CHAR 'reference                                         ', INTEGER '0', BIGINT '3'),
    (DECIMAL '213003587.84', CHAR 'Books                                             ', CHAR 'fiction                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '210406628.74', CHAR 'Books                                             ', CHAR 'travel                                            ', INTEGER '0', BIGINT '5'),
    (DECIMAL '209607409.55', CHAR 'Books                                             ', CHAR 'home repair                                       ', INTEGER '0', BIGINT '6'),
    (DECIMAL '208337086.98', CHAR 'Books                                             ', CHAR 'romance                                           ', INTEGER '0', BIGINT '7'),
    (DECIMAL '207533890.51', CHAR 'Books                                             ', CHAR 'parenting                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '207196147.83', CHAR 'Books                                             ', CHAR 'sports                                            ', INTEGER '0', BIGINT '9'),
    (DECIMAL '206587244.17', CHAR 'Books                                             ', CHAR 'self-help                                         ', INTEGER '0', BIGINT '10'),
    (DECIMAL '205490731.01', CHAR 'Books                                             ', CHAR 'cooking                                           ', INTEGER '0', BIGINT '11'),
    (DECIMAL '202471452.82', CHAR 'Books                                             ', CHAR 'arts                                              ', INTEGER '0', BIGINT '12'),
    (DECIMAL '202003628.94', CHAR 'Books                                             ', CHAR 'science                                           ', INTEGER '0', BIGINT '13'),
    (DECIMAL '198013944.62', CHAR 'Books                                             ', CHAR 'business                                          ', INTEGER '0', BIGINT '14'),
    (DECIMAL '196234147.15', CHAR 'Books                                             ', CHAR 'computers                                         ', INTEGER '0', BIGINT '15'),
    (DECIMAL '193466087.71', CHAR 'Books                                             ', CHAR 'mystery                                           ', INTEGER '0', BIGINT '16'),
    (DECIMAL '5315255.49', CHAR 'Books                                             ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '857047955.51', CHAR 'Children                                          ', CHAR 'infants                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '839203883.10', CHAR 'Children                                          ', CHAR 'toddlers                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '816467818.99', CHAR 'Children                                          ', CHAR 'newborn                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '809235073.35', CHAR 'Children                                          ', CHAR 'school-uniforms                                   ', INTEGER '0', BIGINT '4'),
    (DECIMAL '4275488.01', CHAR 'Children                                          ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '221815643.90', CHAR 'Electronics                                       ', CHAR 'televisions                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '219755557.64', CHAR 'Electronics                                       ', CHAR 'dvd/vcr players                                   ', INTEGER '0', BIGINT '2'),
    (DECIMAL '215455671.62', CHAR 'Electronics                                       ', CHAR 'monitors                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '214252539.04', CHAR 'Electronics                                       ', CHAR 'memory                                            ', INTEGER '0', BIGINT '4'),
    (DECIMAL '211071738.02', CHAR 'Electronics                                       ', CHAR 'disk drives                                       ', INTEGER '0', BIGINT '5'),
    (DECIMAL '210574494.66', CHAR 'Electronics                                       ', CHAR 'karoke                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '207952384.16', CHAR 'Electronics                                       ', CHAR 'personal                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '207942415.75', CHAR 'Electronics                                       ', CHAR 'musical                                           ', INTEGER '0', BIGINT '8'),
    (DECIMAL '207542757.16', CHAR 'Electronics                                       ', CHAR 'scanners                                          ', INTEGER '0', BIGINT '9'),
    (DECIMAL '206961820.52', CHAR 'Electronics                                       ', CHAR 'portable                                          ', INTEGER '0', BIGINT '10'),
    (DECIMAL '203847123.37', CHAR 'Electronics                                       ', CHAR 'wireless                                          ', INTEGER '0', BIGINT '11'),
    (DECIMAL '202265980.72', CHAR 'Electronics                                       ', CHAR 'stereo                                            ', INTEGER '0', BIGINT '12'),
    (DECIMAL '201402141.86', CHAR 'Electronics                                       ', CHAR 'automotive                                        ', INTEGER '0', BIGINT '13'),
    (DECIMAL '200134755.57', CHAR 'Electronics                                       ', CHAR 'camcorders                                        ', INTEGER '0', BIGINT '14'),
    (DECIMAL '193637173.62', CHAR 'Electronics                                       ', CHAR 'cameras                                           ', INTEGER '0', BIGINT '15'),
    (DECIMAL '193530567.75', CHAR 'Electronics                                       ', CHAR 'audio                                             ', INTEGER '0', BIGINT '16'),
    (DECIMAL '4214853.45', CHAR 'Electronics                                       ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '223256946.68', CHAR 'Home                                              ', CHAR 'bedding                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '216443967.64', CHAR 'Home                                              ', CHAR 'curtains/drapes                                   ', INTEGER '0', BIGINT '2'),
    (DECIMAL '212655211.38', CHAR 'Home                                              ', CHAR 'bathroom                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '211837279.05', CHAR 'Home                                              ', CHAR 'blinds/shades                                     ', INTEGER '0', BIGINT '4'),
    (DECIMAL '210244472.68', CHAR 'Home                                              ', CHAR 'kids                                              ', INTEGER '0', BIGINT '5'),
    (DECIMAL '209826478.41', CHAR 'Home                                              ', CHAR 'rugs                                              ', INTEGER '0', BIGINT '6'),
    (DECIMAL '208808168.33', CHAR 'Home                                              ', CHAR 'flatware                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '206146392.12', CHAR 'Home                                              ', CHAR 'paint                                             ', INTEGER '0', BIGINT '8'),
    (DECIMAL '205693059.18', CHAR 'Home                                              ', CHAR 'mattresses                                        ', INTEGER '0', BIGINT '9'),
    (DECIMAL '204432257.33', CHAR 'Home                                              ', CHAR 'furniture                                         ', INTEGER '0', BIGINT '10'),
    (DECIMAL '201828460.70', CHAR 'Home                                              ', CHAR 'tables                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '200350005.38', CHAR 'Home                                              ', CHAR 'accent                                            ', INTEGER '0', BIGINT '12'),
    (DECIMAL '199998868.09', CHAR 'Home                                              ', CHAR 'glassware                                         ', INTEGER '0', BIGINT '13'),
    (DECIMAL '196989193.00', CHAR 'Home                                              ', CHAR 'lighting                                          ', INTEGER '0', BIGINT '14'),
    (DECIMAL '194301003.75', CHAR 'Home                                              ', CHAR 'decor                                             ', INTEGER '0', BIGINT '15'),
    (DECIMAL '189361394.93', CHAR 'Home                                              ', CHAR 'wallpaper                                         ', INTEGER '0', BIGINT '16'),
    (DECIMAL '3734793.12', CHAR 'Home                                              ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '228782403.24', CHAR 'Jewelry                                           ', CHAR 'jewelry boxes                                     ', INTEGER '0', BIGINT '1'),
    (DECIMAL '218079096.96', CHAR 'Jewelry                                           ', CHAR 'rings                                             ', INTEGER '0', BIGINT '2'),
    (DECIMAL '214483016.38', CHAR 'Jewelry                                           ', CHAR 'mens watch                                        ', INTEGER '0', BIGINT '3'),
    (DECIMAL '214275224.35', CHAR 'Jewelry                                           ', CHAR 'gold                                              ', INTEGER '0', BIGINT '4'),
    (DECIMAL '212667068.82', CHAR 'Jewelry                                           ', CHAR 'womens watch                                      ', INTEGER '0', BIGINT '5'),
    (DECIMAL '211255023.31', CHAR 'Jewelry                                           ', CHAR 'estate                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '209654145.16', CHAR 'Jewelry                                           ', CHAR 'pendants                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '204264437.36', CHAR 'Jewelry                                           ', CHAR 'costume                                           ', INTEGER '0', BIGINT '8'),
    (DECIMAL '202217895.03', CHAR 'Jewelry                                           ', CHAR 'consignment                                       ', INTEGER '0', BIGINT '9'),
    (DECIMAL '201705650.65', CHAR 'Jewelry                                           ', CHAR 'custom                                            ', INTEGER '0', BIGINT '10'),
    (DECIMAL '201085136.42', CHAR 'Jewelry                                           ', CHAR 'birdal                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '195762539.38', CHAR 'Jewelry                                           ', CHAR 'semi-precious                                     ', INTEGER '0', BIGINT '12'),
    (DECIMAL '195354549.72', CHAR 'Jewelry                                           ', CHAR 'earings                                           ', INTEGER '0', BIGINT '13'),
    (DECIMAL '192214870.43', CHAR 'Jewelry                                           ', CHAR 'loose stones                                      ', INTEGER '0', BIGINT '14'),
    (DECIMAL '189385376.32', CHAR 'Jewelry                                           ', CHAR 'bracelets                                         ', INTEGER '0', BIGINT '15'),
    (DECIMAL '189256085.14', CHAR 'Jewelry                                           ', CHAR 'diamonds                                          ', INTEGER '0', BIGINT '16'),
    (DECIMAL '3459150.59', CHAR 'Jewelry                                           ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '844608683.12', CHAR 'Men                                               ', CHAR 'accessories                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '827794207.16', CHAR 'Men                                               ', CHAR 'shirts                                            ', INTEGER '0', BIGINT '2'),
    (DECIMAL '824014987.31', CHAR 'Men                                               ', CHAR 'sports-apparel                                    ', INTEGER '0', BIGINT '3'),
    (DECIMAL '778919176.14', CHAR 'Men                                               ', CHAR 'pants                                             ', INTEGER '0', BIGINT '4'),
    (DECIMAL '5033052.67', CHAR 'Men                                               ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '848445381.39', CHAR 'Music                                             ', CHAR 'classical                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '837786250.76', CHAR 'Music                                             ', CHAR 'country                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '811463721.70', CHAR 'Music                                             ', CHAR 'pop                                               ', INTEGER '0', BIGINT '3'),
    (DECIMAL '810411056.17', CHAR 'Music                                             ', CHAR 'rock                                              ', INTEGER '0', BIGINT '4'),
    (DECIMAL '5610924.84', CHAR 'Music                                             ', NULL, INTEGER '0', BIGINT '5'),
    (DECIMAL '840740397.95', CHAR 'Shoes                                             ', CHAR 'athletic                                          ', INTEGER '0', BIGINT '1'),
    (DECIMAL '825310468.77', CHAR 'Shoes                                             ', CHAR 'womens                                            ', INTEGER '0', BIGINT '2'),
    (DECIMAL '820816621.13', CHAR 'Shoes                                             ', CHAR 'kids                                              ', INTEGER '0', BIGINT '3'),
    (DECIMAL '803477226.10', CHAR 'Shoes                                             ', CHAR 'mens                                              ', INTEGER '0', BIGINT '4'),
    (DECIMAL '4000252.07', CHAR 'Shoes                                             ', NULL, INTEGER '0', BIGINT '5')
)
