SELECT *
FROM
(
  VALUES
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'California', BIGINT '8109', BIGINT '8635', BIGINT '8575', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'California_1', BIGINT '8216', BIGINT '8643', BIGINT '8639', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Hawaii/Alaska', BIGINT '8284', BIGINT '8348', BIGINT '8480', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Hawaii/Alaska_1', BIGINT '8220', BIGINT '8450', BIGINT '8499', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic', BIGINT '8197', BIGINT '8704', BIGINT '8602', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic_1', BIGINT '8287', BIGINT '8635', BIGINT '8629', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic_2', BIGINT '8271', BIGINT '8599', BIGINT '8478', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro', BIGINT '8200', BIGINT '8550', BIGINT '8537', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro_1', BIGINT '8269', BIGINT '8703', BIGINT '8620', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro_2', BIGINT '8314', BIGINT '8507', BIGINT '8443', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'North Midwest', BIGINT '8260', BIGINT '8470', BIGINT '8622', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'North Midwest_1', BIGINT '8133', BIGINT '8597', BIGINT '8525', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'North Midwest_2', BIGINT '8448', BIGINT '8548', BIGINT '8622', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Pacific Northwest', BIGINT '8398', BIGINT '8564', BIGINT '8382', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'EXPRESS                       ', VARCHAR 'Pacific Northwest_1', BIGINT '8452', BIGINT '8478', BIGINT '8437', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'California', BIGINT '6304', BIGINT '6533', BIGINT '6271', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'California_1', BIGINT '6173', BIGINT '6252', BIGINT '6442', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Hawaii/Alaska', BIGINT '6160', BIGINT '6414', BIGINT '6336', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Hawaii/Alaska_1', BIGINT '6236', BIGINT '6256', BIGINT '6524', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Mid Atlantic', BIGINT '6250', BIGINT '6517', BIGINT '6400', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Mid Atlantic_1', BIGINT '6080', BIGINT '6543', BIGINT '6398', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Mid Atlantic_2', BIGINT '6128', BIGINT '6616', BIGINT '6370', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'NY Metro', BIGINT '6244', BIGINT '6376', BIGINT '6529', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'NY Metro_1', BIGINT '6067', BIGINT '6404', BIGINT '6443', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'NY Metro_2', BIGINT '6094', BIGINT '6363', BIGINT '6443', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'North Midwest', BIGINT '6210', BIGINT '6453', BIGINT '6284', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'North Midwest_1', BIGINT '6192', BIGINT '6474', BIGINT '6338', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'North Midwest_2', BIGINT '6171', BIGINT '6493', BIGINT '6467', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Pacific Northwest', BIGINT '6149', BIGINT '6516', BIGINT '6376', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'LIBRARY                       ', VARCHAR 'Pacific Northwest_1', BIGINT '6031', BIGINT '6516', BIGINT '6321', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'California', BIGINT '8232', BIGINT '8655', BIGINT '8600', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'California_1', BIGINT '8214', BIGINT '8630', BIGINT '8493', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Hawaii/Alaska', BIGINT '8146', BIGINT '8530', BIGINT '8669', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Hawaii/Alaska_1', BIGINT '8345', BIGINT '8454', BIGINT '8475', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Mid Atlantic', BIGINT '8372', BIGINT '8573', BIGINT '8627', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Mid Atlantic_1', BIGINT '8338', BIGINT '8698', BIGINT '8518', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Mid Atlantic_2', BIGINT '8255', BIGINT '8639', BIGINT '8469', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'NY Metro', BIGINT '8116', BIGINT '8591', BIGINT '8548', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'NY Metro_1', BIGINT '8488', BIGINT '8541', BIGINT '8441', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'NY Metro_2', BIGINT '8303', BIGINT '8557', BIGINT '8413', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'North Midwest', BIGINT '8438', BIGINT '8549', BIGINT '8546', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'North Midwest_1', BIGINT '8213', BIGINT '8475', BIGINT '8436', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'North Midwest_2', BIGINT '8256', BIGINT '8548', BIGINT '8608', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Pacific Northwest', BIGINT '8317', BIGINT '8337', BIGINT '8329', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'NEXT DAY                      ', VARCHAR 'Pacific Northwest_1', BIGINT '8380', BIGINT '8387', BIGINT '8679', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'California', BIGINT '6217', BIGINT '6422', BIGINT '6470', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'California_1', BIGINT '6204', BIGINT '6295', BIGINT '6412', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Hawaii/Alaska', BIGINT '6283', BIGINT '6423', BIGINT '6384', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Hawaii/Alaska_1', BIGINT '6410', BIGINT '6424', BIGINT '6486', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Mid Atlantic', BIGINT '6214', BIGINT '6488', BIGINT '6393', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Mid Atlantic_1', BIGINT '6321', BIGINT '6513', BIGINT '6344', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Mid Atlantic_2', BIGINT '6282', BIGINT '6193', BIGINT '6393', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'NY Metro', BIGINT '6213', BIGINT '6541', BIGINT '6331', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'NY Metro_1', BIGINT '6131', BIGINT '6407', BIGINT '6439', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'NY Metro_2', BIGINT '6161', BIGINT '6367', BIGINT '6464', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'North Midwest', BIGINT '6183', BIGINT '6449', BIGINT '6508', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'North Midwest_1', BIGINT '6115', BIGINT '6434', BIGINT '6324', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'North Midwest_2', BIGINT '6220', BIGINT '6475', BIGINT '6560', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Pacific Northwest', BIGINT '6256', BIGINT '6388', BIGINT '6456', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'OVERNIGHT                     ', VARCHAR 'Pacific Northwest_1', BIGINT '6090', BIGINT '6332', BIGINT '6370', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'California', BIGINT '6276', BIGINT '6343', BIGINT '6489', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'California_1', BIGINT '6194', BIGINT '6514', BIGINT '6318', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Hawaii/Alaska', BIGINT '6069', BIGINT '6351', BIGINT '6401', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Hawaii/Alaska_1', BIGINT '6161', BIGINT '6370', BIGINT '6568', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Mid Atlantic', BIGINT '6062', BIGINT '6490', BIGINT '6463', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Mid Atlantic_1', BIGINT '6236', BIGINT '6400', BIGINT '6339', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Mid Atlantic_2', BIGINT '6162', BIGINT '6431', BIGINT '6450', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'NY Metro', BIGINT '6186', BIGINT '6363', BIGINT '6412', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'NY Metro_1', BIGINT '6085', BIGINT '6387', BIGINT '6354', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'NY Metro_2', BIGINT '6154', BIGINT '6278', BIGINT '6439', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'North Midwest', BIGINT '6159', BIGINT '6460', BIGINT '6554', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'North Midwest_1', BIGINT '6052', BIGINT '6227', BIGINT '6342', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'North Midwest_2', BIGINT '6188', BIGINT '6306', BIGINT '6280', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Pacific Northwest', BIGINT '6228', BIGINT '6390', BIGINT '6453', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'REGULAR                       ', VARCHAR 'Pacific Northwest_1', BIGINT '6196', BIGINT '6474', BIGINT '6423', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'California', BIGINT '6141', BIGINT '6334', BIGINT '6463', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'California_1', BIGINT '6274', BIGINT '6199', BIGINT '6516', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Hawaii/Alaska', BIGINT '6224', BIGINT '6385', BIGINT '6491', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Hawaii/Alaska_1', BIGINT '6178', BIGINT '6391', BIGINT '6502', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Mid Atlantic', BIGINT '5980', BIGINT '6356', BIGINT '6291', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Mid Atlantic_1', BIGINT '6316', BIGINT '6381', BIGINT '6328', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Mid Atlantic_2', BIGINT '6304', BIGINT '6268', BIGINT '6524', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'NY Metro', BIGINT '6194', BIGINT '6383', BIGINT '6390', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'NY Metro_1', BIGINT '6351', BIGINT '6413', BIGINT '6519', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'NY Metro_2', BIGINT '6173', BIGINT '6497', BIGINT '6391', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'North Midwest', BIGINT '6107', BIGINT '6414', BIGINT '6364', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'North Midwest_1', BIGINT '6288', BIGINT '6366', BIGINT '6274', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'North Midwest_2', BIGINT '6141', BIGINT '6356', BIGINT '6385', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Pacific Northwest', BIGINT '6283', BIGINT '6393', BIGINT '6469', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Bad cards must make.', CHAR 'TWO DAY                       ', VARCHAR 'Pacific Northwest_1', BIGINT '6161', BIGINT '6434', BIGINT '6398', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'California', BIGINT '8268', BIGINT '8495', BIGINT '8440', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'California_1', BIGINT '8251', BIGINT '8723', BIGINT '8538', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'Hawaii/Alaska', BIGINT '8271', BIGINT '8723', BIGINT '8498', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'Hawaii/Alaska_1', BIGINT '8224', BIGINT '8559', BIGINT '8569', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic', BIGINT '8316', BIGINT '8628', BIGINT '8532', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic_1', BIGINT '8251', BIGINT '8580', BIGINT '8488', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'Mid Atlantic_2', BIGINT '8242', BIGINT '8632', BIGINT '8603', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro', BIGINT '8245', BIGINT '8582', BIGINT '8638', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro_1', BIGINT '8339', BIGINT '8704', BIGINT '8355', BIGINT '0', BIGINT '0'),
    (VARCHAR 'Conventional childr', CHAR 'EXPRESS                       ', VARCHAR 'NY Metro_2', BIGINT '8294', BIGINT '8658', BIGINT '8440', BIGINT '0', BIGINT '0')
)
