SELECT *
FROM
(
  VALUES
    (CHAR 'n stcallyable                                     ', CHAR 'exportiexporti #2                                 ', CHAR 'toddlers                                          ', CHAR 'Children                                          ', DOUBLE '376.40816326530614'),
    (CHAR 'n stcallyable                                     ', CHAR 'exportiexporti #2                                 ', CHAR 'toddlers                                          ', NULL, DOUBLE '376.40816326530614'),
    (CHAR 'n stcallyable                                     ', CHAR 'exportiexporti #2                                 ', NULL, NULL, DOUBLE '376.40816326530614'),
    (CHAR 'n stcallyable                                     ', NULL, NULL, NULL, DOUBLE '376.40816326530614'),
    (CHAR 'oughtcallycally                                   ', CHAR 'edu packamalgamalg #16                            ', CHAR 'automotive                                        ', CHAR 'Electronics                                       ', DOUBLE '379.1276595744681'),
    (CHAR 'oughtcallycally                                   ', CHAR 'edu packamalgamalg #16                            ', CHAR 'automotive                                        ', NULL, DOUBLE '379.1276595744681'),
    (CHAR 'oughtcallycally                                   ', CHAR 'edu packamalgamalg #16                            ', NULL, NULL, DOUBLE '379.1276595744681'),
    (CHAR 'oughtcallycally                                   ', NULL, NULL, NULL, DOUBLE '379.1276595744681'),
    (CHAR 'ableoughteseought                                 ', CHAR 'exportimaxi #3                                    ', CHAR 'sailing                                           ', CHAR 'Sports                                            ', DOUBLE '380.9782608695652'),
    (CHAR 'ableoughteseought                                 ', CHAR 'exportimaxi #3                                    ', CHAR 'sailing                                           ', NULL, DOUBLE '380.9782608695652'),
    (CHAR 'ableoughteseought                                 ', CHAR 'exportimaxi #3                                    ', NULL, NULL, DOUBLE '380.9782608695652'),
    (CHAR 'ableoughteseought                                 ', NULL, NULL, NULL, DOUBLE '380.9782608695652'),
    (CHAR 'n stn stbarought                                  ', CHAR 'brandnameless #10                                 ', CHAR 'hockey                                            ', CHAR 'Sports                                            ', DOUBLE '386.8541666666667'),
    (CHAR 'n stn stbarought                                  ', CHAR 'brandnameless #10                                 ', CHAR 'hockey                                            ', NULL, DOUBLE '386.8541666666667'),
    (CHAR 'n stn stbarought                                  ', CHAR 'brandnameless #10                                 ', NULL, NULL, DOUBLE '386.8541666666667'),
    (CHAR 'n stn stbarought                                  ', NULL, NULL, NULL, DOUBLE '386.8541666666667'),
    (CHAR 'antiationation                                    ', CHAR 'amalgamalg #2                                     ', CHAR 'dresses                                           ', CHAR 'Women                                             ', DOUBLE '392.34'),
    (CHAR 'antiationation                                    ', CHAR 'amalgamalg #2                                     ', CHAR 'dresses                                           ', NULL, DOUBLE '392.34'),
    (CHAR 'antiationation                                    ', CHAR 'amalgamalg #2                                     ', NULL, NULL, DOUBLE '392.34'),
    (CHAR 'antiationation                                    ', NULL, NULL, NULL, DOUBLE '392.34'),
    (CHAR 'ationbaration                                     ', CHAR 'edu packexporti #2                                ', CHAR 'school-uniforms                                   ', CHAR 'Children                                          ', DOUBLE '393.0408163265306'),
    (CHAR 'ationbaration                                     ', CHAR 'edu packexporti #2                                ', CHAR 'school-uniforms                                   ', NULL, DOUBLE '393.0408163265306'),
    (CHAR 'ationbaration                                     ', CHAR 'edu packexporti #2                                ', NULL, NULL, DOUBLE '393.0408163265306'),
    (CHAR 'ationbaration                                     ', NULL, NULL, NULL, DOUBLE '393.0408163265306'),
    (CHAR 'ationpri                                          ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '394.265306122449'),
    (CHAR 'ationpri                                          ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '394.265306122449'),
    (CHAR 'ationpri                                          ', CHAR 'amalgimporto #2                                   ', NULL, NULL, DOUBLE '394.265306122449'),
    (CHAR 'ationpri                                          ', NULL, NULL, NULL, DOUBLE '394.265306122449'),
    (CHAR 'eingablen stought                                 ', CHAR 'scholarmaxi #9                                    ', CHAR 'history                                           ', CHAR 'Books                                             ', DOUBLE '394.5833333333333'),
    (CHAR 'eingablen stought                                 ', CHAR 'scholarmaxi #9                                    ', CHAR 'history                                           ', NULL, DOUBLE '394.5833333333333'),
    (CHAR 'eingablen stought                                 ', CHAR 'scholarmaxi #9                                    ', NULL, NULL, DOUBLE '394.5833333333333'),
    (CHAR 'eingablen stought                                 ', NULL, NULL, NULL, DOUBLE '394.5833333333333'),
    (CHAR 'able                                              ', CHAR 'amalgamalg #1                                     ', CHAR 'dresses                                           ', CHAR 'Women                                             ', DOUBLE '395.12'),
    (CHAR 'able                                              ', CHAR 'amalgamalg #1                                     ', CHAR 'dresses                                           ', NULL, DOUBLE '395.12'),
    (CHAR 'able                                              ', CHAR 'amalgamalg #1                                     ', NULL, NULL, DOUBLE '395.12'),
    (CHAR 'able                                              ', NULL, NULL, NULL, DOUBLE '395.12'),
    (CHAR 'eseeseableought                                   ', CHAR 'amalgexporti #1                                   ', CHAR 'newborn                                           ', CHAR 'Children                                          ', DOUBLE '395.70212765957444'),
    (CHAR 'eseeseableought                                   ', CHAR 'amalgexporti #1                                   ', CHAR 'newborn                                           ', NULL, DOUBLE '395.70212765957444'),
    (CHAR 'eseeseableought                                   ', CHAR 'amalgexporti #1                                   ', NULL, NULL, DOUBLE '395.70212765957444'),
    (CHAR 'eseeseableought                                   ', NULL, NULL, NULL, DOUBLE '395.70212765957444'),
    (CHAR 'pripripriought                                    ', CHAR 'importounivamalg #2                               ', CHAR 'home repair                                       ', CHAR 'Books                                             ', DOUBLE '396.6470588235294'),
    (CHAR 'pripripriought                                    ', CHAR 'importounivamalg #2                               ', CHAR 'home repair                                       ', NULL, DOUBLE '396.6470588235294'),
    (CHAR 'pripripriought                                    ', CHAR 'importounivamalg #2                               ', NULL, NULL, DOUBLE '396.6470588235294'),
    (CHAR 'pripripriought                                    ', NULL, NULL, NULL, DOUBLE '396.6470588235294'),
    (CHAR 'oughtbarcallyought                                ', CHAR 'importonameless #2                                ', CHAR 'paint                                             ', CHAR 'Home                                              ', DOUBLE '396.9795918367347'),
    (CHAR 'oughtbarcallyought                                ', CHAR 'importonameless #2                                ', CHAR 'paint                                             ', NULL, DOUBLE '396.9795918367347'),
    (CHAR 'oughtbarcallyought                                ', CHAR 'importonameless #2                                ', NULL, NULL, DOUBLE '396.9795918367347'),
    (CHAR 'oughtbarcallyought                                ', NULL, NULL, NULL, DOUBLE '396.9795918367347'),
    (CHAR 'ablen stableought                                 ', CHAR 'scholarmaxi #3                                    ', CHAR 'fishing                                           ', CHAR 'Sports                                            ', DOUBLE '397.0576923076923'),
    (CHAR 'ablen stableought                                 ', CHAR 'scholarmaxi #3                                    ', CHAR 'fishing                                           ', NULL, DOUBLE '397.0576923076923'),
    (CHAR 'ablen stableought                                 ', CHAR 'scholarmaxi #3                                    ', NULL, NULL, DOUBLE '397.0576923076923'),
    (CHAR 'ablen stableought                                 ', NULL, NULL, NULL, DOUBLE '397.0576923076923'),
    (CHAR 'eseoughtantiought                                 ', CHAR 'importoamalg #1                                   ', CHAR 'fragrances                                        ', CHAR 'Women                                             ', DOUBLE '397.83673469387753'),
    (CHAR 'eseoughtantiought                                 ', CHAR 'importoamalg #1                                   ', CHAR 'fragrances                                        ', NULL, DOUBLE '397.83673469387753'),
    (CHAR 'eseoughtantiought                                 ', CHAR 'importoamalg #1                                   ', NULL, NULL, DOUBLE '397.83673469387753'),
    (CHAR 'eseoughtantiought                                 ', NULL, NULL, NULL, DOUBLE '397.83673469387753'),
    (CHAR 'ationn stese                                      ', CHAR 'univamalgamalg #5                                 ', CHAR 'memory                                            ', CHAR 'Electronics                                       ', DOUBLE '398.9583333333333'),
    (CHAR 'ationn stese                                      ', CHAR 'univamalgamalg #5                                 ', CHAR 'memory                                            ', NULL, DOUBLE '398.9583333333333'),
    (CHAR 'ationn stese                                      ', CHAR 'univamalgamalg #5                                 ', NULL, NULL, DOUBLE '398.9583333333333'),
    (CHAR 'ationn stese                                      ', NULL, NULL, NULL, DOUBLE '398.9583333333333'),
    (CHAR 'priationn st                                      ', CHAR 'univnameless #4                                   ', CHAR 'flatware                                          ', CHAR 'Home                                              ', DOUBLE '401.8775510204082'),
    (CHAR 'priationn st                                      ', CHAR 'univnameless #4                                   ', CHAR 'flatware                                          ', NULL, DOUBLE '401.8775510204082'),
    (CHAR 'priationn st                                      ', CHAR 'univnameless #4                                   ', NULL, NULL, DOUBLE '401.8775510204082'),
    (CHAR 'priationn st                                      ', NULL, NULL, NULL, DOUBLE '401.8775510204082'),
    (CHAR 'antiprieingought                                  ', CHAR 'brandbrand #6                                     ', CHAR 'decor                                             ', CHAR 'Home                                              ', DOUBLE '407.44897959183675'),
    (CHAR 'antiprieingought                                  ', CHAR 'brandbrand #6                                     ', CHAR 'decor                                             ', NULL, DOUBLE '407.44897959183675'),
    (CHAR 'antiprieingought                                  ', CHAR 'brandbrand #6                                     ', NULL, NULL, DOUBLE '407.44897959183675'),
    (CHAR 'antiprieingought                                  ', NULL, NULL, NULL, DOUBLE '407.44897959183675'),
    (CHAR 'ationoughteingought                               ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '407.53846153846155'),
    (CHAR 'ationoughteingought                               ', CHAR 'amalgimporto #2                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '407.53846153846155'),
    (CHAR 'ationoughteingought                               ', CHAR 'amalgimporto #2                                   ', NULL, NULL, DOUBLE '407.53846153846155'),
    (CHAR 'ationoughteingought                               ', NULL, NULL, NULL, DOUBLE '407.53846153846155'),
    (CHAR 'oughtpri                                          ', CHAR 'scholarmaxi #2                                    ', CHAR 'fishing                                           ', CHAR 'Sports                                            ', DOUBLE '408.15686274509807'),
    (CHAR 'oughtpri                                          ', CHAR 'scholarmaxi #2                                    ', CHAR 'fishing                                           ', NULL, DOUBLE '408.15686274509807'),
    (CHAR 'oughtpri                                          ', CHAR 'scholarmaxi #2                                    ', NULL, NULL, DOUBLE '408.15686274509807'),
    (CHAR 'oughtpri                                          ', NULL, NULL, NULL, DOUBLE '408.15686274509807'),
    (CHAR 'oughtn stableought                                ', CHAR 'scholarmaxi #8                                    ', CHAR 'history                                           ', CHAR 'Books                                             ', DOUBLE '408.76'),
    (CHAR 'oughtn stableought                                ', CHAR 'scholarmaxi #8                                    ', CHAR 'history                                           ', NULL, DOUBLE '408.76'),
    (CHAR 'oughtn stableought                                ', CHAR 'scholarmaxi #8                                    ', NULL, NULL, DOUBLE '408.76'),
    (CHAR 'oughtn stableought                                ', NULL, NULL, NULL, DOUBLE '408.76'),
    (CHAR 'callyationcallyought                              ', CHAR 'amalgimporto #1                                   ', CHAR 'accessories                                       ', CHAR 'Men                                               ', DOUBLE '408.9795918367347'),
    (CHAR 'callyationcallyought                              ', CHAR 'amalgimporto #1                                   ', CHAR 'accessories                                       ', NULL, DOUBLE '408.9795918367347'),
    (CHAR 'callyationcallyought                              ', CHAR 'amalgimporto #1                                   ', NULL, NULL, DOUBLE '408.9795918367347'),
    (CHAR 'callyationcallyought                              ', NULL, NULL, NULL, DOUBLE '408.9795918367347'),
    (CHAR 'oughtcallyeingought                               ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', CHAR 'Shoes                                             ', DOUBLE '410.51020408163265'),
    (CHAR 'oughtcallyeingought                               ', CHAR 'amalgedu pack #2                                  ', CHAR 'womens                                            ', NULL, DOUBLE '410.51020408163265'),
    (CHAR 'oughtcallyeingought                               ', CHAR 'amalgedu pack #2                                  ', NULL, NULL, DOUBLE '410.51020408163265'),
    (CHAR 'oughtcallyeingought                               ', NULL, NULL, NULL, DOUBLE '410.51020408163265'),
    (CHAR 'ationeseableought                                 ', CHAR 'amalgscholar #2                                   ', CHAR 'rock                                              ', CHAR 'Music                                             ', DOUBLE '410.921568627451'),
    (CHAR 'ationeseableought                                 ', CHAR 'amalgscholar #2                                   ', CHAR 'rock                                              ', NULL, DOUBLE '410.921568627451'),
    (CHAR 'ationeseableought                                 ', CHAR 'amalgscholar #2                                   ', NULL, NULL, DOUBLE '410.921568627451'),
    (CHAR 'ationeseableought                                 ', NULL, NULL, NULL, DOUBLE '410.921568627451'),
    (CHAR 'eingeingought                                     ', CHAR 'scholarunivamalg #9                               ', CHAR 'fiction                                           ', CHAR 'Books                                             ', DOUBLE '414.0'),
    (CHAR 'eingeingought                                     ', CHAR 'scholarunivamalg #9                               ', CHAR 'fiction                                           ', NULL, DOUBLE '414.0'),
    (CHAR 'eingeingought                                     ', CHAR 'scholarunivamalg #9                               ', NULL, NULL, DOUBLE '414.0'),
    (CHAR 'eingeingought                                     ', NULL, NULL, NULL, DOUBLE '414.0'),
    (CHAR 'oughtanticallyought                               ', CHAR 'importoamalg #2                                   ', CHAR 'fragrances                                        ', CHAR 'Women                                             ', DOUBLE '414.19607843137254'),
    (CHAR 'oughtanticallyought                               ', CHAR 'importoamalg #2                                   ', CHAR 'fragrances                                        ', NULL, DOUBLE '414.19607843137254'),
    (CHAR 'oughtanticallyought                               ', CHAR 'importoamalg #2                                   ', NULL, NULL, DOUBLE '414.19607843137254'),
    (CHAR 'oughtanticallyought                               ', NULL, NULL, NULL, DOUBLE '414.19607843137254')
)
