SELECT *
FROM
(
  VALUES
    (DECIMAL '-0.43', NULL, NULL, INTEGER '2', BIGINT '1'),
    (DECIMAL '-0.45', CHAR 'Books                                             ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '-0.45', CHAR 'Men                                               ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '-0.45', CHAR 'Music                                             ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '-0.45', CHAR 'Shoes                                             ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '-0.45', NULL, NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '-0.44', CHAR 'Sports                                            ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '-0.44', CHAR 'Women                                             ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '-0.42', CHAR 'Children                                          ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '-0.42', CHAR 'Home                                              ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '-0.42', CHAR 'Jewelry                                           ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '-0.41', CHAR 'Electronics                                       ', NULL, INTEGER '1', BIGINT '11'),
    (DECIMAL '-0.66', CHAR 'Books                                             ', CHAR 'self-help                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.55', CHAR 'Books                                             ', CHAR 'reference                                         ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.54', CHAR 'Books                                             ', CHAR 'fiction                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.52', CHAR 'Books                                             ', CHAR 'romance                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.52', CHAR 'Books                                             ', CHAR 'sports                                            ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.48', CHAR 'Books                                             ', CHAR 'parenting                                         ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.45', CHAR 'Books                                             ', CHAR 'cooking                                           ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.43', CHAR 'Books                                             ', CHAR 'history                                           ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.42', CHAR 'Books                                             ', CHAR 'entertainments                                    ', INTEGER '0', BIGINT '9'),
    (DECIMAL '-0.41', CHAR 'Books                                             ', CHAR 'home repair                                       ', INTEGER '0', BIGINT '10'),
    (DECIMAL '-0.40', CHAR 'Books                                             ', CHAR 'travel                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.39', CHAR 'Books                                             ', CHAR 'arts                                              ', INTEGER '0', BIGINT '12'),
    (DECIMAL '-0.38', CHAR 'Books                                             ', CHAR 'science                                           ', INTEGER '0', BIGINT '13'),
    (DECIMAL '-0.36', CHAR 'Books                                             ', CHAR 'computers                                         ', INTEGER '0', BIGINT '14'),
    (DECIMAL '-0.34', CHAR 'Books                                             ', CHAR 'mystery                                           ', INTEGER '0', BIGINT '15'),
    (DECIMAL '-0.25', CHAR 'Books                                             ', CHAR 'business                                          ', INTEGER '0', BIGINT '16'),
    (DECIMAL '-0.49', CHAR 'Children                                          ', CHAR 'toddlers                                          ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.44', CHAR 'Children                                          ', CHAR 'newborn                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.40', CHAR 'Children                                          ', CHAR 'school-uniforms                                   ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.34', CHAR 'Children                                          ', CHAR 'infants                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.74', CHAR 'Electronics                                       ', CHAR 'scanners                                          ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.61', CHAR 'Electronics                                       ', CHAR 'portable                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.49', CHAR 'Electronics                                       ', CHAR 'disk drives                                       ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.49', CHAR 'Electronics                                       ', CHAR 'karoke                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.48', CHAR 'Electronics                                       ', CHAR 'cameras                                           ', INTEGER '0', BIGINT '5'),
    (DECIMAL '-0.45', CHAR 'Electronics                                       ', CHAR 'televisions                                       ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.41', CHAR 'Electronics                                       ', CHAR 'monitors                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.41', CHAR 'Electronics                                       ', CHAR 'musical                                           ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.41', CHAR 'Electronics                                       ', CHAR 'stereo                                            ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.41', CHAR 'Electronics                                       ', CHAR 'wireless                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.39', CHAR 'Electronics                                       ', CHAR 'memory                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.38', CHAR 'Electronics                                       ', CHAR 'camcorders                                        ', INTEGER '0', BIGINT '12'),
    (DECIMAL '-0.34', CHAR 'Electronics                                       ', CHAR 'personal                                          ', INTEGER '0', BIGINT '13'),
    (DECIMAL '-0.33', CHAR 'Electronics                                       ', CHAR 'audio                                             ', INTEGER '0', BIGINT '14'),
    (DECIMAL '-0.29', CHAR 'Electronics                                       ', CHAR 'automotive                                        ', INTEGER '0', BIGINT '15'),
    (DECIMAL '-0.29', CHAR 'Electronics                                       ', CHAR 'dvd/vcr players                                   ', INTEGER '0', BIGINT '15'),
    (DECIMAL '-0.68', CHAR 'Home                                              ', CHAR 'glassware                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.56', CHAR 'Home                                              ', CHAR 'accent                                            ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.54', CHAR 'Home                                              ', CHAR 'lighting                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.50', CHAR 'Home                                              ', CHAR 'furniture                                         ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.50', CHAR 'Home                                              ', CHAR 'mattresses                                        ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.48', CHAR 'Home                                              ', CHAR 'kids                                              ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.43', CHAR 'Home                                              ', CHAR 'decor                                             ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.41', CHAR 'Home                                              ', CHAR 'flatware                                          ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.41', CHAR 'Home                                              ', CHAR 'paint                                             ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.41', CHAR 'Home                                              ', CHAR 'wallpaper                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.34', CHAR 'Home                                              ', CHAR 'blinds/shades                                     ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.34', CHAR 'Home                                              ', CHAR 'curtains/drapes                                   ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.33', CHAR 'Home                                              ', CHAR 'bathroom                                          ', INTEGER '0', BIGINT '13'),
    (DECIMAL '-0.33', CHAR 'Home                                              ', CHAR 'rugs                                              ', INTEGER '0', BIGINT '13'),
    (DECIMAL '-0.33', CHAR 'Home                                              ', CHAR 'tables                                            ', INTEGER '0', BIGINT '13'),
    (DECIMAL '-0.32', CHAR 'Home                                              ', CHAR 'bedding                                           ', INTEGER '0', BIGINT '16'),
    (DECIMAL '-0.78', CHAR 'Jewelry                                           ', CHAR 'mens watch                                        ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.57', CHAR 'Jewelry                                           ', CHAR 'diamonds                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.52', CHAR 'Jewelry                                           ', CHAR 'loose stones                                      ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.50', CHAR 'Jewelry                                           ', CHAR 'semi-precious                                     ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.48', CHAR 'Jewelry                                           ', CHAR 'womens watch                                      ', INTEGER '0', BIGINT '5'),
    (DECIMAL '-0.47', CHAR 'Jewelry                                           ', CHAR 'custom                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.46', CHAR 'Jewelry                                           ', CHAR 'costume                                           ', INTEGER '0', BIGINT '7'),
    (DECIMAL '-0.44', CHAR 'Jewelry                                           ', CHAR 'earings                                           ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.44', CHAR 'Jewelry                                           ', CHAR 'gold                                              ', INTEGER '0', BIGINT '8'),
    (DECIMAL '-0.42', CHAR 'Jewelry                                           ', CHAR 'estate                                            ', INTEGER '0', BIGINT '10'),
    (DECIMAL '-0.32', CHAR 'Jewelry                                           ', CHAR 'bracelets                                         ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.32', CHAR 'Jewelry                                           ', CHAR 'consignment                                       ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.32', CHAR 'Jewelry                                           ', CHAR 'jewelry boxes                                     ', INTEGER '0', BIGINT '11'),
    (DECIMAL '-0.31', CHAR 'Jewelry                                           ', CHAR 'pendants                                          ', INTEGER '0', BIGINT '14'),
    (DECIMAL '-0.29', CHAR 'Jewelry                                           ', CHAR 'birdal                                            ', INTEGER '0', BIGINT '15'),
    (DECIMAL '-0.20', CHAR 'Jewelry                                           ', CHAR 'rings                                             ', INTEGER '0', BIGINT '16'),
    (DECIMAL '-0.54', CHAR 'Men                                               ', CHAR 'accessories                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.44', CHAR 'Men                                               ', CHAR 'sports-apparel                                    ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.42', CHAR 'Men                                               ', CHAR 'shirts                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.40', CHAR 'Men                                               ', CHAR 'pants                                             ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.50', CHAR 'Music                                             ', CHAR 'rock                                              ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.45', CHAR 'Music                                             ', CHAR 'country                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.44', CHAR 'Music                                             ', CHAR 'classical                                         ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.42', CHAR 'Music                                             ', CHAR 'pop                                               ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.52', CHAR 'Shoes                                             ', CHAR 'kids                                              ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.46', CHAR 'Shoes                                             ', CHAR 'athletic                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.43', CHAR 'Shoes                                             ', CHAR 'mens                                              ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.41', CHAR 'Shoes                                             ', CHAR 'womens                                            ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.77', CHAR 'Sports                                            ', CHAR 'tennis                                            ', INTEGER '0', BIGINT '1'),
    (DECIMAL '-0.59', CHAR 'Sports                                            ', CHAR 'sailing                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '-0.55', CHAR 'Sports                                            ', CHAR 'basketball                                        ', INTEGER '0', BIGINT '3'),
    (DECIMAL '-0.49', CHAR 'Sports                                            ', CHAR 'camping                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '-0.48', CHAR 'Sports                                            ', CHAR 'baseball                                          ', INTEGER '0', BIGINT '5'),
    (DECIMAL '-0.47', CHAR 'Sports                                            ', CHAR 'fitness                                           ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.47', CHAR 'Sports                                            ', CHAR 'golf                                              ', INTEGER '0', BIGINT '6'),
    (DECIMAL '-0.45', CHAR 'Sports                                            ', CHAR 'guns                                              ', INTEGER '0', BIGINT '8')
)
