SELECT *
FROM
(
  VALUES
    (CHAR 'Adams                         ', CHAR 'Catherine           ', VARCHAR 'Riverdale', VARCHAR 'Summit', BIGINT '2987', DECIMAL '1600.79', DECIMAL '-15133.13'),
    (CHAR 'Adams                         ', CHAR 'Chris               ', VARCHAR 'Spring Hill', VARCHAR 'Fairfield', BIGINT '3922', DECIMAL '0.00', DECIMAL '-12338.60'),
    (CHAR 'Adams                         ', CHAR 'Chris               ', VARCHAR 'Spring Hill', VARCHAR 'Lakeview', BIGINT '114', DECIMAL '286.99', DECIMAL '-12862.22'),
    (CHAR 'Albert                        ', CHAR 'John                ', VARCHAR 'Wildwood', VARCHAR 'Mount Zion', BIGINT '7114', DECIMAL '2368.73', DECIMAL '-13170.27'),
    (CHAR 'Aldridge                      ', CHAR 'Eugene              ', VARCHAR 'Bethel', VARCHAR 'Tanglewood', BIGINT '8212', DECIMAL '3006.79', DECIMAL '-10788.48'),
    (CHAR 'Allen                         ', CHAR 'Richard             ', VARCHAR 'Oak Ridge', VARCHAR 'Greenwood', BIGINT '259', DECIMAL '144.86', DECIMAL '-6686.56'),
    (CHAR 'Andrews                       ', CHAR 'Catherine           ', VARCHAR 'Lincoln', VARCHAR 'Mount Pleasant', BIGINT '1846', DECIMAL '196.05', DECIMAL '-12250.41'),
    (CHAR 'Archie                        ', CHAR 'Geneva              ', VARCHAR 'Enterprise', VARCHAR 'Lakeview', BIGINT '89', DECIMAL '2620.27', DECIMAL '-19554.84'),
    (CHAR 'Bailey                        ', CHAR 'Margie              ', VARCHAR 'Oakwood', VARCHAR 'Five Points', BIGINT '8684', DECIMAL '375.94', DECIMAL '-19943.05'),
    (CHAR 'Bailey                        ', CHAR 'Mark                ', VARCHAR 'Enterprise', VARCHAR 'Plainview', BIGINT '6815', DECIMAL '1643.32', DECIMAL '-15523.19'),
    (CHAR 'Baker                         ', CHAR 'Monique             ', VARCHAR 'Waterloo', VARCHAR 'Harmony', BIGINT '2429', DECIMAL '10572.56', DECIMAL '-8309.10'),
    (CHAR 'Bartley                       ', CHAR 'Mark                ', VARCHAR 'Oak Ridge', VARCHAR 'Forest Hills', BIGINT '4556', DECIMAL '1693.29', DECIMAL '-12111.81'),
    (CHAR 'Bell                          ', CHAR 'David               ', VARCHAR 'Antioch', VARCHAR 'Riverview', BIGINT '7909', DECIMAL '294.67', DECIMAL '-6547.65'),
    (CHAR 'Benjamin                      ', CHAR 'Jesse               ', VARCHAR 'Riverdale', VARCHAR 'Riverside', BIGINT '4116', DECIMAL '3026.83', DECIMAL '-8970.08'),
    (CHAR 'Bennett                       ', CHAR 'Myrtle              ', VARCHAR 'Brownsville', VARCHAR 'Highland Park', BIGINT '8745', DECIMAL '231.80', DECIMAL '-7746.77'),
    (CHAR 'Berry                         ', CHAR 'Nancy               ', VARCHAR 'Woodruff', VARCHAR 'Oak Ridge', BIGINT '2352', DECIMAL '932.46', DECIMAL '-4679.93'),
    (CHAR 'Betz                          ', CHAR 'Bruce               ', VARCHAR 'Jackson', VARCHAR 'Crossroads', BIGINT '8410', DECIMAL '4851.71', DECIMAL '-5137.38'),
    (CHAR 'Billings                      ', CHAR 'Dorothy             ', VARCHAR 'Brownsville', VARCHAR 'Green Acres', BIGINT '6074', DECIMAL '3339.78', DECIMAL '-10685.06'),
    (CHAR 'Billings                      ', CHAR 'Dorothy             ', VARCHAR 'Brownsville', VARCHAR 'La Grange', BIGINT '9167', DECIMAL '6938.10', DECIMAL '-15732.81'),
    (CHAR 'Black                         ', CHAR 'Margaret            ', VARCHAR 'Royal', VARCHAR 'Shady Grove', BIGINT '2717', DECIMAL '5133.88', DECIMAL '-17266.96'),
    (CHAR 'Blair                         ', CHAR 'John                ', VARCHAR 'Spring Valley', VARCHAR 'Valley View', BIGINT '654', DECIMAL '5466.98', DECIMAL '-10040.21'),
    (CHAR 'Blount                        ', CHAR 'Diane               ', VARCHAR 'Spring Hill', VARCHAR 'Lakeside', BIGINT '4208', DECIMAL '103.96', DECIMAL '-8765.24'),
    (CHAR 'Boles                         ', CHAR 'Eduardo             ', VARCHAR 'Ludlow', VARCHAR 'Unionville', BIGINT '5129', DECIMAL '3757.41', DECIMAL '-19078.19'),
    (CHAR 'Bond                          ', CHAR 'Larry               ', VARCHAR 'Cedar Grove', VARCHAR 'Mount Olive', BIGINT '6527', DECIMAL '0.00', DECIMAL '-1347.28'),
    (CHAR 'Bond                          ', CHAR 'Larry               ', VARCHAR 'Cedar Grove', VARCHAR 'Newtown', BIGINT '324', DECIMAL '1502.67', DECIMAL '-4705.91'),
    (CHAR 'Boston                        ', CHAR 'Janet               ', VARCHAR 'Valley View', VARCHAR 'Lakeside', BIGINT '3561', DECIMAL '3771.62', DECIMAL '-15891.04'),
    (CHAR 'Bowles                        ', CHAR 'Sherry              ', VARCHAR 'Forest Hills', VARCHAR 'Five Points', BIGINT '8250', DECIMAL '6076.06', DECIMAL '-11983.57'),
    (CHAR 'Bray                          ', CHAR 'Guy                 ', VARCHAR 'Clinton', VARCHAR 'Marion', BIGINT '4562', DECIMAL '2088.69', DECIMAL '-2841.34'),
    (CHAR 'Britt                         ', CHAR 'Inez                ', VARCHAR 'Sunnyside', VARCHAR 'Green Acres', BIGINT '9595', DECIMAL '6575.91', DECIMAL '-16438.08'),
    (CHAR 'Britt                         ', CHAR 'Inez                ', VARCHAR 'Sunnyside', VARCHAR 'Plainview', BIGINT '61', DECIMAL '24.99', DECIMAL '-8704.00'),
    (CHAR 'Brooks                        ', CHAR 'Melissa             ', VARCHAR 'Providence', VARCHAR 'Fowler', BIGINT '8466', DECIMAL '4095.74', DECIMAL '-10387.59'),
    (CHAR 'Brown                         ', CHAR 'Heather             ', VARCHAR 'Riverdale', VARCHAR 'Aberdeen', BIGINT '2393', DECIMAL '9493.94', DECIMAL '-10618.67'),
    (CHAR 'Brown                         ', CHAR 'Marie               ', VARCHAR 'Lincoln', VARCHAR 'Deerfield', BIGINT '4072', DECIMAL '2.41', DECIMAL '-5139.29'),
    (CHAR 'Brown                         ', CHAR 'Michael             ', VARCHAR 'Webb', VARCHAR 'Bloomingdale', BIGINT '9277', DECIMAL '6429.26', DECIMAL '-12723.49'),
    (CHAR 'Brown                         ', CHAR 'Michael             ', VARCHAR 'Webb', VARCHAR 'Oak Grove', BIGINT '7856', DECIMAL '323.80', DECIMAL '-9731.79'),
    (CHAR 'Brown                         ', CHAR 'Sandra              ', VARCHAR 'Walnut Grove', VARCHAR 'Union Hill', BIGINT '2866', DECIMAL '356.75', DECIMAL '-2946.28'),
    (CHAR 'Brown                         ', CHAR 'Theresa             ', VARCHAR 'New Hope', VARCHAR 'Brownsville', BIGINT '6825', DECIMAL '165.07', DECIMAL '-5015.12'),
    (CHAR 'Brown                         ', CHAR 'Theresa             ', VARCHAR 'New Hope', VARCHAR 'Woodland', BIGINT '9407', DECIMAL '1402.79', DECIMAL '-9068.50'),
    (CHAR 'Browning                      ', CHAR 'Margie              ', VARCHAR 'Shiloh', VARCHAR 'Oak Ridge', BIGINT '2740', DECIMAL '3817.40', DECIMAL '-21209.48'),
    (CHAR 'Brunson                       ', CHAR 'Albert              ', VARCHAR 'Whitesville', VARCHAR 'Salem', BIGINT '7076', DECIMAL '783.32', DECIMAL '1468.92'),
    (CHAR 'Buchanan                      ', CHAR 'Alvin               ', VARCHAR 'Walnut Grove', VARCHAR 'Green Acres', BIGINT '3100', DECIMAL '4401.31', DECIMAL '-15707.98'),
    (CHAR 'Buchanan                      ', CHAR 'Alvin               ', VARCHAR 'Walnut Grove', VARCHAR 'Marion', BIGINT '537', DECIMAL '3844.58', DECIMAL '-9759.31'),
    (CHAR 'Buchanan                      ', CHAR 'Theresa             ', VARCHAR 'Brownsville', VARCHAR 'Valley View', BIGINT '7406', DECIMAL '395.25', DECIMAL '478.51'),
    (CHAR 'Burch                         ', CHAR 'James               ', VARCHAR 'Concord', VARCHAR 'Plainview', BIGINT '9253', DECIMAL '0.00', DECIMAL '-2516.68'),
    (CHAR 'Burns                         ', CHAR 'Kevin               ', VARCHAR 'Woodland', VARCHAR 'Collinsville', BIGINT '1585', DECIMAL '843.57', DECIMAL '-4030.62'),
    (CHAR 'Burns                         ', CHAR 'Kevin               ', VARCHAR 'Woodland', VARCHAR 'New Hope', BIGINT '1069', DECIMAL '2318.68', DECIMAL '-10807.43'),
    (CHAR 'Burt                          ', CHAR 'Evelyn              ', VARCHAR 'Oak Ridge', VARCHAR 'Saratoga', BIGINT '8555', DECIMAL '6706.77', DECIMAL '-8744.54'),
    (CHAR 'Butler                        ', CHAR 'Claudia             ', VARCHAR 'Five Points', VARCHAR 'Forest Hills', BIGINT '205', DECIMAL '941.70', DECIMAL '-23002.50'),
    (CHAR 'Butler                        ', CHAR 'Gregory             ', VARCHAR 'Blair', VARCHAR 'Brownsville', BIGINT '6986', DECIMAL '603.17', DECIMAL '-13404.34'),
    (CHAR 'Butler                        ', CHAR 'Gregory             ', VARCHAR 'Blair', VARCHAR 'Lakeview', BIGINT '3024', DECIMAL '1296.59', DECIMAL '-10047.65'),
    (CHAR 'Butler                        ', CHAR 'Rebecca             ', VARCHAR 'Union', VARCHAR 'Harmony', BIGINT '2035', DECIMAL '5292.73', DECIMAL '-9678.61'),
    (CHAR 'Byrd                          ', CHAR 'James               ', VARCHAR 'Calhoun', VARCHAR 'Tipton', BIGINT '4918', DECIMAL '61.11', DECIMAL '-2720.01'),
    (CHAR 'Caldwell                      ', CHAR 'Joseph              ', VARCHAR 'Forest Hills', VARCHAR 'Clearview', BIGINT '2069', DECIMAL '889.20', DECIMAL '-13359.04'),
    (CHAR 'Callahan                      ', CHAR 'Ambrose             ', VARCHAR 'Superior', VARCHAR 'Glendale', BIGINT '5496', DECIMAL '653.67', DECIMAL '-4222.16'),
    (CHAR 'Campbell                      ', CHAR 'Sheila              ', VARCHAR 'Springfield', VARCHAR 'Friendship', BIGINT '1589', DECIMAL '673.44', DECIMAL '-16348.22'),
    (CHAR 'Campbell                      ', CHAR 'Sheila              ', VARCHAR 'Springfield', VARCHAR 'Lakewood', BIGINT '7325', DECIMAL '190.41', DECIMAL '-3632.10'),
    (CHAR 'Carl                          ', CHAR 'Natasha             ', VARCHAR 'Crossroads', VARCHAR 'Midway', BIGINT '302', DECIMAL '446.88', DECIMAL '993.11'),
    (CHAR 'Carlton                       ', CHAR 'Gloria              ', VARCHAR 'Midway', VARCHAR 'Bloomingdale', BIGINT '2939', DECIMAL '1716.38', DECIMAL '-9942.34'),
    (CHAR 'Carroll                       ', CHAR 'Bryan               ', VARCHAR 'Glenwood', VARCHAR 'Jamestown', BIGINT '1346', DECIMAL '873.39', DECIMAL '-12524.84'),
    (CHAR 'Chambers                      ', CHAR 'Adam                ', VARCHAR 'Stringtown', VARCHAR 'Ashland', BIGINT '5867', DECIMAL '2951.03', DECIMAL '-4220.68'),
    (CHAR 'Chambers                      ', CHAR 'Adam                ', VARCHAR 'Stringtown', VARCHAR 'Red Hill', BIGINT '2', DECIMAL '4891.64', DECIMAL '-25970.86'),
    (CHAR 'Chan                          ', CHAR 'Howard              ', VARCHAR 'Bridgeport', VARCHAR 'Woodland', BIGINT '7628', DECIMAL '815.66', DECIMAL '-24226.87'),
    (CHAR 'Chapa                         ', CHAR 'Marilyn             ', VARCHAR 'Woodlawn', VARCHAR 'Hamilton', BIGINT '3066', DECIMAL '115.52', DECIMAL '-10350.26'),
    (CHAR 'Chappell                      ', CHAR 'Victor              ', VARCHAR 'Sulphur Springs', VARCHAR 'Oak Ridge', BIGINT '8577', DECIMAL '4259.90', DECIMAL '-25517.17'),
    (CHAR 'Chester                       ', CHAR 'Julie               ', VARCHAR 'Pinecrest', VARCHAR 'Fowler', BIGINT '4532', DECIMAL '11151.60', DECIMAL '-16167.69'),
    (CHAR 'Child                         ', CHAR 'Hellen              ', VARCHAR 'Providence', VARCHAR 'Deerfield', BIGINT '4794', DECIMAL '520.42', DECIMAL '-1565.94'),
    (CHAR 'Child                         ', CHAR 'Hellen              ', VARCHAR 'Providence', VARCHAR 'Riverside', BIGINT '7950', DECIMAL '4223.51', DECIMAL '-16342.19'),
    (CHAR 'Chu                           ', CHAR 'William             ', VARCHAR 'Fairview', VARCHAR 'Valley View', BIGINT '6485', DECIMAL '905.42', DECIMAL '-5942.73'),
    (CHAR 'Clark                         ', CHAR 'Marie               ', VARCHAR 'Highland Park', VARCHAR 'Hillcrest', BIGINT '6609', DECIMAL '3307.62', DECIMAL '-5528.52'),
    (CHAR 'Clark                         ', CHAR 'Sammie              ', VARCHAR 'Macedonia', VARCHAR 'Oak Hill', BIGINT '8312', DECIMAL '1277.21', DECIMAL '-5254.21'),
    (CHAR 'Clark                         ', CHAR 'Sammie              ', VARCHAR 'Macedonia', VARCHAR 'Parkwood', BIGINT '8226', DECIMAL '2753.69', DECIMAL '-5827.13'),
    (CHAR 'Clarke                        ', CHAR 'Walter              ', VARCHAR 'Mount Zion', VARCHAR 'Spring Hill', BIGINT '3317', DECIMAL '2412.97', DECIMAL '-21646.44'),
    (CHAR 'Clawson                       ', CHAR 'Robert              ', VARCHAR 'Pleasant Grove', VARCHAR 'Arlington', BIGINT '2657', DECIMAL '812.08', DECIMAL '-16198.07'),
    (CHAR 'Clawson                       ', CHAR 'Robert              ', VARCHAR 'Pleasant Grove', VARCHAR 'Bethel', BIGINT '8606', DECIMAL '567.15', DECIMAL '-9196.08'),
    (CHAR 'Cole                          ', CHAR 'Ruby                ', VARCHAR 'Edgewood', VARCHAR 'Arlington', BIGINT '7637', DECIMAL '544.11', DECIMAL '-9282.16'),
    (CHAR 'Collins                       ', CHAR 'Margaret            ', VARCHAR 'Pine Grove', VARCHAR 'Riverside', BIGINT '6023', DECIMAL '39.85', DECIMAL '-14086.76'),
    (CHAR 'Combs                         ', CHAR 'Betty               ', VARCHAR 'Friendship', VARCHAR 'Oak Ridge', BIGINT '8691', DECIMAL '1634.65', DECIMAL '-10338.68'),
    (CHAR 'Conyers                       ', CHAR 'Joseph              ', VARCHAR 'Oakwood', VARCHAR 'Oak Grove', BIGINT '3195', DECIMAL '3219.24', DECIMAL '-14746.79'),
    (CHAR 'Cook                          ', CHAR 'Ingrid              ', VARCHAR 'Colfax', VARCHAR 'Shiloh', BIGINT '4039', DECIMAL '4630.14', DECIMAL '-8766.50'),
    (CHAR 'Cowan                         ', CHAR 'Shawn               ', VARCHAR 'Bethel', VARCHAR 'Woodville', BIGINT '1780', DECIMAL '4266.76', DECIMAL '-5263.53'),
    (CHAR 'Cox                           ', CHAR 'Amanda              ', VARCHAR 'Clifton', VARCHAR 'Kingston', BIGINT '4148', DECIMAL '4511.00', DECIMAL '-8771.06'),
    (CHAR 'Cox                           ', CHAR 'Amanda              ', VARCHAR 'Clifton', VARCHAR 'Lebanon', BIGINT '7121', DECIMAL '5275.31', DECIMAL '-15290.79'),
    (CHAR 'Craig                         ', CHAR 'William             ', VARCHAR 'Sutton', VARCHAR 'Clinton', BIGINT '8303', DECIMAL '1800.72', DECIMAL '-1884.72'),
    (CHAR 'Cyr                           ', CHAR 'Pauline             ', VARCHAR 'Parkwood', VARCHAR 'Belmont', BIGINT '3825', DECIMAL '4214.63', DECIMAL '-8859.76'),
    (CHAR 'Daniels                       ', CHAR 'Brandi              ', VARCHAR 'Peoria', VARCHAR 'Highland', BIGINT '1242', DECIMAL '2501.48', DECIMAL '-8775.32'),
    (CHAR 'Davidson                      ', CHAR 'Darrell             ', VARCHAR 'Shiloh', VARCHAR 'Mountain View', BIGINT '4114', DECIMAL '771.74', DECIMAL '-8117.24'),
    (CHAR 'Davis                         ', CHAR 'Colleen             ', VARCHAR 'Ashland', VARCHAR 'Marion', BIGINT '5405', DECIMAL '315.14', DECIMAL '-1398.93'),
    (CHAR 'Davis                         ', CHAR 'Colleen             ', VARCHAR 'Ashland', VARCHAR 'Waterloo', BIGINT '4322', DECIMAL '802.22', DECIMAL '-14639.12'),
    (CHAR 'Davis                         ', CHAR 'Rita                ', VARCHAR 'Clinton', VARCHAR 'Antioch', BIGINT '7900', DECIMAL '1095.64', DECIMAL '-3405.06'),
    (CHAR 'Davis                         ', CHAR 'Rita                ', VARCHAR 'Clinton', VARCHAR 'Bridgeport', BIGINT '4680', DECIMAL '779.33', DECIMAL '-11417.03'),
    (CHAR 'Dawkins                       ', CHAR 'Steven              ', VARCHAR 'Oak Ridge', VARCHAR 'Marion', BIGINT '2054', DECIMAL '992.57', DECIMAL '-11116.84'),
    (CHAR 'Dawkins                       ', CHAR 'Steven              ', VARCHAR 'Oak Ridge', VARCHAR 'Valley View', BIGINT '1081', DECIMAL '170.54', DECIMAL '-3082.05'),
    (CHAR 'Delarosa                      ', CHAR 'Jerald              ', VARCHAR 'Woodville', VARCHAR 'Crossroads', BIGINT '3359', DECIMAL '2269.82', DECIMAL '-6197.87'),
    (CHAR 'Dewey                         ', CHAR 'Lucas               ', VARCHAR 'Friendship', VARCHAR 'Lakeside', BIGINT '8447', DECIMAL '9443.65', DECIMAL '-31140.94'),
    (CHAR 'Dewey                         ', CHAR 'Lucas               ', VARCHAR 'Friendship', VARCHAR 'Oakwood', BIGINT '2685', DECIMAL '0.00', DECIMAL '-3277.97'),
    (CHAR 'Dickey                        ', CHAR 'Timothy             ', VARCHAR 'Unionville', VARCHAR 'Hamilton', BIGINT '9750', DECIMAL '850.89', DECIMAL '6370.06'),
    (CHAR 'Doolittle                     ', CHAR 'Brigida             ', VARCHAR 'Oak Hill', VARCHAR 'Antioch', BIGINT '4502', DECIMAL '114.54', DECIMAL '-6332.42'),
    (CHAR 'Duarte                        ', CHAR 'Ruth                ', VARCHAR 'Fairview', VARCHAR 'Lebanon', BIGINT '8414', DECIMAL '13.15', DECIMAL '-4969.85'),
    (CHAR 'Dudley                        ', CHAR 'Tonia               ', VARCHAR 'Union Hill', VARCHAR 'Green Acres', BIGINT '6887', DECIMAL '1720.50', DECIMAL '-12001.32'),
    (CHAR 'Dudley                        ', CHAR 'Tonia               ', VARCHAR 'Union Hill', VARCHAR 'Newport', BIGINT '142', DECIMAL '3551.31', DECIMAL '-15564.69')
)
