SELECT *
FROM
(
  VALUES
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Books                                             ', BIGINT '1', DECIMAL '411.07'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Children                                          ', BIGINT '3', DECIMAL '5081.44'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Electronics                                       ', BIGINT '2', DECIMAL '2289.60'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Home                                              ', BIGINT '3', DECIMAL '20528.20'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Men                                               ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Music                                             ', BIGINT '1', DECIMAL '7169.65'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '1', CHAR 'Women                                             ', BIGINT '1', DECIMAL '783.30'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '2', CHAR 'Electronics                                       ', BIGINT '3', DECIMAL '988.68'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '2', CHAR 'Home                                              ', BIGINT '1', DECIMAL '5616.97'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '2', CHAR 'Shoes                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '2', CHAR 'Sports                                            ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '2', CHAR 'Women                                             ', BIGINT '2', DECIMAL '2018.66'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Electronics                                       ', BIGINT '3', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Home                                              ', BIGINT '4', DECIMAL '16414.34'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Jewelry                                           ', BIGINT '2', DECIMAL '1485.80'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Men                                               ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Music                                             ', BIGINT '3', DECIMAL '5168.32'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Shoes                                             ', BIGINT '1', DECIMAL '6325.48'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '3', CHAR 'Women                                             ', BIGINT '1', DECIMAL '2587.99'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Books                                             ', BIGINT '2', DECIMAL '10982.79'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Electronics                                       ', BIGINT '2', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Home                                              ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Jewelry                                           ', BIGINT '2', DECIMAL '502.80'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Men                                               ', BIGINT '3', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Music                                             ', BIGINT '6', DECIMAL '1944.39'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Shoes                                             ', BIGINT '3', DECIMAL '10873.96'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Sports                                            ', BIGINT '1', DECIMAL '615.68'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1998', INTEGER '4', CHAR 'Women                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Children                                          ', BIGINT '1', DECIMAL '3401.60'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Electronics                                       ', BIGINT '1', DECIMAL '5949.64'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Home                                              ', BIGINT '1', DECIMAL '4617.60'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Jewelry                                           ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Music                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Shoes                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Sports                                            ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '1', CHAR 'Women                                             ', BIGINT '2', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '2', CHAR 'Books                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '2', CHAR 'Home                                              ', BIGINT '2', DECIMAL '2451.60'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '2', CHAR 'Sports                                            ', BIGINT '1', DECIMAL '929.61'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Books                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Children                                          ', BIGINT '1', DECIMAL '4644.36'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Electronics                                       ', BIGINT '3', DECIMAL '719.86'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Home                                              ', BIGINT '1', DECIMAL '13627.53'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Jewelry                                           ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Men                                               ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Music                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Shoes                                             ', BIGINT '2', DECIMAL '320.00'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '3', CHAR 'Women                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Books                                             ', BIGINT '1', DECIMAL '355.64'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Children                                          ', BIGINT '5', DECIMAL '3494.36'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Home                                              ', BIGINT '2', DECIMAL '4285.15'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Jewelry                                           ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Men                                               ', BIGINT '3', DECIMAL '3802.19'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Music                                             ', BIGINT '3', DECIMAL '7736.54'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Shoes                                             ', BIGINT '2', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Sports                                            ', BIGINT '1', DECIMAL '1908.00'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '1999', INTEGER '4', CHAR 'Women                                             ', BIGINT '1', DECIMAL '0.00'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Electronics                                       ', BIGINT '1', DECIMAL '3637.44'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Jewelry                                           ', BIGINT '1', DECIMAL '5254.92'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Men                                               ', BIGINT '1', DECIMAL '1407.56'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Music                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Sports                                            ', BIGINT '2', DECIMAL '261.56'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '1', CHAR 'Women                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Children                                          ', BIGINT '2', DECIMAL '17293.39'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Electronics                                       ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Jewelry                                           ', BIGINT '1', DECIMAL '513.88'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Men                                               ', BIGINT '3', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Music                                             ', BIGINT '3', DECIMAL '871.40'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Sports                                            ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '3', CHAR 'Women                                             ', BIGINT '2', DECIMAL '11188.46'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Children                                          ', BIGINT '3', DECIMAL '4957.80'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Electronics                                       ', BIGINT '2', DECIMAL '694.35'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Home                                              ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Jewelry                                           ', BIGINT '5', DECIMAL '3850.72'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Men                                               ', BIGINT '1', DECIMAL '1913.42'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Music                                             ', BIGINT '2', DECIMAL '3908.30'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Shoes                                             ', BIGINT '3', DECIMAL '5489.84'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Sports                                            ', BIGINT '1', DECIMAL '386.00'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2000', INTEGER '4', CHAR 'Women                                             ', BIGINT '4', DECIMAL '23596.92'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '1', CHAR 'Men                                               ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '1', CHAR 'Sports                                            ', BIGINT '1', DECIMAL '1828.96'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '1', CHAR 'Women                                             ', BIGINT '1', DECIMAL '3771.48'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', CHAR 'Books                                             ', BIGINT '2', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', CHAR 'Electronics                                       ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', CHAR 'Shoes                                             ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', CHAR 'Sports                                            ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', CHAR 'Women                                             ', BIGINT '2', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '2', NULL, BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Children                                          ', BIGINT '1', DECIMAL '5406.96'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Electronics                                       ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Jewelry                                           ', BIGINT '2', DECIMAL '365.64'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Men                                               ', BIGINT '1', NULL),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Music                                             ', BIGINT '2', DECIMAL '7328.70'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '3', CHAR 'Sports                                            ', BIGINT '2', DECIMAL '713.58'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Children                                          ', BIGINT '4', DECIMAL '14013.84'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Electronics                                       ', BIGINT '2', DECIMAL '1540.36'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Home                                              ', BIGINT '2', DECIMAL '3852.50'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Jewelry                                           ', BIGINT '5', DECIMAL '12789.31'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Men                                               ', BIGINT '3', DECIMAL '11276.70'),
    (VARCHAR 'catalog', VARCHAR 'cs_ship_addr_sk', INTEGER '2001', INTEGER '4', CHAR 'Music                                             ', BIGINT '3', DECIMAL '2311.16')
)
