SELECT *
FROM
(
  VALUES
    (CHAR 'AAAAAAAABKCAAAAA', CHAR 'Dr.       ', CHAR 'Terrence            ', CHAR 'Albright                      ', CHAR '419       ', VARCHAR 'View Miller', CHAR 'Wy             ', CHAR 'Suite 360 ', VARCHAR 'Pleasant Grove', VARCHAR 'Cobb County', CHAR 'GA', CHAR '34136     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '5079.60'),
    (CHAR 'AAAAAAAACKBAAAAA', CHAR 'Dr.       ', CHAR 'Maurice             ', CHAR 'Morales                       ', CHAR '313       ', VARCHAR '2nd Eigth', CHAR 'Avenue         ', CHAR 'Suite 40  ', VARCHAR 'Marion', VARCHAR 'Glascock County', CHAR 'GA', CHAR '30399     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '3038.84'),
    (CHAR 'AAAAAAAACNAAAAAA', CHAR 'Ms.       ', CHAR 'Diane               ', CHAR 'Blount                        ', CHAR '780       ', VARCHAR '4th ', CHAR 'Ave            ', CHAR 'Suite T   ', VARCHAR 'Spring Hill', VARCHAR 'Worth County', CHAR 'GA', CHAR '36787     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '5614.20'),
    (CHAR 'AAAAAAAADADAAAAA', CHAR 'Mr.       ', CHAR 'Charles             ', CHAR 'Loveless                      ', CHAR '24        ', VARCHAR 'Central ', CHAR 'Blvd           ', CHAR 'Suite 490 ', VARCHAR 'Crossroads', VARCHAR 'Brooks County', CHAR 'GA', CHAR '30534     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '1429.42'),
    (CHAR 'AAAAAAAADGDAAAAA', CHAR 'Mr.       ', CHAR 'Alberto             ', CHAR 'Mccreary                      ', CHAR '379       ', VARCHAR 'Spring Eigth', CHAR 'Street         ', CHAR 'Suite R   ', VARCHAR 'Cedar Grove', VARCHAR 'Wilcox County', CHAR 'GA', CHAR '30411     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '544.12'),
    (CHAR 'AAAAAAAADGDAAAAA', CHAR 'Mr.       ', CHAR 'Alberto             ', CHAR 'Mccreary                      ', CHAR '379       ', VARCHAR 'Spring Eigth', CHAR 'Street         ', CHAR 'Suite R   ', VARCHAR 'Cedar Grove', VARCHAR 'Wilcox County', CHAR 'GA', CHAR '30411     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '2712.19'),
    (CHAR 'AAAAAAAAEMDAAAAA', CHAR 'Dr.       ', CHAR 'Aline               ', CHAR 'Ramos                         ', CHAR '416       ', VARCHAR '10th ', CHAR 'Boulevard      ', CHAR 'Suite R   ', VARCHAR 'Calhoun', VARCHAR 'Miller County', CHAR 'GA', CHAR '36909     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '2204.66'),
    (CHAR 'AAAAAAAAEMDAAAAA', CHAR 'Dr.       ', CHAR 'Aline               ', CHAR 'Ramos                         ', CHAR '416       ', VARCHAR '10th ', CHAR 'Boulevard      ', CHAR 'Suite R   ', VARCHAR 'Calhoun', VARCHAR 'Miller County', CHAR 'GA', CHAR '36909     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '4518.97'),
    (CHAR 'AAAAAAAAENDAAAAA', CHAR 'Sir       ', CHAR 'Richard             ', CHAR 'Bell                          ', CHAR '419       ', VARCHAR 'View Miller', CHAR 'Wy             ', CHAR 'Suite 360 ', VARCHAR 'Pleasant Grove', VARCHAR 'Cobb County', CHAR 'GA', CHAR '34136     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '14670.20'),
    (CHAR 'AAAAAAAAFBCAAAAA', CHAR 'Mr.       ', CHAR 'Douglas             ', CHAR 'Scott                         ', CHAR '498       ', VARCHAR 'Lake ', CHAR 'Way            ', CHAR 'Suite 490 ', VARCHAR 'Spring Valley', VARCHAR 'Habersham County', CHAR 'GA', CHAR '36060     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '6745.16'),
    (CHAR 'AAAAAAAAFDAAAAAA', CHAR 'Mr.       ', CHAR 'Paul                ', CHAR 'Higgins                       ', CHAR '828       ', VARCHAR '2nd Miller', CHAR 'ST             ', CHAR 'Suite S   ', VARCHAR 'Mechanicsburg', VARCHAR 'Wheeler County', CHAR 'GA', CHAR '32219     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'apartment           ', DECIMAL '2881.20'),
    (CHAR 'AAAAAAAAFGAAAAAA', CHAR 'Dr.       ', CHAR 'Jeffrey             ', CHAR 'Bruce                         ', CHAR '52        ', VARCHAR '6th Park', CHAR 'Drive          ', CHAR 'Suite E   ', VARCHAR 'Farmington', VARCHAR 'Johnson County', CHAR 'GA', CHAR '39145     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '3347.84'),
    (CHAR 'AAAAAAAAFLDAAAAA', CHAR 'Ms.       ', CHAR 'Margaret            ', CHAR 'Roberts                       ', CHAR '780       ', VARCHAR '4th ', CHAR 'Ave            ', CHAR 'Suite T   ', VARCHAR 'Spring Hill', VARCHAR 'Worth County', CHAR 'GA', CHAR '36787     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '2150.71'),
    (CHAR 'AAAAAAAAFLDAAAAA', CHAR 'Ms.       ', CHAR 'Margaret            ', CHAR 'Roberts                       ', CHAR '780       ', VARCHAR '4th ', CHAR 'Ave            ', CHAR 'Suite T   ', VARCHAR 'Spring Hill', VARCHAR 'Worth County', CHAR 'GA', CHAR '36787     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '2369.63'),
    (CHAR 'AAAAAAAAHMAAAAAA', CHAR 'Mr.       ', CHAR 'Edwardo             ', CHAR 'Porter                        ', CHAR '986       ', VARCHAR 'West East', CHAR 'Blvd           ', CHAR 'Suite F   ', VARCHAR 'Pleasant Grove', VARCHAR 'Coweta County', CHAR 'GA', CHAR '34136     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'apartment           ', DECIMAL '3294.48'),
    (CHAR 'AAAAAAAAHNAAAAAA', CHAR 'Miss      ', CHAR 'Lillian             ', CHAR 'Morgan                        ', CHAR '420       ', VARCHAR 'Park ', CHAR 'Street         ', CHAR 'Suite L   ', VARCHAR 'Oakwood', VARCHAR 'Lamar County', CHAR 'GA', CHAR '30169     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '1885.51'),
    (CHAR 'AAAAAAAAIHDAAAAA', CHAR 'Sir       ', CHAR 'Mark                ', CHAR 'Bartley                       ', CHAR '353       ', VARCHAR 'Sixth ', CHAR 'Ln             ', CHAR 'Suite 410 ', VARCHAR 'Oak Ridge', VARCHAR 'Charlton County', CHAR 'GA', CHAR '38371     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '1834.90'),
    (CHAR 'AAAAAAAAIOCAAAAA', CHAR 'Dr.       ', CHAR 'Julio               ', CHAR 'Mcdaniel                      ', CHAR '344       ', VARCHAR 'Oak ', CHAR 'Circle         ', CHAR 'Suite S   ', VARCHAR 'Five Forks', VARCHAR 'Montgomery County', CHAR 'GA', CHAR '32293     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '2765.35'),
    (CHAR 'AAAAAAAAJHAAAAAA', CHAR 'Mrs.      ', NULL, NULL, CHAR '780       ', VARCHAR '4th ', CHAR 'Ave            ', CHAR 'Suite T   ', VARCHAR 'Spring Hill', VARCHAR 'Worth County', CHAR 'GA', CHAR '36787     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '3618.05'),
    (CHAR 'AAAAAAAAJMAAAAAA', CHAR 'Dr.       ', CHAR 'James               ', CHAR 'Scott                         ', CHAR '562       ', VARCHAR '5th Smith', CHAR 'Ct.            ', CHAR 'Suite G   ', VARCHAR 'Concord', VARCHAR 'Marion County', CHAR 'GA', CHAR '34107     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '1967.80'),
    (CHAR 'AAAAAAAAKCAAAAAA', CHAR 'Dr.       ', CHAR 'Deborah             ', CHAR 'Burton                        ', CHAR '129       ', VARCHAR 'Valley ', CHAR 'Circle         ', CHAR 'Suite 410 ', VARCHAR 'Ashland', VARCHAR 'Decatur County', CHAR 'GA', CHAR '34244     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '3480.13'),
    (CHAR 'AAAAAAAAKCAAAAAA', CHAR 'Dr.       ', CHAR 'Deborah             ', CHAR 'Burton                        ', CHAR '129       ', VARCHAR 'Valley ', CHAR 'Circle         ', CHAR 'Suite 410 ', VARCHAR 'Ashland', VARCHAR 'Decatur County', CHAR 'GA', CHAR '34244     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '3625.94'),
    (CHAR 'AAAAAAAALJBAAAAA', CHAR 'Sir       ', CHAR 'Cleo                ', CHAR 'Spangler                      ', CHAR '264       ', VARCHAR 'Main ', CHAR 'Drive          ', CHAR 'Suite V   ', VARCHAR 'Cedar Grove', VARCHAR 'Wilcox County', CHAR 'GA', CHAR '30411     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '2334.40'),
    (CHAR 'AAAAAAAALOAAAAAA', CHAR 'Mr.       ', CHAR 'Salvador            ', CHAR 'Ramirez                       ', CHAR '444       ', VARCHAR 'Lake ', CHAR 'Boulevard      ', CHAR 'Suite A   ', VARCHAR 'Marion', VARCHAR 'Macon County', CHAR 'GA', CHAR '30399     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '3057.86'),
    (CHAR 'AAAAAAAALOAAAAAA', CHAR 'Mr.       ', CHAR 'Salvador            ', CHAR 'Ramirez                       ', CHAR '444       ', VARCHAR 'Lake ', CHAR 'Boulevard      ', CHAR 'Suite A   ', VARCHAR 'Marion', VARCHAR 'Macon County', CHAR 'GA', CHAR '30399     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '3212.18'),
    (CHAR 'AAAAAAAAMPBAAAAA', CHAR 'Mr.       ', CHAR 'Carlos              ', CHAR 'Garza                         ', CHAR '335       ', VARCHAR '7th ', CHAR 'Blvd           ', CHAR 'Suite 230 ', VARCHAR 'Plainview', VARCHAR 'Taylor County', CHAR 'GA', CHAR '33683     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'apartment           ', DECIMAL '4215.74'),
    (CHAR 'AAAAAAAANJCAAAAA', CHAR 'Mrs.      ', CHAR 'Ella                ', CHAR 'Barnette                      ', CHAR '949       ', VARCHAR '12th ', CHAR 'Boulevard      ', CHAR 'Suite V   ', VARCHAR 'Arlington', VARCHAR 'Tift County', CHAR 'GA', CHAR '36557     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'single family       ', DECIMAL '4484.34'),
    (CHAR 'AAAAAAAAPMBAAAAA', CHAR 'Sir       ', CHAR 'Charlie             ', CHAR 'Deleon                        ', CHAR '148       ', VARCHAR 'Fourth Elm', CHAR 'Street         ', CHAR 'Suite W   ', VARCHAR 'Oak Hill', VARCHAR 'Clayton County', CHAR 'GA', CHAR '37838     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '2505.77'),
    (CHAR 'AAAAAAAAPMBAAAAA', CHAR 'Sir       ', CHAR 'Charlie             ', CHAR 'Deleon                        ', CHAR '148       ', VARCHAR 'Fourth Elm', CHAR 'Street         ', CHAR 'Suite W   ', VARCHAR 'Oak Hill', VARCHAR 'Clayton County', CHAR 'GA', CHAR '37838     ', VARCHAR 'United States', DECIMAL '-5.00', CHAR 'condo               ', DECIMAL '4005.21')
)
