SELECT *
FROM
(
  VALUES
    (DECIMAL '5189585.33', NULL, NULL, INTEGER '2', BIGINT '1'),
    (DECIMAL '655046.32', CHAR 'Men                                               ', NULL, INTEGER '1', BIGINT '1'),
    (DECIMAL '626624.82', CHAR 'Women                                             ', NULL, INTEGER '1', BIGINT '2'),
    (DECIMAL '581067.68', CHAR 'Books                                             ', NULL, INTEGER '1', BIGINT '3'),
    (DECIMAL '561790.19', CHAR 'Music                                             ', NULL, INTEGER '1', BIGINT '4'),
    (DECIMAL '510840.54', CHAR 'Shoes                                             ', NULL, INTEGER '1', BIGINT '5'),
    (DECIMAL '495178.04', CHAR 'Electronics                                       ', NULL, INTEGER '1', BIGINT '6'),
    (DECIMAL '472123.12', CHAR 'Jewelry                                           ', NULL, INTEGER '1', BIGINT '7'),
    (DECIMAL '459386.12', CHAR 'Children                                          ', NULL, INTEGER '1', BIGINT '8'),
    (DECIMAL '405665.89', CHAR 'Sports                                            ', NULL, INTEGER '1', BIGINT '9'),
    (DECIMAL '401556.14', CHAR 'Home                                              ', NULL, INTEGER '1', BIGINT '10'),
    (DECIMAL '20306.47', NULL, NULL, INTEGER '1', BIGINT '11'),
    (DECIMAL '68702.95', CHAR 'Books                                             ', CHAR 'romance                                           ', INTEGER '0', BIGINT '1'),
    (DECIMAL '65051.89', CHAR 'Books                                             ', CHAR 'fiction                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '59783.06', CHAR 'Books                                             ', CHAR 'business                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '45029.55', CHAR 'Books                                             ', CHAR 'entertainments                                    ', INTEGER '0', BIGINT '4'),
    (DECIMAL '44560.70', CHAR 'Books                                             ', CHAR 'reference                                         ', INTEGER '0', BIGINT '5'),
    (DECIMAL '39990.72', CHAR 'Books                                             ', CHAR 'cooking                                           ', INTEGER '0', BIGINT '6'),
    (DECIMAL '34990.25', CHAR 'Books                                             ', CHAR 'self-help                                         ', INTEGER '0', BIGINT '7'),
    (DECIMAL '29650.97', CHAR 'Books                                             ', CHAR 'computers                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '29327.70', CHAR 'Books                                             ', CHAR 'travel                                            ', INTEGER '0', BIGINT '9'),
    (DECIMAL '28930.75', CHAR 'Books                                             ', CHAR 'history                                           ', INTEGER '0', BIGINT '10'),
    (DECIMAL '25491.36', CHAR 'Books                                             ', CHAR 'sports                                            ', INTEGER '0', BIGINT '11'),
    (DECIMAL '24398.83', CHAR 'Books                                             ', CHAR 'arts                                              ', INTEGER '0', BIGINT '12'),
    (DECIMAL '24164.51', CHAR 'Books                                             ', CHAR 'parenting                                         ', INTEGER '0', BIGINT '13'),
    (DECIMAL '23909.89', CHAR 'Books                                             ', CHAR 'home repair                                       ', INTEGER '0', BIGINT '14'),
    (DECIMAL '22835.73', CHAR 'Books                                             ', CHAR 'mystery                                           ', INTEGER '0', BIGINT '15'),
    (DECIMAL '13053.94', CHAR 'Books                                             ', CHAR 'science                                           ', INTEGER '0', BIGINT '16'),
    (DECIMAL '1194.88', CHAR 'Books                                             ', NULL, INTEGER '0', BIGINT '17'),
    (DECIMAL '130979.49', CHAR 'Children                                          ', CHAR 'toddlers                                          ', INTEGER '0', BIGINT '1'),
    (DECIMAL '128151.67', CHAR 'Children                                          ', CHAR 'newborn                                           ', INTEGER '0', BIGINT '2'),
    (DECIMAL '111833.79', CHAR 'Children                                          ', CHAR 'school-uniforms                                   ', INTEGER '0', BIGINT '3'),
    (DECIMAL '88421.17', CHAR 'Children                                          ', CHAR 'infants                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '85432.91', CHAR 'Electronics                                       ', CHAR 'televisions                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '61661.11', CHAR 'Electronics                                       ', CHAR 'dvd/vcr players                                   ', INTEGER '0', BIGINT '2'),
    (DECIMAL '42718.00', CHAR 'Electronics                                       ', CHAR 'stereo                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '37591.39', CHAR 'Electronics                                       ', CHAR 'cameras                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '37375.54', CHAR 'Electronics                                       ', CHAR 'disk drives                                       ', INTEGER '0', BIGINT '5'),
    (DECIMAL '35997.36', CHAR 'Electronics                                       ', CHAR 'karoke                                            ', INTEGER '0', BIGINT '6'),
    (DECIMAL '26723.20', CHAR 'Electronics                                       ', CHAR 'musical                                           ', INTEGER '0', BIGINT '7'),
    (DECIMAL '23368.30', CHAR 'Electronics                                       ', CHAR 'memory                                            ', INTEGER '0', BIGINT '8'),
    (DECIMAL '23305.78', CHAR 'Electronics                                       ', CHAR 'camcorders                                        ', INTEGER '0', BIGINT '9'),
    (DECIMAL '22707.58', CHAR 'Electronics                                       ', CHAR 'monitors                                          ', INTEGER '0', BIGINT '10'),
    (DECIMAL '19521.01', CHAR 'Electronics                                       ', CHAR 'automotive                                        ', INTEGER '0', BIGINT '11'),
    (DECIMAL '19237.68', CHAR 'Electronics                                       ', CHAR 'scanners                                          ', INTEGER '0', BIGINT '12'),
    (DECIMAL '18458.48', CHAR 'Electronics                                       ', CHAR 'wireless                                          ', INTEGER '0', BIGINT '13'),
    (DECIMAL '17131.00', CHAR 'Electronics                                       ', CHAR 'audio                                             ', INTEGER '0', BIGINT '14'),
    (DECIMAL '13635.23', CHAR 'Electronics                                       ', CHAR 'portable                                          ', INTEGER '0', BIGINT '15'),
    (DECIMAL '10313.47', CHAR 'Electronics                                       ', CHAR 'personal                                          ', INTEGER '0', BIGINT '16'),
    (DECIMAL '56487.04', CHAR 'Home                                              ', CHAR 'rugs                                              ', INTEGER '0', BIGINT '1'),
    (DECIMAL '45508.16', CHAR 'Home                                              ', CHAR 'lighting                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '39962.88', CHAR 'Home                                              ', CHAR 'bedding                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '32120.99', CHAR 'Home                                              ', CHAR 'flatware                                          ', INTEGER '0', BIGINT '4'),
    (DECIMAL '31748.57', CHAR 'Home                                              ', CHAR 'decor                                             ', INTEGER '0', BIGINT '5'),
    (DECIMAL '30547.36', CHAR 'Home                                              ', CHAR 'paint                                             ', INTEGER '0', BIGINT '6'),
    (DECIMAL '29553.20', CHAR 'Home                                              ', CHAR 'curtains/drapes                                   ', INTEGER '0', BIGINT '7'),
    (DECIMAL '27484.90', CHAR 'Home                                              ', CHAR 'furniture                                         ', INTEGER '0', BIGINT '8'),
    (DECIMAL '25394.01', CHAR 'Home                                              ', CHAR 'mattresses                                        ', INTEGER '0', BIGINT '9'),
    (DECIMAL '21519.60', CHAR 'Home                                              ', CHAR 'blinds/shades                                     ', INTEGER '0', BIGINT '10'),
    (DECIMAL '20562.09', CHAR 'Home                                              ', CHAR 'glassware                                         ', INTEGER '0', BIGINT '11'),
    (DECIMAL '15843.61', CHAR 'Home                                              ', CHAR 'kids                                              ', INTEGER '0', BIGINT '12'),
    (DECIMAL '13783.44', CHAR 'Home                                              ', CHAR 'accent                                            ', INTEGER '0', BIGINT '13'),
    (DECIMAL '6563.55', CHAR 'Home                                              ', CHAR 'bathroom                                          ', INTEGER '0', BIGINT '14'),
    (DECIMAL '3573.14', CHAR 'Home                                              ', CHAR 'wallpaper                                         ', INTEGER '0', BIGINT '15'),
    (DECIMAL '903.60', CHAR 'Home                                              ', CHAR 'tables                                            ', INTEGER '0', BIGINT '16'),
    (DECIMAL '63303.57', CHAR 'Jewelry                                           ', CHAR 'bracelets                                         ', INTEGER '0', BIGINT '1'),
    (DECIMAL '56115.38', CHAR 'Jewelry                                           ', CHAR 'pendants                                          ', INTEGER '0', BIGINT '2'),
    (DECIMAL '53681.29', CHAR 'Jewelry                                           ', CHAR 'costume                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '52150.66', CHAR 'Jewelry                                           ', CHAR 'jewelry boxes                                     ', INTEGER '0', BIGINT '4'),
    (DECIMAL '40625.64', CHAR 'Jewelry                                           ', CHAR 'gold                                              ', INTEGER '0', BIGINT '5'),
    (DECIMAL '38009.46', CHAR 'Jewelry                                           ', CHAR 'loose stones                                      ', INTEGER '0', BIGINT '6'),
    (DECIMAL '35536.66', CHAR 'Jewelry                                           ', CHAR 'diamonds                                          ', INTEGER '0', BIGINT '7'),
    (DECIMAL '31842.23', CHAR 'Jewelry                                           ', CHAR 'womens watch                                      ', INTEGER '0', BIGINT '8'),
    (DECIMAL '31031.51', CHAR 'Jewelry                                           ', CHAR 'estate                                            ', INTEGER '0', BIGINT '9'),
    (DECIMAL '21041.50', CHAR 'Jewelry                                           ', CHAR 'birdal                                            ', INTEGER '0', BIGINT '10'),
    (DECIMAL '14870.47', CHAR 'Jewelry                                           ', CHAR 'rings                                             ', INTEGER '0', BIGINT '11'),
    (DECIMAL '12185.93', CHAR 'Jewelry                                           ', CHAR 'custom                                            ', INTEGER '0', BIGINT '12'),
    (DECIMAL '10806.73', CHAR 'Jewelry                                           ', CHAR 'earings                                           ', INTEGER '0', BIGINT '13'),
    (DECIMAL '4282.96', CHAR 'Jewelry                                           ', CHAR 'semi-precious                                     ', INTEGER '0', BIGINT '14'),
    (DECIMAL '3864.57', CHAR 'Jewelry                                           ', CHAR 'mens watch                                        ', INTEGER '0', BIGINT '15'),
    (DECIMAL '2774.56', CHAR 'Jewelry                                           ', CHAR 'consignment                                       ', INTEGER '0', BIGINT '16'),
    (DECIMAL '248232.12', CHAR 'Men                                               ', CHAR 'accessories                                       ', INTEGER '0', BIGINT '1'),
    (DECIMAL '168075.09', CHAR 'Men                                               ', CHAR 'sports-apparel                                    ', INTEGER '0', BIGINT '2'),
    (DECIMAL '125910.01', CHAR 'Men                                               ', CHAR 'shirts                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '112829.10', CHAR 'Men                                               ', CHAR 'pants                                             ', INTEGER '0', BIGINT '4'),
    (DECIMAL '172709.93', CHAR 'Music                                             ', CHAR 'pop                                               ', INTEGER '0', BIGINT '1'),
    (DECIMAL '136352.75', CHAR 'Music                                             ', CHAR 'rock                                              ', INTEGER '0', BIGINT '2'),
    (DECIMAL '129374.40', CHAR 'Music                                             ', CHAR 'country                                           ', INTEGER '0', BIGINT '3'),
    (DECIMAL '123353.11', CHAR 'Music                                             ', CHAR 'classical                                         ', INTEGER '0', BIGINT '4'),
    (DECIMAL '158284.43', CHAR 'Shoes                                             ', CHAR 'mens                                              ', INTEGER '0', BIGINT '1'),
    (DECIMAL '121177.11', CHAR 'Shoes                                             ', CHAR 'kids                                              ', INTEGER '0', BIGINT '2'),
    (DECIMAL '119174.81', CHAR 'Shoes                                             ', CHAR 'athletic                                          ', INTEGER '0', BIGINT '3'),
    (DECIMAL '112204.19', CHAR 'Shoes                                             ', CHAR 'womens                                            ', INTEGER '0', BIGINT '4'),
    (DECIMAL '76821.59', CHAR 'Sports                                            ', CHAR 'guns                                              ', INTEGER '0', BIGINT '1'),
    (DECIMAL '53949.93', CHAR 'Sports                                            ', CHAR 'golf                                              ', INTEGER '0', BIGINT '2'),
    (DECIMAL '36112.01', CHAR 'Sports                                            ', CHAR 'hockey                                            ', INTEGER '0', BIGINT '3'),
    (DECIMAL '35802.31', CHAR 'Sports                                            ', CHAR 'outdoor                                           ', INTEGER '0', BIGINT '4'),
    (DECIMAL '35004.59', CHAR 'Sports                                            ', CHAR 'fitness                                           ', INTEGER '0', BIGINT '5'),
    (DECIMAL '31211.29', CHAR 'Sports                                            ', CHAR 'camping                                           ', INTEGER '0', BIGINT '6'),
    (DECIMAL '27549.99', CHAR 'Sports                                            ', CHAR 'fishing                                           ', INTEGER '0', BIGINT '7')
)
