SELECT *
FROM
(
  VALUES
    (VARCHAR '1-URGENT', BIGINT '93'),
    (VARCHAR '2-HIGH', BIGINT '103'),
    (VARCHAR '3-MEDIUM', BIGINT '109'),
    (VARCHAR '4-NOT SPECIFIED', BIGINT '102'),
    (VARCHAR '5-LOW', BIGINT '128')
)
